### ISSUE TITLE
bgset not working correctly on Windows IE / Windows Chrome

### ISSUE THREAD

**Issue by MischaSz** [aFarkas/lazysizes#100]
Hi there

I've implemented lazy sizes together with beset and respimage on a website with a Bootstrap Carousel slider. The code works fine on OS X browsers (Safari and Chrome); however, it is not working on Windows platforms. 

The way I've implemented is that I load a LQIP in the style sheet and then I apply the data-bgset parameter on the slider element div. 

Please see an example here:
http://beta.verium.acribis.ch/de/index.php

On OS X, the LQIP gets replaced with the correct sized picture; on Windows, the LQIP is not getting replaced. If I inspect the code in Chrome (Windows), I can see that the style parameter which gets applied by respimg only contains the lowest width file even that the viewport is much larger. 

Do you have any idea? 

Best regards
Mischa

**Comment by aFarkas** [comment]
I actually don't see a ``data-bgset `` on the page above. Have you just changed it?

**Comment by MischaSz** [comment]
Sorry I’ve uploaded the wrong file. Should be online now… Thanks!

Von:  Alexander Farkas
Antworten an:  aFarkas/lazysizes
Datum:  Donnerstag, 21. Mai 2015 13:00
An:  aFarkas/lazysizes
Cc:  Mischa Szeker
Betreff:  Re: [lazysizes] bgset not working correctly on Windows IE / Windows Chrome (#100)


I actually don't see a data-bgset on the page above. Have you just changed it?

**Comment by MischaSz** [comment]
It’s a bit confusing, but in IE11 I get „almost“ correct values. Almost because the script loads the 1400 px version even that the size is larger than 1400px. In Chrome (Windows) it always loads the 700px version no matter how wide the viewport is. In Safari and Chrome (OS X) it always loads the correct size.

Best
Mischa

Von:  Alexander Farkas
Antworten an:  aFarkas/lazysizes
Datum:  Donnerstag, 21. Mai 2015 13:00
An:  aFarkas/lazysizes
Cc:  Mischa Szeker
Betreff:  Re: [lazysizes] bgset not working correctly on Windows IE / Windows Chrome (#100)


I actually don't see a data-bgset on the page above. Have you just changed it?

**Comment by aFarkas** [comment]
I think I can only reproduce this on Chrome. Your initial bug report isn't right? The problem does not exist in IE on Windows, only on Chrome on windows?

**Comment by MischaSz** [comment]
Hi Alex

IE works, but not 100% correctly. It loads the 1400w version even thou the viewport size is > 1400px.

Chrome only loads the 700px version. Again – this only happens on Windows and not on Mac.

If you like I can reproduce it again on all browsers with disabled cache and send you the results. 

Best regards
Mischa

Von:  Alexander Farkas
Antworten an:  aFarkas/lazysizes
Datum:  Donnerstag, 21. Mai 2015 16:44
An:  aFarkas/lazysizes
Cc:  Mischa Szeker
Betreff:  Re: [lazysizes] bgset not working correctly on Windows IE / Windows Chrome (#100)


I think I can only reproduce this on Chrome. Your initial bug report isn't right? The problem does not exist in IE on Windows, only on Chrome on windows?

**Comment by aFarkas** [comment]
@MischaSz 
For IE. I'm not sure whether this is an error. I'm using [this source selection algorithm](http://jsfiddle.net/trixta/9dponzs2/). 

Just run the following code in your console and report the numbers back:

```js
({
	dpr: window.devicePixelRatio,
	sizes: document.querySelector('picture img[data-sizes]').getAttribute('sizes'),
	curSrc: document.querySelector('picture img[data-sizes]').currentSrc || document.querySelector('picture img[data-sizes]').src
})
```

I look into what is going on with Chrome, but I think it is a Chrome bug.

**Comment by aFarkas** [comment]
It turns out you have an invalid markup (you have "../img/stilfset-joch-25_700.jpg" without a descriptor):

Change this:
```
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w, ../img/stilfset-joch-25_700.jpg"
```

To this:

```
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w"
```

**Comment by MischaSz** [comment]
Oh you’re right – I’m sorry! I’m gonna change it tomorrow and let you know the results ASAP.

Thanks and best regards
Mischa

Von:  Alexander Farkas
Antworten an:  aFarkas/lazysizes
Datum:  Donnerstag, 21. Mai 2015 19:44
An:  aFarkas/lazysizes
Cc:  Mischa Szeker
Betreff:  Re: [lazysizes] bgset not working correctly on Windows IE / Windows Chrome (#100)


It turns out you have an invalid markup (you have "../img/stilfset-joch-25_700.jpg" without a descriptor):

Change this:
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w, ../img/stilfset-joch-25_700.jpg"
To this:
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w"

**Comment by MischaSz** [comment]
Hi Alex

Problem is solved! Sorry again for the wrong bug report and thanks for your help.

Best regards,
Mischa

Von:  Alexander Farkas
Antworten an:  aFarkas/lazysizes
Datum:  Donnerstag, 21. Mai 2015 19:44
An:  aFarkas/lazysizes
Cc:  Mischa Szeker
Betreff:  Re: [lazysizes] bgset not working correctly on Windows IE / Windows Chrome (#100)


It turns out you have an invalid markup (you have "../img/stilfset-joch-25_700.jpg" without a descriptor):

Change this:
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w, ../img/stilfset-joch-25_700.jpg"
To this:
data-bgset="../img/stilfset-joch-25_700.jpg 700w, ../img/stilfset-joch-25_1400.jpg 1400w, ../img/stilfset-joch-25_2800.jpg 2800w"

**Comment by aFarkas** [comment]
absolutely no problem. About your image quality problem on IE: Please update lazySizes including plugins (especially the respimg plugin with the newest version in master).
