### ISSUE TITLE
aspectratio: calculate width from height? 

### ISSUE THREAD

**Issue by neatonk** [aFarkas/lazysizes#102]
This is a feature request relating to the [aspectratio](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/aspectratio) plugin. 

I have a horizontal layout of equal height images for which the height of the image is defined in CSS before it loads. I would like to use the apectratio plugin to define the width of the image from the calculated height using the provided aspect ratio. 

This can be done by modifying the [`addAspectRatio`](https://github.com/aFarkas/lazysizes/blob/1120b7a/plugins/aspectratio/ls.aspectratio.js#L150-L171) function to use the image height if the width is not usable. Is this something you would be interested in adding? If so I'll be happy to send a pull request your way.

**Comment by aFarkas** [comment]
yep.
