### ISSUE TITLE
aspectratio: not just for images?

### ISSUE THREAD

**Issue by neatonk** [aFarkas/lazysizes#103]
This is a feature request relating to the [aspectratio](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/aspectratio) plugin. I currently use this plugin to define the aspect ratio for images along with the standard css padding trick for iframes and other content. I'd like to extend this plugin so that it can be used with iframes and other content as well, like lazysizes. 

If this is something you're interested in adding, I'd be happy to take a stab at it.

**Comment by aFarkas** [comment]
You can try. Please work on a branch from the master

**Comment by neatonk** [comment]
Hello, I'm closing this issue, since the feature is covers has become a lower priority at work and I have not had time to work on it in my own time.
