### ISSUE TITLE
Using lazysizes' own respimg polyfill, can we leave out sizes completely?

### ISSUE THREAD

**Issue by bitinn** [aFarkas/lazysizes#105]
As far as I know `sizes` is `100vw` by default? Does the polyfill handle this scenario?

I do have `display: inline-block` set on images in most case, but not sure how efficient `data-sizes="auto"` will be. Looks like it has to read actual element width (and recursively goes up parentNode if `< 40`?).

Mixing it with `lazysizes` means browser has to do more DOM read/write batching (I would guess you have optimized that with rAF, but still, if the default case is handled, I would like to avoid it).

Apologize in adavance if I misunderstood anything.

**Comment by bitinn** [comment]
OK, done my test, works in Chrome (which natively support `w` descriptor) but not in Safari (doesn't have native support for `w`), so answer to my early question is **no** then.

But I realize in most case I might just want `data-sizes="auto"` (image grid size is defined in media query, so really has little to do with screen width).

**Comment by aFarkas** [comment]
Also note, the ``data-sizes="auto"`` feature gives you an API to set/use any size you want:

```js
document.addEventListener('lazybeforesizes', function(e){
    //calculate the size as a number
    e.detail.width =  yourCalculation(e.target) || e.detail.width;
});
```

Example to return 100vw:

```js
document.addEventListener('lazybeforesizes', function(e){
    e.detail.width =  Math.max(innerWidth, document.documentElement.clientWidth);
});
```

**Comment by bitinn** [comment]
Very cool, thx, been using it on my project and works like a charm.
