### ISSUE TITLE
Problem with noscript and AJAX

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#107]
Hi!
Not sure if this is an issue with my code or yours, but I think the latter.
When I use the noscript-plugin and fetch more markup with AJAX the content of the noscript-tag is output as text instead of HTML.
I'll attach a screenshot to avoid any misunderstandings.
You'll notice a difference when I log the content. 
I don't have trouble when not using the noscript plugin,
so it might be a combination of my code and yours resulting in the error.

Thanks!

![error](https://cloud.githubusercontent.com/assets/5993909/7907940/fa1bd518-083f-11e5-8774-f63a08ff9319.png)

**Comment by aFarkas** [comment]
I can't really reproduce your special error. All I can say, that it sometimes depends, how this noscript tag is created and due to the fact that I haven't found a way to detect it, it might be, that I can't help (in my script).

This means: I need to see, how you create and add the HTML/DOM. Can you create a simple testcase?

**Comment by JonWallsten** [comment]
I can't do a test case. It's part of a really big project. But I did investigate some more. The problem is on our side. I checked the content again, and on the second fetch I can see all the entities already! Sorry for wasting your time!

**Comment by JonWallsten** [comment]
http://stackoverflow.com/questions/828195/why-does-retreiving-html-from-inside-a-noscript-return-htmlentities

**Comment by JonWallsten** [comment]
It seems like appending the HTML with jQuery's html() leaves entities inside the noscript tag. Not sure why.

**Comment by aFarkas** [comment]
I  general, I do use "text". In case you have identified the problem you can create simple testcase.

Here is a testcase with $.append/$.html. It works:
http://jsfiddle.net/trixta/8sqpsntw/

So there must be something else.

**Comment by JonWallsten** [comment]
That's really weird! Anyway, I used the parseHTML function and removed some old code and now it seems to work! Thanks!
