### ISSUE TITLE
How to use in angular?

### ISSUE THREAD

**Issue by ZacksTsang** [aFarkas/lazysizes#108]
when use in angular, it seems not works.

**Comment by aFarkas** [comment]
Could you please provide a testcase for this? Demonstrating your problem. 

Also note: lazySizes automatically works with elements with the class ``lazyload``. In case you dynamically change the ``data-src``/``data-srcset`` attributes, you might also need to re-add the class ``lazyload`` to get it work.

**Comment by ZacksTsang** [comment]
can not go into the element of *section*

**Comment by aFarkas** [comment]
I don't understand what you mean, some code or some more explanation would be helpful.

**Comment by aFarkas** [comment]
@ZacksTsang 
I'm still not sure, what your problem is, but in case you do not (re-)add the class ``lazyload``, the following script might help:

```js
new MutationObserver( function(mutations){
	var i, len, mutation, target;
	for(i = 0, len = mutations.length; i < len; i++){
		mutation = mutations[i];
		target = mutation.target;

		if(!target.getAttribute(mutation.attributeName)){continue;}

		if(target.nodeName.toLowerCase() == 'source'){
			target = target.parentNode.querySelector('img');
		}

		if(target && target.matches('.lazyloaded, .lazyloading')){
			target.classList.remove('lazyloaded');
			target.classList.add('lazyload');
		}
	}
} ).observe( document.documentElement, { subtree: true, attributes: true, attributeFilter: ['data-src', 'data-srcset', 'data-bgset']} );
```

**Comment by aFarkas** [comment]
@ZacksTsang 
In case the script above helped, here is an improved version of it:
https://github.com/aFarkas/lazysizes/tree/master/plugins/attrchange

In case it does not help, please reopen.

**Comment by ZacksTsang** [comment]
Thanks, well done.

**Comment by codener** [comment]
It seems there now is a plugin that does the reinitialization cross-browser: https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/attrchange/

The above suggestion does not work in IE10-.
