### ISSUE TITLE
aspectratio: run autosizer after processing images

### ISSUE THREAD

**Issue by neatonk** [aFarkas/lazysizes#111]
This is a feature request for the [aspectratio](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/aspectratio) plugin. I currently use this plugin with lazysizes on image tags which include the `data-sizes="auto"` attribute. In order to ensure that the calculated value of the `sizes` attribute is updated, I call `lazySizes.autoSizer.checkElems()` in response to the window `load` event. This seems to work, but I'm not confident this handles all cases in which the `sizes` attribute might need to be updated.

It would be nice if this plugin could take care to update the `sizes` attribute by calling `lazySizes.autoSizer.updateElem()` when needed.

**Comment by aFarkas** [comment]
> This seems to work, but I'm not confident this handles all cases in which the sizes attribute might need to be updated.

I would need something concrete here. Can you give me a testcase?

**Comment by aFarkas** [comment]
Please reopen, if you can give me a tescase or something more concrete, where it does not work for you.
