### ISSUE TITLE
Is the respimage plugin still required if i am also using respimage? (and will loading both conflict)

### ISSUE THREAD

**Issue by deantpt** [aFarkas/lazysizes#117]
Hello, i'm currently using respimage to polyfill srcset and am now looking to add lazy loading support for other images, in this case, can i use both together and should i\do i still need the respimage plugin?

i notice the plugin code checks for respimage on line 18 and returns, so i'm guessing both arent required?

Thanks in advance - lazysizes seems great so far!

**Comment by aFarkas** [comment]
In case you are using either the respimage or the picturefill polyfill, you **won't need** the plugin (It is basically a subset of a polyfill).

Please re-open if it is not clear.

**Comment by deantpt** [comment]
Appreciate the quick response!

**Comment by deantpt** [comment]
Just a very quick question on this - if i have full respimage and lazysizes loaded (without plugin) will sizes auto still work (just for lazyloaded images)?

**Comment by aFarkas** [comment]
Yes, this is a base feature of lazysizes. respimage polyfill or the respimage plugin are really just full or partial polyfills and we want the data-sizes="auto" feature to work everywhere (without polyfill).
