### ISSUE TITLE
Isotope + Lazysizes - Help with example 

### ISSUE THREAD

**Issue by HybridSolutions** [aFarkas/lazysizes#118]
Hi Alexander,

I need some help again. :)
I'm using Isotope and since I'm already using your plugin for lazy loading other images, tried to apply it to Isotope as well. Checked your demo at http://codepen.io/aFarkas/pen/VYGvde but I noticed that all your images have the same size and you're specifying 165% of padding-top for items and 60% padding for items:before. How did you get to these numbers and how would you code this assuming you don't know the size of the images you'll be loading and that they can even have different sizes.

I have your example loading other images with different sizes but since you have 100% on width and height, they get deformed. If It's easier for you to look at it, you can DL a zip file from http://gofile.me/2B2vF/ZWdPUVEN

Hope you can help me on this!
Hugo

**Comment by aFarkas** [comment]
In short you can't, isotope needs to know the final dimensions of those boxes.

I have written something about this:
https://github.com/aFarkas/lazysizes#user-content-specify-dimensions

Here is a fiddle which tries to workaround:
http://codepen.io/aFarkas/pen/JdrXjm

But I strongly recommend that you specify height and width, it is actually quite easy (This is something the backend can do for you. You don't need to use :after/:before, the padding-top/padding-bottom trick can also be used with new elements.)

**Comment by HybridSolutions** [comment]
Hi Alexander,

tries to workaround?? It worked perfectly! :) Even works after adapting your code to work with Bootstrap 3! If you want i can send you the code. You should have both examples along with the plugin code. I need to ask you another thing. Using your example, how can have the images appear with a fade out? Tried to use .lazyloading and .lazyloaded classes but didn't work.

Once again, Thank you!
