### ISSUE TITLE
Images load but not lazily?

### ISSUE THREAD

**Issue by brendanfalkowski** [aFarkas/lazysizes#120]
I setup this HTML:

```html
<img class="lazyload" data-src="http://placehold.it/1400x900/" />
<br>
<img class="lazyload" data-src="http://placehold.it/1400x950/" />
<br>
<img class="lazyload" data-src="http://placehold.it/1400x1930/" />
<br>
<img class="lazyload" data-src="http://placehold.it/1400x940/" />
<br>
<img class="lazyload" data-src="http://placehold.it/1400x2940/" />
<br>
<img class="lazyload" data-src="http://placehold.it/1400x3940/" />
```

Watching Chrome's network tab, everything loads immediately. Shouldn't the assets way off screen be delayed?

**Comment by raywongjr** [comment]
I'm assuming this is your exact HTML, and you do not have any styles applied to the markup. 

If that's the case, the `<img>`'s don't initially know the size of the source, so before the images are loaded, they all appear at the very top of the page. Lazysizes considers them to be "in view" and lazy loads all the images.

You could define the sizes of the images with css, or simply something like:
`<img class="lazyload" data-src="http://placehold.it/1400x900/" width="1400" height="900" />`

This will allow the browser to render each `<img>` with the correct size on initial page load. Hope this helps.

**Comment by brendanfalkowski** [comment]
@raywongjr Thanks that does appear to be what's happening.

I tried integrating into a more complex example first (carousel) and it wasn't working, so I added those images at the end of the page (roughly 900px from top) expecting them to not load being way off screen. But I guess without dimensions they were within the threshold to load.

Adding an explicit width/height does trigger lazyloading properly, but the site is responsive so dimensions cannot be set on the `<img>` tags because they aspect ratio won't be maintained during scaling.

Looks like there isn't a way to use this if the image may begin within the viewport, even if it's pushed outside it as content loads+renders.

**Comment by aFarkas** [comment]
@brendanfalkowski 
I wrote something about this in the documentation:
https://github.com/aFarkas/lazysizes/tree/master#specify-dimensions

Here is an example using the aspect-ration CSS technique:
http://codepen.io/aFarkas/pen/VYGvde

And here is an example using a min-height workaround:
http://codepen.io/aFarkas/pen/JdrXjm

Please close if this helps.

**Comment by brendanfalkowski** [comment]
Thanks @aFarkas, closing now. Getting there with the aspect ratio plugin because we're using `<picture>` for art direction: https://github.com/aFarkas/lazysizes/tree/master/plugins/aspectratio
