### ISSUE TITLE
bgset width descriptor calculation in chrome simulator

### ISSUE THREAD

**Issue by bitinn** [aFarkas/lazysizes#122]
This seem like a bug with bgset plugin, in my client js I have got:

```
require('lazysizes/plugins/respimg/ls.respimg.js');
require('lazysizes/plugins/bgset/ls.bgset.js');
require('lazysizes');
```

And my html looks like this:

```
<div data-bgset="https://local.dev/images/header-320.jpg 320w, https://local.dev/images/header-640.jpg 640w, https://local.dev/images/header-960.jpg 960w, https://local.dev/images/header-1280.jpg 1280w" data-sizes="auto" style="background-image: url(https://local.dev/images/header-320.jpg);" class="page-heading lazyload"> content ... </div>
```

After loading `header-320.jpg`, `lazysizes` set background image to `header-1280.jpg` when simulating iPhone 5 in chrome (on real device it loads `header-640.jpg` as expected). Detected `sizes` for my div is set correctly at `320px`.

I didn't notice this problem with img tag and `data-src`, so probably a plugin related issue?

**Comment by bitinn** [comment]
Observe the same problem in your demo (2nd one, resolution switching only), largest image with w1920 always chosen, don't need simulation, just resize the window with dev tool can see this problem.

http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

**Comment by aFarkas** [comment]
This is not a bug, it is a feature. Chrome detects, that the largest image is already in cache and simply takes this image. If you want to test disable your cache.

**Comment by bitinn** [comment]
@aFarkas confirmed working uncached, that's an optimization I didn't thought of.

So is it a chrome thing or a lazysizes thing? I assume Chrome tell lazysizes which file is available? Unlike  `srcset` Chrome doesn't actually select the file itself right?

**Comment by bitinn** [comment]
wait I got it now, bgset is loading the image through an `img` element, so all the `srcset` stuff applies.
