### ISSUE TITLE
data-include and js-loading / js-calls

### ISSUE THREAD

**Issue by jochenthomas** [aFarkas/lazysizes#125]
Hi,
again I need and would like to get a better understanding about the combination of data-include and javascript-initializings.

Example:
An index.html will load e.g. a jquery.js and a slider.js
After full load the page starts with rendering the first slider.
Below are some lazyloaded content areas, e.g. 
div class="lazyload" data-include="content/file05.html" data-lazyqueue="05"  /div

File05.html contains as well a second slider, which is using the same slider.js / libraries + jquery.

As far as I understand the second slider will ONLY start if I put the jquery.js and the slider.js again on the file05.html.
It's like a complete new page, like an iframe.

Questions:
Is this a correct understanding?
Is there a way to avoid loading again (...and again) the same .js files?
Is there a way to create a "call-trough", so the already loaded js-file/function can be called or initialized from the later inview-loaded lazysize files?
My aim is to avoid long loading times during initializing of the page but as well later during the lasysize loadings.

To make it more clear: Let's say the slider.js has a function(forward), how I can call this function on the file05.html (if I don't want to load jqury.js and slider.js again)?

Thanks for clarifying :-)

**Comment by aFarkas** [comment]
> Is this a correct understanding?

No.

> Is there a way to avoid loading again (...and again) the same .js files?

Yes.

To be honest everything is explained in detail on the plugin page. In case this isn't clear it would be great, if you would help to improve the documentation. 

I just updated the plunk: http://embed.plnkr.co/9G5Cb7/preview

On slide5 you will now see a magic button, that is initialized.

While there are multiple ways to do this (see documentation for ``lazyincluded`` event and documentation for special AMD/system Module features), here is an example using the ``lazyincluded``event:

```js
(function(){
	'use strict';
	var init = function(context){
		//magic slider
		$('#fullpage', context).slider();

		//magic button
		$('button.alert', context)
			.css('textDecoration', 'underline')
			.on('click', function(){
				alert('yeah, this is dynamic');
			})
		;
	};

	$(function(){
		init(document);
		$(document).on('lazyincluded', function(e){
			init(e.target);
		});
	});
})();
```

**Comment by jochenthomas** [comment]
Hi,
sorry for the delayed answer - busy week ;-)
And *thanks* for the answer - will check it ASAP. 
Was reading already, but I am not doing js only...
