### ISSUE TITLE
Responsive img

### ISSUE THREAD

**Issue by WillyBrownHair** [aFarkas/lazysizes#126]
Hi, 
I use your wonderful plugin in many project. 
My question is about the syntax og responsive image.

Currently, my image looks like this : 

    <img src="pictest-landscape.jpg" class=" lazyautosizes lazyloaded" 
    data-src="pictest-landscape.jpg" data-sizes="auto" 
    data-srcset="pictest-landscape-240.jpg 250w,
    pictest-landscape-360.jpg 360w,
    pictest-landscape-480.jpg 480w, 
    pictest-landscape-720.jpg 720w,
    pictest-landscape-768.jpg 768w,
    pictest-landscape-960.jpg 960w" 
    sizes="auto">

In your documentation, it seem's to be enought. The problem is, the right image is not always load with Chrome and Safari. FireFox is ok even if I rezise the window.

Is it because I don't use `<picture>` and `<source>` attribute ? 

Thanks for your help.

**Comment by aFarkas** [comment]
This isn't enough information for me. 

Check the calculated ``sizes`` value. Is this value correct? (I.e.: Does it match the width of your image?)

In general: I will need a testcase or the link to your project. With the following information. What image is loaded and what image do you expect to be loaded?

**Comment by WillyBrownHair** [comment]
Actually, the calculated `size`change fine when I rezise the window but the pic isn't always changing for the smaller I need. The bigest appear. When I refresh the page after first load, my bigest img appear too.

first load : small images are load : (number in pic is the width corresponding to this one)
![capture d ecran 2015-07-16 a 13 10 29](https://cloud.githubusercontent.com/assets/7604357/8721626/76105578-2bbc-11e5-8228-b4ee0be9489f.png)

when I reload my page or after ajax call content : 
![capture d ecran 2015-07-16 a 13 11 16](https://cloud.githubusercontent.com/assets/7604357/8721634/88ded24c-2bbc-11e5-8294-ba95913f3710.png)

And some time the version of image load is changing :
![capture d ecran 2015-07-16 a 13 10 47](https://cloud.githubusercontent.com/assets/7604357/8721653/cc7b7c6c-2bbc-11e5-92d3-b30326321d02.png)

My question : 
- I feel after images were caching in my browser, the bigest one is always loaded. Is it possible ? 
- I remove `src` attribute with jquery. Maybe I have to put a small img instead ?

Thanks !

**Comment by aFarkas** [comment]
srcset gives the browser the freedom to choose an image candidate. In case the browser has a larger image candidate already in cache, the browser might take this larger image. 

Due to the fact, that ``srcset`` is all about resolution switching, it shouldn't bother you.

In case you want to do art direction: Serving different images depending your layout, you should use the ``picture`` element.  Note: Of course you can mix art direction with resolution switching.

So yes, cache might change what image gets chosen.

**Comment by WillyBrownHair** [comment]
Ok !
I understand what's append if the caching img is showing. The browser caching largest img because in my exemple, all images you can see are the same ! so The first on"960" of the page (above the two "480") is loaded and caching, the others below (who are the same img) were loaded in "960" after refresh my page.

Thanks you very much !

**Comment by WillyBrownHair** [comment]
Last question : Is it necessary to add lazyautosizes class ?

**Comment by aFarkas** [comment]
You should not add the class ``lazyautosizes``. This class is automatically added by JS, if you use the ``data-sizes="auto"`` feature, after the images are transformed/unveiled.

**Comment by WillyBrownHair** [comment]
ok thank you.
