### ISSUE TITLE
Lazysizes plugin integration 

### ISSUE THREAD

**Issue by WillyBrownHair** [aFarkas/lazysizes#127]
I have a new issue with my integration.
I try to use the plugin only with jquery. The problem is that all originals images are loaded when the page is loading. After that, responsive images are lazy-loaded normally when I scroll my page.

My reflection : 

* I replace src attribute with a small image - but browser keeps to load original images before change src with this small image.
* all images aren't display in the viewport when the page load because I use the padding ratio trick for each of them.
* I tried to move my script in the header of the page, but nothing change.
* I run my script in a  `$('document).ready` before lazysizes script

Maybe this isn't possible only this Jquery ? Do I need to rewrite my script with a server-side language like php ? 

here my script :

    //lazy init
    window.lazySizesConfig = window.lazySizesConfig || {};
    lazySizesConfig.loadMode = 2;   
    lazySizesConfig.preloadAfterLoad = false;
    $('img').addClass('lazyload');

    $("img.lazyload").each(function() { 
    var src = $(this).attr('src').replace(/\.jpg$/i, "");
    $(this).attr("data-sizes","auto"); 
    $(this).attr("data-srcset", 
      src + '-240.jpg 240w,' + 
      src + '-360.jpg 360w,' + 
      src + '-480.jpg 480w, ' + 
      src + '-720.jpg 720w,' + 
      src + '-768.jpg 768w,' + 
      src + '-960.jpg 960w,' + 
      src + '-1280.jpg 1280w'
    ); 
    $(this).attr(
       "src",
       "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
    );
    });

**Comment by aFarkas** [comment]
> Maybe this isn't possible only this Jquery ? Do I need to rewrite my script with a server-side language like php ?

It depends: I don't know what you want to achieve in general. What I can say for sure, you will never get image request aborted in Safari.

> The problem is that all originals images are loaded when the page is loading.

Normally the so called preload parser gets all image sources and starts to download those images. This happens before scripts and stylesheets are loaded, parsed and evaluated. It actually also happens before even the DOM is parsed. Therefore you won't be able to remove these image requests entirely with JS and yes you need to render the HTML without ``src`` to get this done. 

However Chrome, IE and Firefox 36+ do support aborting an already started image download (This means it doesn't work in FF 35- and it won't work in any Safari/Webkit version). But this needs to be done quickly, you can't wait for the dom ready event for this.

You can try this by doing the following. Move jquery and all your JS at the bottom of your page (or add the ``async`` and then include the following script inline (not in an external js file!), after all images but **before** any other JS file, that has no ``async`` attribute:

```html
<script>
[].slice.call(document.querySelectorAll('img[src]')).forEach(function(elem){
	var src = elem.src.replace(/\.jpg$/i, "");
	elem.setAttribute('data-sizes', 'auto');
	elem.setAttribute('data-srcset', src + '-240.jpg 240w,' +
		src + '-360.jpg 360w,' +
		src + '-480.jpg 480w, ' +
		src + '-720.jpg 720w,' +
		src + '-768.jpg 768w,' +
		src + '-960.jpg 960w,' +
		src + '-1280.jpg 1280w');

	elem.className += ' lazyload';

	if(!elem.complete){
		elem.removeAttribute('src');
	}
});
</script>
````
With this approach you will see that some images are fully loaded (2-6), but most are aborted (you will still see them in the network panel, but the downloaded data/size is (much) smaller than the actual size of the image).

Please close if this answers your question.

**Comment by WillyBrownHair** [comment]
Ok, it's what I thought... the right way of this integration is to use a server-side language. Do you have a link to a tutorial for a php integration of lazysizes ? 

Thanks a lot.
