### ISSUE TITLE
Does it make sense to mix srcset with data-srcset?

### ISSUE THREAD

**Issue by bitinn** [aFarkas/lazysizes#128]
Because we async load javascript, our hero image, which is currently using `data-srcset` with LQIP, will flash a bit as `lazysizes` kicks in and load the hi-res image. This happens even when both images are in browser cache.

Given `srcset` and `w` descriptor are getting wider support, I am thinking whether I should add both `srcset` and `data-srcset` to my hero image. So that a browser with native srcset support won't see the flash but instead load the hi-res image from cache.

Is this supported by `lazysizes`? I am basically using it as a polyfill (for this instance, my other image still default to using only `data-srcset`)

**Comment by aFarkas** [comment]
Yes, you should be able to do this. But this means, that you can't use features, that need to alter the DOM before the source selection is done by the browser (for example: the ``data-sizes="auto"`` or ``data-optimumx`` features).

Also as I said in the other issue: If you have one crucial image (always above the fold), it absolutely makes sense to load it with the preparser and not with lazyload.

In case the LQIP source is more distracting than useful, you should also consider to remove it entirely.

**Comment by bitinn** [comment]
Thanks, actually I forget to add the progressive plugin (my images progressive JPEG), with that plugin the flash is a lot less noticeable.

> it absolutely makes sense to load it with the preparser and not with lazyload.

For prosperity, may I ask what do you mean by preparser in this context?

**Comment by aFarkas** [comment]
> For prosperity, may I ask what do you mean by preparser in this context?

In general use ``src``/``srcset`` instead of ``data-*``.

For what I mean:
http://calendar.perfplanet.com/2013/big-bad-preloader/

**Comment by bitinn** [comment]
Got it, cheers!
