### ISSUE TITLE
Progressive plugin behaviors seem weird

### ISSUE THREAD

**Issue by bitinn** [aFarkas/lazysizes#129]
Apologize for another question, this is what I am seeing:

http://www.webpagetest.org/video/compare.php?tests=150722_46_V54-r%3A2-c%3A0&thumbSize=100&ival=1000&end=visual

When progressive plugin kicks in, the LQIP (using `src`) actually got removed and then replaced with the Hi-Res version. The flash is very noticeable on slow connection (see the thumbnails and visual progress)

I can reproduce it using chrome dev tool to throttle network speed.

Any idea?

**Comment by bitinn** [comment]
also source

```html
<div class="image"><img data-srcset="https://rubu-maihq.netdna-ssl.com/images/header-320.jpg?r2015072201 320w, https://rubu-maihq.netdna-ssl.com/images/header-640.jpg?r2015072201 640w, https://rubu-maihq.netdna-ssl.com/images/header-960.jpg?r2015072201 960w, https://rubu-maihq.netdna-ssl.com/images/header-1280.jpg?r2015072201 1280w" data-sizes="auto" role="presentation" src="https://rubu-maihq.netdna-ssl.com/images/header-320.jpg?r2015072201" alt="" class="lazyload"></div>
```

**Comment by aFarkas** [comment]
At this point I can only advice to either remove the progressive plugin or to remove the LQIP ``src`` (or both).

There is no event or something similar, that tells us that the image is progressively rendered.

**Comment by aFarkas** [comment]
@bitinn 
Are your [image dimensions specified](https://github.com/aFarkas/lazysizes#user-content-specify-dimensions)?

@jschroeter 
Do you have any other ideas?

**Comment by bitinn** [comment]
The container has width 100% and height 130px, image has 100% width and height auto. Yeah, could be CSS related. The `sizes` is calculated correctly though.

I can see the background-image is applied using a throttled network speed. But still have to figure out why it flash when starting to load hi-res image. Will report back...

**Comment by bitinn** [comment]
Yep looks like `height: auto` is the poison here. Browser will show no image even when background-image is set in this case. With a defined height the blank state goes away.

**Comment by bitinn** [comment]
For prosperity, as I don't know the current height for image but do know the ratio of my image, using the `vw` unit as height solve my issue without needing to set a fixed height :)

(I can't use percentage height as my image doesn't fit exactly into the container, as my container ratio do change)
