### ISSUE TITLE
Finished loading event

### ISSUE THREAD

**Issue by prohtex** [aFarkas/lazysizes#131]
I have a preload script that is preventing lazysizes from loading its thumbnails. I need to know when lazysizes has finished loading all currently visible elements, so I can fire my preload. Is there a way to do with without polling the DOM for 'lazyloaded' elements?

**Comment by aFarkas** [comment]
Can't you simply use the load-after-onload pattern?

```js
window.addEventListener('load', startPreload);
```

This should be the time, when all cruical images are loaded. In case you want to preload a lot of assets (8+), that are used sometimes in the future, you should also do this in a queue (of 2-4 assets at a time) instead of loading them once.

**Comment by prohtex** [comment]
Well, I have a lot of content dynamically appended, so this event doesn't really apply. I also notice that the onload event fires way before lazysizes finishes loading its loading - usually before the page is even rendered!

**Comment by aFarkas** [comment]
Can you give me a link to your site or mail me the prototype?

**Comment by aFarkas** [comment]
Some useful information.
>  I also notice that the onload event fires way before lazysizes finishes loading its loading...

In case lazySizes starts to load images before the onload event. All images that are loaded after the onload event are not inview (they are preloaded). So you should be able to use the `onload` event and share the download slots/queue with lazysizes.

But I might be able to help more, if I can see your page.

**Comment by aFarkas** [comment]
Please re-open with a link to a testcase or the site, if this didn't help.

**Comment by prohtex** [comment]
Hi Alex,
I implemented a better preloading queue which resolved the issue. Thanks so much for your help.
