### ISSUE TITLE
Skip images with srcset of certain class

### ISSUE THREAD

**Issue by syropian** [aFarkas/lazysizes#132]
Is there a way to tell lazysizes to leave a subset of images alone, and let picturefill do its thing normally? There are spots where we want to lazy load, and others we don't.

**Comment by aFarkas** [comment]
If you don't want lazyload you should switch ``data-srcset`` to ``srcset``.

You can also add the class ``lazypreload`` if this helps.

**Comment by syropian** [comment]
Thank you very much!
