### ISSUE TITLE
No Image Displayed In Safari 6 Using respimg 

### ISSUE THREAD

**Issue by Undistraction** [aFarkas/lazysizes#134]
I'm using Lazysizes with the respimg plugin with the following markup pattern:

```
<img 
  alt="Quidem Nihil Qui Rerum Et Delectus Modi Corrupti Id Omnis In Repellat Quo Aut"   
  class="ResponsiveImage   lazyloaded"
  data-parent-fit="contain"
  src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
  srcset="http://s3-eu-west-1.amazonaws.com/unwalked-com-development/image_assets/placeholder_02-small-ab9621f318b9efcc9320954c85c81a63.jpg 300w 200h, 
          http://s3-eu-west-1.amazonaws.com/unwalked-com-development/image_assets/placeholder_02-medium-ab9621f318b9efcc9320954c85c81a63.jpg 610w 406h, 
          http://s3-eu-west-1.amazonaws.com/unwalked-com-development/image_assets/placeholder_02-large-ab9621f318b9efcc9320954c85c81a63.jpg 1230w 820h">
```

Whilst this works fine in Chrome and Firefox, No image is displayed in Safari. There are no JS errors, with Safari reporting:

> Failed to load resource: the server responded with a status of 404 (Not Found) http://example.com/images/img

You can see this live [here](http://unwalked-v2-staging.herokuapp.com/)

If I switch from using `srcset` to using `data-srcset`, the images load fine, so I'm assuming the issue is with the plugin.

**Comment by aFarkas** [comment]
The respimage polyfill plugin is intended to be used with `data-srcset` not `srcset`only. I thought this was clear, but I realize now, that I should improve the documentation. If you want a full polyfill you can try picturefill 3.0 or respimage.

The 404 error comes from the fact, that your `src` attribute has a wrong URL path.

Your intended demo isn't working fine in Chrome or Firefox either. For the `data-parent-fit="contain"` to kick in, you need to use also `data-sizes="auto"` **and** `data-srcset` instead of `srcset`.

**Comment by aFarkas** [comment]
I tried to fix the documentation. I also changed the code so that in case there is neither a `data-sizes` nor `sizes` at the element, but a `data-parent-fit`, I will automatically add `data-sizes="auto"`

**Comment by Undistraction** [comment]
Thanks. So to clarify:

> The respimage polyfill plugin is intended to be used with data-srcset not srcset only. I thought this was clear, but I realize now, that I should improve the documentation. If you want a full polyfill you can try picturefill 3.0 or respimage.

1. The plugin will only work with `data-srcset` - it won't use the `srcset` attribute if present?
2. Can should `data-srcset` be used to supplement `srcset` or is it intended that it is used only when there is no `srcset` attribute.
3. If I switch to using respimage instead of the plugin, does this mean I can only declare a `srcset` attribute (and skip declaring a `data-srcset` attribute?

> The 404 error comes from the fact, that your src attribute has a wrong URL path.

You're right, just made some changes and broke it.

> Your intended demo isn't working fine in Chrome or Firefox either. For the data-parent-fit="contain" to kick in, you need to use also data-sizes="auto" and data-srcset instead of srcset.

I removed the `data-sizes="auto" attribute because of this line from the docs:

> In case you use the "unknown intrinsic ratio pattern" and the width of the loaded image will not approximately match the width of its container the data-sizes="auto" feature should not be used. 

I thought this meant that if the image was not  (or might not be) of the same aspect=ratio as the intrinsic container, the auto feature should be removed. 

I've fixed the [demo](http://unwalked-v2-staging.herokuapp.com/) for anyone interested.

**Comment by aFarkas** [comment]
> The plugin will only work with data-srcset - it won't use the srcset attribute if present?

Yes.

> Can should data-srcset be used to supplement srcset.

Yes, you can use as supplement. But then you need to define the ``sizes`` attribute.

> If I switch to using respimage instead of the plugin, does this mean I can only declare a srcset

Yes, but this means, you don't need lazysizes at all.

> I thought this meant that if the image was not (or might not be) of the same aspect=ratio as the intrinsic container

No, what I was trying to say. `data-sizes="auto"` does not work correctly in that case, unless you additionally use the `data-parent-fit` extension.

Could you help me to clarify this sentence, I'm not so good in english.

What is important. If you use `srcset` instead of `data-srcset`, all this automatic size generating (data-sizes="auto"` with and without `data-parent-fit`) can't work, because the browser already selects images to download before JS can write the corresponding `sizes` attribute. This means in that case you must set the right `sizes` attribute yourself.

**Comment by Undistraction** [comment]
> No, what I was trying to say. data-sizes="auto" does not work correctly in that case, unless you additionally use the data-parent-fit extension. Could you help me to clarify this sentence, I'm not so good in english.

OK. That makes sense, but was definitely not clear from the docs. I will take a run at improving that part of the docs. In fact, looking at how the `parent-fit` extension is working, I think there is a bug with how it handles images that don't have `width: 100%`. In some case, if the image is smaller than the container it doesn't recalculate the image's fit, leaving the image narrower than its parent. I will open a separate issue for this.

> What is important. If you use srcset instead of data-srcset, all this automatic size generating (data-sizes="auto" with and without data-parent-fit) can't work, because the browser already selects images to download before JS can write the corresponding sizes attribute. This means in that case you must set the right sizes attribute yourself.

This really helps clarify things for me, and I don't think this is clear form the docs. From the `README`:

> For full cross browser responsive image support you must either use a polyfill like respimage or picturefill or use the extreme lightweight partial respimg polyfill plugin or the responsive image on demand plugin. Alternatively you can simply define a fallback src via the data-src attribute.

This makes it sound like lazysizes needs to be used ontop of either Picturefill or respimage - that one of those needs to be used alongside lazysizes for 'full cross browser image support'. The description for the respimage polyfill  plugin then says – 'The respimg polyfill plugin is an extreme lightweight alternate polyfill for the most important subsets of responsive images (srcset and picture).'  – which makes it sound like it does the same thing, but using only the subset of functionality needed by lazysizes. My incorrect assumption was that as a polyfill, it would add in functionality only in browsers that needed it, so I assumed that I could use `srcset`, and that it would make `srcset` functional in browsers that don't support it (like Picturefill). I then assumed lazysizes would use `srcset` if had been declared, or `data-srcset` if it hadn't. 

I think that it needs to made clear in the docs that lazysizes (with or without the respimg plugin) does not polyfill browsers, but adds *srcset-like* functionality (with some great extras) by using a *srcset-like* syntax. I think explaining this in the intro would make it much easier to understand the functionality offered by this (great) lib.
