### ISSUE TITLE
Parent Fit Extension Fails Fit Image To Container

### ISSUE THREAD

**Issue by Undistraction** [aFarkas/lazysizes#137]
I've noticed that the logic in the parent fit extension seems to expect that an image has had its width set in the CSS. In situations (using `fit="contain"`) where an image is smaller than its container but hasn't had a (100%) percentage width set on it, it will not be fitted to its container.

It comes down to this line of logic in `ls.parent-fit.js` (Line 83): 

```
		if(height > 40 && (displayRatio =  width / height) && ((fit == 'cover' && displayRatio < imageRatio) || (fit == 'contain' && displayRatio > imageRatio))){
					retWidth = width * (imageRatio / displayRatio);
				}
```

If an image has no width set on it (which is necessary in situations where varying sized images must be fitted to a container with an intrinsic ratio), and the image has an aspect ratio (`imageRatio`) that is smaller than the container's aspect ratio (`displayRatio`) and the image is smaller than its container (perhaps because the window has just been maximised), the calculation and assignment to `retWidth` never happens, even though the image does still need to be fitted. Without a 100% width it will not naturally fill its container, and in this situation, giving the image a 100% width would mean portrait images would be stretched to fit.

This can clearly be seen [here](http://unwalked-v2-staging.herokuapp.com/galleries) when the browser is resized upwards (it is intermittent though). By removing the check on the aspect ratio, this logic runs and the images are upsized correctly:

```
		if(height > 40 && (displayRatio =  width / height) && ((fit == 'cover') || (fit == 'contain' && displayRatio > imageRatio))){
					retWidth = width * (imageRatio / displayRatio);
				}
```

![cap copy](https://cloud.githubusercontent.com/assets/161489/9057761/227afa8a-3a94-11e5-9a18-41ff6656d796.png)

**Comment by aFarkas** [comment]
I never thought about the use case to not use CSS to style image dimension at all and only relie on the intrinsic sizing. 

I fixed this now, but be aware, there were some Chrome bugs related to `sizes` mutation which are fixed in Canary.

**Comment by Undistraction** [comment]
@aFarkas  Thanks for fixing that. Can you be slightly more specific on the effect of these bugs? Does this mean the calculations will not be accurate / not be carried out when needed in Chrome? Is there an alternative?

**Comment by aFarkas** [comment]
Older Chrome only evaluates `sizes` during resize events. It can happen, that the last set sizes value is added after a resize and therefore the image will be slightly too small.

Workaround do resize either pure with CSS or additionally hook into the lazybeforesizes event and also set `styles.width`:

```js
addEventListener('lazybeforesizes', function(e){
    e.target.styles.width = e.detail.width + 'px';
});
