### ISSUE TITLE
Safari 8- support of srcset

### ISSUE THREAD

**Issue by crstauf** [aFarkas/lazysizes#140]
http://caniuse.com/#search=srcset
CodePen: http://codepen.io/crstauf/pen/VLRYve (works in Chrome, not Safari)

If you don't specify a `data-src` attribute, and only use `data-srcset`, Safari (v8 and lower) shows no image at all. Is it suggested to use both `data-src` and `data-srcset`? Will they conflict in any way?? In an effort to keep the code as short and clean as possible, I'm currently only using `data-src` if there's only one size for the image, otherwise, I use `data-srcset` with all image sizes listed, with no `data-src`.

What's the suggestion here?

**Comment by messenjer** [comment]
For Safari and others browsers without srcset support you must use a polyfill, see the Readme https://github.com/aFarkas/lazysizes/blob/gh-pages/README.md#about-responsive-image-support-picture-andor-srcset

**Comment by crstauf** [comment]
ahhhh, thank you. :-)

**Comment by aFarkas** [comment]
I think this is clarified now. Basically you have two options:

1. Use a polyfill
2. Use an additional fallback `data-src` in conjunction with your `data-srcset`
