### ISSUE TITLE
have you considered unloading images no longer on screen?

### ISSUE THREAD

**Issue by doronfeldman** [aFarkas/lazysizes#141]
A feature request, maybe as a plugin

for example, https://github.com/toddmotto/echo have this feature,
this seems especially useful for mobile development

**Comment by aFarkas** [comment]
Nice Feature.  Will do but will take two weeks.

**Comment by aFarkas** [comment]
Just added the plugin. It should work fine. But needs some testing especially if it is used with other plugin combinations (optimumx, bgset, attrchange for example) and more documentation. 

But if you want you can already play with it.

**Comment by aFarkas** [comment]
This should work now:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unload

**Comment by doronfeldman** [comment]
Thank you, love the new feature, already using it
