### ISSUE TITLE
lazybeforeunveil not firing on all images?

### ISSUE THREAD

**Issue by syropian** [aFarkas/lazysizes#143]
So, I'm running into a bit of a weird issue. I'm relying on hiding a certain element within the image's container when each image has lazyloaded. For some reason, `lazybeforeunveil` is only firing on elements further down. Everything is lazyloading properly, but the actual event is only firing for certain elements. [See gif](http://d.pr/i/1dufJ)

You can see the images with spinners didn't fire a `lazybeforeunveil` event, but the ones without the spinner did.

**Edit:** The more I shrink my viewport the more images fire the event properly. Weird.

**Comment by aFarkas** [comment]
The event is fired just fine. It is just fired before you have started to listen to this event. You have multiple options here. 1. Use event delegation and bind your listener right away. ( do not add it into dom ready event). 2. Query for .lazyloading/.lazyloaded elements to find elements that are already loading. 3. Don't use js for spinners at all. You can use the classes.


Also the lazybeforeunveil event should fire before the image is actually visible to the user. It would make more sense to wait for the load event.
