### ISSUE TITLE
lazySizesConfig.srcset not working

### ISSUE THREAD

**Issue by petulla** [aFarkas/lazysizes#144]
hi

I am trying to setup my images like this, with two possible srcsets:

```
<img data-sizes="auto" data-srcset="./photos/se/responsive/min/image-10-600.jpg 300w,
                              ./photos/se/responsive/image-10-1000.jpg 600w,
                              ./photos/se/responsive/image-10-1200.jpg 800w" 

                              data-webpsrcset="./photos/se/responsive/webp/min/image-10-600.jpg 300w,
                              ./photos/se/responsive/webp/image-10-1000.jpg 600w,
                              ./photos/se/responsive/webp/image-10-1200.jpg 800w"

                               class="photo-3-2-one lazyload full-width">
```

I then have a test for webp support:
```
    if (webpYN) {
       window.lazySizesConfig.srcset = "data-webpsrcset";
      }
```

lazysizes still falls back on `data-srcset` though. Even if I remove the `data-srcset` attr from the image, lazysizes still ignores my window.lazySizesConfig setting.

 I'm testing the conditions prior to loading the library loading. Is there an easy fix?

**Comment by aFarkas** [comment]
You should use the picture element and add a type attribute to your source element. This way you can load lazysizes right away and your inview images will be loaded much faster.

About your specific problem: this is an documentation error. The option is called srcsetAttr not srcset.
