### ISSUE TITLE
<picture> support

### ISSUE THREAD

**Issue by petulla** [aFarkas/lazysizes#146]
I am trying to use the `picture` tag to display images responsively.

This is my implementation:

```
<picture>
                <!--[if IE 9]><video style="display: none"><![endif]-->
                <source type="image/webp" data-sizes="auto" 
                   data-srcset="./photos/se/responsive/webp/min/image-1-600.webp 500w, 
                   ./photos/se/responsive/webp/min/image-1-1000.webp 750w,
                   ./photos/se/responsive/webp/min/image-1-1200.webp 1000w" 
                    class="photo-3-3-one lazyload full-width">
                  <!--[if IE 9]></video><![endif]-->
                 <img data-sizes="auto"
                  data-srcset="./photos/se/responsive/min/image-1-600.jpg 300w,
                                ./photos/se/responsive/min/image-1-1000.jpg 600w,
                                ./photos/se/responsive/min/image-1-1200.jpg 800w" 
                  class="lazyload photo-3-3-one full-width" alt="">
              </picture>
```

In this implementation, the height of the webp images is always `0`. The images meant not to be loaded aren't shown in network traffic, but are nonetheless visible in inspector and have the appropriate height/width.

What is going wrong here?

**Comment by aFarkas** [comment]
I assume that everything is working fine. Your expectation is just wrong. The picture element associates  source elements with the img element. The img element is always the layout element and used to display the selected src no matter which source was chosen by the browser. This means that you don't need to add any style specfic classes to the source element and also no lazyload class.
