### ISSUE TITLE
IE11 image not loading

### ISSUE THREAD

**Issue by ajmerainfo** [aFarkas/lazysizes#148]
Hi,

I use below code and image is not loading on IE11.
```
<img src="images/blank.gif" data-srcset="images/work/qe-sm.jpg 500w, images/work/qe.jpg 1024w" class="lazyload" alt="qe" />
```

It's work if I use data-src and image loading perfectly fine. But I want to use two different version image for mobile and desktop.

Thanks in advance for help.

**Comment by aFarkas** [comment]
You might need to use a polyfill or add a data-src as fallback. Read here: https://github.com/aFarkas/lazysizes/blob/gh-pages/README.md#about-responsive-image-support-picture-andor-srcset

**Comment by ajmerainfo** [comment]
Thank you so much. 
I use "plugins/respimg/ls.respimg.min.js" and it's working. 
I like also idea about use fallback "data-src" it's work great.
