### ISSUE TITLE
Question regarding IE8

### ISSUE THREAD

**Issue by fnagel** [aFarkas/lazysizes#149]
After reading the documentation and some of the issues already posted here I'm still not sure if with Picturefill and MatchMedia available lazySizes with srcset should work for IE8?

Using following setup: 

````
<noscript>
	<img src="486c8d4f4b.jpg" >
</noscript>
<img data-sizes="auto" data-srcset="486c8d4f4b.jpg 1024w,e57d541ce2.jpg 700w,2d5725a18a.jpg 1400w" src="blank.gif">
````

**Comment by aFarkas** [comment]
Hi felix,

lazySizes clearly does not support IE8 and this is documented here: https://github.com/aFarkas/lazysizes#browser-support. You can however use conditional comments to enhance your progressive enhancement code.

This could look something like this:

```html
<!--[if lte IE 8]><noscript><![endif]-->
    <img src="486c8d4f4b.jpg" >
<!--[if lte IE 8]></noscript><![endif]-->
<!--[if !(lte IE 8)]> -->
<img data-sizes="auto" data-srcset="486c8d4f4b.jpg 1024w,e57d541ce2.jpg 700w,2d5725a18a.jpg 1400w" src="blank.gif">
<!-- <![endif]-->
```

Or you can use the [noscript plugin in conjunction with conditional comments](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/noscript#add-ie8--support-with-conditional-comments), but in that case you can't use the ``data-sizes="auto"`` feature.

I hope this answers your question and I'm very sorry, that you must support old IE.

**Comment by fnagel** [comment]
Thanks for your fast answer, very appreciated! 

Your code snippet is what I've ended up with. Thanks for confirming this is the best possible option.

I'm sorry to support IE8 too :-D
