### ISSUE TITLE
Publish plugins to npm and move to separate repos?

### ISSUE THREAD

**Issue by mrmartineau** [aFarkas/lazysizes#152]
Would it be possible to do this? It would allow each plugin to be updated and installed independently, what do you think?

**Comment by mrmartineau** [comment]
I may have answered my own question.. but after a little digging I realised that I could do this:

```
require('lazysizes/plugins/bgset/ls.bgset');
```

Is that how you intend plugins to be used in a Browserified codebase?

**Comment by aFarkas** [comment]
Yes, this is exactly the way. I'm doing it my own.

**Comment by nordisk** [comment]
Sorry to hijack this thread … but how would you load the plugin using ES6 module pattern?
Thanks.

**Comment by yongzhihuang** [comment]
@raphaelokon maybe just 
`import 'lazysizes/plugins/respimg/ls.respimg.min.js';`
