### ISSUE TITLE
Help allowing images to be pinned using pinterest extension

### ISSUE THREAD

**Issue by tlcsalad** [aFarkas/lazysizes#153]
Hi
Just having some trouble allowing my images to be pinned using the pinterest browser extension. Can you help me fix this to keep the placeholder gif but allow the browser extension to pick up the actual image once loaded?

![screen shot 2015-09-03 at 15 46 54](https://cloud.githubusercontent.com/assets/13416296/9661541/0ec8e5f2-5253-11e5-987a-de7c51477e16.png)

 Your help is much appreciated, thanks.

**Comment by aFarkas** [comment]
Do you mean the following extension: https://chrome.google.com/webstore/detail/pin-it-button/gpdjojdkbbmdfjfahjcgigfpmkopogic?

**Comment by tlcsalad** [comment]
Yeah that's the one.

**Comment by aFarkas** [comment]
You can use the following pattern https://github.com/aFarkas/lazysizes#combine-data-srcset-with-data-src:

```html
<picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
    <source
        data-srcset="http://placehold.it/500x600/11e87f/fff"
        media="--small" />
    <source
        data-srcset="http://placehold.it/700x300"
        media="--medium" />
    <source
        data-srcset="http://placehold.it/1400x600/e8117f/fff"
        media="--large" />
    <source
        data-srcset="http://placehold.it/1800x900/117fe8/fff" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-src="http://placehold.it/700x300"
        class="lazyload"
        alt="image with artdirection" />
</picture>
```

**Comment by aFarkas** [comment]
In case this helped please close this issue. Otherwise please inform me.

I also tried to improve documentation on this:

###Combine ``data-srcset`` with ``data-src``

In case you want to use responsive images for supporting browsers, but don't want to include a polyfill, simply combine your ``data-srcset`` with a ``data-src`` attribute.

```html
<!-- responsive example: -->
<img
	data-sizes="auto"
    data-src="image3.jpg"
	data-srcset="lqip-src.jpg 220w,
	    image2.jpg 300w,
	    image3.jpg 600w,
	    image4.jpg 900w"
	class="lazyload" />
```

Note: Due to the fact that the ``data-src`` will also be picked up by "Read-Later" Apps and other tools (Pin it button), this pattern also makes sense if you use a polyfill.

**Comment by tlcsalad** [comment]
Thank you so much for helping with this issue, it is now working using the code in your first example (using the picture element). I had to remove the 'data:' from the image tag to maintain the full page size on initial load and prevent resizing during scroll.

Thanks again! :)

**Comment by aFarkas** [comment]
@tlcsalad 
Nice, that I could help. I might some small improvements in master in case this pattern is used. It will be there with next update. Until then you can download it here:
- https://rawgit.com/aFarkas/lazysizes/master/lazysizes.js
- https://rawgit.com/aFarkas/lazysizes/master/lazysizes.min.js
