### ISSUE TITLE
Firefox loads small version on first load

### ISSUE THREAD

**Issue by sjelfull** [aFarkas/lazysizes#154]
I'm having a problem in Firefox 40, where the first image that shows have the small / mobile version loaded. When I replace the image with the next in the album, it shows the correct size.

I'm using lazysizes 1.1.3 + respimg + custommedia plugin, as well as the <picture> syntax.

This is the custom media queries: 

    window.lazySizesConfig = window.lazySizesConfig || {};
    window.lazySizesConfig.customMedia = {
        '--small': '(max-width: 500px)',
        '--smallish': '(min-width: 501px)',
        '--until-medium': '(max-width: 749px)',
        '--medium': '(min-width: 750px)',
        '--large': '(min-width: 1400px)'
    };

This is the picture element:

```
<picture>
        <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source
        data-srcset="/imager/FOod/Untitled-01_e7529372b9e5cb61fb3d78cac01c270d.jpg"
        media="--until-medium" />
        <source
        data-srcset="/imager/FOod/Untitled-01_97f7820f6ba9e9418a0a8856cbbba27d.jpg"
        media="--medium" />
        <!--[if IE 9]></video><![endif]-->
        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
    data-srcset="/imager/FOod/Untitled-01_e7529372b9e5cb61fb3d78cac01c270d.jpg" data-sizes="auto" class="lazyload" width="1400" height="933" />
</picture>
```

You can see the test site here: http://tommy.neue.no

Do you see anything wrong with my setup / syntax?

**Comment by aFarkas** [comment]
About your actual problem:

I'm a little bit ashamed, that I forgot to fix this. Here is the corresponding mozilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1170572

If you want, you can try the following updated version of lazysizes, which should fix the bug (I try my best to get a fix out soon):
https://gist.github.com/aFarkas/136cbbbadc8ef56720b5

About your markup in general.
I would rewrite it to something like this:

```html
<picture>
        <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source
        data-srcset="/imager/FOod/Untitled-01_e7529372b9e5cb61fb3d78cac01c270d.jpg"
        media="--until-medium" />
        <source
        data-srcset="/imager/FOod/Untitled-01_97f7820f6ba9e9418a0a8856cbbba27d.jpg"
        media="--medium" />
        <source
        data-srcset="/imager/FOod/Untitled-01_e7529372b9e5cb61fb3d78cac01c270d.jpg" />
        <!--[if IE 9]></video><![endif]-->
        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        class="lazyload" width="1400" height="933" />
</picture>
```

There are two changes:

1. Move the ``data-srcset`` from `img` to `source` without a `media`. (Reason: There are browser which do support `srcset`, but don't understand `picture`, which also produces a double request.)
2. Remove `data-sizes="auto"`. This feature is usefull, if you are using width descriptors inside of your `srcset` (i.e.:  `"image-300.jpg 300w, image-600.jpg 600w"`). You don't have that and therefore you don't need it.

**Comment by sjelfull** [comment]
Awesomely quick reply! I uploaded the patched version to the dev site, but it doesn't seem to fix the problem.

I also updated the markup according to your recommendations. I actually had changed the markup yesterday, because I finally read your documentation on custommedia properly (hehe).

Anything else I can try to debug? Or give you more information?

**Comment by aFarkas** [comment]
@sjelfull 
I just made some small adjustments to the fix. 

To be honest, I have difficulties to see/really understand the problem on your site, which has to do with the images used.

Therefore I tried to replicate this.

Here is the example with the old/current lazysizes script:
http://jsbin.com/xafimicexu/1/edit?html,js,output

and here with the new one:
http://jsbin.com/cufototacu/1/edit?html,js,output

In my eyes this is fixed. But maybe I'm looking at another issue? 

If yes or if it isn't fixed, it would help me dramatically if you could produce a simplified test case.

**Comment by sjelfull** [comment]
I'll try to create a reduced testcase when I get back from lunch here.

In the meantime, this is how you (should be able to) replicate this.

I'm testing this in Firefox 40.0.3

1. Load http://tommy.neue.no/
2. The first image shows the mobile version: http://tommy.neue.no/imager/FOod/Untitled-01_e7529372b9e5cb61fb3d78cac01c270d.jpg
3. Press right arrow key to navigate to picture #2, then left arrow key to navigate back to picture #1.
4. You see the same image, but now it's showing the correct version: http://tommy.neue.no/imager/FOod/Untitled-01_97f7820f6ba9e9418a0a8856cbbba27d.jpg

Do you see it now?

Your right in that your JSbin seems to work. I'm not sure if this is a different problem or not.

**Comment by sjelfull** [comment]
Result! The version of lazysizes in your working testcase seems to fix the problem on my site. This version had some small differences from the one you linked in the previous message.

Thanks!
