### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by Sinclone** [aFarkas/lazysizes#158]
Hi, I have just implemented lazysizes in my site and I must say this is good. But the issue I have is that my pictures are not loading well in IE 11. I am using LQIP technique. If you go to my site clickproperty.sg you will realise it works great in Chrome and FF, but in IE, the actual pic just wont load.

Please help

**Comment by aFarkas** [comment]
@Sinclone 
IE doesn't support responsive images. For not supporting browser you either need to use a polyfill or add an additional ``data-src`` attribute. See here for more information: https://github.com/aFarkas/lazysizes#responsive-image-support-picture-andor-srcset

Please close if this helps.
