### ISSUE TITLE
Conflict with RequireJS

### ISSUE THREAD

**Issue by minhjamin** [aFarkas/lazysizes#159]
Hi, 

I just tried integrating lazysizes v1.2.2  into my project and RequireJS v2.1.10 seems to be complaining:

Uncaught Error: Mismatched anonymous define() module: [object Object]

any ideas?

**Comment by aFarkas** [comment]
Because I'm an idiot ;-). Please re-try with the newest version from master.

Please close if this helps.

**Comment by seangates** [comment]
Can you publish this latest change to NPM?

**Comment by minhjamin** [comment]
It didn't really fix the problem, just gave a name to the object. 

I solved the problem my moving the script tag before the jQuery tag. jQuery conflict?

Thanks for the great work!

**Comment by aFarkas** [comment]
@seangates 
Just push this as version `1.2.3-rc1`. Can you test?

@minhjamin 
Can't believe this. Also there is no dependency to jQuery. Actually the old module definition should have also worked. Can you give me a link to the project so I can check this out?

I tried to test this with version 1.2.2 and with 1.2.3 and I could not reproduce the error.

**Comment by seangates** [comment]
@aFarkas Nope, still getting an error that AMD is required.

**Comment by aFarkas** [comment]
@seangates 
I really want to help, but I can't reproduce your error. Here is a working plunk using require js in conjunction with lazysizes:
http://embed.plnkr.co/b71O26fpkRTvWTGHRIzy/preview

If you can give me a link to a not working site/project/plunk or tell me what's wrong, I would be able to fix.

**Comment by aFarkas** [comment]
Please re-open, if it still doesn't work for you and you can provide a test case.
