### ISSUE TITLE
Unload plugin with `autoUnload` set to `true` throws error if SVG elements are present

### ISSUE THREAD

**Issue by robinnorth** [aFarkas/lazysizes#161]
If you include the unload plugin and use the default `true` setting for the `autoUnload` config option on a page that has SVG elements present, you will receive errors similar to this:

```
Uncaught TypeError: e.target.className.indexOf is not a function
```

This is due to capturing all `load` events and checking their targets for the existence of lazySizes classes using `className.indexOf`, which is not available on the `className` property of a SVG element, as this property is a [`SVGAnimatedString`](http://www.w3.org/TR/SVG/types.html#InterfaceSVGAnimatedString), not a `DOMString`.

To check the class name of a SVG element, you can test `className.baseVal`, as this *is* a `DOMString`.

To work around this issue at present, you can simply set `window.lazySizesConfig.autoUnload = false` and then mark up your img elements with whatever `window.lazySizesConfig.unloadClass` is set to (default is `"lazyunload"`).

**Comment by aFarkas** [comment]
@robinnorth 
Many thanks for the detailed information. I changed this part now.

**Comment by robinnorth** [comment]
No problem, @aFarkas! Your fix works for me in the project which revealed the error previously, so feel free to close this issue :+1: 

*Technically, as `SVGElement` doesn't implement the `naturalWidth` or `naturalHeight` properties, you might want to be more explicit in checking if the element being tested is an image element, as `e.target.naturalWidth * e.target.naturalHeight` will return `NaN` in this case. However, the check for `e.target.className.indexOf` is sufficient to ensure this logic only applies to image elements.

**Comment by aFarkas** [comment]
@robinnorth 
I already have moved the indexOf test after the naturalWidth test. So it should already abort at this point. But I still wanted to check against the API I'm using.
