### ISSUE TITLE
lazysizes doenst work with microsoft Edge

### ISSUE THREAD

**Issue by sopparus** [aFarkas/lazysizes#162]
it doesnt load the picture..

**Comment by aFarkas** [comment]
Have you read this:
https://github.com/aFarkas/lazysizes#responsive-image-support-picture-andor-srcset

Do you have a testsite/testcase or can you at least provide the markup and the included JS (lazysizes, plugins and resp image polyfills)?

**Comment by sopparus** [comment]
my lines are like this.

<td rowspan="4"><img class="lazyload" src="bg.png" data-src="'https://mysite.com/otherpic.jpg"/>

works fine in both chrome and firefox

**Comment by sopparus** [comment]
just noticed i ran 1.1.5rc1, do you want me to upgrade first?

**Comment by aFarkas** [comment]
no need to. I think I got it. but must confirm and my virtual machine doesn't want how  want.

**Comment by sopparus** [comment]
ok, I can replace my lazysizes file in a second if you give me a new link

**Comment by aFarkas** [comment]
So this has nothing todo with lazysizes itself. So I didn't hunt down the bug itself.

Either it's the URL (pretty nasty special characters) or something with your certificate:

You can check this error, if you add the following code to your console...:

```js
document.createElement('img').src = 'https://pub:angelsofsippan@braxnacke.se/dav/pub/flac/6/And+You+Will+Know+Us+by+the%20Trail%20of%20Dead%20-%20The%20Century%20of%20Self%20%282009%29/Folder.jpg'
```

...  or if you would add the image with normal `src`

The images should load, if you would serve them from the same domain with relative urls.

**Comment by sopparus** [comment]
ok thanks, sorry for your time

**Comment by aFarkas** [comment]
No problem.

**Comment by sopparus** [comment]
do you mind remove that url you posted btw?.)
if this is googleable

**Comment by aFarkas** [comment]
done
