### ISSUE TITLE
Image not scaling properly in IE

### ISSUE THREAD

**Issue by DennisGi** [aFarkas/lazysizes#163]
We are currently using lazysizes on my Bootstrap site right now. Great tool really like working with it!

There seems to be a compatibility issue with Internet Explorer where the responsive image would not jump to full size after reaching the given breakpoint of Bootstrap. This problem only exists in IE with other Browsers (Chrome, Safari) it works just fine. What could be the problem here?

I have created a small testing site to demonstrate the issue:
[Testsite](http://dev.lstest.acribis.dennisgilli.com)

**Comment by aFarkas** [comment]
I just checked your site with IE9, IE 11 and EDGE. I can't reproduce your issue. Which IE version do you mean?

**Comment by DennisGi** [comment]
Thank you for the quick reply.

I am using IE 11 to test. See the screenshot for the issue. After reaching the breakpoint the image should jump to display full width. It does in Safari but not in IE.

<img width="1427" alt="screen shot 2015-09-28 at 13 35 43" src="https://cloud.githubusercontent.com/assets/14869578/10134431/ed5991d6-65e5-11e5-94e1-3dc5e4d6a2a3.png">

**Comment by aFarkas** [comment]
Ok, I think I understand now. There are basically multiple problems. In short change your markup to this:

I.e: Use ``data-sizes="auto" instead of `100vw`
```html
<img data-src="img/jonas_birk.jpg" data-srcset="img/jonas_birk.jpg 450w, img/jonas_birk@2x.jpg 900w" data-sizes="100vw" class="img-responsive lazyload" />
```

*and*:

Add the following CSS:

```css
.img-responsive {
    width: 100%;
}
```

**Comment by DennisGi** [comment]
Works just fine now. Thank you!

Also, could edit your previous post and delete jonas_**** from the image tag. Im sorry I missed that.
