### ISSUE TITLE
Background images, text and location of JS

### ISSUE THREAD

**Issue by ollie007** [aFarkas/lazysizes#164]
1. Can you load this JS at the foot of the page?
2. can it lazyload background images?
3. what about lazyloading element with text and other html?

**Comment by aFarkas** [comment]
1. yes
2. yes (old school plugin: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks, responsive plugin: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset)
3. yes (include plugin: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/include) 

Or you can roll your own. It's easy and simple to extend:
```js
//add simple support for background images:
//<div class="lazyload" data-bg="image.jpg"></div>
document.addEventListener('lazybeforeunveil', function(e){
    var bg = e.target.getAttribute('data-bg');
    if(bg){
        e.target.style.backgroundImage = 'url(' + bg + ')';
    }
});
//or add AJAX loading
//<div class="lazyload" data-ajax="my-url.html"></div>

$(document).on('lazybeforeunveil', function(){
    var ajax = $(e.target).data('ajax');
    if(ajax){
        $(e.target).load(ajax);
    }
});
```

BTW.: The hole answer is copied from the readme.
