### ISSUE TITLE
Using RIAS plugin with images loaded immediately

### ISSUE THREAD

**Issue by fatpixelstudio** [aFarkas/lazysizes#168]
Hi,

I'm are using Lazysizes with the RIAS plugin to load images from the ReSRC service. Works really smooth!

But when there is an image that's always present in the head, like an article cover or something, I would like to load it immediately, not checking if it's in the viewport. Just use the RIAS plugin to set the correct height and width etc. 

Is that in any way possible? What are your thoughts on this?

**Comment by aFarkas** [comment]
You could use the `lazySizes.loader.unveil` method. This would look something like this:

```js
[].slice.call(document.querySelector('.header img.lazyload, img.loadimmediate').forEach(lazySizes.loader.unveil);
```

A little lazier way would be to simply add the class `lazypreload`, but this only kicks in after the window is loaded.

**Comment by fatpixelstudio** [comment]
Great suggestion! I'm going to implement this. Thank you :)

One question: why do you use `[].slice.call()` around the `document.queryselector`? I assume this is necessary, but I've not seen this used before?

**Comment by aFarkas** [comment]
This kind of a workaround to transform a nodelist into an array. This only works with list, so I should have used `querySelectorAll` instead of `querySelector`. http://stackoverflow.com/questions/2125714/explanation-of-slice-call-in-javascript

In case you use jQuery, you can also do:

```js
$('.header img.lazyload, img.loadimmediate').get().forEach(lazySizes.loader.unveil);

//or
$('.header img.lazyload, img.loadimmediate').each(function(){
    lazySizes.loader.unveil(this);
});
```

**Comment by fatpixelstudio** [comment]
Allright, thanks for clearing that up. And thanks for the quick replies!
