### ISSUE TITLE
Any way to lazyload fonts?

### ISSUE THREAD

**Issue by ollie007** [aFarkas/lazysizes#169]
Any way to lazyload fonts?

fonts are so huge, it would be great to lazyload them in the background?

**Comment by daltonrooney** [comment]
[Web Font Loader](https://github.com/typekit/webfontloader) handles asynchronous font loading, seems like it would make sense to use a dedicated library for this.

**Comment by aFarkas** [comment]
If you are using a font on an element, that is "below the fold", it might make sense to use lazySizes. Then you can your font declarations into a CSS file and use the unveilhooks plugin to load this CSS file.

For the most usecases, where you want to load fonts async that are visible immediately, lazysizes is not a good tool.

Use a font loader or go native. For example you can add the following inline above all your stylesheets and JS:

```html
<style>
	@font-face {
		font-family: 'MyFont';
		src: url('fonts/MyFont.woff') format('woff');
		font-style: normal;
		font-weight: 400;
	}
</style>
<script>
	
	(function(docElem){
		if(!document.fonts || !document.fonts.load){
			docElem.classList.add('fonts-loaded');
		} else {
			Promise.all([document.fonts.load('1em MyFont')])
					.then(function(){
						docElem.classList.add('fonts-loaded');
					})
			;
		}
	})(document.documentElement);
</script>

<! -- stylesheets -->
```

More informations here: https://dev.opera.com/articles/better-font-face/

**Comment by Niresh12495** [comment]
Yes, you can try [LazyHTML](https://github.com/Niresh12495/LazyHTML) 

Add LazyHTML into Head
`<script async src="https://cdn.jsdelivr.net/npm/lazyhtml@1.2.3/dist/lazyhtml.min.js" crossorigin="anonymous" debug></script>`

then 

```
<div class="lazyhtml" onvisible data-lazyhtml>
  <script type="text/lazyhtml">
  <!--
   <link rel="stylesheet" href="/path/to/fonts.css">
   -->
 </script>
</div>

<p style='font-family: "MyFont";'>Here goes your HTML</p>
```

or 

```
<div class="lazyhtml" onvisible data-lazyhtml>
  <script type="text/lazyhtml">
  <!--
<style>
    @font-face {
        font-family: 'MyFont';
        src: url('fonts/MyFont.woff') format('woff');
        font-style: normal;
        font-weight: 400;
    }
</style>
   -->
 </script>
</div>
<p style='font-family: "MyFont";'>Here goes your HTML</p>
```
