### ISSUE TITLE
bgset plugin is whitespace sensitive

### ISSUE THREAD

**Issue by Jiia** [aFarkas/lazysizes#170]
I just spend some hours wondering why the bgset plugin wasn't doing anything. I had my markup written like this:

```html
<div class="lazyload" data-sizes="auto" data-bgset="
    image1,cropped.jpg 240w,
    image2,cropped.jpg 360w,
    image3,cropped.jpg 540w" >
```

Finally I figured that the plugin didn't trim the whitespace correctly and wasn't working because of that. I had to write the markup like this for it to work:

```html
<div class="lazyload" data-sizes="auto" data-bgset="image1,cropped.jpg 240w, image2,cropped.jpg 360w, image3,cropped.jpg 540w" >
```

EDIT: After talking with my colleagues I heard that the issue may also consider the main lazysizes.js too.

**Comment by aFarkas** [comment]
This is very unfortunate. Sorry. Thanks for reporting.

**Comment by mrmartineau** [comment]
I found this aswell, thanks for fixing @aFarkas
