### ISSUE TITLE
How to use unload plugin

### ISSUE THREAD

**Issue by rootion** [aFarkas/lazysizes#172]
Hello,

I can't make the `plugin unload` to work. It seems that I don't understand the documentation completely or I am missing something. I loaded `lazysizes.min.js` in the header and right after I loaded the plugin file `ls.unload.min.js`. Images lazyloaded perfectly, but they don't disappear when they are out of view, they remain there (this is what I am expecting to happen when they say they "unload").

The documentation only says `Simply add the lazysizes unload extension to your site`. 

What does it mean? Should I include the default class (default: "lazyunload") to all my images? I did this, but I see the images anyway. Should I initialize the plugin somewhere?

I know the question is basic, but I don't seem to get it working. 
Any guide would be appreciated. Thanks a lot for the amazing work!

**Comment by aFarkas** [comment]
It seems you have a misunderstanding. The image are unloaded as soon as you scroll them far away from the viewport. If you scroll back you will see them again. I don't understand your usecase.

You can see the unload plugin working on this side:
http://afarkas.github.io/lazysizes/no-src.html

The idea is, that it only unloads large images, if you want to also unload small ones, you can either explicitly set the `lazyunload` class or change the ``lazySizesConfig.unloadPixelThreshold`` value.

For example:

``js 
window.lazySizesConfig = window.lazySizesConfig || {};
lazySizesConfig.unloadPixelThreshold = 200 * 100; //unloads images that are larger than 200 x 100
```

**Comment by rootion** [comment]
Hello, thanks a lot for the clarification.

I am building a site that has no scroll whatsoever, as my width and height are 100% and overflow is hidden. Its a big slideshow, and the markup is build when the website loads and I am moving through the slides with next, previous, up and back controls. 

What I want to do, is when the slide is outside the viewport area, that the image that was lazyloaded by lazysizes is "unloaded" again. This is not exactly what's happening with the plugin as it's expecting a scroll event. Is that correct?

**Comment by aFarkas** [comment]
Actually no. lazysizes does not expect a scroll event. It should work. Can you please give me a link or mail me your prototype. So I can investigate what's going wrong.

**Comment by aFarkas** [comment]
Please reopen, if it still don't work for you and you can provide a testcase.
