### ISSUE TITLE
Not working in Chrome for dynamically injected img with missing alt attribute

### ISSUE THREAD

**Issue by russellbrown** [aFarkas/lazysizes#174]
In Chrome, lazySizes doesn't appear to be invoked on newly inserted elements (in my case via Turbolinks) where the new `<img>` element (inside a `<picture>` element) doesn't have an `alt` attribute.

It works fine when the newly inserted `<img>` element has an `alt`, even if `alt` is an empty string. It even works for the first proper page load where the `alt` attribute is missing, just not for subsequent DOM injections.

I've only encountered this in Chrome (45.0.2454.101). Safari and Firefox aren't affected.

**Comment by aFarkas** [comment]
This seems extremely strange. Can you give me a link or mail me something, where i can replicate this issue.

**Comment by russellbrown** [comment]
Sure: http://jsfiddle.net/xr63aj2a/2/

On initial page load, both images with and without an `alt` attribute are rendered as expected. But when injecting a new element dynamically e.g. via jQuery, only the image with an `alt` attribute is rendered in Chrome (45.0.2454.101).  Safari (9.0) and Firefox (41.0.1) work as expected. Mac OS X Yosemite 10.10.5.

I'm not clever enough to understand what's going on but I hope this helps!

**Comment by aFarkas** [comment]
Thanks. This is a Chrome bug. It seems that this is a variation of this bug:
https://code.google.com/p/chromium/issues/detail?id=478153

You can workaround this, by setting an alt or a src attribute. 

Here is a working fiddle:
http://jsfiddle.net/xr63aj2a/4/

**Comment by russellbrown** [comment]
OK, understood, thanks for looking into that.  Really great plugin by the way, thanks so much for creating and releasing it.

**Comment by aFarkas** [comment]
Thanks for your kind words ;-)
