### ISSUE TITLE
Lazybeforeunveil eventlistener and image shown

### ISSUE THREAD

**Issue by fatpixelstudio** [aFarkas/lazysizes#175]
I have a question about the lazybeforeunveil eventlistener.

What I'm trying to do is load a cover image via the Lazysizes RIAS plugin. Once that image is loaded, I want to display an animation over it and execute the rest of the scripts on the site (initialize video's, add navigation, and so on). Thanks to your earlier help I'm close, but still have an issue.

The result I'm seeing is that the `lazybeforeunveil` event is picked up before the image is actually shown on the page. 

I isolated the issue and made a JSFiddle where you can see this happening: http://jsfiddle.net/fatpixel/6c5Lm7wt/10/  (use chrome to test this)

You can see it especially on slower connections, so I reproduce it in https://jsfiddle.net/fatpixel/6c5Lm7wt/10/embedded/result/ with network throttling on.

What can I do to fix this? Am I missing something? Is there a `lazyafterunveil` hook or something? Any other solutions? Any help is appreciated!

**Comment by aFarkas** [comment]
You have two options:

1. JS Use `load` instead of `lazybeforeunveil`. A working fiddle:
https://jsfiddle.net/6c5Lm7wt/11/embedded/result/
2. CSS: Refactor your markup and use the class `lazyloaded`. A working fiddle:
https://jsfiddle.net/6c5Lm7wt/14/

Hope this helps.

**Comment by fatpixelstudio** [comment]
Thank you so much! The first solution by using load works perfectly in this situation. Exactly what I needed.

Thanks again for the super quick reply!

**Comment by fatpixelstudio** [comment]
Sorry to re-open this, but I found out that the `lazySizes.loader.unveil(cover);` does not seem to display the image on Safari.

The `lazyloaded` class is set, but the image is not displayed. So the `cover.addEventListener('load', addClasses, true);` also does not execute the addClasses function.

I tested this in Safari (on OSX and iOS9) with your example: https://jsfiddle.net/6c5Lm7wt/11/embedded/result/

Is this a known issue or a bug or something?

**Comment by aFarkas** [comment]
Safari doesn't support the picture element. Therefore you need a polyfill or the respimg plugin.

Here is an example using the the respimg plugin:
https://jsfiddle.net/6c5Lm7wt/15/

See also:
https://github.com/aFarkas/lazysizes#responsive-image-support-picture-andor-srcset

**Comment by fatpixelstudio** [comment]
Thanks! Damn you Safari ;) I totally overlooked that this could be an issue...

The RespImg plugin works like a charm like you suggested.
