### ISSUE TITLE
Rias and Respimg plugins on Safari

### ISSUE THREAD

**Issue by fatpixelstudio** [aFarkas/lazysizes#176]
Hi,

After your working solution on issue #175 I've been developing the rest of the page and I'm encountering something unexpected. The 'cover image' is loaded fine using `lazySizes.loader.unveil()`, but after the cover load, I would like to enable the regular lazyload behavior, with the RIAS plugin.

But, while the cover loads perfectly on Safari using Respimg (like you suggested), all the other images in the site do not load. As far as I can tell, there is no picture element added, so the Respimg plugin is not working for these images? I see the file requested still has the {width} in the url, so it retuns a 404. What's going on here?

A JSFiddle that illustrates what's going on: https://jsfiddle.net/fatpixel/6c5Lm7wt/21/embedded/result/
Cover works in Chrome and Safari, but images within the text only work in Chrome.

Probably I'm missing something important, but I can't figure out what!

By the way, I also have a staging environment which uses ReSRC if you need it. But I think the JSFiddle example is more usable.

Thanks in advance!

**Comment by aFarkas** [comment]
Sorry for the bug. Could give a long explanation, but I think I fixed it in the newest master. Please test.

**Comment by fatpixelstudio** [comment]
Awesome! This commit fixed the issue!

Thank you for the lightning quick reply and fix.
