### ISSUE TITLE
Multiple instances of same image do not show when using position absolute + ratio technique.

### ISSUE THREAD

**Issue by KrisOlszewski** [aFarkas/lazysizes#177]
Hi there, I'm having an issue where I want to load the same image more than once on a single page. However, the image loads only once when using `ratio` + `position: absolute;` technique.

Here is a demo where I try to load 4 images: http://s.codepen.io/KrisOlszewski/debug/yYzXWb?

Any thoughts?

**Comment by aFarkas** [comment]
All images are loaded. You need to add position: relative to the div:

```css
div {
    position: relative;
}
```

**Comment by KrisOlszewski** [comment]
Ahh, sorry, missed `position: relative;` in my demo. However, that wasn't the problem. It turns out I was using wrong transparent image in base64. For some reason that was causing issues in my project where I have a ton of CSS and JS.

```
data:image/gif;base64,R0lGODlhAQABAAAAADs=
```
vs
```
data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
```

Thanks for a great plugin!
