### ISSUE TITLE
Not swapping for "above the fold" elements, still applies .lazyloaded

### ISSUE THREAD

**Issue by evvvritt** [aFarkas/lazysizes#178]
Hi, thanks for the great plugin I'm using it for responsive image backgrounds. 

It's working as I scroll to new elements but it seems it misses swaps for the elements visible in the window, on load. 

[example](http://new.zarchitecture.com/news/page/2/)
First image isn't being swapped in but .lazyloaded class is still applied. Console is logging widths of .lazyload elements if they have data-bg attribute. Also doesn't work if you load the page over another image. 

script, inside doc ready
```
document.addEventListener('lazybeforeunveil', function(e){
		    var el = $(e.target),
		          bg = el.attr('data-bg');

    		    if(bg){ 
    		    	var bg_m = el.attr('data-medium'),
				    	bg_l = el.attr('data-large'),
				    	bg_xl = el.attr('data-xl'),
				    	//portrait = el.hasClass('portrait') > -1,
				    	w = el.width() * window.devicePixelRatio;

    	        	bg = w > config.max_img_w.s && typeof bg_m !== 'undefined' ? bg_m : bg ;
    	        	bg = w > config.max_img_w.m && typeof bg_l !== 'undefined' ? bg_l : bg ;
    	        	bg = w > config.max_img_w.l && typeof bg_xl !== 'undefined' ? bg_xl : bg ;
    		        e.target.style.backgroundImage = 'url("' + bg + '")';
    		        console.log('resp. bg img - w: '+ w);
    		    }
		    
		});
``` 
Maybe lazyload is running before this listener is applied? If so, any way I can ensure it waits for it?
(All my scripts are requirejs compiled into one file and loaded in the footer)

Any thoughts?

**Comment by aFarkas** [comment]
If every scripts include lazysizes are in the same file and you move the listener binding outside of ready and do it immediately it should work. 

Otherwise you can check the init /autoinit method/option:
https://github.com/aFarkas/lazysizes#lazysizesinit

**Comment by aFarkas** [comment]
@evvvritt 

Did this help?

**Comment by evvvritt** [comment]
yeah moved it earlier but thanks for pointing out the init method :)

**Comment by aFarkas** [comment]
Moving it is the best thing you can do. earlier is better + your problem analysis was 100% correct ;-).
