### ISSUE TITLE
Get the current responsive img loaded

### ISSUE THREAD

**Issue by WillyBrownHair** [aFarkas/lazysizes#179]
I would like to know if it's possible to get the current url to the responsive version of image load.

If my image has these differentes versions 
```
data-srcset="
http://url.com/img-240.jpg 240w, 
http://url.com/img-360.jpg 360w, 
http://url.com/img-480.jpg 480w, 
http://url.com/img-720.jpg 720w "
```

Can I get witch of these one is loaded when my page is loaded ? 

I try this : 
```
var srcset = $('img').attr('srcset');
console.log(srcset);
```
but the console return `undefined `

Thanks

**Comment by aFarkas** [comment]
In short, not in every browser. In case `srcset` reports `undefined` than the image hasn't started to load yet.

In most browsers you can get the current source after the image is loaded using the `currentSrc` property.

This would look than:

```js
document.addEventListener('load', function(e){
    console.log(e.target.currentSrc || e.target.src);
}, true);
```

**Comment by WillyBrownHair** [comment]
Thanks,
I can rightnow use the current image display like a placeholder of my lightbox plugin called photoswipe.

The problem is, it's working on Chrome & Firefox but not on safari actually.
Do you have any recommendation about this issue on safari ?

Thanks a lot.

**Comment by aFarkas** [comment]
In Safari this is technically not possible. I haven't really understood what you want to achieve here.

What do you need the currentSrc for? Can't you use simply just use the hole `srcset`? How is this related to lazysizes.

All browsers which do support `picture` also support `currentSrc`: This means you can also workaround this by using a `picture` pattern. This way Safari gets polyfilled and you have access to the normal `src`.

```html
<picture>
    <source data-srcset="
http://url.com/img-240.jpg 240w, 
http://url.com/img-360.jpg 360w, 
http://url.com/img-480.jpg 480w, 
http://url.com/img-720.jpg 720w " />
    <img class="lazyload" data-sizes="auto" />
</picture>
```

Please re-open if this is a lazysizes problem and I couldn't answer your question.

**Comment by WillyBrownHair** [comment]
I understand my contradiction, I didn't understand what did respimg.
I get simply the src of the image for my placeholder in Safari.

Tanks.
