### ISSUE TITLE
Does responsive polyfill only kick in on browsers that dont support srcset?

### ISSUE THREAD

**Issue by farzd** [aFarkas/lazysizes#182]
Can I do something like this with SRCSET attr, so the responsive images are dealt with newer browsers, like chrome?
But also have data-srcset for older browsers ? 

```
    <img
    src="LQT.jpg"
    sizes="(min-width: 36em) 388px, 60px"
    srcset="images/olympus/thumbs/1.jpg 60w, images/olympus/1.jpg 388w"
    data-srcset="images/olympus/thumbs/1.jpg 60w, images/olympus/1.jpg 388w" class="lazyload"/>
```

**Comment by antigirl** [comment]
Also doesnt seem to work at all in Firefox 30

**Comment by aFarkas** [comment]
You mean this https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg plugin right?

I just tested and it works pretty good in FF 30. 

While this works, it doesn't make to much sense and I would suggest a real respimage polyfill for this. Also note, that `sizes` attribute is then not used, but calculated according to the size of the image or its parent.

**Comment by antigirl** [comment]
Thanks for getting back to me, but that plugin is also using data-srcset not just srcset?
A real polyfill you would just be using srcset. 
So for example if i use lazysizes in the latest chrome, even though it supports srcset, your JS will still kick in and compute things when chrome already has?

**Comment by aFarkas** [comment]
> So for example if i use lazysizes in the latest chrome, even though it supports srcset, your JS will still kick in and compute things when chrome already has?

For the polyfill part no. For the core part yes , this is because you marked the `img` with the class `lazyload`.

In case you really don't want to use picturefill. Here is how you can go:

```html
<img
    src="LQT.jpg"
    sizes="(min-width: 36em) 388px, 60px"
    srcset="images/olympus/thumbs/1.jpg 60w, images/olympus/1.jpg 388w" />
```

```js
if(lazySizes.cfg.pf && !('sizes' in document.createElement('img')){
    lazySizes.cfg.pf({
        elements: document.querySelectorAll('img[srcset], picture > img');
    });
}
```

But note that sizes is not computed by the plugin, it simply tries to use the display size of the image itself.

**Comment by antigirl** [comment]
> For the polyfill part no. For the core part yes , this is because you marked the img with the class lazyload.

I do want the Polyfill to kick in but if i have srcet and data-srcet then i assumed the Polyfill would kick in even if chrome has support for it

**Comment by aFarkas** [comment]
To be honest, I don't really understand, what you want.

To clarify how this works:
1. lazysizes core transforms the `data-srcset` to `srcset` on images with the class `lazyload`.
2. After that the respimg polyfill transforms multiple sources defined by `srcset` into one `src`. In Chrome and FF this is a noop.
