### ISSUE TITLE
not loading correct image sizes and not displaying on safari 

### ISSUE THREAD

**Issue by MrNicolson** [aFarkas/lazysizes#183]
it dose not seam to be loading in the right image sizes i am pretty sure its not caching as i have turd it off and tested it after clearing all browser data plus the load times are the same for both screen sizes the images also do not display on safari desktop browser but do on mobile.

**Comment by aFarkas** [comment]
If it is working on my demo page, I really need more information that helps me to reproduce the problem.

1. environment
So what is your markup? What did you include in your page? (only lazysizes core or some plugins/polyfills)? Do you have a test case? Give me a link or mail me one.

2. What happens?

3. What should happen?

**Comment by codev0** [comment]
I have same problem.
Latest safari.
I use owl carousel, inside background images.
``` html
<script>
    function loadJS(u){var r=document.getElementsByTagName("script")[0],s=document.createElement("script");s.src=u;r.parentNode.insertBefore(s,r);}

    if(!window.HTMLPictureElement || !('sizes' in document.createElement('img'))){
      loadJS("/components/lazysizes/plugins/respimg/ls.respimg.min.js");
    }
</script>
// Another code
<div class="slider__item">
<a class="slider__img lazyload"
        href="{{ $banner->url }}"
        data-bgset="/uploads/banners/grand/{{ $banner->path_phone }} [(max-width: 640px)] |,
        /uploads/banners/grand/{{ $banner->path_tablet }} [(max-width: 940px)] |,
        /uploads/banners/grand/{{ $banner->path_desktop }}" data-sizes="auto"></a>
</div>
```

**Comment by aFarkas** [comment]
@codev0 

Here is a simplified testcase of your markup:
https://jsfiddle.net/trixta/cycp1cda/7/embedded/result/

It works for me. Can you either give me a test case, where it is not working or share your hole project? Otherwise I can't help.

**Comment by codev0** [comment]
@aFarkas 
Thanks for response.

My case https://jsfiddle.net/cycp1cda/8/embedded/result/

**Comment by aFarkas** [comment]
@codev0 

You have set the wrapper element to `display: none;` As long as this is invisible the image doesn't start to load.

As soon as you remove `display: none;` everything works as expected.

**Comment by MrNicolson** [comment]
hey sorry for not responding i had to find a fix fast and ended up just making my own JS function to achieve the same effect but thank you very much for your speedy reply and sorry for being crap.

**Comment by RegisBiron** [comment]
@aFarkas If you take a look at the fiddle you set up the bgset plugin is currently not working in Safari 9.1. http://jsfiddle.net/trixta/bfqqnosp/embedded/result/ 

I can also e-mail you a site that is currently using the plugin and it is currently loading the lowest res image. 

Would love to get this working since this is such a great plugin.

**Comment by aFarkas** [comment]
@RegisBiron 
Yeah, please mail me. I can't reproduce your issue with the fiddle in Safari 9.1. I can only see that it needs some time to adjust to viewport changes.
