### ISSUE TITLE
Problem with IE and Safari when using lazysizes with Swiper 3

### ISSUE THREAD

**Issue by Jiia** [aFarkas/lazysizes#184]
Hey there,

I'm very fond of lazysizes and I recently started a photo gallery project that uses lazysizes for loading the photographs.

The plugin works very well in Chrome and Firefox but IE11 and latest Safari never load higher quality images, just the LQIP. I'm using lazysizes along with idangerous swiper. I had to make some ugly hacks to get the carousel working properly in IE as it refused to calculate the image widths properly when using 100% height and auto width.

I tried calling various lazySizes methods after swiper initialization but nothing seems to work. The plugin seems to run without errors as the images get the "lazyloaded" class.

http://kamara.fi/x/fotosoini/
(open an album from the top right corner)

**Comment by aFarkas** [comment]
I haven't looked deeper into this issue. Can it be, that you mean Safari 8 and not 9? To me it looks like, that you forgot to add a polyfill like picturefill or the respimg plugin.

**Comment by Jiia** [comment]
Oh, that was completely the problem. Thanks for pointing that out!
