### ISSUE TITLE
Mutation event issues?

### ISSUE THREAD

**Issue by bradoyler** [aFarkas/lazysizes#187]
@aFarkas Awesome library.
I noticed this is using the Mutation Event(https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events) DOMNodeInserted & DOMAttrModified [here](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L521) and was curious if you've seen any nasty side effects in IE9/10 or Android.

Reference: http://help.dottoro.com/ljmcxjla.php 
> Note that the DOMNodeInserted event is buggy in Internet Explorer 9, it is not fired when a node is inserted for the first time.

**Comment by aFarkas** [comment]
@bradoyler 
No, I haven't. 

**About accuracy**
I'm pretty sure, that there are some pretty nasty bugs (mutation event not fired correctly). But how lazysizes is designed, it doesn't count really. In most cases there are multiple events yielding to a visibility change of an image.

**About performance**
As soon as you treat it async and throttled, it's quite performant. I know that FF had it's issues tough. Fortunately FF runs with mutation observers.

About the quote:
I can't confirm this. The following code produces two logs as exprected in IE9:

```html
<div id="test">

</div>
<script>
	document.documentElement.addEventListener('DOMNodeInserted', function(e){
		console.log(e)
	})

	setTimeout(function(){
		document.querySelector('#test').innerHTML = '<div>foo</div>';
	}, 300)

	setTimeout(function(){
		var div = document.createElement('div');
		document.querySelector('#test').appendChild(div);

	}, 600)
</script>
```

**Comment by bradoyler** [comment]
Thx!
