### ISSUE TITLE
Lazyloading not being removed intermittently from first load viewport

### ISSUE THREAD

**Issue by ChronixPsyc** [aFarkas/lazysizes#188]
Not sure if this is an issue with the images in my current project loading quicker than lazysizes can run (unlikely) or something that happens on a cold-start on the site, but some times the images that are loaded into my homepage viewport don't have lazyloaded added to them, they only go from lazyload to lazyloading.

I'm no expert when it comes to JavaScript, and this plugin seems to be exactly what I need to get images to load as I am scrolling through a view. I was looking to see if there was a way to add a fallback if lazyloading doesn't get removed from images after a certain amount of time.

If there isn't could someone point me in the right direction as to where I could add one? Maybe a fallback of 3000ms?

Cheers!

**Comment by aFarkas** [comment]
@ChronixPsyc 
I assume a browser bug. Does this happen with all browser or one specific? Can you give me a link? Because it will be quite hard to replicate and fix the issue.

Here is a workaround:
 ```
document.addEventListener('lazybeforeunveil', function(e){
	var timer;
	var switchClasses = function(){
		e.target.classList.remove('lazyloading');
		e.target.classList.add('lazyloaded');
		clearTimeout(timer);
		e.target.removeEventListener('load', switchClasses);
		e.target.removeEventListener('error', switchClasses);
	};

	setTimeout(function(){
		if(e.target.complete){
			switchClasses();
		}
	});
	e.target.addEventListener('load', switchClasses);
	e.target.addEventListener('error', switchClasses);
	timer = setTimeout(switchClasses, 3000);
});
```

**Comment by ChronixPsyc** [comment]
@aFarkas 

It seems to be an issue with the Chrome's Device Mode trying to emulate an iPhone 6 Plus as I've tested it in Firefox, IE11, Android Chrome and iOS Safari and they all work fine.

Thanks for your help! Great plugin by the way!
