### ISSUE TITLE
Safari 8.0.5 - picture tag does not load (error in picturefill)

### ISSUE THREAD

**Issue by DenisMir** [aFarkas/lazysizes#189]
I got the following picture tag in my site: 

```html
    <picture>
       <!--[if IE 9]><video style="display: none;"><![endif]-->
       <source srcset="/some-image-1024.jpg" alt="Some alternative" title="Some title" media="(min-width: 1024px)">
       <source srcset="/some-image-640.jpg" alt="Some alternative" title="Some title" media="(min-width: 640px)">
       <!--[if IE 9]></video><![endif]-->      
       <img srcset="/some-image.jpg" alt="Some Alternative" title="Some title" />
    </picture>
```

This does work perfectly with Chrome and Firefox. 
When using Picturefill 3.0.1 this does work with Safari 8.0.5 as well.

But when I'm adding lazysizes version 1.3.1 and updating the picture tag like this:
```html
    <picture>
       <!--[if IE 9]><video style="display: none;"><![endif]-->
       <source data-srcset="/some-image-1024.jpg" alt="Some alternative" title="Some title" class="lazyload" media="(min-width: 1024px)">
       <source data-srcset="/some-image-640.jpg" alt="Some alternative" title="Some title" class="lazyload" media="(min-width: 640px)">
       <!--[if IE 9]></video><![endif]-->      
       <img data-srcset="/some-image.jpg" alt="Some Alternative" class="lazyload" title="Some title" />
    </picture>
```
 the picture tag does not get displayed in Safari 8.0.5 on the desktop and I'm getting the error message in the picturefill script: 

```js
TypeError: Attempted to assign to readonly property.
```

Since it does work without lazysizes I assume that the error comes from the lazysizes script. But I'm not quite sure what leads to the error.

**Comment by aFarkas** [comment]
You markup is wrong. You should not set the class *lazyload* to the `source` element. Also note, that 

1. the title and the alt attribute do not belong to the `source` elements.
2. while technically correct, it is currently wise to move the `srcset` at the `img` element to the latest `srcset` of a `source` element without a `media` attribute. Additionally you can use a `data-src` with the same or another image as the fallback.

Your corrected markup looks then like this:

```html
    <picture>
       <!--[if IE 9]><video style="display: none;"><![endif]-->
       <source data-srcset="/some-image-1024.jpg" media="(min-width: 1024px)" />
       <source data-srcset="/some-image-640.jpg" media="(min-width: 640px)" />
       <source data-srcset="/some-image.jpg" />
       <!--[if IE 9]></video><![endif]-->      
       <img data-src="/some-image.jpg" alt="Some Alternative" class="lazyload" title="Some title" />
    </picture>
```

**Comment by DenisMir** [comment]
Thank you for your answer. It does work perfectly now.
