### ISSUE TITLE
additional classes in img element

### ISSUE THREAD

**Issue by gvlachos** [aFarkas/lazysizes#190]
If I have an image element like this:

img class="custom_a lazyload" alt="an image" title="image title" data-srcset="image 1x, image_hd 2x" src="blank.png" 

then after it is loaded the 'custom_a' class is no longer present, instead I get the following: 

img class=" lazyloaded" alt="an image" title="image title" data-srcset="image 1x, image_hd 2x" srcset="image 1x, image_hd 2x" src="blank.png"

It would be great to have any custom classes still present in the element after lazysizes completes processing to allow for any extra CSS styling.

**Comment by aFarkas** [comment]
This is indeed unfortunate. But I can't reproduce this issue. Do you have a test case or can you give me link to your site?

**Comment by gvlachos** [comment]
The site is not released yet so I am afraid it is not possible to give a link. If it helps I am using lazysizes v1.3.1 and  picturefill v3.0.1

**Comment by aFarkas** [comment]
if you have a static version you could zip it and mail it. i don't need the images, fonts, css, just html and js ;-). Or you could create a test case with jsfiddle or jsbin.

The other way is to debug it your own. You can do so by using the break on attribute mutation breakpoint.

Or you can add this script and open the firefox/IE debugger panel (Chrome/Safari does not support "DOMAttrModified" events) and wait until it holds:

```js
<script>
	document.documentElement.addEventListener('DOMAttrModified', function(e){
		var myClassName = 'custom_a';
		if(e.attrName == 'class' && (e.prevValue || '').contains(myClassName) && !(e.newValue || '').contains(myClassName)){
			console.log('removed class');
			console.trace();
			debugger;
		}
	}, true);
</script>
```

**Comment by gvlachos** [comment]
I just tested this a simpler html file where it worked  and re-visit my html pages where I thought it failed only to find that it was a typo from my part that I had removed the custom class when I added the lazyload class. thank you for your time and sorry about that.
