### ISSUE TITLE
Displayed image width

### ISSUE THREAD

**Issue by puyaalexxx** [aFarkas/lazysizes#191]
Hi! 

```
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-sizes="auto" data-srcset=".../featured-image-vertical-295x166.jpg 295w" alt="Horizontal Featured Image" data-maxdpr="1.7" class="attachment-post-thumbnail  lazyautosizes lazyloaded" sizes="750px" srcset=".../featured-image-vertical-295x166.jpg 295w">
```

In this example I have set the image of size 295w, but it takes the container size of 750 , my question is if there is a way to get  the width of 295 not 750 as 

```
$(document).on('lazybeforesizes', function(e){
    console.log(e.detail.width); // 750
   console.log(e.target.width); // 750
});

```

this returned

Regards!!!

**Comment by aFarkas** [comment]
Not 100% sure what you want to achieve here. The `sizes` attribute is all about how the image is displayed and not about what image candidates you have.

You can influence the `sizes` by using CSS or JS:

```html
<img data-srcset="..." data-sizes="auto" style="width: 295px" .... />
```

```js
$(document).on('lazybeforesizes', function(e){
    e.detail.width = 295;
});
```
From the documentation:

**Important: How ``sizes`` is calculated**: The automatic sizes calculation uses the width of the image. If it is below ``40`` (can be configured through the ``minSize`` option), lazysizes traverses up the DOM tree until it finds a parent which is over ``40`` and uses this number. Often the following general CSS rule might help: ``img[data-sizes="auto"] { display: block; width: 100%; }`` (see also [specifying image/iframe dimensions](https://github.com/aFarkas/lazysizes#specify-dimensions)).

The ``data-sizes="auto"`` feature only makes sense if you use the ``data-srcset`` attribute with *width* descriptors which allows the most appropriate image can be selected (It does not make sense if you use the x descriptor or only ``src``.). The width auto-calculated by lazysizes can be modified using the ``lazybeforesizes`` event. Alternatively, the [parent fit plugin](plugins/parent-fit) can be used for sizing images to fit a parent / container, and is the only solution when an image's height needs to be taken into account when fitting it to its container.
