### ISSUE TITLE
Possible bug fadeIn images with Firefox

### ISSUE THREAD

**Issue by WillyBrownHair** [aFarkas/lazysizes#196]
I think, there is an issue about showing fadeIn images this the class `lazyloaded` with Firefox. 
When I scroll quickly the page, Image are fade In correctly when the class change but disappears just after load for appear again with scall  (same effect when the plugin is desabled). 

I test on the demo page of the plugin `https://afarkas.github.io/lazysizes/`. There is the same issue.

browser firefox version : 42.0

my CSS

```
.lazyload, .lazyloading { 
    opacity: 0;
 }

.lazyloaded {
     opacity: 1;
    -webkit-transition: opacity 500ms;
       -moz-transition: opacity 500ms;
         -o-transition: opacity 500ms;
            transition: opacity 500ms;     
}
```

**Comment by aFarkas** [comment]
Not sure, whether I was able to replicate your bug. Through my testing I came a cross the following problem, that appears, if you have the site in cache already.

What to do:
1. Open the page: https://jsfiddle.net/tzutp2np/embedded/result/
2. Load it fully.
3. Hit reload button.

---

What you get:
On subsequent load you first see the image from your previous visit. Then it suddenly switches to the new one.
 
--- 
What you expect:
On subsequent load you should only see one image without switch and flicker.

Now, in case the images are the same, you would see something like this:
1. The image loads.
2. Disappear.
3. Loads again.

Is this what you mean?

**Comment by WillyBrownHair** [comment]
I can't recreate my issue on your exemple. I'm not sur it's a cache problem because I clear the cache of my browser before testing again and the issue is the same. 

Can I send you a

**Comment by aFarkas** [comment]
Yes, you can.
