### ISSUE TITLE
Image-Size issues on iPad Air (Chrome)

### ISSUE THREAD

**Issue by mik3e** [aFarkas/lazysizes#198]
Hi there,

First of all: Great plugin!
I found one issue I can´t explain at the moment: On an iPad Air (Chrome) I´ve the problem, that it always loads a far to small image. I think that´s an issue with the Retina Pixel Ratio or something like that. On my Hi-Res Smartphone (Galaxy S6 Edge with Chrome) it works without any problems.

Can anybody confirm this issue?

Here´s the HTML source I´m using:

<img
                                            src="{$BASE_URL_SSL}templates/tpl/assets/img/productimage-loading.gif"
                                            alt="{$product.PRODUCTS_NAME}"
                                            data-sizes="auto"
                                            data-src="{$BASE_URL_SSL}images/product_images/300x300/{$product.PRODUCTS_ID}_0.jpg"
                                            data-srcset="
                                            {$BASE_URL_SSL}images/product_images/55x55/{$product.PRODUCTS_ID}_0.jpg 55w,
                                            {$BASE_URL_SSL}images/product_images/130x130/{$product.PRODUCTS_ID}_0.jpg 130w,
                                            {$BASE_URL_SSL}images/product_images/150x150/{$product.PRODUCTS_ID}_0.jpg 150w,
                                            {$BASE_URL_SSL}images/product_images/210x210/{$product.PRODUCTS_ID}_0.jpg 210w,
                                            {$BASE_URL_SSL}images/product_images/260x260/{$product.PRODUCTS_ID}_0.jpg 260w,
                                            {$BASE_URL_SSL}images/product_images/280x280/{$product.PRODUCTS_ID}_0.jpg 280w,
                                            {$BASE_URL_SSL}images/product_images/300x300/{$product.PRODUCTS_ID}_0.jpg 300w,
                                            {$BASE_URL_SSL}images/product_images/410x410/{$product.PRODUCTS_ID}_0.jpg 410w,
                                            {$BASE_URL_SSL}images/product_images/475x475/{$product.PRODUCTS_ID}_0.jpg 475w,
                                            {$BASE_URL_SSL}images/product_images/680x680/{$product.PRODUCTS_ID}_0.jpg 680w"
                                            class="lazyload img-responsive product-image" />

Maybe anybody has an idea what´s wrong?

Thanks a lot,
Michael

**Comment by aFarkas** [comment]
Have you tried:

```css
.product-image.lazyload {
    display: block;
    width: 100%;
}
```

**Comment by mik3e** [comment]
Yes,

    .lazyload, .lazyloaded {
          display: block;
          width: 100%;
    }

That blows up the image but it still get´s the wrong image from the server - very low resolution (I think it get´s the 55px version) and then CSS blows it up which makes it look extremely pixelated. I think the jQuery Lib can´t get the correct resolution that´s required.

**Comment by mik3e** [comment]
Same issue on FF for iPad Air. So it´s a device-specific and not browser-specific issue.

**Comment by aFarkas** [comment]
What is the calculated data-sizes?

You can check this with the following code:

```js
jQuery(document).on('lazybeforesizes', '.product-image'. function(e){
    alert(JSON.stringify(e.originalEvent.detail)):
});
```

> Same issue on FF for iPad Air.

Chrome and FF on Ipad are technically both the same. It's a branded apple webview. Apple prohibits other to add new browser technology to iOS.

**Comment by mik3e** [comment]
Desktop: 260 (with chrome inspector in iPad Size an 2x Pixel ration)
iPad: 260

But it doesn´t look like that size... Can I send you a personal message with a demo URL in any way?

**Comment by aFarkas** [comment]
yes, please

**Comment by mik3e** [comment]
I´ve sent you an email....
Interessting: when I look in my apache log the image for 475x475 (which sounds like the correct resolution) is requested:
"[18/Nov/2015:16:54:12 +0100] "GET /images/product_images/475x475/3064_0.jpg HTTP/1.1" 304 349 "https://dev.domain.com/dr-boehm-omega-3-forte-kapseln-60-stk" "Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53"
"

**Comment by aFarkas** [comment]
I haven't received an email. (info (at) corrupt-system.de).

But I think I know what your problem is. I assume you have a) no respimg polyfill and b) no respimg polyfill plugin installed.

I would recommend that you should add the respimg polyfill plugin:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg

If you don't want to use a polyfill for stupid browsrs, add your fallback source as first image candidate in `data-srcset`.

Like so:
```
data-src="{$BASE_URL_SSL}images/product_images/300x300/{$product.PRODUCTS_ID}_0.jpg"
data-srcset="
{$BASE_URL_SSL}images/product_images/300x300/{$product.PRODUCTS_ID}_0.jpg 300w,
{$BASE_URL_SSL}images/product_images/55x55/{$product.PRODUCTS_ID}_0.jpg 55w,
{$BASE_URL_SSL}images/product_images/130x130/{$product.PRODUCTS_ID}_0.jpg 130w,
{$BASE_URL_SSL}images/product_images/150x150/{$product.PRODUCTS_ID}_0.jpg 150w,
{$BASE_URL_SSL}images/product_images/210x210/{$product.PRODUCTS_ID}_0.jpg 210w,
{$BASE_URL_SSL}images/product_images/260x260/{$product.PRODUCTS_ID}_0.jpg 260w,
{$BASE_URL_SSL}images/product_images/280x280/{$product.PRODUCTS_ID}_0.jpg 280w,
{$BASE_URL_SSL}images/product_images/300x300/{$product.PRODUCTS_ID}_0.jpg 300w,
{$BASE_URL_SSL}images/product_images/410x410/{$product.PRODUCTS_ID}_0.jpg 410w,
{$BASE_URL_SSL}images/product_images/475x475/{$product.PRODUCTS_ID}_0.jpg 475w,
{$BASE_URL_SSL}images/product_images/680x680/{$product.PRODUCTS_ID}_0.jpg 680w"
```
-----

Short question: Because I don't have a real iOS only iOS simulator from XCode. Is this happening with the webview of iOS 9.x or with iOS webview 8.x?

**Comment by mik3e** [comment]
Hi,

Sorry for my late answer...
The device is on IOS 8.3 at the moment.

I will try to add the polyfill lib and let you know the result.

I´ve sent the email again - please have a look at your junkmail - maybe it´s there? :)

**Comment by mik3e** [comment]
Thanks for your hint... I´ve added the pollyfill Lib and now the images are shown correctly also on the iPad.

**Comment by aFarkas** [comment]
If this issue isn't fixed, please re-open.
