### ISSUE TITLE
bgset plugin fails on some browsers

### ISSUE THREAD

**Issue by lunelson** [aFarkas/lazysizes#203]
The [jsfiddle demo](https://jsfiddle.net/trixta/bfqqnosp/) for the [bgset plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset) works in current versions of Safari and Firefox but is initially blocked in Opera and does not seem to work at all in Chrome/Canary, in my testing on OSX. Any advice?

**Comment by aFarkas** [comment]
This shouldn't be a problem for you. jsfiddle changed to https, while lorempixel is served through http and therefore blocked. Will need to find fix this.
