### ISSUE TITLE
new plugin request

### ISSUE THREAD

**Issue by boynet** [aFarkas/lazysizes#207]
I hope its ok to request new plugin, I need some way to give lazysizes
some class name,
and function to run when that class is detected..

so instead of always search for '.lazyload' and look for data-src when a class is detected, call some function with the  detected object and let us to decide what to do with it, I hope it clear enough

so I want to give it multiple class to look for, and what function to run when it found like:
lazysizes.lookFor('.my-profile-image').than(function($item){
//do something with the item
}).thanChangeTo('.my-profile-image-loaded');

(I can do something simmilar right now with the lazybeforeunveil but I need to detect multiple class and not only one, and also keep the default functioning of lazyloading normals images)
is it possible? thanks

**Comment by aFarkas** [comment]
Sorry for taking so long to answer.

You can do this only in combination with an adjoining class (`lazyload` or whatever + another class).

lazySizes is built on top of the power of (one) live nodelist returned by `getElementsByClass`. Therefore you need one unique class. If you do this lazyloading normal images will still work.

Here is an example code:

```js
(function(){
	'use strict';
	var lookups = {};

	document.addEventListener('lazybeforeunveil', function(e){
		var cls, i;
		for(cls in lookups){
			if(lazySizes.hC(e.target, cls)){
				for(i = 0; i < lookups[cls].fns.length; i++){
					lookups[cls].fns[i](e.target, cls);
				}
			}
		}
	});

	window.lazySizes.lookFor = function(cls){
		if(!lookups[cls]){
			lookups[cls] = {fns: [], then: function(fn){
				this.fns.push(fn);
				return this;
			}};
		}

		return lookups[cls];
	};
})();
```

This would work with the following markup:

```html
<img class="lazyload" data-src="...." />

<div class="lazyload special-class">
    ...
</div>

<script>
lazySizes.lookFor('special-class').then(function(elem, className){

});
</script>
```

**Comment by boynet** [comment]
Thanks a lot! working great, the base of this script can do a lot more than just dealing with lazyload images
