### ISSUE TITLE
Possible bgset Issue with Photoswipe

### ISSUE THREAD

**Issue by kerns** [aFarkas/lazysizes#208]
I can't be sure this is an issue with `bgset`. I only know that when I implement it, another thing breaks. And when I remove it, the other thing works.

The "other thing" is our [Photoswipe](http://photoswipe.com/) gallery, with thumbnails in a masonry style layout, where the thumbnails are actually background images on a figure element.

When you open/close an image from a Photoswipe gallery, the thumbnail normally animates in a scaling motion up to the fullsize original...and likewise, when you close a full size image, it scales down to the coordinates of the thumbnail, in a transition. You can see an example of this here.

[Photoswipe.com](http://photoswipe.com/)

And all of this works very well with lazysizes using `data-bg` ...all OK and very performant!

But when I paste in the alternative version of this template, using `data-bgset` and `window.lazySizesConfig` ...everything still works, only when entering/exiting a Photoswipe gallery, images no longer animate from and back to their thumbnails. Rather, the animation originates and returns to what seems like (0,0), the top left corner of the page.

Can you see ANY reason why `data-bgset` should interfere with Photoswipe in this way?...and in a way that `data-bg` does not?

**Comment by kerns** [comment]
@aFarkas The `getThumbBoundsFn` [described here](http://photoswipe.com/documentation/options.html) seems to be the one that `data-bgset`disagrees with. Any idea what the issue might be?

**Comment by aFarkas** [comment]
I couldn't look into this. But I suspect the following:

`data-bgset` delegates the actual source selection to the browser using `picture`/`srcset` and reads the `currentSrc` property from the `img`. This property is only updated after the image candidate was successfully loaded. This means the source is written much later to your `div` element than it would be written using `data-bg`. Which means that photoswipe is working on an empty/none source.

Only way I can think of, is that you must delay the animation after the image was loaded.

**Comment by kerns** [comment]
@aFarkas Thanks. And... [I made a pen](http://codepen.io/kerns/pen/wMMwoa)! If you want to see the problem yourself.

I am not sure if your suggested work-around is viable, or how exactly to implement it, but I appreciate the input.
