### ISSUE TITLE
Images are distorted in terms of dimension? Isotope + LazySizes

### ISSUE THREAD

**Issue by danno2423** [aFarkas/lazysizes#212]
Hey aFarkas!

First of all, thank you so much for your lazyload + isotope thingy. I was searching for one that would work and I found your jsFiddle, and it worked beautifully for me...except for one problem:

My images, in terms of dimension, become distorted. For example, if you scroll over to my demo site:

http://danno2423.github.io/writing.html

You can see that some of the images render properly and others are stretched out weird, i.e. Aziz Ansari, the Indian guy in the lower right. I've tried to research this issue, and i think I found an example where you helped someone out, but honestly I couldn't understand how it worked.

I'm very new to coding, basically been doing it for 6 months while taking a class, so I'm still very much a beginner. Any help with this problem would be so greatly appreciated. I see you are quite helpful with troubleshooting your products, which I genuinely appreciate.

If you want to check out the repo of my project, here it is:

https://github.com/danno2423/danno2423.github.io

The writing.html file is the one with the isotope+lazysizes layout.

Thank you so much!!!
danno

**Comment by danno2423** [comment]
It seems like this might be relevant. This is the discussion I found before, but I don't know what to do?

https://github.com/aFarkas/lazysizes/issues/118

**Comment by aFarkas** [comment]
You have removed your content.

There are two solutions to this problem:

a) specify width and height of your images using the aspect ratio technique
b) only specify width and progressively update isotope after load

a) Is a little bit more complicated, but the recommended way.
b) Should be used if you can't retrieve the aspect ratio before images are loaded.

Here is how you do a):

Add the following CSS to your stylesheet:

```css
.ratio-box {
    position: relative;
    height: 0;
    display: block;
    width: 100%;
    /* padding-bottom is calculated and rendered in to HTML */
}

.ratio-box img,
.ratio-box iframe,
.ratio-box video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: block;
}
```

Now add the following markup:

```html
<div class="ratio-box" style="padding-bottom: 42.85% /* calc(75 / 175 * 100%)*/;">
    <img
        data-sizes="auto"
        data-srcset="http://placehold.it/175x75 175w,
        http://placehold.it/350x150 350w,
        http://placehold.it/700x300 700w,
        http://placehold.it/1400x600 1400w"
        data-src="http://placehold.it/700x300"
        class="lazyload" />
</div>
```

If you have a 640x360 image you can do the following math:

```
360 / 640 * 100% = 56.25
```

Which yields to the following markup:

```html
<div class="ratio-box" style="padding-bottom: 56.25% /* calc(360 / 640 * 100%)*/;">
    <img
        data-sizes="auto"
        data-src="http://placehold.it/640x360"
        class="lazyload" />
</div>
```

**Comment by aFarkas** [comment]
In 118 I showcase the b) workaround. For this to work you need to remove the aspect ratio markup and CSS and only use:

```css
.isotope-item img {
  display: block;
  width: 100%;
  height: auto;
}
```

And then your relayout isotope on image load with the following JS:

```js
$('.isotope-wrapper')
    .each(function(){

        var $isotope = $('.isotope-box', this);
        var $filterCheckboxes = $('input[type="radio"]', this);

        var filter = function(){
            var type = $filterCheckboxes.filter(':checked').data('type') || '*';
            if(type !== '*'){
                type = '[data-type="'+ type +'"]';
            }
            $isotope.isotope({ filter: type });
        };

        $isotope.isotope({
            itemSelector: '.isotope-item',
            layoutMode: 'masonry'
        });

        $isotope[0].addEventListener('load', (function(){
            var runs;
            var update = function(){
                $isotope.isotope('layout');
                runs = false;
            };
            return function(){
                if(!runs){
                    runs = true;
                    setTimeout(update, 33);
                }
            };
        }()), true);

        $(this).on('change', filter);
        filter();
    })
;
```

**Comment by danno2423** [comment]
Thanks Alexander!  I will try a). Also, I apologize for removing my content! Here it is:

http://nycda.zone/dan587/portfolio_new/writing.html

Let me know if you need me to upload a repo along side it. I will try your fix and report back. Thank you for your answer!

Dan.

**Comment by danno2423** [comment]
Hi Alexander,

I've tried both A) and B), and things are screwing up majorly. It seems now that the pictures are all the same size, but the proportions are all out of whack which looks even worse than before. I uploaded this for you to take a look at. (This is A).

Here's the repo:
https://github.com/danno2423/portfolio_help

And here's the server upload:
http://nycda.zone/dan587/portfolio_help/writing.html

Writing.html is the page where I attempt to deploy your lazysizes build.

Is there anyway you would be open to a short Skype conversation to fix this problem? I would so appreciate it, it would make my day, I would bake you 10,000 virtual cookies. Your project saved my ass and I'm so close to getting it to work, but I don't know what is going wrong. Even 10 minutes of your time would be greatly appreciated. I'm young and trying to kickstart my career with this portfolio.

Here is my skype:
danno2423

Here is my email:
danno2423@gmail.com

If you would want to set up a time to chat, let me know what is convenient for you.

Thank you for all your help thus far!!!!
Dan

**Comment by aFarkas** [comment]
https://github.com/danno2423/portfolio_help/pull/1

**Comment by danno2423** [comment]
It still doesn't work :(

http://nycda.zone/dan587/portfolio_help/writing.html

**Comment by danno2423** [comment]
It worked!!!

http://nycda.zone/dan587/portfolio_help-master/writing.html

I have a question. For the portrait photos (photos more tall than wide), what do I do in terms of the aspect ratio markup calculations? For example, if a picture was 720 x 1280, how would i calculate the ratio? I see that in the code you did not use the ratios for the portrait photos?

```html
<div class="isotope-item item-portrait" data-type="sports">
	<a href="writing/brettmyers.html" class="ratio-box" style="padding-bottom: calc(600 / 400 * 100%);">
		<img data-sizes="auto" data-src="img/writing_img/brettmyers.jpg" class="lazyload" />
	</a>
</div>
```

**Comment by danno2423** [comment]
I'm so confused. Did you use the ratios for portrait and landscape photos? Take a look at this:

```html
<div class="isotope-item" data-type="life">
   <a href="writing/bodyhair.html" class="ratio-box" style="padding-bottom: 75.00% /* calc(450 / 600 * 100%)*/;">
	<img data-sizes="auto" data-src="img/writing_img/bodyhair.jpg"  class="lazyload" />
    </a>
</div>
<div class="isotope-item item-portrait" data-type="sports">
   <a href="writing/brettmyers.html" class="ratio-box" style="padding-bottom: calc(600 / 400 * 100%);">
		<img data-sizes="auto" data-src="img/writing_img/brettmyers.jpg" class="lazyload" />
   </a>
</div>
```

Why does one have the percentage in front and the other does not? Did it just comment out the calculation in the first and not in the second? So for the second portrait picture, the padding-bottom aspect ratio is 150% ?

Dan

**Comment by danno2423** [comment]
I figured it out:

calc(height/width * 100%)

thanks for this help.
