### ISSUE TITLE
SEO Improved, but how?

### ISSUE THREAD

**Issue by muratcorlu** [aFarkas/lazysizes#215]
Your readme file says for SEO:

> lazysizes does not hide images/assets from google. No matter what markup pattern you use.

But, I couldn't understand how we does not hide images from google with a markup like that:

    <img data-src="image.jpg" class="lazyload" />

That `img` tag has not a `src` attribute. How google can read the url of image? Is there any undocumented trick?

**Comment by aFarkas** [comment]
The problem with google bot is not that google doesn't execture JS. In fact google bot exectues JS. The problem with the google bot and normal lazyloaders is, that google doesn't scroll/interact with your website.

lazysizes detects, whether the user agent is capable to scroll and if not, reveals all images instantly.

**Comment by muratcorlu** [comment]
OK then. I created a pull request to add that explanation to Readme document.

**Comment by johndillonuk** [comment]
OK but you mention only Google which does read javascript, what about all the bots and social engines which dont?
Why is it not possible (like http://ivopetkov.com/b/lazy-load-responsive-images/ for example) to leave src intact for these?

**Comment by aFarkas** [comment]
If you read the documentation you will see that this is also an option: https://github.com/aFarkas/lazysizes#modern-transparent-srcset-pattern

**Comment by johndillonuk** [comment]
Ah brilliant thanks. Really great product thanks for sharing.
