### ISSUE TITLE
unload plugin: recheck elements on each "run"

### ISSUE THREAD

**Issue by rdehouss** [aFarkas/lazysizes#218]
Hi,

Thx for the plugin "unload".
But, for me, it would need to redo this:
<code>
checkElements = document.getElementsByClassName([config.unloadClass, config.loadedClass].join(' '));
</code>
on each unloader.checkElements because it's possible that new images has been added via ajax for example.

WDYT?

Cheers,

Raphaël

**Comment by aFarkas** [comment]
`document. getElementsByClassName` returns a live nodelist and is always up to date
