### ISSUE TITLE
Firefox doesn't add the 'lazyloading' class

### ISSUE THREAD

**Issue by LFeh** [aFarkas/lazysizes#219]
Hi, I am using the Lazysizes in my last projects and is awesome!

But I am use a blur effect for a soft transition in the images.

```
.lazyload
.lazyloading  
  filter: blur(50px)
  transition filter .4s, -webkit-filter .4s

.lazyloaded
  filter blur(0)
```

The problem is because the Firefox doesn't add the `.lazyloading` during the transition and the blur effect doesn't work.

Can you help me?

**Comment by aFarkas** [comment]
@LFeh 

Thx for the issue, I actually always add the lazyloading class and remove it as soon as the img is fires the load event. At this time the image gets the lazyloaded class.

Maybe your issue is fixed if you do this:

```
.lazyload
.lazyloading
.lazyloaded  
  filter: blur(50px)
  transition filter .4s, -webkit-filter .4s

.lazyloaded
  filter blur(0)
```

Or better:

```
.my-image  
  filter: blur(50px)
  transition filter .4s, -webkit-filter .4s

.my-image.lazyloaded
  filter blur(0)
```

**Comment by LFeh** [comment]
Hey @aFarkas, thanks for your reply.

But, the problem is curious now.

I used the second technique (add the double class). When I added the class `.lazyloaded` in devtools for test it works, but doesn't work when I added in the project.

You can test here: http://www.filtro.is/

Do you know what the problem?

**Comment by aFarkas** [comment]
You were right. In FF the lazyloaded class was added to early (which is a FF bug in my eyes, need to clarify). 

I have fixed this. Unfortunately the effect isn't that good in FF. Sometimes it seems, that FF isn't rendering the loaded image right and then does the blur from black. (Which is another FF bug, but something I can't fix).

You can try the newest version in master.

If you want to go down this rabbit hole you can try to fix this your own, by doing something like this:

```js
document.addEventListener('load', function(e){
    if(e.target.contains('lazyloading') && e.target.contains('lazyblur'){
        setTimeout(function(){
            e.target.classList.add('lazyunblur');
        }, isFF ? 150 : 0);
    }
}, true);
```

**Comment by LFeh** [comment]
Perfect @aFarkas, it work very good!

````
document.addEventListener('load', function(e) {
    if(e.target.contains('lazyloading') && e.target.contains('lazyblur')) {
        setTimeout(function(){
            e.target.classList.add('lazyunblur');
        }, isFF ? 150 : 0);
    }
}, true);
````

I added an `)` in if (jsLint warning me) and it fixed 100% right now!

**Comment by thasmo** [comment]
This still seems to be an issue in Firefox. What I did was to use a @supports hack:
```css
@supports (-moz-appearance: meterbar) {
    .lazyloading.lazyblur {
        transition-delay: 50ms;
    }
}
```
