### ISSUE TITLE
data-bgset for Retina images.

### ISSUE THREAD

**Issue by chriscodeweb** [aFarkas/lazysizes#223]
Hello, Thanks for your great plugin! 

Is it possible to use the data-bgset for retina images?
Just like the data-srcset using 1x and 2x to target the 2 variant image? but then inside a media query?
<img data-srcset="responsive-image1.jpg 1x, responsive-image2.jpg 2x" class="lazyload" />

Something like this?
`<div class="lazyload"
                data-bgset="Image.jpg x1, Image@2x.jpg x2 [(max-width: 766px)]></div>`

Is something like this possible?

**Comment by aFarkas** [comment]
Yes, it is possible. But you need to fully replicate the "picture" element here (i.e.: You forgot the last `source` without a media attribute).

```html
<div class="lazyload" data-bgset="Image.jpg x1, Image@2x.jpg x2 [(max-width: 766px)] | data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></div>
```

Also note, I always would prefer width descriptors with `data-sizes="auto"`. The width descriptor does take retina also into account and also accounts for different display sizes. (It gives you simply more):

```html
<div class="lazyload" data-bgset="Image-800.jpg 800w, Image-1500.jpg 1500w [(max-width: 766px)] | data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-sizes="auto"></div>
```

**Comment by chriscodeweb** [comment]
Thank you so much for these examples and your quick reply! :) 
I will implement this technique for the website that I am going to work on. You saved the day ;)

**Comment by chriscodeweb** [comment]
Thank you very much Alexander for your quick reply! 
Unforunately I did not get it to work.  I tried it with for example this code:
`<div class="box ratio-container lazyload" 
     data-bgset="http://placehold.it/200x400?text=desktop-1x x1, http://placehold.it/400x800?text=desktop-2x x2 [(max-width: 500px)] | http://placehold.it/400x800?text=fallback"></div>`

And this is the link to the codepen fiddle [http://codepen.io/chriscodeweb/pen/XXyVvX](url) 

All I want to do is exactly like the standard html but then with a background picuture and with retina support (1x and 2x)
`<picture>
  <source srcset="http://placehold.it/200x400?text=desktop-1x 1x, http://placehold.it/400x800?text=desktop-2x 2x"       
          media="(min-width: 990px)">
  <source srcset="http://placehold.it/300x450?text=tablet-1x 1x, http://placehold.it/600x900?text=tablet-2x 2x" 
          media="(min-width: 750px)">
  <img srcset="http://placehold.it/150x250?text=mobile-1x 1x, http://placehold.it/300x500?text=mobile-2x 2x" 
       alt="some picture">
</picture>`

Could you please help me out?

Thanks in advance!

Chris.

**Comment by tststs** [comment]
use `2x` and `1x` instead of `x1` and `x2`.

e.g.:
`data-bgset="img/image-s.png 1x, img/stories/viessmann/story-viessmann-s@2x.png 2x [--small] | ...`

**Comment by chriscodeweb** [comment]
Thanks!! 👍👍

**Comment by chriscodeweb** [comment]
Thanks!! I will try it! 👍👍

**Comment by SirBirdy** [comment]
does this work also in IE11? when I use 1x, 2x its not working :( without anything so just 1 image it works (I added respimg and picturefill)

**Comment by aFarkas** [comment]
Using picturefill it should work in ie11. Respimg polyfill does not fully support the X syntax as documented any X syntax can be rewritten into the w syntax. 

There is no point to use the X syntax (it's only shorter).

**Comment by nikadevs** [comment]
Hi,

I've downloaded the latest lazysizes.js and unveilhooks.js but looks like the data-bgset functionality is missed now. Can you back this functionality, because now I've to manually add this code to my scripts, to enable the data-bgset:

`document.addEventListener('lazybeforeunveil', (function(){
    var parent = document.createElement('div');

    return function(e){
        var set, image, load;

        if(e.defaultPrevented || !(set = e.target.getAttribute('data-bgset'))){return;}
        image = document.createElement('img');
        image.setAttribute('sizes', e.target.getAttribute('data-sizes') || (e.target.offsetWidth +'px'));

        load = function(){
            var bg = image.currentSrc || image.src;
            if(bg){
                e.target.style.backgroundImage = 'url('+ bg +')';
            }
            if(lazySizes.cfg.clearAttr){
                e.target.removeAttribute('data-bgset');
            }
            image.removeEventListener('load', load);
            parent.removeChild(image);
            image = null;
        };

        image.addEventListener('load', load);

        image.setAttribute('srcset', set);
        parent.appendChild(image);
        if(!window.HTMLPictureElement){
            if(window.respimage){
                respimage({elements: [image]});
            } else if(window.picturefill) {
                picturefill({elements: [image]});
            }
        }

        if(image.complete && (image.src || image.currentSrc)){
            load();
        }
    };
})());`

Thanks.

**Comment by aFarkas** [comment]
@nikadevs 
I don't really understand. Nothing has changed with the bgset plugin. Can you please create a tescase that demonstrates what you expect and what fails?

Only thing it is in most cases deprecated and you should use `object-fit`. There is also a polyfill to add support for bad browsers.

**Comment by nikadevs** [comment]
Hi,
Can you please point me, where is the bgset plugin is placed? I have lazysizes.js and unveuilhooks.js and the code example in this topic is not working.
Thanks for great plugins!
