### ISSUE TITLE
Fire an event right after image is loaded

### ISSUE THREAD

**Issue by obzenner** [aFarkas/lazysizes#225]
@aFarkas I might have overlooked something in the documentation, but I think it would be handy to fire an event right after the image is loaded so that some other actions could be performed.
In my case there is a little preloader element that I would like to remove right after a given image is loaded.
I could achieve it by adding `triggerEvent(e.target, 'lazyImageLoaded');` to `switchLoadingClass`:

```
        var switchLoadingClass = function(e){
            addClass(e.target, lazySizesConfig.loadedClass);
            removeClass(e.target, lazySizesConfig.loadingClass);
            addRemoveLoadEvents(e.target, switchLoadingClass);
            triggerEvent(e.target, 'lazyImageLoaded');
        };
```

I then listen to that event and then trigger the relevant function:

```
            document.addEventListener('lazyImageLoaded', function(e){
                that.removeGifPreloader(e.target);
            });
```

Maybe an option in config `afterLoadEvent` or similar could work? What do you think?

**Comment by maketimetodesign** [comment]
You can use the traditional load event on the image for this problem...

`const imgs = document.querySelectorAll('img');

  if (imgs === null) {
    return;
  }

  Array.from(imgs).forEach(img => {
    img.addEventListener('load', () => {
      // Do what you need to do...
    });
  });
`

**Comment by seanpoulter** [comment]
I'd say this issue can be closed.

**Comment by simplenotezy** [comment]
No @maketimetodesign - that won't work for background images.

**Comment by simplenotezy** [comment]
Plus one eventlistener is better than 100's.

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-core.js#L429
