### ISSUE TITLE
Weird issue with bgset - lazyload class flashing

### ISSUE THREAD

**Issue by alexslack0** [aFarkas/lazysizes#227]
Hello,

First of all thanks for your great plugin, I've been experimenting with it for a while.
I recently found a weird problem with the plugin. 

I'm using the bgset plugin in order to lazyload some background images on my website. Let me make an example markup to help you understand what's going on:

```
<div class="some-class another-class lazyload" data-bgset="image.jpg" data-sizes="auto">
  ...some things going on in here
</div>
```
and css:

```
.some-class.another-class {
  background-image:url('really-really-low-quality-of-image.jpg');
}
```

So, I'm loading with CSS a really low quality of the image that I want just to be there, and I lazyload the full quality image.

It works as expected. My website loads the low quality image first, and when/if needed the full quality. Great.

BUT the weird part is this: When I open the DevTools from chrome (or any other browser), the div of the image has .some-class .another-class and "lazyloaded/lazyloading" classes keep switching every few miliseconds.

Everything works fine though. Any ideas?
URL : http://bit.ly/1VgLZJs
Actual class name: .su-second-section-wrapper

What I tried: 
- remove background-image from css - Didn't work
- Use parent-fit plugin - Didn't work
- no console errors
- If you switch tab with DevTools open, you'll see that the switching stops.

I used to have the exact same markup (I think) just a few days ago, and it worked fine, without the class switching bug. But after that I had an accident with GIT, and everything got overwritten with a previous version of the template file (Wordpress theme), so I'm guessing that this bug is caused by missconfiguration by my side. Do you have any ideas from the top of your head?

Thanks for any advice!

**Comment by aFarkas** [comment]
no, but i have to look into this, because it's quite bad.

**Comment by alexslack0** [comment]
Well don't worry, it's probably caused by my bad code, I don't think it's a bug! I just asked for some suggestions, there's no need to waste your time on that! 

I also tried to load the first image (via CSS) as a jpg/png file instead of Data URI. It didn't work.

**Comment by alexslack0** [comment]
Oh god, ok I should probably do some more research before posting an issue next time.

After a shot in the dark, I found out that the problem was caused by Cloudflare's Rocket Loader. So I guess it's a bug?

Anyway, sorry for the trouble and thanks for your time and your great plugins! Saved me about 1-2s of loading time!

**Comment by estellechvl** [comment]
Hello, I have the same "flashing class" issue.

Once an image is loaded, the 'lazyloaded' class is added, but it removes the other class that is on the image. (So I guess that is a first bug?)

before image is loaded :
`<img class='picture__image'>`

after image is loaded (note the blankspace):
`<img class=' lazyloaded'>`

I'm guessing the expected behaviour would be :
`<img class='picture__image lazyloaded'>`

Anyway, since I don't need the lazyloaded class, I used the js API to find a way to fix this : 
`window.lazySizesConfig.loadedClass = 'picture__image';` 

Now, after the image is loaded, the class "picture__image" is removed and added again, but every few miliseconds, which of course drives my computer crazy.

Any idea where these bugs could come from ?

**Comment by aFarkas** [comment]
I can't say anything about this. I assume it's also the rocket loader bug mentioned above.

Simply add `document.getElementsByClassName.toString()` into your console. This should return `"function getElementsByClassName() { [native code] }"`. If it doesn't, than you know, that the script where it comes from is done by a very bad developer. And you should remove it.

**Comment by estellechvl** [comment]
It does return `"function getElementsByClassName() { [native code] }"` 
So I guess the bug does come from the Rocket Loader. Unfortunately my code is only local so I can't share any link. I'll try to find a solution by myself then. Thank you for your quick answer !

**Comment by aFarkas** [comment]
If it is returning `"function getElementsByClassName() { [native code] }"`it should be actually fine. If you have the code you can use codepen, jsfiddle etc. and if you know, that you are using rocket loader than simply remove it. It is bad code.
