### ISSUE TITLE
Don't load images that's display: none;

### ISSUE THREAD

**Issue by landerss0n** [aFarkas/lazysizes#228]
Hi, thanks for an great plugin.

Im having two divs that I use data-bgset on, and on mobile I only show one of them. However both of the images loads when I only have one of them to display: block; in css. The other one is display: none;

**Comment by aFarkas** [comment]
This is strange. Because that is the normal behavior. Can you create a testcase?

**Comment by landerss0n** [comment]
My bad, I had another image tag under. We can close this
