### ISSUE TITLE
400w doesn't trigger on iOS

### ISSUE THREAD

**Issue by vegardsando** [aFarkas/lazysizes#229]
I'm using Craft and I have this issue where the smallest image doesn't load on iOS. It also happens in Chrome on my Mac when I simulate iPhones.

Here is my code as of now:

```
            {% set img = entry.bilde.first | default(false) %}
            {% set focalpoint = img.focalPoint | default('50% 50%') %}

            {% set bilde = craft.imager.transformImage(img, [
                { height: 450, width: 320, position: focalpoint, ratio: "0" },
                { width: 840 },
                { width: 1680 },
                ], { mode: 'crop' }) %}

            <img class="lazyload" data-sizes="auto" src="{{ craft.imager.base64Pixel(16, 9) }}" data-srcset="{{bilde[0].url}} 400w, {{bilde[1].url}} 767w, {{bilde[2].url}}" alt="{{img.title | default("")}}">
```

I've noticed that it's the second image that gets loaded, the one where 767w is set. And it only triggers at that exact pixel width. I also tried to use `{{bilde[0].url}} 767w,` instead of `{{bilde[1].url}} 767w,` and that triggers the correct image. Am I doing something obviously wrong here?

Btw, this is the site:
http://135229-www.web.tornado-node.net/

It's the first top image I'm talking about. It looks like it creates the correct images, and I don't do anything custom in js.

**Comment by aFarkas** [comment]
This is not really an issue. iPhone has a pixel ratio of two, which means if you see this image with 320/375 display width you need 640/750 for full image quality.

But your site reveals another problem.

All your image candidates need a width descriptor, but on your site the descriptor is missing from the las image candidate.

Please close if this helps.

**Comment by vegardsando** [comment]
Ah I see, at least about the width descriptor :)
But, doesn't your plugin have a 2x option of images? What would be the point of using images with 400w descriptor then? If it never uses it? Or is it only retina displays this applies to?

**Comment by aFarkas** [comment]
Yes this only applies to retina images. The width descriptor also includes retina support. There is no need to use density descriptors, if you already use width descriptors.
