### ISSUE TITLE
lazy load on background-image

### ISSUE THREAD

**Issue by Szymon-dziewonski** [aFarkas/lazysizes#23]
Hello, 

   What I'm tryin to do is loading some element <div class="load" style="background-image:" data-bg="">
and its empty and lets say, after this on click for example 
$(".load").click(function(){
      $(".sliceImg").css({
               backgroundImage: 'url(pictures/pic.jpg)'
      }).attr("data-bg", "newPic.jpg");
});

And it's doesnt work, it is loading new background-image but set data-bg (on inspector element) but script does not change background for better quality.

Is there anything so I can update script after click ? or make it working?

Thank you :)

**Comment by serenity81** [comment]
Thanks for the info:

How do you import the module I see you have to add:
import lazySizes from 'lazysizes';
import 'ls.unveilhooks';

1) But where do you add these lines?

2) Do you also have to add a link as such:
<script src="lazysizes.min.js" ></script>
