### ISSUE TITLE
LazySizes and Packery

### ISSUE THREAD

**Issue by O-Dog5960** [aFarkas/lazysizes#230]
I have tried StackExchange, but that didn't help so this is last place I can think of to get help. I am trying to use packery along with lazysizes, but I can not seem to get packery to fire after my images load. 
`var $container = $('#container');
        $container.packery({
            itemSelector: '.item',
            percentPosition: true,
          });`
This is the script to run packery, and if I put in the console in chrome it works perfectly, I just can't figure out how to have it fire after the images load. If you need any more info about my code, just let me know any help would be greatly appreciated.

**Comment by aFarkas** [comment]
Have you read:

a) https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps

and

b) https://github.com/aFarkas/lazysizes#updateing-layout-of-js-widgets

?

**Comment by O-Dog5960** [comment]
I have read a, but because I am using multiple sizes based on screen size (300w, 500w,750w) the height is different for each screen so I can't accurately define the heights of every element. How exactly would you do b? (I'm a beginner to JS, sorry)

**Comment by aFarkas** [comment]
@O-Dog5960 
About a) it is not about knowing the height, it is about knowing the aspect ratio of your images. In case you use `srcset`, this should be doable.

About b):

```js
$('#container').each(function(){

    var $module = $(this);
    var update = (function(){
        var running;
        var run = function(){
            running = false;
            $module.packery('layout');
        };
        return function(){
            if(!running){
                running = true;
                setTimeout(run, 9);
            }
        };
    });

    // Note: Instead of waiting for all images until we initialize the widget
    // we use event capturing to update the widget's layout progressively.
    this.addEventListener('load', update, true);

    $module.packery({
        itemSelector: '.item',
        percentPosition: true,
    });
});
```

**Comment by O-Dog5960** [comment]
I am getting so frustrated! Your code is perfect! If I run it in the console after all the images load, it works perfectly, your code even triggers packery without me needing to manually run it in the console, except that it only runs once and all the images overlap. I don't understand what is going on, it seems that for some reason no matter what, it will not continuously run every time an image loads! Thank you for trying, though, if you know of any other ways that would be amazing but don't let this keep you up at night.

**Comment by aFarkas** [comment]
I can provide you with a fix, if you could replicate your issue with codepen, jsfiddle, jsbin or similiar.
