### ISSUE TITLE
Image Size problem with isotope plugin

### ISSUE THREAD

**Issue by ncou** [aFarkas/lazysizes#231]
Hi,

First very nice plugin :)
I have a problem when i use lazysize in the isotope plugin. The size seems incorrect after lazyloading the picture.

If i use an empty src gif but with the right "width" and "height" args

ex : -img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="600" height="800" data-src="http://placehold.it/600x800" class="lazyload" >

The size is not correctly interpreted. And the masonry function is broken.
Codepen example : http://codepen.io/anon/pen/adrezJ

But If I set the src arg to the right picture, the masonry plugin rendering is correct.

ex : -img src="http://placehold.it/600x800" width="600" height="800" data-src="http://placehold.it/600x800" class="lazyload" >

Codepen example with the working mansonry rendering : 
http://codepen.io/anon/pen/yeWmLy

Do you have a workaround for this issue ?

PS : I tried data-sizes=auto but without success.

Thank you.

**Comment by aFarkas** [comment]
The solutions are documented here:
https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps

Here is also an older issue with isotope, that provides examples with both solutions documented above:
https://github.com/aFarkas/lazysizes/issues/118

Please close if this helped.

**Comment by aFarkas** [comment]
Please re-open if it didn't help.

**Comment by ncou** [comment]
hi,

sorry for the late answer.
I made it work with the following code.

        // init isotope.
	var $grid = $('#container').isotope({
	    itemSelector: '.item',
	    percentPosition: true,
	    layoutMode : 'masonry'
	  });

	//***
	// refresh after each picture lazyloading
	$('#container').each(function(){
	    var $module = $(this);

	    var update = (function(){
	        $module.isotope('layout');
	        //return true;
	    });

	    this.addEventListener('load', update, true);   
	});


Hope this help. you can close the issue. thank you.
