### ISSUE TITLE
bgset not working on Edge 13

### ISSUE THREAD

**Issue by derghostface** [aFarkas/lazysizes#235]
The plugin bgset is not working anymore in Microsoft Edge 13. You can see this in the example provided in the bgset documentation:
http://jsfiddle.net/trixta/w96o9xm5/

It works with Edge 12, but not 13.

**Comment by aFarkas** [comment]
Stupid question. I use ievms https://github.com/xdissent/ievms and with edge it is working.

As edge version in more actions -> settings -> about this app it says: Microsoft 20.10240.163...

How can I get the normal version number and more important, how can I update?

**Comment by derghostface** [comment]
I am using browserstack.com for testing. When I am starting the virtual machine it says "Starting real Edge 13 on Windows 10". Then when I go to settings -> about this app it says:
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

Don't know how to update, because I don't have Edge installed on my local machine.

**Comment by aFarkas** [comment]
I will fix this by the end of this week.

**Comment by aFarkas** [comment]
In short:
https://connect.microsoft.com/IE/feedbackdetail/view/2405716/srcset-parser-for-img-source-elements-lacks-support-of-the-future-compat-h-descriptor-parsing

**Comment by derghostface** [comment]
Thx for reporting!
