### ISSUE TITLE
Lazysizes + full page (heavy) images + slow connection = fast loading. Can that be achieved?

### ISSUE THREAD

**Issue by ModDM** [aFarkas/lazysizes#237]
Dear aFarkas,

​​I have some questions regarding website performance. In summary the title shows my main question. I read Lazysizes has features to make the performance of the site faster. I am rebuilding our website and I seriously want to reduce loading time of images and (if possible) other elements.

I use Fullpage.js with background images.

Example:
[http://alvarotrigo.com/fullPage/examples/backgrounds.html](http://alvarotrigo.com/fullPage/examples/backgrounds.html)

Above is an example of the creator of Fullpage. Well, of course this is not acceptable as a performance for mobile devices on slow connections. Do you know what I mean?
But still I want to use these kind of full page images, preferably background images, without affecting the performance of the page. I know it's a challenge. Because my full page images are background images, the content that is placed on top of it, like text and other images, must have the highest loading priority and full screen images must have the lowest loading priority.

Of course it's essential to hide the image untill the user needs it (he scrolls to it or uses CTRL-F to jump to it and then the image is on screen and will load), and that's where I use Lazysizes for.

But can Lazysizes also do some extra performance improvement when the connection is too slow, to prevent that the loading process of an on-screen image affects the overall page performance negatively? Does it adapts to lower connections or is suitable for those cases, for example by sending a very limited light version of the (background) image or make the image load with a very low priority?

In my case I want to use high quality textures with big shapes (images of 1400 x 1400 pixels). Because they have a sober light color, just for the background (put text on top of it) it is no problem if they load totally blurred or something like that.

I am very interested in your advice what is the best to do and thanks in advance,

With kind regards,

ModDM

**Comment by rajruprai** [comment]
Have you looked into [Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)? This can help loading images on all devices. 

As it relates to only loading images that are used as backgrounds with text on top, have you tried writing your own JS to detect the user's scroll and if they are within reach you can load the image?
