### ISSUE TITLE
Multiple data-uri requests in Chrome

### ISSUE THREAD

**Issue by Regaddi** [aFarkas/lazysizes#238]
Hi,

with the following use-case I'm experiencing some strange behaviour in Google Chrome:

Having a picture with several source-Tags and a data-uri as default-src on the image leads to one data-uri request per source.

A demo can be found here: http://codepen.io/Regaddi/pen/adQdBb

If you open the Chrome Dev Tools and look into the Network Panel/Img, you'll see 3 requests onload to the default data-uri.

![bildschirmfoto 2016-02-23 um 10 42 52](https://cloud.githubusercontent.com/assets/1336590/13247505/3ae790b2-da1a-11e5-86de-979bd6fb11f1.png)

The same example without lazysizes: http://codepen.io/Regaddi/pen/QyeyZw

![bildschirmfoto 2016-02-23 um 10 44 30](https://cloud.githubusercontent.com/assets/1336590/13247548/734ec70e-da1a-11e5-9d63-c8292ca56fa6.png)

You can see, here's only one data-uri request (besides the real image request).

Yes, it's only a "local" request and not even a real network request.
But our customers get picky about this behaviour.

My Chrome version is 48.0.2564.116 (64-bit).
lazysizes version: your latest from master branch.

It'd be supercool, if you'd had a look at this :)

**Comment by LOK-Soft** [comment]
An analysis and fix of this behavior would be really nice.

**Comment by aFarkas** [comment]
I can't fully replicate this issue. But I have two "requests". One initialized by the page and another by lazysizes. This effect can be reproduced by the simplest code:

```js
Array.prototype.slice.call(document.querySelectorAll('source[data-srcset]')).forEach(function(source){
    source.srcset = source.getAttribute('data-srcset');
});
```

This is indeed interesting, but as you see there isn't anything wrong with the code and more important I can't reproduce this with Chrome "50.0.2657.0 canary" anymore.

Can you?

> But our customers get picky about this behaviour.

I'm sorry.

**Comment by aFarkas** [comment]
@Regaddi

I hope you are fine with this answer. Maybe @yoavweiss can explain, what was/is going on here. But I don't see a need for us frontend developers to fix this issue.

**Comment by Regaddi** [comment]
@aFarkas You can reproduce the issue, when your pen-view is below 600px width.

There's another pen using your code snippet from above, which fully reproduces the data-uri requests (but, as said, only in mobile viewport)...

**Comment by yoavweiss** [comment]
I could dig deeper to see what happens here, but I'm not sure I understand the problem. Is it a reporting issue? Do you see perf costs (in the timeline) related to the multiple calls?

Looking at the code, it seems that each setting of `<source>`'s srcset triggers a mutation event, which picks an candidate resource, and it makes sense that if you do that one by one, you'd end up with multiple candidate resources. That has no impact on non-local images, as the image loading is async, but data-URI images do get picked and processed synchronously. (I tried to [tackle that](https://bugs.chromium.org/p/chromium/issues/detail?id=514206) but it resulted in perf regressions and got reverted. I probably need to get back to that.)

**Comment by aFarkas** [comment]
@yoavweiss 
Sorry for taking so long.

Thanks for explaining what is happening here. I don't see it as a problem. It could have been only a symptom for something else.

The only thing I don't understand is why I couldn't replicate it in Chrome canary (50.x).

At the end it seems just an issue with some clients not understanding the web.
