### ISSUE TITLE
Are Lazy Loaded Images Crawled By Google?

### ISSUE THREAD

**Issue by ModDM** [aFarkas/lazysizes#239]
Regarding the widely found issue on the web about dynamically loaded content that is / was not crawled by Google, my question is if Lazysizes images are available for Google to crawl it and to show it for example on Google Images site (images.google.com).

**Comment by hvelarde** [comment]
that's a very good question indeed.

**Comment by aFarkas** [comment]
@hvelarde 

You can't take an image search for an article that was listed today. google has many different type of bots and the bot that is indexing lazysizes images isn't coming every 24h to a page.

Here is another example:
1. [page](http://www.cartacapital.com.br/revista/873/o-espirito-da-desigualdade-7153.html)
2. [image](http://www.cartacapital.com.br/revista/873/o-espirito-da-desigualdade-7153.html/henrique-pereira-de-sousa-sofre-com-o-desemprego/@@images/340c7e19-88af-410b-94b0-380417096dd6.jpeg)
3. [search result](https://www.google.com.br/search?hl=en-BR&tbs=sbi:AMhZZislEMWhzh7CTYxlAl5_1hP5twKqU_1q2jOJrqcCXFVk5FLfLvEMLKNiNYC8f8FoNpwXcDGVC4Z-edlFLXJsMshPAqXx-lrZlJCZLxk_1Q2kMadmL_1nAbs_1QpPrx5M0_1Obt8pySQtaYeu9uirecmBqVHJrJ0F25ZUhrXuTUXbWwbv-4tHDaJ_1S5OUDL7DkNXbMeiizosck0BUEasAH_1quwF5IR8UFClaV9QKATUZznes3Wuk_1VKni72Lm1ZYYu8BA0ACmp6O2TPUCS_1W8CiKZqr7OnCgi_1La2LoWKS7MOOAJOFLcEkDfq4l49i4bBfTQqaxZ598neqd8Kb7AgfIYK_1g3SDOP5ZjLyfHnTx2Tg75gsSehexhn6QFBNWyswoYqceHt6hmYhoOMQ8Zm_1bygvCKR0E37cqSqSUd0nfs_1QBuWrWaQygMCJ1dBo-af6rkHv1FOHyN6O1PLsSluOp0_1s6P6O_1shZsBXLV-iLK30ff2gFpKbUBs_1o4F9LzVqCEF_1a54YDo7X_1EipteUx7DuOzvNNDBbjxUtJDmn64imAxoHJhiJnj_1P-H_1BWRPL6_1qA-D2bp2g2gJhWoDEDJMU2rWgCm0CWnN7tY-ZrllHmPhi8Z_1A_1uHqXtnuHCkiC1aJ9Xw1JAtfEBdX1O7FY8fNgcKIISLubxe2HsWBGNsoizgAFZNzj4C2DpQ0GoFKU5V_1E-52zLHpXJAqCB1gkj8jYDoQy2bPq6pFfOc3QnxUL168pJH5XgpV2hjQGTbGson_1JC_1aFFiHUHrFDDKoEx9vvfDyElKmqABSZWPxFF7lKuLkdF4UQM3gw7Gt1Wt3tCktwig0x0RG-1o4AcpNxG6Tt9nUvSWZawi9e7HBooNVturIj3kE5GB8PIW2dDBQqV-AxPvfai6yhGGDqzDEy-aw-rOM4xup749JoYMwP_1cY-g9F8jTggf7fWOOWVdYowksxHPQjI82cFTJRy7W6jcUchZtPL86xAmG5RvanUDPlBVzUht8inY8OGtej9bamfdyRvlsqo0aEKYhlpdqrFXYWErhIQ5MoG3PL1GUMT85C7i3ZHFf4aklDR1vUu7wDQSntNmJznu_1o_1bQ_1NsyouYM_1I0UMg-G8UWOwX0T2X3n5Id743ZTbETNJNgVjMjcHkQYUlGAbrseA53lUMrzUAhnLED0ghqxF8rRg5pHfAAq-o66ONkuvXHNIsLZo5ay7NQOe1Q-SSKMZsLcKAZvmmREXNRQAJJpbYa_1rK0K7818kn9xcjaR-uSAIxbk55FRfwmJ9BV3PsgQHTlPEKB9R6MjWuTaYRZSlECzQeK0z4KWA_1gXGXGSTmkxBaTbugLUpHd9qgr9ZJZVHuhQozOJJbUt42jM2EVYYgDxsCdZpPzX-nVaXe-uYQETPj1GGsShPy95duwQAv_1L4rLdH7uEX2dxQrSAg51Bq6VjRApN6CWj-oZcIUs2T1di2a8t3M2qJ2B4_1LhWB_14YpY60q1bgUnR5posIT78L5LJPFS_1-F6Tyaqi1qSc2bJhaJPLrNKqPagg5oSIxjdLtPDLFxXdvTIWV0D8MzI0TQYX2brYw&ei=_abNVtuXKMTcPJmQrZgD&start=10&sa=N&biw=1356&bih=732&dpr=2)

found ;-)

**Comment by hvelarde** [comment]
@aFarkas good to know! I'll keep an eye on this :-)

**Comment by hvelarde** [comment]
further research: I used the Search Console on Google's Webmasters Tools to check how the image is rendered by Googlebot; that confirms Google will indeed index the image (there's even a second image below the fold that is also already loaded).

![selecao_013](https://cloud.githubusercontent.com/assets/341393/13286278/07bd7286-dadf-11e5-9ba3-92e5f44a7722.png)

thanks again, @aFarkas, your rock!

**Comment by ModDM** [comment]
Thank you @hvelarde and @aFarkas for these quick and clear answers!

**Comment by HectorLS** [comment]
Hello, i know this is close but, i have the same problem @aFarkas, images are not being indexed ( Talking about webs published 2 months ago)

There is an specific way to use your library 🎉 and also to index the images ? 
Thanks in advance

**Comment by interactivespace** [comment]
Does anyone has a workaround how to make the lazyloaded images indexable?

**Comment by ModDM** [comment]
Have you tried the Search Console from Google, as hvelarde commented above on Feb 24, 2016? Also, have you commanded Google to do a crawl execution on your site? Maybe you can also add a link to your images in your site map, for the crawler. How knows that helps.

**Comment by interactivespace** [comment]
According to the search console screenshot, the images are loaded and also all my pages are indexed. But I didn't added the images to the sitemap.xml. I will give it a try and add them to the sitemap.xml, I think this is anyway best practice.

**Comment by ModDM** [comment]
Glad I could help you with at least an option, since the other options didn't work out well for you. Hope this helps a bit. If so, maybe more users would like to know it!
