### ISSUE TITLE
Respimg plugin: iPhone landscape loads incorrect image size

### ISSUE THREAD

**Issue by awaer** [aFarkas/lazysizes#240]
Demo: http://s.codepen.io/ydna/debug/XXvEeQ

When loading in landscape on iPhone (I've tested iOS 7 through iOS 9), the 1024w image is selected for the above example —instead of the 800w— for an image that is rendered at a width of 528px. 

Portrait behaves as expected, correctly selecting the 480w image. 

Is this the intended behavior? If so, why?

**Comment by awaer** [comment]
I'm going to close this, as I assume it's related to pixel density. Feel free to leave additional feedback if you have any. For now, I'll probably try to work this out using optimumx. It still seems odd to me though that the device would resolve as if the device is 1x for portrait, but behave as 2x for landscape.

**Comment by aFarkas** [comment]
Yes it is device pixel ratio.

The algorithm doesn't try to go above the 2x, it tries to balance between performance and quality.

For this two image candidates are compared. Here is an example:

For an iPhone5 you have 320 x 568 layout and 2 DPR.

The image is shown at 280 (x 2 = 560) in portrait and 528 (x 2 = 1036):

You have the following images in portrait:
* 480 (which is 480 / 280 = **1.72**) (i.e.: only 0.28 missing)
* 800 (which is 800 / 280 = **2.85**) (i.e.: 0.85 too much)

And in landscape:
* 1024 (800 / 528 = **1.93**) (i.e.: only 0.07 missing)
* 1024 (1280 / 528 = **2.43**) (i.e.: 0.43 too much)

Here is a calculator, that you can feed these numbers:
http://jsfiddle.net/trixta/9dponzs2/

**Comment by awaer** [comment]
Thanks for the explanation!
