### ISSUE TITLE
Trigger animations only when lazyloaded object enters viewport

### ISSUE THREAD

**Issue by andreynovikov** [aFarkas/lazysizes#245]
Currently `lazyloaded` class is set as soon as image is loaded. But because of `expand` feature it is almost always is done outside the browser viewport. Thus all that nice fade-in and zoom-in affects triggered by CSS become useless as user does not see them. Can you add a way to trigger animations only when lazyloaded objects enter the viewport? Currently it can be achieved only by setting `expand` to `0` but I wan to leave loading of objects in advance intact.

**Comment by aFarkas** [comment]
Thanks for your report. The basic idea is that the user only sees (has to see) the animation, if he/she already has to wait for the image.

In most cases, such an animation is nice once, but is disturbing in the long run. 

If you still want to do animations you can use the `data-expand` attribute on a container element:

```html
<style>
.lazyload,
.lazyloading {
    opacity: 0;
}
.lazyloaded {
    opacity: 1;
    transition: opacity 300ms;
}
</style>

<div class="teaser lazyload" data-expand="-20">
    <img data-src="image.jpg" class="lazyload" />
    <h1>Teaser Title</h1>
    <p>...</p>
</div>
```

Please close if this helps.

**Comment by andreynovikov** [comment]
No, it's not what I want. `data-expand` makes it load with delay, but I want to continue to load it in advance. But after some thinking I agree with you, animation will be disturbing.

**Comment by Glumanda99** [comment]
@andreynovikov @aFarkas Do you've any idea on how to do this anyway? I would like to use https://github.com/michalsnik/aos with lazysizes. I'm lazy myself.
