### ISSUE TITLE
bxSlider with lazyloaded images aren't triggered on page load

### ISSUE THREAD

**Issue by oilvier** [aFarkas/lazysizes#246]
Hi,

First of all, I'm sorry if it's not an issue directly regarding lazysizes as there are other scripts involved (mainly bxSlider as mentioned in the title). 
I'd like to know if my problem can be solved at the lazysizes level or if I should go and knock on the door of the other libraries involved (any help is welcomed anyway :) )

I have a much larger case on a project, involving several slideshow and carousel that I have tried to sum up in  [a test case on jsfiddle](https://fiddle.jshell.net/oilvier/tas9fvp6/show/).

A vertical carousel of small images, that I need to convert to an horizontal carousel if the screen is smaller than 600px.

For this, I use bxSlider and [enquire.js](http://wicky.nillia.ms/enquire.js/) to reload my bxSlider with new parameters depending on the screen size.

- [Expected result : Vertical carousel for big screens](http://imgur.com/I6nBxr2)
- [Expected result : Horizontal carousel for small screens](http://imgur.com/Eu3BQcA)
- [The result in Chrome : Vertical carousel for small screens, breaks everything](http://imgur.com/UX1D0if)

The problem here is that, on certain browsers (I'd say WebKit or Blink browsers), the bxSlider is not triggered on page load (probably because images aren't loaded at first) and as a consequence, if the screen size is below 600px, the carousel stays vertical because the bxSlider is never "reloaded" with the parameters contained in the enquire.js query.

The weird thing is that it works perfectly fine in Firefox.
And of course, if I don't lazyload images, it works fine everywhere.

So maybe it's more a problem with bxSlider and the way it handles preload ? I don't know, and I must say I don't know where to look anymore... 
I would be grateful for any help solving this.

I hope my explainations are clear :/

**Comment by aFarkas** [comment]
@oilvier 

Sorry, for taking so long to answer. This is clearly an issue with bxslider's reload method.

You initialize with `vertical` mode and without any information how many slides to show. This yields to the default, that the hole viewport is taken, after changing to the mobile mode the width of the items is set to something lot higher than you actually need, but bxslider operates with wrong values here. 

Maybe it helps to fully destroy and re-init bxslider. If bxslider is written bad here, you manually  have to remove all inline styles.

Here is a "better" working fiddle:
https://fiddle.jshell.net/tas9fvp6/10/

**Comment by oilvier** [comment]
No problem, I, myself, took a long time to answer back :)

After your post, I put Lazysizes out of the picture and I focused on debugging bxSlider. 
In fact, it returns an error at load when there are images without "src", which my case due to lazysizes requirements. 

I changed that to look for image without "src" and "data-srcset" and now it works fine !

Thanks for your time.
