### ISSUE TITLE
Size doesn't update on resize

### ISSUE THREAD

**Issue by clambelet** [aFarkas/lazysizes#247]
Hi,

I must certainly be doing something wrong, but can't make it work properly.
I'm using lazysizes with data-srcset and data-sizes="auto" but when I resize the window, it doesn't load bigger src. 

Here's the markup after page load: 
`<img class="lazyautosizes lazyloaded"
	 src="img/200/img.jpg" 
	 data-src="img/200/img.jpg" 
	 srcset="200/img.jpg 200w,
			 320/img.jpg 320w,
			 420/img.jpg 420w,
			 490/img.jpg 490w,
			 560/img.jpg 560w,
			 620/img.jpg 620w,
			 680/img.jpg 680w,
			 740/img.jpg 740w,
			 780/img.jpg 780w,
			 840/img.jpg 940w,
			 980/img.jpg 980w,
			 1120/img.jpg 1120w" 
	 data-srcset="200/img.jpg 200w,
			320/img.jpg 320w,
			420/img.jpg 420w,
			490/img.jpg 490w,
			560/img.jpg 560w,
			620/img.jpg 620w,
			680/img.jpg 680w,
			740/img.jpg 740w,
			780/img.jpg 780w,
			840/img.jpg 940w,
			980/img.jpg 980w,
			1120/img.jpg 1120w" 
	data-sizes="auto" 
	alt="alt text" 
	sizes="198px">`

"sizes" stays the same regardless of the window width when I resize.
I tried with respimg polyfill plugin without success.
Script included: lazysizes (the page also contains picturefill).

Thanks a lot.

**Comment by aFarkas** [comment]
Try:

```css
img[data-sizes="auto"] { display: block; width: 100%; }
```

**Comment by clambelet** [comment]
Perfect! Thanks you!

**Comment by raphaelokon** [comment]
Sorry to reopen … but the solution above will only work for portrait-orientated images … and skew responsive images when you use percentage-based `max-width/max-height`

**Comment by aFarkas** [comment]
@raphaelokon 

The full answer to this problem is documented in the readme:
https://github.com/aFarkas/lazysizes#specify-dimensions

**Comment by Deepak2322** [comment]
<img class="lazyload"
                                     data-sizes="auto"
                                     src="/content/dam/placeholder.png.transform/TransformerWidth290Height161/image.jpeg"
                                     data-srcset="${properties.imageLink @ context='uri'}.transform/TransformerWidth699Height388/image.jpeg 1920w,
                                                  ${properties.imageLink @ context='uri'}.transform/TransformerWidth699Height388/image.jpeg 768w,
                                                  ${properties.imageLink @ context='uri'}.transform/TransformerWidth290Height161/image.jpeg 500w"
                                     alt="${properties.imgTitle}" /></div>


Where am I doing wrong, only 'TransformerWidth290Height161' image is loading in all viewport
