### ISSUE TITLE
requirejs / lazysizes

### ISSUE THREAD

**Issue by klopfdreh** [aFarkas/lazysizes#249]
Hi,

under certain circumstances there is an issue if you use lazysizes as amd module, because it invokes anonymously define in a local way:

https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#l7

It would be better to give lazysizes a module name so that the error mentioned here:

http://requirejs.org/docs/errors.html#mismatch

> If you manually code a script tag in HTML to load a script with an anonymous define() call, this error can occur.

can not occur if you use it in a external script file.

WDYT?

Thanks

**Comment by klopfdreh** [comment]
Seems that someone else has the same issue:

https://github.com/aFarkas/lazysizes/issues/220

**Comment by aFarkas** [comment]
@klopfdreh 

Have you seen this discussion?
https://github.com/aFarkas/lazysizes/pull/221

If this is needed I can create a new version with 2 or more files you can choose from.

Currently only thinking how to name the new file.

lazysizes.js
lazysizes.min.js

Are already reserved for the umd module pattern:

lazysizes-simple.js
lazysizes-clean.js
lazysizes-moduleless.js

Do you have an idea?

**Comment by shimonenator** [comment]
Not simple or clean. Either moduleless or nonamd

**Comment by aFarkas** [comment]
noumd it is

**Comment by aFarkas** [comment]
I changed this but a little bit different to what I thought I will do.

I removed the AMD pattern from the main file and created a new one named lazysizes-umd.js

**Comment by klopfdreh** [comment]
Thank you very much! :+1:
