### ISSUE TITLE
Chrome resize issue: data-sizes="auto" in multi grid

### ISSUE THREAD

**Issue by raphaelokon** [aFarkas/lazysizes#257]
Hi.
I am experiencing a weird behavior when I shrink the browser window using Chrome. The image sits in a column of a simple grid which changes its width based on mediaQueries. I am using following markup for the responsive image:

```html
<!-- 
Styles set in CSS:
.img {
    max-width: 100%;
    max-height: 100%;
    width: auto;
    height: auto;
}
-->
<img src=data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
     alt="foo"
     data-src="orig.jpg"
     data-sizes="auto"
     class="lazyload img"
     data-srcset="300.jpg 300w, 1000.jpg 1000w, orig.jpg 1900w">
```

The calculated `sizes` attribute makes the image not spanning across the whole parent (which is a square) – I have to reload the page to get it fit again. The sizes value somehow decreases throughout the shrinking of the window. When I reload the page in the shrunken state, the images (and the sizes value) display at correct sizes. There sometimes a difference of 100px for the sizes value between the resized and reloaded state. 

Any ideas? I will try to setup a Codepen to make this obvious.

**Comment by aFarkas** [comment]
The problem is documented in the readme. The `data-sizes="auto"` has no big magic it simply allows you to move the presentational markup (content of the `sizes` attribute) into your CSS. For this you need to define at least the `width` of your images. Using `width: auto` won't work, because lazysizes needs to guess what you want.

I always advice to use the aspect ratio CSS, so that width and height of the images are defined. This might be more work but it really pays off. (https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps)

If you don't want, you can also modify how the `sizes` attribute is calculated by using the `lazybeforesizes` event. There is also the parent-fit plugin, which does just that.

See also:
http://jsfiddle.net/trixta/w96o9xm5/

Please close, if this helps.

**Comment by raphaelokon** [comment]
Hi @aFarkas.
Sorry for my late response.
Just to be clear, the outer container of the `<img>` has a defined ratio with `::after`, like in your example. This ratio just do not reflect the ratio of the image (thus height/width auto and max-width/max-height as needed). All works good on page load, just not when the browser is resized. I will investigate further and keep you posted.

**Comment by aFarkas** [comment]
This is still an issue with the fact, that `width: auto` is set on the image.

You can try this for example:

```js
$(document).on('lazybeforesizes', function(e){
    //use width of parent node instead of the image width itself
    (e.originalEvent || e).detail.width = $(e.target).closest(':not(picture)').innerWidth() || (e.originalEvent || e).detail.width;
});
```

**Comment by raphaelokon** [comment]
Optionally, what would help is just to use the initial sizes calc, and disable it on resize.

> If you don't want, you can also modify how the sizes attribute is calculated by using the lazybeforesizes event. There is also the parent-fit plugin, which does just that.

Does the event fire before every resize?

**Comment by raphaelokon** [comment]
> This is still an issue with the fact, that width: auto is set on the image.
Thanks! Do you have a vanilla JS example somewhere in the docs?

**Comment by raphaelokon** [comment]
Oh, I also forgot to mention …

```
img { 
  &.lazyload {
    backface-visibility: hidden;
    opacity: 0;
    transition: opacity 400ms;
    width: 100%;
    height: 100%;
    display: block;
  }

  &.lazyloaded {
    backface-visibility: hidden;
    opacity: 1;
    transition: opacity 400ms;
    width: auto !important;
    height: auto !important;
  }
}

**Comment by aFarkas** [comment]
```js
//if you use a modern browser/or a closest polyfill:
document.addEventListener('lazybeforesizes', function(e){
    //use width of parent node instead of the image width itself
    e.detail.width = e.target.closest(':not(picture)').offsetWidth || e.detail.width;
});
```

```js
//if you use a legacy browser and no closest polyfill:
document.addEventListener('lazybeforesizes', function(e){
    //use width of parent node instead of the image width itself
    var parent = e.target.parentNode;

    if(parent.nodeName == 'PICTURE'){
        parent = parent.parentNode;
    }
    e.detail.width = parent.offsetWidth || e.detail.width;
});
```
