### ISSUE TITLE
Run JS with unveilhooks

### ISSUE THREAD

**Issue by yoyurec** [aFarkas/lazysizes#258]
i'm already using lazysizes for images, but now trying to do lazy-ads.
as lazysizes already has functionality to detect user position, it would be great to reuse it somehow (instead of adding another heavy script)...
there is **unveilhooks** plugin for lazy-widgets.
but is it possible to run some inline js code when it's in viewport ("core ads loader" already loaded)?

something like:
```
<div class="lazyload">
    loadAd(12345);
</div>
```
tnx

**UPD:**
as a solution for now i see only move out inline code:
```
<div class="lazyload" data-script="loadad.php?id=12345">
</div>
```
to PHP generator which will output JS:
```
loadAd(12345);
```
will unveilhooks load php in **data-script**?

**Comment by boynet** [comment]
maybe this will help you:
https://github.com/aFarkas/lazysizes/issues/207

**Comment by aFarkas** [comment]
Everything is in the documentation:

```html
<div class="lazyload" data-ad="12345">
</div>
```

```js
document.addEventListener('lazybeforeunveil', function(e){
    var ad = e.target.getAttribute('data-ad');
    if(ad){
        loadAd(ad, e.target);
    }
});
```

**Comment by yoyurec** [comment]
simple! just works. tnx
