### ISSUE TITLE
Updating layout of js widgets with several images per widget

### ISSUE THREAD

**Issue by oilvier** [aFarkas/lazysizes#260]
Hi,

I'm trying to use a visual diff tool (before/after) on a new project. I chose [TwentyTwenty](http://zurb.com/playground/twentytwenty) to do so.

The problem when I use LazySizes is that TwentyTwenty can't calculate image dimensions as they are not yet loaded.

I can't use the different solutions to specify image dimensions because the images that I'll use will have variable heights.

So I've implemented the solution with JS detailed here : https://github.com/aFarkas/lazysizes#updating-layout-of-js-widgets
The only problem is that it updates two times (as there are two images if I'm not mistaken) and all the div's created by TwentyTwenty are doubled.

Test case here : https://jsfiddle.net/oilvier/08sqj77m/

It works but I wonder if there's a cleaner option (Considering TwentyTwenty doesn't have an update callback).

**Comment by aFarkas** [comment]
I suggest that you update the widget not to re-initialize it. But twentytwenty doesn't really allow this (shame on them).

From reading the source code you might by able to workaround this problem by doing this:

```js
$('.container').each(function(){
  var $module = $(this);
  var update = function(){
    $(window).trigger("resize.twentytwenty");
  };

  // Note: Instead of waiting for all images until we initialize the widget
  // we use event capturing to update the widget's layout progressively.
  this.addEventListener('load', update, true);

  $module.twentytwenty();
});
```

**Comment by oilvier** [comment]
Awesome, thank you very much !

:+1:
