### ISSUE TITLE
current version of lazysizes = images sometimes stuck on 'lazyloading' in firefox

### ISSUE THREAD

**Issue by propertunist** [aFarkas/lazysizes#264]
since i upgraded the version of lazysizes i am using to a more recent one, i found that images on my site are not always loading in firefox. this page (https://www.ureka.org/thoughts/view/2828/mistakenly-seeking-love-and-acceptance-from-others), for example, has one main blog image on it and it has failed to render in both windows firefox and linux firefox here. the class 'lazyloading' is set for the image, but i don't know more than that presently. the image usually loads correctly when i refresh the page.

**Comment by aFarkas** [comment]
Could you please re-check with the current alpha version. (https://afarkas.github.io/lazysizes/lazysizes.min.js) This should be fixed.

**Comment by propertunist** [comment]
ok thanks. the github pages section is down for maintenance presently, so i couldn't access the file you linked. i have downloaded and am testing this version though and so far it looks ok: https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js
