### ISSUE TITLE
Lazy Loading Video Sources

### ISSUE THREAD

**Issue by TomS-** [aFarkas/lazysizes#266]
Hello,

Would it be possible to lazy load video sources? I'm using unveilhooks however it seems to only lazy load the poster. See: http://i.imgur.com/nX9oWyL.jpg (Speed Test - Pingdom Tools)

Such as LazyLoadXT and bLazy. 

Thanks

**Comment by aFarkas** [comment]
You can use `preload="none"` for this.

**Comment by TomS-** [comment]
In the example above I was using preload="none", however I completely understand this is a browser feature so the pingdom test could be ignoring it. Thanks for drawing that to my attention.
