### ISSUE TITLE
not working on iPhone 4

### ISSUE THREAD

**Issue by astraussondigo** [aFarkas/lazysizes#268]
Lazysizes is not working on iPhone 4 (simulator and native). Even with a polyfill like picturefill. Neither my code nor the lazysizes demo page is working http://afarkas.github.io/lazysizes/#examples
On iPhone 4s and later everything works fine.

![lazysizes_on_iphone4](https://cloud.githubusercontent.com/assets/16756068/15388069/749f8c7c-1db0-11e6-9463-b1a28e48e0b3.png)

**Comment by aFarkas** [comment]
What iOS version is this, what does the console say?

**Comment by aFarkas** [comment]
And how many users are using this iOS version anyway?

**Comment by astraussondigo** [comment]
It's iOS 7.1.2. iPhone4 can't update to a higher version.

5.4 % are still using iOS 7.1 and 1.7 % iOS 7.0

http://hwstats.unity3d.com/mobile/os-ios.html

So every 14th person (with iOS) will see no pictures.

Console doesn't say anything.

**Comment by robsonrobi** [comment]
Is there any chance, that this could be fixed?
Lots of our clients use lower iOS versions. For example older iPads use that version a lot...

**Comment by aFarkas** [comment]
I have just tested the current version (in master) with iOS 7.0 and it works.

Can you use the newest version of lazysizes? Otherwise I can not replicate your issue.

**Comment by robsonrobi** [comment]
You are using an iPhone 5s simulator, thats working correctly, iPhone 4s, too. But the iPhone 4 with a maximum version of iOS of 7 is not working.

**Comment by aFarkas** [comment]
But I tested with iOS7.0 and iOS7.1 and there shouldn't be a difference with different hardware. Additionally I don't have access to iPhone 4.

**Comment by robsonrobi** [comment]
Obviously there is a difference :-( I do not know how to get an older IOS and iphone4 into the simulator. Than i could debug the beast.

**Comment by robsonrobi** [comment]
Okay, it works now, CRAZY Stuff. Thanks for your help.

**Comment by aFarkas** [comment]
> Okay, it works now, CRAZY Stuff.

Maybe because of the new version. I released yesterday.
