### ISSUE TITLE
[lazySize + shuffle.js] Some images are not loading

### ISSUE THREAD

**Issue by kimek** [aFarkas/lazysizes#271]
undefined lazySizes.loader.checkElems() on invoking with shuffle.js

I have access to lazySizes.loader prototypes unveil and checkElems when I'm making console.log in:

// Filter elements
 this.shuffle.filter(this._activeFilters);
setTimeout(function() { // check lazySizes
console.log(lazySizes.loader);
 }, 2000);

As I understand you don't need to pass any DOM to checkElems. Whats wrong in this case as lazySizes and shuffle.js works fine except refreshing on filtering ?

**Comment by aFarkas** [comment]
No you don't. But I think you don't even need to call `checkElems`.

**Comment by kimek** [comment]
Unfortunately with or without it is not detecting that images are visible. I'm planning after filtering get all .shuffle-item--visible and loop them with lazySizes.loader.unveil(DOMNode) but this is not a good idea to mix jquery, shuffle and lazysizes. I'm trying to avoid it as possible. jQuery too. I can pass some code and playground if it needed but on priv msg if possible.

**Comment by kimek** [comment]
Hm.. i dont know why.. but i see that local VM works differently comparing to staging version. On staging it works fine.

**Comment by kimek** [comment]
@aFarkas as You said your plugin works like a charm and detecting changing layout from shuffle.js
However it's seems that 'data-expand="-30"' and shuffle.js dont like each. 
When you use data-expand some images are not loading. Why, hard to say as there is no error. 

If I will have more time I will try to look into code deeper and send more details. For a now say to guys to not use data-expand with shuffle.js if they will have some 'loading image' problems.

Cheers Mate



Cheers Mate

**Comment by kimek** [comment]
update: 
removing data-expand didnt fix issue on mobiles. 
I've added src="dummy.jpg" and works fine now
