### ISSUE TITLE
W3Validation

### ISSUE THREAD

**Issue by Allmedialab** [aFarkas/lazysizes#275]
Hi,

Love your plug in!

 How can I get the following code W3validate?
data-src="/images/Athene-gulpen.jpg"  

And 

<picture>

<source media="(max-width: 1920px)"

type="image/webp"
data-sizes="auto"
data-srcset="
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_584.webp 584w,
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_871.webp 871w,
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_1096.webp 1096w" class="lazyload">

<img
data-sizes="auto"
data-srcset="
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_584.jpg 584w,
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_871.jpg 871w,
/img/deerehuuske-1column-image/deerehuuske_c_scale,w_1096.jpg 1096w"
src="Ditxxxxxxxisxxxwatxxxxxtext" class="lazyload"
alt="">
</picture>
Regards & Thanks
David

**Comment by aFarkas** [comment]
Add `src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="` to your image and `srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="` to your `source`.

**Comment by Allmedialab** [comment]
Thanks! David
