### ISSUE TITLE
Ajax'd site not firing lazysizes

### ISSUE THREAD

**Issue by CHEWX** [aFarkas/lazysizes#283]
Hi,

Sometimes, mostly on iOS devices, lazysizes isn't self-initializing.

My site is built with ajax architecture so JavaScript is re-initialised when Ajax return is done, but sometimes lazysizes isn't firing, I've tried to do a manual init, but still no joy, is there a hook I can test to double check init ?

            window.lazySizesConfig = window.lazySizesConfig || {};
            window.lazySizesConfig.init = false;
            window.lazySizesConfig.lazyClass = 'lazy';
            lazySizesConfig.expand = -100;`

            window.lazySizes.init();

            // Double check it's initiated
            // Nothing to hook onto
            setTimeout(function() {
                window.lazySizes.init();
            }, 1000);

Thanks,
Tom

**Comment by aFarkas** [comment]
Actually there shouldn't be the need to it. You might want to try the following:

```js
setTimeout(function() {
            lazySizes.loader.checkElems();
}, 1000);
```

But I doubt, that this helps. Can you give me a link to your site to test myself?

**Comment by aFarkas** [comment]
I just saw, that you have this:

```js
lazySizesConfig.expand = -100;
```

You should really use only positive numbers here:

```js
lazySizesConfig.expand = 100; // at least 50
```

I really suspect, that this is your issue.

**Comment by CHEWX** [comment]
Ok, thanks, will give that a try and report back. Wanted to delay the lazyload, but this can be done with `animation-delay`, so no need for the negative value now.

**Comment by floq-design** [comment]
I'm also experiencing the same issue with an ajax site - however on IE 11 *(groan)*.
*(Works fine in Firefox, Chrome and Safari btw.)*

**The problem seems to be with images with srcset style markup - images with bgset are loading correctly**.

When I check the markup of srcset images that aren't showing - they're missing the `src=".."` attribute.

If I open the Developer Tools this seems to prompt a refresh of some kind and the images then appear...

I'm using `unveilhooks`, `parent-fit` & `bgset` plugins with Lazysizes.

Tried implementing `lazySizes.loader.checkElems();` but still not working...

**Comment by aFarkas** [comment]
@floq-design 
Thanks, I don't think this is the same issue. For IE you additionally need a polyfill like resoimg plugin or picturefill.

Can you send me a linke to your site or a reduced testcase?

**Comment by floq-design** [comment]
@aFarkas Thanks for the rapid response.

I'm using Picturefill v3.0.2 as my polyfill.

Unfortunately I'm developing in Wordpress locally - no live version to show. Creating a reduced test case would be a lot of work. Thanks for the offer though.

Just tried (out of curiosity) using v1.5 of Lazysizes but same problem :(

Are there any other initalising methods for lazysizes?

**Comment by floq-design** [comment]
Just tested same site under Windows 10 with IE Edge - and I'm getting the reverse of the problem in IE 11... so **bgset images are not loading** however srcset images are.

**Comment by CHEWX** [comment]
To clarify, I too am use WordPress. The output of the images are:

`<img width="1000" height="667" class="attachment-6x4-medium size-6x4-medium lazy fade-in" alt="x" srcset="http://x.wpengine.com/wp-content/uploads/2016/06/x-1000x667.jpg" data-src="http://x.wpengine.com/wp-content/uploads/2016/06/x-1000x667.jpg" data-srcset="http://x.wpengine.com/wp-content/uploads/2016/06/x-1000x667.jpg 1000w, http://x.wpengine.com/wp-content/uploads/2016/06/x-300x200.jpg 300w, http://x.wpengine.com/wp-content/uploads/2016/06/x-768x512.jpg 768w, http://x.wpengine.com/wp-content/uploads/2016/06/x-1320x880.jpg 1320w, http://x.wpengine.com/wp-content/uploads/2016/06/x-600x400.jpg 600w, http://x.wpengine.com/wp-content/uploads/2016/06/x.jpg 1400w" data-sizes="(max-width: 1000px) 100vw, 1000px">`

**Comment by aFarkas** [comment]
Please I really need a testcase or a link. It should be easy to simply save some html output including all CSS and JS.

**Comment by floq-design** [comment]
@aFarkas Just want to report my conclusions.
Firstly I was using JS to update the sizes attribute on images without including `ls.attrchange.min.js`.
Secondly using this code: <https://github.com/scottjehl/picturefill/issues/644#issuecomment-188809805> to re-prompt picturefill resolved missing images on ajax load.
Thanks again for the rapid response.

**Comment by CHEWX** [comment]
None of those suggesions have worked.

I can send you a staging link @aFarkas , do you have an email ?

**Comment by aFarkas** [comment]
info@corrupt-system.de

**Comment by aFarkas** [comment]
@CHEWX

I got your email. The problem is your lazysizes configuration code. Your code is executed after DOM ready, but you need to execute it immediately. In case you want to wait you can set `lazySizesConfig.init = false;`, but in this case you also have to do this immediately.

You current code looks something like this:

```js
    lazysizes: function() {
		window.lazySizesConfig = window.lazySizesConfig || {};
		window.lazySizesConfig.init = false;
		window.lazySizesConfig.lazyClass = "lazy";
		lazySizesConfig.expand = 100;
		window.lazySizes.init();
		setTimeout(function() {
			lazySizes.loader.checkElems();
		}, 1e3);
	},
```

You can modify it to this:

```js
    lazysizes: (function(){
		window.lazySizesConfig = window.lazySizesConfig || {};
		window.lazySizesConfig.init = false;

		return function() {
			window.lazySizesConfig.lazyClass = "lazy";
			window.lazySizesConfig.expand = 100;
			window.lazySizes.init();
		};
	}),
```

and it should work.

**Comment by aFarkas** [comment]
I just modified the code. The working config is looking like this:


```js
    lazysizes: (function(){
		window.lazySizesConfig = window.lazySizesConfig || {};
		window.lazySizesConfig.init = false;

		return function() {
			window.lazySizesConfig.lazyClass = "lazy";
			window.lazySizesConfig.expand = 100;
			window.lazySizes.init();
		};
	})(),
```

Please close this issue, if it works for you.

**Comment by CHEWX** [comment]
Looking good so far @aFarkas - thanks.

Will re-open if the problems arises again.

**Comment by evromalarkey** [comment]
Is it possible that this is not working again with latest version of Chrome? It's working for me for every other browser, even IE9 but not Chrome. Can somebody confirm this?
