### ISSUE TITLE
bgset support for Angular 2

### ISSUE THREAD

**Issue by sergiomcc** [aFarkas/lazysizes#285]
Hi,

I'm trying to use the bgset plugin in my Angular 2 website and the following error appears:

`EXCEPTION: Template parse errors:
Can't bind to 'bgset' since it isn't a known native property`

This is because of Angular, right? 

-----

Here's how I declare things:

**index.html**
```
<head>
  ...
  <script>
    function loadJS(u){var r=document.getElementsByTagName("script")[0],s=document.createElement("script");s.src=u;r.parentNode.insertBefore(s,r);}
    
    if (!window.HTMLPictureElement || !('sizes' in document.createElement('img'))) {
        loadJS("libs/ls.respimg.min.js");
    }
  </script>
  <script src="libs/ls.bgset.min.js"></script>
  <script src="libs/ls.attrchange.min.js"></script>
  <script src="libs/lazysizes-umd.min.js"></script>
  ...
</head>

<body>
  <app>Loading...</app>
</body>
```

**template.html**
```
<div class="card main">
  <img class="lazyload" data-bgset="img/abc.png 1x, img/2x/abc.png 2x"/>
</div>
```

-------

*Thanks for the help and all the work you put into this library, is really awesome!!!*

**Comment by aFarkas** [comment]
This might help:
http://stackoverflow.com/questions/34542619/angular-2-data-attributes/34542844

**Comment by sergiomcc** [comment]
Setting `attr.data-bgset` does the trick. That's it, there's no issue...
