### ISSUE TITLE
object fit extension not loading new images on resize in edge

### ISSUE THREAD

**Issue by hvbe** [aFarkas/lazysizes#297]
Hi there

I stumbled upon an issue in MS Edge (20.10240.16384.0).
Ehen using the object-fit extension, new images do not get loaded after initialization. This is particularly annoying when using the LQIP method.

I created a reduced test-case here: https://jsfiddle.net/fL9423ag/3/

thanks so much for looking into this!

**Comment by aFarkas** [comment]
You need to inform the parent-fit plugin about the aspect-ratio of your images. You can do this by adding a h descriptor:

```html
<img class="lazyload" data-sizes="auto" data-srcset="https://unsplash.it/320x180/?image=777 320w 180h, https://unsplash.it/640x360/?image=777 640w, https://unsplash.it/960x540/?image=777 960w, https://unsplash.it/1280x720/?image=777 1280w, https://unsplash.it/1920x1080/?image=777 1920w" src="https://unsplash.it/320x180/?image=777">
```

or by adding a `data-aspectratio` attribute:

```html
<img class="lazyload" data-aspectratio="1.78" data-sizes="auto" data-srcset="https://unsplash.it/320x180/?image=777 320w, https://unsplash.it/640x360/?image=777 640w, https://unsplash.it/960x540/?image=777 960w, https://unsplash.it/1280x720/?image=777 1280w, https://unsplash.it/1920x1080/?image=777 1920w" src="https://unsplash.it/320x180/?image=777">
```

**Comment by aFarkas** [comment]
Please close if this helps.

**Comment by hvbe** [comment]
this seems to work only when initially loading the page but not when the user resizes the window or let's say triggers (a more realistic case) an orientationchange on a windows device.

**Comment by aFarkas** [comment]
I have just tested the [following demo](https://jsfiddle.net/aLj1zadg/1/) in Edge (Microsoft Edge 38.14393.0.0 / Microsoft EdgeHTML 14.14393) as also in IE11 and it is just working fine.

**Comment by hvbe** [comment]
indeed, it works fine with newer versions of edge. tested with 25 & 34 on browserstack. this seems to be an issue only with really early versions of edge. so, i think we can safely ignore it :) thanks for your support!

**Comment by saulhardman** [comment]
Just for posterity and others who run into the same issue: in my experience, Edge (Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134) will fallback to the `src` attribute when the height component is included in the `srcset` attribute (e.g. `https://image.com/image.jpg 320w 180h`). When the `data-aspectratio` attribute is used, all works as expected 👍

**Comment by aFarkas** [comment]
@saulhardman 
This is documented. MS Edge has a buggy implementation of the srcset parsing. This can be fixed by either adding the [respimg polyfill extension](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg) or using the `data-aspectratio` instead.

**Comment by saulhardman** [comment]
@aFarkas thanks for the response and for updating your comment. Apologies, I hadn't seen the MS Edge note in the parent-fit extension readme.
