### ISSUE TITLE
custommedia extension markup validation failed (W3C)

### ISSUE THREAD

**Issue by LDSign** [aFarkas/lazysizes#304]
Hi
 I am using the custom media extension with media="--small" a.s.o. like in the examples.

Unfortunatley this markup is no valid html and so highlighted by the W3C-Validator:

"Bad value --small for attribute media on element source: Expected ( or letter at start of a media query part but saw - instead."
"Stray end tag source."

Is this a normal behavior or do I make something wrong? How could this be avoided?

Thanks,
Frank

**Comment by aFarkas** [comment]
You make everything right. Custom media queries might be a future feature and therefore the validator does not validate. We basically polyfill this with lazySizes. It doesn't harm your page.

You can avoid this by using the `data-media` attribute instead:

```
<source 
    srcset="data:,pixel" 
    media="(max-width: 1px)" 
    srcset="your_srces" 
    data-media="--small" />
```
