### ISSUE TITLE
Lazy loaded iFrames don't appear at their full height

### ISSUE THREAD

**Issue by mattymess** [aFarkas/lazysizes#306]
If I lazy load an iframe, the height of the iframe is only about 150px. See [this pen](http://codepen.io/mattymess/pen/kkLGBY) for an example.

![image](https://cloud.githubusercontent.com/assets/1108825/18693463/b1fc8c52-7f56-11e6-96a8-ffb86467ec21.png)

Of course if I set the height of the iframe, this problem would be mitigated. However, there are times when it's impossible to know the height. Like if I copy an embed code from YouTube, Instagram, Twitter, etc. 

Thanks

**Comment by aFarkas** [comment]
This is a pretty normal behavior of iframes you need to explicitly set the height of the iframe. The embed code youtube also already does this.
