### ISSUE TITLE
Lazyloading filenames that contain parentheses fail

### ISSUE THREAD

**Issue by nokturnal** [aFarkas/lazysizes#314]
Hey,

In the the following snippet:

```
<div class="lazyload" style="height:200px; width:200px; background-position:center center; background-size:cover;" data-bg="https://xxx.com/img/some-image-(1).jpg"></div>
<div class="lazyload" style="height:200px; width:200px; background-position:center center; background-size:cover;" data-bg="https://xxx.com/img/some-image.jpg"></div>
```

... the first DIV does not render an image, but the second DIV does.  I have tracked it down to any filenames that contain parentheses fail to load.

I have included both lazysizes.unveilhooks.min.js & lazysizes.js on this page.

**Comment by nokturnal** [comment]
... and the solution is:

In lazysizes.unveilhooks.js, change line 82:

`e.target.style.backgroundImage = 'url(' + bg + ')';`

with:

`e.target.style.backgroundImage = 'url("' + bg + '")';`

**Comment by aFarkas** [comment]
I fixed it in master.
