### ISSUE TITLE
[Question] When using with picturefill & caching

### ISSUE THREAD

**Issue by BMCwebdev** [aFarkas/lazysizes#316]
Hi there. My question is regarding caching of images. When using picturefill, if the user downloads a larger image, then shrinks the browser, it will not download the smaller image. Rather it will use the already downloaded larger image it has in cache.

I'm wondering if when you are using picturefill in conjunction with lazysizes, will this behavior be followed, or will lazysizes override with it's own logic? Thank you.

**Comment by aFarkas** [comment]
lazySizes does not override this behavior. Btw.: Also the [respimg polyfill plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg) does not load smaller images as soon as a large image is already loaded.

**Comment by BMCwebdev** [comment]
Thank you!
