### ISSUE TITLE
Flicker after enabling the library

### ISSUE THREAD

**Issue by manake** [aFarkas/lazysizes#317]
I've just discovered and installed this library and this is what happens for me:

I create two 250px images, one visible and one hidden.

```
<a class="my-link" href="#">
    <img class="first">
    <img class="second">
</a>
```

I use the following script to switch them on mouse over:

```
$('body').on('mouseenter', '.my-link', function() {
    $('.first').addClass('hide');
    $('.second').addClass('show');
});

$('body').on('mouseleave', '.my-link', function() {
    $('.first').removeClass('hide');
    $('.second').removeClass('show');
});
```

This is the CSS:

```
.second { opacity: 0; }
.show { opacity: 1; }
.hide { opacity: 0; }
```

This works perfectly well. However, I wanted to add lazysizes because:
1. I have many images on that page and I only want to load them as user gets near them.
2. The grid of images has "large/small thumbnails" toggle and some JavaScript has to update "sizes". This library seems to be what I need.

When I set `lazyload` and `data-sizes="auto"` to both images then on every `mouseenter`:
1. the first image disappears,
2. then there is nothing for about 50ms (just white space),
3. and then the second appears.

The flicker lasts maybe 50-100ms but it's definitely visible and it's permanent. No matter if the second image is already loaded or not the flicker always happens. What can I do?

**Comment by aFarkas** [comment]
Can you make a test case? I doubt, that this is the right JS or the right CSS. The JS would change classes on all elements not only the hovered once. 

In case you are using additionally `display: none` on the image that is hidden, this is the explanation for the time you need to wait. You can use `position:absolute; visibility: hidden;` instead to improve the situation.

But I really need a test case to see what is happening there. You can use codepen, jsfiddle, jsbin...

**Comment by aFarkas** [comment]
Please re-open with more details, if this did not help you.
