### ISSUE TITLE
Lazy loading of OBJECT?

### ISSUE THREAD

**Issue by joacim-boive** [aFarkas/lazysizes#318]
I have an SVG with a background image and the only way to get it to show is to use the OBJECT-element.

But the OBJECT element relies on the DATA-attribute.
From what I could find in the docs there's no support for my required behaviour: data-data -> data
```
<object class="startpage-teasers__image **lazyload**" **data-data**="images/sma_boxar/upp-till-70-procent-rabatt-se.svg"></object>

<object class="startpage-teasers__image **lazyloaded**" **data**="images/sma_boxar/upp-till-70-procent-rabatt-se.svg"></object>
```

The referenced SVG looks something like this:
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Image_Tag

To get the image to show in Chrome, Safari, FireFox, Edge, IE11, the only way is to use the OBJECT-element and you're not able to use the IMG-element. 

Am I missing something or do you have any plans to implement the ability to lazyload OBJECT-elements as well?

**Comment by joacim-boive** [comment]
You can see how it works here:
https://www.lensway.se

The four small boxes on the middle of the page.

**Comment by aFarkas** [comment]
This is documented [here](https://github.com/aFarkas/lazysizes#js-api---events).

**Comment by joacim-boive** [comment]
Awesome! Thanks.

**Comment by dlewand691** [comment]
Sorry for the noob question but I haven't been able to track down a clear answer. Can you please explain how this can be done with the API? I've tried several variations but cannot get it to work in iOS. Thank you!

**Comment by dlewand691** [comment]
Fixed by adding:

```
document.addEventListener('lazybeforeunveil', function(e){
    var svgObject = e.target.getAttribute('data-object');
    if(svgObject){
        $('object').attr('data', svgObject);
    }
});
```
```
<object class="lazyload" type="image/svg+xml" data-object="[IMAGE URL].svg"></object>
```

**Comment by mprofitl** [comment]
The code above will give all html <object> Tags the same data attribute. The following code will give each <object> tag its own data attribute, taken from the individual data-object attribute.

```
document.addEventListener('lazybeforeunveil', function(e){
    var svgObject = e.target.getAttribute('data-object');
    if(svgObject){
        $(e.target).attr('data', svgObject);
    }
});
```
