### ISSUE TITLE
API event for each element loaded to hook into? 

### ISSUE THREAD

**Issue by 23d1** [aFarkas/lazysizes#319]
Is there a `lazybeforeunveil` to hook into on each individual element like .each() `$(this).parent().find('.loader').remove();`?

**Comment by 23d1** [comment]
Sorted with CSS direct sibling selector.

**Comment by aFarkas** [comment]
This would have also worked:

```js
document.addEventListener('lazybeforeunveil', function(e){
    $(e.target).parent().find('.loader').remove();
});
```

**Comment by 23d1** [comment]
I tried calling it as

```
$(document).on('lazybeforeunveil', function(e) {
   $(e.target).parent().find('.loader').remove();
});
```
Which didn't work...

**Comment by aFarkas** [comment]
This depends on your markup: `e.target` only references one single image that is currently transformed (not multiple elements). If the parentNode of your image includes multiple images and therefore loaders it obviously will remove all found descendants with the class `.loader`. Maybe `$(e.target).next('.loader')` is what you want then. But I can't tell without seeing your markup. I only saw that you were referencing `this` (i.e.: the `document`), which should be changed to `event.target`. Maybe your are mixing up what `lazybeforeunveil` actually means. It means, that the image is transformed. It does **not** mean that the transformed image is already loaded yet. Which you would get with the `load` event.
