### ISSUE TITLE
Back button will not position the user where he was before on the page

### ISSUE THREAD

**Issue by Jacques03** [aFarkas/lazysizes#320]
Hi,

Have installed the script on my Magento category pages, no problem.

But...

I have a page with a lot of products.

When I scroll down somewhere on the page and then click on a product, I go to Magento product page.

When I click on back button of the browser, I am not positioned well on the page, meaning I am not positioned where I clicked before.

Is there anything that could correct that ?

Have tested on Chrome, Firefox, Safari, and on mobile, same issue.

I can provide a test link if needed.

Thanks .

Kind regards,
Jacques

**Comment by aFarkas** [comment]
Please read this: https://github.com/aFarkas/lazysizes/#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps
