### ISSUE TITLE
Certain image not appearing in IE while using object-fit plugin

### ISSUE THREAD

**Issue by crealistiques** [aFarkas/lazysizes#321]
[On this page](http://www.gruene-lebensraeume.de/produkte/produktuebersicht/) the last image (at the bottom right) in not shown in IE (tested in version 11). It seems that the background-url of the newly generated image helper element is not set correctly upon load. I observed this behaviour on other pages too where sometimes especially the last image on a page is not appearing at all in IE, not even after resize or reflow.

By the way, thank you so much Alexander for your great lazysizes suit!

**Comment by aFarkas** [comment]
Thx! I will check this tonight.

**Comment by aFarkas** [comment]
I just checked your markup and your srcset looks like this:

``fileadmin/_processed_/csm_Steine_3_131e1ee2b3.jpg 120wfileadmin/_processed_/csm_Steine_3_aa7f4064ef.jpg 220wfileadmin/_processed_/csm_Steine_3_6a74e56581.jpg 555wfileadmin/GL/Bilder/Teaser/Steine_3.jpg 737wfileadmin/GL/Bilder/Teaser/Steine_3.jpg 1140w``

If you put a `,` between the image candidates it should work.

**Comment by crealistiques** [comment]
Wonderful! Thank you. I haven't been aware of that because I didn't suppose to find the error in the markup. It turns out that a bug related to Typo3 optionSplit functionality caused the wrong markup. Keep going.
