### ISSUE TITLE
Not all images are loaded, and lazybeforeunveil gets triggered repeatedly on the ones that are

### ISSUE THREAD

**Issue by Boldewyn** [aFarkas/lazysizes#322]
I see a peculiar behaviour on a live page using lazysizes 2.0.4 (installed via `npm`):

**How to reproduce**

1. Go to http://emojipedia.org/apple/ I tested with recent Firefox and Chrome on Linux. Apparently [Firefox and Opera on Win7](https://twitter.com/redvahido/status/794438048754724864) are affected, too.
2. Put this into the developer console:
    ```js
    document.addEventListener('lazybeforeunveil', function(e){
       console.log(e.target.title);
    });
    ```
3. Scroll down a bit.

**What happens?**

The console gets repeatedly filled with the same entries of already revealed images over and over again.

At the same time, some images get not loaded whatsoever. Even repeatedly scrolling past them doesn't work. There isn't even a request showing for them in the network tab of the dev tools.

All images are hosted on Amazon's S3 and served directly from the bucket.

**What should happen?**

I don't see that behaviour locally, when the images are loaded from `localhost`. There all images get lazy-loaded perfectly and one after the other. Each triggers exactly _one_ `lazybeforeunveil`.

It would be great to have this behaviour on the live site, too :smile:. There are no code differences between dev and live site. Both load the exactly same JS and feature the same HTML (modulo image source attribute).

If there are any more pointers that I can provide, I'd be glad to help.

**Comment by aFarkas** [comment]
The reason is: You are using rocket.js (http://emojipedia.org/cdn-cgi/nexp/dok3v=1613a3a185/cloudflare/rocket.js) which basically destroys `document.getElementsByClassName`. See here for inofmration: https://github.com/aFarkas/lazysizes/issues/254

**Comment by Boldewyn** [comment]
OK. Thanks for the answer and the pointer!
