### ISSUE TITLE
Above the fold background images are not loaded correctly with lazysizes ASYNC

### ISSUE THREAD

**Issue by ericvalois** [aFarkas/lazysizes#323]
Sometimes above the fold images are not loaded correctly when lazysizes scripts are ASYNC.

Background images below the fold are always loaded correctly.

```
<div class="lazyload"  	
data-sizes="auto"																					data-bgset="photo-14616.jpeg [(min-width: 60em)] |
photo-146169611.jpeg [(min-width: 52em)] |
photo-146169.jpeg">

<script async src='/lazysizes/plugins/bgset/ls.bgset.min.js'></script>
<script async src='/lazysizes/lazysizes.min.js'></script>
```

Do you know a work around?

**Comment by aFarkas** [comment]
This happens because sometimes the plugin is loaded after the core script is executed.

Both scripts are very small and are crucial. You really should combine these two scripts into one. As soon as you have combined your scripts it will work.
