### ISSUE TITLE
Display: none !important;

### ISSUE THREAD

**Issue by slumbering** [aFarkas/lazysizes#325]
Hi,

I don't know what I'm doing wrong... Lazysize add automatically a **display: none !important**
Here is a codepen : [codepen.io/slumbering/pen/eBJmVj](http://codepen.io/slumbering/pen/vyLOJZ)

Many thanks in advance
Jeff

ps: This code doesn't work only on **Chrome**

**Comment by aFarkas** [comment]
I can not reproduce this. Do you mean that it works only in Chrome or that it doesn't work only in Chrome. The only thing I saw, is that adblockers start to kick in. This has nothing to do with lazySizes but with the image url you are using.

**Comment by slumbering** [comment]
It did not work in Chrome only but my bad, if adblock is unactivate it works. 
Sorry and thanks
