### ISSUE TITLE
picture-issue with Edge and Firefox preferring .webp

### ISSUE THREAD

**Issue by Duncank** [aFarkas/lazysizes#326]
I've got several picture elements on my webpage that use both .webp and .png or .jpg images for several sizes. The example code comes from the lazysizes examples, but that example did not have multiple filetypes specified.

When I do, Firefox and Edge try to display the .webp-images, but because they don't have support for that, the image can not be displayed.

The code I've used looks like this:
`<picture class="fullwidth">`
`<!--[if IE 9]><video style="display: none"><![endif]-->`
`<source data-srcset="/img/home_header_screenshots_500.webp" media="(max-width: 543px)" />`
`<source data-srcset="/img/home_header_screenshots_500.png" media="(max-width: 543px)" />`
`<source data-srcset="/img/home_header_screenshots_800.webp" media="(max-width: 1024px)" />`
`<source data-srcset="/img/home_header_screenshots_800.png" media="(max-width: 1024px)" />`
`<source data-srcset="/img/home_header_screenshots.webp" />`
`<source data-srcset="/img/home_header_screenshots.png" />`
`<!--[if IE 9]></video><![endif]-->`
`<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/img/home_header_screenshots.png" class="lazyload" alt="5X Screenshots" />`
`</picture>`

I'd like lazysizes to use the next supported image when the .webp fails, but falling back to the regular img-element would be acceptable as well.

I'm using lazysizes 2.0.7 without other plugins.
[Test site](https://website.5-x.nl/home_test)

**Comment by aFarkas** [comment]
You must add the ` type="image/webp"` to your `source` elements, that contain a webp image.

Please close if this helps.

**Comment by Duncank** [comment]
Thanks so much, it works with `type="image/webp"` added to the source elements.
