### ISSUE TITLE
Lazyloading triggered on images without `lazyload` class name

### ISSUE THREAD

**Issue by lmartins** [aFarkas/lazysizes#328]
Im working on a WP project that uses a plugin called WP Rocket. That plugins allows the editor to add lazyloading to inline images, changing the markup to something like:

```
<img class="aligncenter size-full wp-image-24330 lazyloaded" src="data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs=" data-lazy-src="[IMAGE_PATH]" alt="who-what-when-dashboard" width="939" height="363" data-lazy-srcset="[IMAGE_PATH] 939w, [IMAGE_PATH] 200w, [IMAGE_PATH] 300w" data-lazy-sizes="(max-width: 939px) 100vw, 939px">
```

Even though these images don't have the class name `lazyload` before javascript parses the page, they still getting the classname `lazyloaded` which leads me to believe that somehow lazysizes is still processing these images and in that way conflicting with WP Rocket.

Any way I can prevent lazysizes from making any changes to these images?

**Comment by aFarkas** [comment]
Pretty sure, that lazySizes doesn't do this if there is no marker class. But I can only help if you can give me a link to see this behavior in action.

You can also try to check. break on... attribute modifications is your best friend here.

**Comment by aFarkas** [comment]
From re-reading. WP Rocket is a bad corrupt script, that destroys native browser methods. You simply should remove this script or demand a fix of WP Rocket.
