### ISSUE TITLE
data-src img without width not lazyloading on ajax'd page

### ISSUE THREAD

**Issue by CanRau** [aFarkas/lazysizes#330]
I really love your plugin more and more, really like the auto initialization and watching, just learned about MutuationObserver from your code! Thanks for that ;)

I'm using the simplest markup (the first one from the readme) in one project right now
`<img data-src="image.jpg" class="lazyload" />`
which is working fine on page load, but on pjax page load they wont load at all..just found out that adding a width to the img tag helps, is that right? Am I missing something?

Don't know if it's a but or my misunderstanding, just had the feel to share and maybe learn something ;-)

**Comment by aFarkas** [comment]
I would need to see a test case or a live page that demonstrates the issue. In case an image has a height and width of 0 it might be considered as invisible to the user and won't get lazyloaded.

**Comment by CanRau** [comment]
don't have the time right now and I'm fine specifying width on the images which did the trick..I think this could be interesting information in the readme because (at least for me) it works without width/height on page load..just the ajax loaded won't show up..
just a thought..

**Comment by sammyzeal** [comment]
I'm having this same issue, lazyload is working fine but when i try use it after ajax call it won't load img

<img class='lazy' data-src='"+imgUrl+$items[i].profile_img+"' width='150' alt='"+$items[i].title+"' title='"+$items[i].title+"'>"+

but if i remove the lazy class and set the data-src to src then it works why is this happening in ajax call and how to fix this

**Comment by aFarkas** [comment]
> I would need to see a test case or a live page that demonstrates the issue. In case an image has a height and width of 0 it might be considered as invisible to the user and won't get lazyloaded.

**Comment by sammyzeal** [comment]
currently my project is not on live server, but the portion of the code that fail looks like
<img class='lazy' data-src='"+img+$items[i].profile_img+"' alt='"+$items[i].title"' >
the image width and height is set to 100% and this code works with the same image in php file and lazyload works good also, but using it in ajax return data it won't work
