### ISSUE TITLE
usage with imagesLoaded

### ISSUE THREAD

**Issue by magicspon** [aFarkas/lazysizes#331]
Hello,

Firstly, thanks for your amazing work here. This is a must use plugin...

Anyhow, I've tried to use it in conjunction with imagesLoaded, but alas it is not working.  Essentially I have a grid of images (masonry type layout) that I can only initialize once all of the images have been loaded.  The Aspect ratio css trick isn't going to work as all of the images are different sizes.

Any thoughts.

Thanks

**Comment by magicspon** [comment]
I've done this... I never used MutationObservers before, so not 100% this is the best way to do this

```
function lazyLoadedImagesLoaded(el, each, complete) {
	const $tag = $(el)
	const config = {
		attributes: true,
		childList: false,
		characterData: false,
		subtree: true,
		attributeFilter: ['class']
	}

	const images = el.querySelectorAll('img')
	const total = images.length

	let previous = ''
	const observer = new MutationObserver((mutations) => {
		mutations.filter((mutation) => mutation.target.tagName.toUpperCase() === 'IMG')
						.forEach((mutation) => {
							if(previous === mutation.target.currentSrc && typeof each === 'function') {
								each(mutation.target)
							}
							previous = mutation.target.currentSrc
							if($tag.find('.lazyloaded').length >= total) {
								observer.disconnect()
								if(typeof complete === 'function') {
									complete()
								}
							}
						})
	})
	observer.observe(el, config)
}
```

**Comment by aFarkas** [comment]
@magicspon 
This is a possible solution. 

Other ones: 
1.re-Update your layout (https://github.com/aFarkas/lazysizes#updating-layout-of-js-widgets): http://codepen.io/aFarkas/pen/JdrXjm

2. If an image is loaded there is always a load event. lazySizes adds/removes classes only inside a rAf so. So if you check after load + rAF you can see wether there are still `.lazyloading, ..lazyload` classes in your DOM. Or you can filter .lazyloading` with `image.complete` to remove loaded images, without a rAF. (See also: https://github.com/aFarkas/lazysizes/issues/329)

3. You can also lighten your test with the detect above.

```js
function lazyLoadedImagesLoaded(el, each, complete) {
	const $tag = $(el)
	const config = {
		attributes: true,
		childList: false,
		characterData: false,
		subtree: true,
		attributeFilter: ['class']
	}

	const observer = new MutationObserver((mutations) => {
		if($tag.find('.lazyloading, .lazyload').length){
			observer.disconnect()
			if(typeof complete === 'function') {
				complete()
			}
		}	
	})
	
	observer.observe(el, config)
};
```

**Comment by magicspon** [comment]
Hi Thanks for your reply.

I'm using this in conjunction with packery so I've filtered out any mutations on non image elements.  

And then this bit:

```
if(previous === mutation.target.currentSrc && typeof each === 'function') {
   each(mutation.target)
}
previous = mutation.target.currentSrc
```

ensures that the each function is only called once per image.

```
const pkr = new Packery(el, {
			itemSelector: '.js-cell',
			resize: true,
			gutter: 10,
			percentPosition: true,
			initLayout: false
		})
		lazyLoadedImagesLoaded(el, pkr.layout.bind(pkr), log.bind(null, 'all finished'))
```
