### ISSUE TITLE
Use "data-ls-lazyload" instead "lazyload" class

### ISSUE THREAD

**Issue by rolandtoth** [aFarkas/lazysizes#332]
Consider the following snippet:

```php
<img <?php echo functionToGenerateLazysizeAttributes(); ?> class="lazyload align-right" />
````
The function here generates all the attributes lazysizes needs but the lazyload class should be added manually. However, the function could also add the class but that would result in double class attributes.

Using "data-ls-lazyload" attribute could fix this:

```php
<img <?php echo functionToGenerateLazysizeAttributes(); ?> data-ls-lazyload class="align-right" />
````

The php function is part of a module in a CMS and it's configurable whether to include the "lazyload" class or not, but even so it often leads to confusion. The data attribute could easily solve it.

I can create a PR if you wish.

**Comment by aFarkas** [comment]
The answer is, that you can't switch this so easily. lazySizes uses live nodelists, which are returned by functions like `getElementsByTagName`/`getElementsByName` and `getElementsByClassName`. Methods like `querySelectorAll` only return static nodelists.

The best way is to change your php code:

```
//note i don't know how to create a map in php
<img <?php echo functionToGenerateLazysizeAttributes({classes: 'align-right'}); ?> />
```

**Comment by rolandtoth** [comment]
Thanks for the info, I have to admit it's the first time I heard of live vs static nodelists.

I'm already using the same approach now as you suggested.
