### ISSUE TITLE
Preloader callback

### ISSUE THREAD

**Issue by microcipcip** [aFarkas/lazysizes#334]
Is it possible to have a preload all images callback, or at least for all images in-view? I'd like to hide a preloader when all images ara ready. I am using the `bgset` plugin.

**Comment by aFarkas** [comment]
Yes, you already have the `lazybeforeunveil` and the native `load` event on the one hand and the `lazySizes.loader.unveil(DOMNode)` method on the other.

I don't really understand what you exactly need. You can also use the `lazyloading` and `lazyloaded` classes.
