### ISSUE TITLE
Retina Images IE

### ISSUE THREAD

**Issue by haenson** [aFarkas/lazysizes#335]
Hello,

Unfortunately, the retina srcset does not work in IE (on non retina and retina Devices).
No image is displayed.

Code:
`<img data-srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x" class="lazyload" />`

Output IE11:
`<img class=" lazyloading" data-srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x" srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x">` 

Output IE10:
`<img class=" lazyloading" data-srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x" srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x"/>`

Output IE9:
`<img class="lazyload" data-srcset="http://placehold.it/1024x1024 1x, http://placehold.it/1026x1026 2x"/>`

Thank you & best,
Henning

**Comment by aFarkas** [comment]
This is documented here: https://github.com/aFarkas/lazysizes#responsive-image-support-picture-andor-srcset.
