### ISSUE TITLE
No speed difference on iFrame

### ISSUE THREAD

**Issue by eladnova** [aFarkas/lazysizes#337]
I've a page with a few iframes. 
Before adding the lazyload class to the iframe, I get the following results in GTMetrix

PageSpeed Score: 41%
Page Load Time: 2.5s
Total Page Size:2.43MB

Shouldn't I notice a faster PageSpeed score, load time and smaller page size after applying the lazyload score?

Re-running the test in GT Metrix gives me the same results with and without LazySizes running.

**Comment by aFarkas** [comment]
This totally depends on your page setup and for what and you use lazysizes. I can't say what you are doing wrong, as long as I don't see a test case.

Please re-open if you can provide a testcase.
