### ISSUE TITLE
Combine w and x descriptor errors

### ISSUE THREAD

**Issue by kdesigns** [aFarkas/lazysizes#338]
I'm getting errors when combining width and x descriptors. Should I achieve beneath code in a different way?

```
<img class="lazyload"
   src="img_placeholder.jpg"
   data-srcset="    img_lg@1x.jpg 1x, img_lg@2x.jpg 2x,
                    img_xlg@1x.jpg 1200w 1x, img_xlg@2x.jpg 1200w 2x,
                    img_md@1x.jpg 992w 1x, img_md@2x.jpg 992w 2x,
                    img_sm@1x.jpg 768w 1x, img_sm@2x.jpg 768w 2x"
    width="300"
    height="300"
    alt="" />
```

My goal is to have responsive images && retina images.

**Comment by lunelson** [comment]
Short answer: don't combine `x` and `w`, it's not necessary. The whole point is that the browser figures out which image it needs from the `w` descriptors, based on the `sizes` attribute, which here is provided by the script. 

@aFarkas effectively answers this question here http://stackoverflow.com/a/26937237/1204994
