### ISSUE TITLE
Question: Cached images

### ISSUE THREAD

**Issue by mendrik** [aFarkas/lazysizes#344]
is there a way for skipping a css animation if an image was already loaded and is in cache?

Basically right now all my images always css animate, and I would like to have that effect only for new/not yet cached images...

**Comment by aFarkas** [comment]
This isn't really doable. What I did for a customer was that I created a kind of a blur up plugin, that only did the blur up animation if image loading took longer than 33ms.

The hole code looked something like this:

```js
const matchingMedia = (source)=> {
    const media = source.getAttribute('media');
    return !media || matchingMedia(media).matches;
};

const createBlurup = (insertElement, img, src)=>{
    let timer, blurImg;
    const removeImg = ()=>{
        requestAnimationFrame(()=>{
            blurImg.remove();
        });
    };
    const onload = ()=> {
        clearTimeout(timer);
        img.removeEventListener('load', onload);

        if(blurImg){
            blurImg.classList.add('is_loaded');
            setTimeout(removeImg, 999);
        }
    };

    img.addEventListener('load', onload);

    timer = setTimeout(()=>{
        if(!img.complete){
            requestAnimationFrame(()=>{
                if(!img.complete) {
                    blurImg = document.createElement('img');
                    blurImg.className = 'mediabox_blurupmedia';
                    blurImg.src = src;
                    insertElement.parentNode.insertBefore(blurImg, insertElement.nextSibling);
                }
            });
        }
    }, 33);
};

document.addEventListener('lazybeforeunveil', function(e){
    const img = e.target;
    const picture = img.closest('picture');
    const sources = picture ?
        Array.form(picture.querySelectorAll('source, img')) :
        [img]
    ;
    const source = sources.find(matchingMedia);
    const src = source.getAttribute('data-lowsrc');

    if(src){
        createBlurup(picture || img, img, src);

    }
});
```

**Comment by lunelson** [comment]
FWIW there seems to be consensus on SO that the check `img.complete || img.width + img.height > 0` should allow you to check whether an image is cached or not... possibly one could use the lifecycle hooks to append a different class (e.g. `is-cached`) or set of classes, and hang the animation/transition CSS on those?

**Comment by aFarkas** [comment]
@lunelson 
I will look into this. I'm currently on holiday.

**Comment by mario-merino** [comment]
@aFarkas first of all, many thanks for this library, it's terrific.

I'm currently looking for solutions to this issue but haven't quite find one. it would be amazing if you add this functionality

**Comment by aFarkas** [comment]
@mario-merino 
In case you are working with effects plugin you can already use the following configuration:

```js
lazysizes.cfg.blurupMode = 'auto'; // default is 'always'
```

or from an image by image basis:

```css
img {
    font-family: "blur-up: always", "object-fit: cover";
}
```
