### ISSUE TITLE
Google bot search console query

### ISSUE THREAD

**Issue by code-mattclaffey** [aFarkas/lazysizes#345]
Hello,

I am having an issue trying to propose a solution to a clients problem by suggesting to implement plugin into the solution. The clients concern is that they will not be able to view the images correctly in their search console(which lowers their SEO rank). So before I implemented it I created a test page where the client can test this page only before implementation. 

They have come back with this:

![google_render_-_lazyload](https://cloud.githubusercontent.com/assets/10598938/21806036/3b2725b6-d72f-11e6-9ff4-d78c40af0600.gif)

I have looked at previous issues relating to SEO on this repository. Is there any justification in why this is happening in their search console?

Thank you

**Comment by aFarkas** [comment]
This shouldn't be a lazysizes problem. Here is an example of testpage:

<img width="916" alt="bildschirmfoto 2017-01-10 um 14 52 30" src="https://cloud.githubusercontent.com/assets/188254/21808776/0cee249a-d745-11e6-9738-b22cc0cd9bdd.png">

Here is a possible explanation:
https://productforums.google.com/forum/#!topic/webmasters/3X0X8c3c39U
