### ISSUE TITLE
does srcset need to be in a specific order?

### ISSUE THREAD

**Issue by lunelson** [aFarkas/lazysizes#347]
So I'm implementing something using the wordpress REST API. This is handily able to output an `srcset` value for an image. However if I customize the `thumbnail_sizes` configuration in WP, the srcset does not come out *in order*, i.e. they are formatted correctly but not in order of ascending sizes. Is it a false assumption that the `srcset` or rather `data-srcset` in this case needs to be in any specific order?

**Comment by aFarkas** [comment]
No it doesn't have to be in order the browsers as also the polyfills order the image candidates themselves.

**Comment by lunelson** [comment]
Perfect. Thanks for clarifying 👍
