### ISSUE TITLE
Control load and unveil independently

### ISSUE THREAD

**Issue by 0xsven** [aFarkas/lazysizes#348]
My use case is this:
- Preload images with 500px 'expand'
- Unvleil them only when in viewport.

Is that possible?

**Comment by aFarkas** [comment]
You would need to write a plugin for this. But you can also already do something like this:

```html
<div class="lazyload" data-expand="-9">
   <img class="lazyload" data-src="..." data-srcset="..." src="..." />
</div>

**Comment by 0xsven** [comment]
This would start downloading the image 9 pixels before?

**Comment by aFarkas** [comment]
I assume you want to do this for animations:

The image element has no expand attribute, but a lazyload class so the default kicks in (between 0-750 depending on viewport size and the download situation). So it can download some time earlier.

The div has a lazyload class and a negative `data-expand` value. 
The `expand` option defines the margin, that the viewport should expand to find elements. A negative value makes this more narrow. So `-9` means the `div` is at least already 9 Pixel in view.

With this you can build something you want. 

Your css could look something like this:

```html
<style>
/* set all images inside of an .img-wrapper to opacity: 0 */
.img-wrapper .img {
    opacity: 0;
    transition: opacity 400ms;
}

/* set .img to opacity:1 as soon as 1. image is loaded and 2. .img-wrapper is inview. */
.img-wrapper.lazyloaded .img.lazyloaded {
    opacity: 1;
}
</style>
<div class="img-wrapper lazyload" data-expand="-9">
   <img class="img lazyload" data-src="..." data-srcset="..." src="..." />
</div>
```

**Comment by aFarkas** [comment]
If this helped can you close?

**Comment by aFarkas** [comment]
Please re-open with more information, if this didn't help.
