### ISSUE TITLE
Quote issue in unveilhooks plugin with background images

### ISSUE THREAD

**Issue by dannyvw** [aFarkas/lazysizes#349]
If you have a background url image like this https://www.domain.com/uploads/media/image -® image image-1.jpg. Then it will not be rendered with the unveilhooks plugin. Adding quotes like done in  https://github.com/aFarkas/lazysizes/pull/288/commits/b4502abe5b2f95baa0922f558f3728b784de93a8 will fix the issue.

**Comment by dannyvw** [comment]
@aFarkas Thanks for fixing. Can you tag this?

**Comment by aFarkas** [comment]
done
