### ISSUE TITLE
Use .classList() where available

### ISSUE THREAD

**Issue by stowball** [aFarkas/lazysizes#351]
Modern browsers (including IE10) support adding, removing and checking whether classes exist with [`.classList()`](https://developer.mozilla.org/en/docs/Web/API/Element/classList).

I'm sure it's more performant to use native features than custom regular expressions etc, so it would be good to use `.classList()` where it's available, and fallback to your custom methods when it's not.

**Comment by aFarkas** [comment]
This would be a classical version of premature optimization. Setting/Checking/Removing a class is already extremely fast. If classList is faster than my implementation (which is not clear) the hole lazySizes transformation would be improved by 0.001%.

The downside of this is that I need to 

a) either add a feature detection (which not only tests for the existence of the API, but als for bugs in this API and [introduce an additional code path](https://developer.mozilla.org/en-US/docs/Web/Guide/Writing_forward-compatible_websites#Don't_unnecessarily_create_separate_codepaths_for_different_browsers) (duplicates the source of error and make testing more difficult)
b) or add a dependence to a battle tested polyfill.

I might go with option b) at some point, but currently not. (BTW.: In my personal projects, I always use option b in form of [DOM4](https://github.com/WebReflection/dom4), but I cannot force most current lazySizes developers to add an additional polyfill.)

Also note: That lazySizes addClass/removeClass/hasClass implementation supports svg elements, which is not supported by IE11. So current lazySizes users, who are using lazySizes in conjunction with svg elements would be forced to use a classlist polyfill for even the latest version of IE.

**Comment by stowball** [comment]
That's a fair and reasoned response. Thanks
