### ISSUE TITLE
Trigger event when image is rendered

### ISSUE THREAD

**Issue by Jones-S** [aFarkas/lazysizes#355]
Hi there 
This is rather a question than an issue.
Anyway, this is what I want to achieve:
I am working on a pjax transition where I go to a new page and load a large image. During the transition I have an image (from the old page) in front, and I fade it out after replace the content in the back with the ajax-response.

I am using this altogether with your nice lazysizes plugin.

The problem is, that I don't know when the image in the back is rendered, so I don't know when I can fade out the image in the front.

What I would love to have is an event triggered as soon as the image in the back is ready on screen, and then fade out the image in the front, revealing the one below.

If you have cached the image, that is working perfectly fine, but with that and even combined with a bad internet connection the image in front is faded out to white and suddenly the one below appears. (Currentyl I just set a timeout for the fade to wait a little bit).

Does your lazysizes provide something like an event I could listen to? Or do I have to look elsewhere?

Cheers and thank you : 1. for your awesome work and 2. for any hint or help you can give to me.

J

**Comment by aFarkas** [comment]
you can use the native `load` event for this.

**Comment by aFarkas** [comment]
Try this:

```js
$(document).on('lazybeforeunveil', '.your-image-selector', (e)=> {
    $(e.target).one('load', yourReadyHandler);
});
```

**Comment by Jones-S** [comment]
Hm, I see, I made a major mistake by not placing the two images on top of each other. (Had to give them `position: absolute` obviously 🙈 ). Well anyway, why I get back to you is, because I found out that while the image is being loaded lazysizes assigns the class `lazyloading`, and when done it assigns `lazyloaded`. Which is great. I can now get the effect I wanted by doing this:

```
hero {
	transition: opacity 300;
}

hero.lazyloading {
	opacity: 0;
}

hero.lazyloaded {
	opacity: 1;
}
```

the thing is that I have other elements I'd want to fade out at that timepoint.
I thought, well your lazysizes must somehow change those extra classes at the moment when the image is loaded. So maybe it would be possible to add an event-trigger at the same time. How could I do that? Or does lazysizes offer some possibilites to listen to this moment already? Maybe the event `lazybeforeunveil` ?

If you could direct me to the right path that would be great.
Anyway thank you very much.

**Comment by Jones-S** [comment]
Oh hey I totally missed your last comment. I'll try that. Thank you so much.

**Comment by Jones-S** [comment]
👍 😸  Thanks man. It works! Great success.
