### ISSUE TITLE
RIAS - Include a h (height) descriptor in srcset image candidates

### ISSUE THREAD

**Issue by t-kelly** [aFarkas/lazysizes#357]
I would love to be able to use the RIAS plugin along with parent-fit plugin for images and background images that are set to to `cover`. From what I understand, I need to have a `h` descriptor in srcset to do this, which RIAS currently does not do.

Can we make this available?

**Comment by aFarkas** [comment]
I don't know your use case but if you want to workaround IE/Edge lack of `object-fit` support. Use the following polyfill instead: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit

You should still use the the parent-fit plugin for the right `sizes` calculation. 

For your h problem, you can workaround this problem by adding a `data-aspectratio` attribute (i.e. `srcset="img.jpg 50w 100h" data-aspectratio="0.5"`).

**Comment by t-kelly** [comment]
Hey @aFarkas - yeah I was using parent-fit for the `sizes` calculation, but one of the requirements is that:

> at least one of the image candidates inside the srcset attribute also need to include a h (height) descriptor for at least one image candidate in each srcset.

The RIAS plugin does not export srcset candidates with `h` descriptors. I was unaware of `data-aspectratio` being used by parent-fit for size calculation. Do you need to be using the aspectRatio plugin in order to use `data-aspectratio`?

**Comment by dnwhte** [comment]
I am using rias + bgset and also need the ability to set the h descriptor. Since rias creates the srcset I cannot add it manually.
