### ISSUE TITLE
iframes and firefox - broken browser history back button

### ISSUE THREAD

**Issue by Kithaitaa** [aFarkas/lazysizes#36]
Hi,

on firefox the browser back button behaviour is somekind of broken - it fills all the empty iframe sources in the browser history. Here's a discussion about it:
http://stackoverflow.com/questions/2245883/browser-back-acts-on-nested-iframe-before-the-page-itself-is-there-a-way-to-av

Would be great if you could fix this in your script.

bye
Kith

**Comment by aFarkas** [comment]
@Kithaitaa 
Thank you so much! I fixed it in master but forgot to mention the issue number. Here is the commit: https://github.com/aFarkas/lazysizes/commit/512800de6ebddf6a5000624b67f86c4f0d77d8c6
