### ISSUE TITLE
Different loading behaviour seen on Safari vs Chrome/Firefox

### ISSUE THREAD

**Issue by voodoo6** [aFarkas/lazysizes#360]
Hi,

Lazysizes looks great – and seems to solve my biggest problems with other lazy-loaders. However I'm testing it on an image-heavy site I'm building and and noticing different behaviour on Safari vs Chrome and Firefox.

It seems Safari loads most of the content with class '.lazyload' resulting in a large initial download,  whereas Chrome and Firefox do not and behave as expected.

You can see this happening here:
http://tenfold.webflow.io/home-colour

In dev tools, notice how Safari (with an empty cache) loads ~25mb of data, whereas Chrome and Firefox (with an empty cache) load  around 10mb – which is what I would expect with how lazysizes is setup. 

So Chrome and Firefox appear to be working as expected, is this a Safari bug?

Many thanks for any help.

----------

Note that I have no control over the HTML for the `<img>` tags, so am using this method to replace pre-existing src, srcset and sizes attributes, prior to initialising lazysizes:

```
<script>
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/3.0.0/lazysizes.min.js"></script>
</script>

<script>
$(document).ready(function() {

  $('.lazyload').each(function() {
      $(this).attr('data-src', $(this).attr('src'));
      $(this).removeAttr('src');

      $(this).attr('data-srcset', $(this).attr('srcset'));
      $(this).removeAttr('srcset');
      
      $(this).removeAttr('sizes');
      $(this).attr('data-sizes', 'auto'); 
      
      lazySizes.init(); 
  });

});
<script>

</body>
```

lazysizes v3.0.0 (via CDN)
Safari 10.0.3 (12602.4.8)
Chrome 56.0.2924.87
Firefox 51.0.1

**Comment by aFarkas** [comment]
> Note that I have no control over the HTML for the <img> tags, so am using this method to replace pre-existing src, srcset and sizes attributes, prior to initialising lazysizes

There is nothing wrong with lazysizes here. Your way of trying to lazyload things simply doesn't work in Safari. You can not abort a started download by removing or changing the `src` in Safari.

Also note: That around one year ago this didn't even work in FF and around 1 1/2- 2 years ago it didn't work in Chrome. IE was the only browser that aborts downloading images by changing/removing the `src`.

See: https://bugs.webkit.org/show_bug.cgi?id=6656

**Comment by voodoo6** [comment]
Thanks you very much for the information, it's very helpful.

Given my circumstances, it looks like I'll have to live with the wait times for Safari users.
Many thanks for lazysizes.
