### ISSUE TITLE
Isotope + Lazysizes

### ISSUE THREAD

**Issue by nfq** [aFarkas/lazysizes#361]
I found the jQuery version of this. But is there a demo or gist somewhere for achieving this with Vanilla JS?
Thanks!

**Comment by Kracheads** [comment]
I'm looking for the same but with JQuery I have a card design with an image inside of it I would like to lazy load, but isotope glitches badly.

**Comment by aFarkas** [comment]
Please read through these issues:
https://github.com/aFarkas/lazysizes/issues/118
https://github.com/aFarkas/lazysizes/issues/212

You should be able to solve your problem with the information given there.

**Comment by nfq** [comment]
Thanks @aFarkas. But I didn't find a way to Init Isotope and Lazysizes using vanilla JS on any of the issues you mentioned. Am I missing something?
