### ISSUE TITLE
Lazyloaded class getting set on bgset image before image actually loaded (images loading twice?)

### ISSUE THREAD

**Issue by blimpmason** [aFarkas/lazysizes#363]
Hey, I'm having trouble getting unveil CSS animations in place on bgset images because it seems like the "lazyloaded" class is getting added before the image asset has actually loaded. So for example the opacity transitions to 1 but then the image loads and hard cuts into view. 

As an example, take a look at the hero image at the top of of this page and perhaps try throttling connection speed (it happens consistently for me when the connection is throttled to DSL / 2Mb/s):

http://trollback.grossdevelopment.net/

One other thing I noticed which is probably related is that each image asset on that page (when monitoring the network tag of Chrome developer tools) gets loaded twice (at the exact same size). On my localhost build each image gets loaded only once, and the unveil animations work perfectly even when throttling the connection and disabling cache.

I notice that same behavior (each image loading twice and loading animation going away prematurely) on your bgset example jsfiddle:

http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

Thanks a lot for this awesome package and for any ideas you have on the issue above.

**Comment by aFarkas** [comment]
You have to change to things:

1. Your cache headers are pretty bad:
(The demo is similar)
```
Cache-Control:max-age=0, private, no-cache, no-store, must-revalidate
```
2. Dev Cache
Don't use disable cache option (Although I think, Chrome isn't this bad here.)

**Comment by blimpmason** [comment]
Got it, thanks! I had to set the cache headers while in development because my staging server host was automatically caching everything — I'd roll out iterative updates but they wouldn't show up. I should have known that would have affected those image loads.

**Comment by catsr** [comment]
@aFarkas question regarding the above issue of images loading twice - you mention setting cache headers appropriately to make sure images actually get cached.

Is this just to avoid the second image load hitting the server, or would that somehow fix the issue by eliminating the second load itself?

Also, could you explain how or why the second image request is being triggered in the first place?

Thank you!

**Comment by aFarkas** [comment]
> Is this just to avoid the second image load hitting the server, or would that somehow fix the issue by eliminating the second load itself?

What is the exact difference? I'm not a native english speaking guy.

> Also, could you explain how or why the second image request is being triggered in the first place?

The cache header: `...no-store, must-revalidate`  means that the browser has to reload images even if there was no image change, but for example the dom node that has referenced an image has changed in the dom tree. (For example by sort or wrap).

In our case we have an `img.src/img.srcset/source.srcset` for the first image and `style: background-image: image` for the second.
