### ISSUE TITLE
Image is downloaded but not assigned to the src attribute

### ISSUE THREAD

**Issue by lmartins** [aFarkas/lazysizes#367]
Hi,

First of all, thanks for this excellent library which I've been using for a while, along with its various extensions, with great success. It is awesome, really!

Recently I've been working with sites using Vue to render some views and I think I got into an issue that might be a consequence of combining these two technologies. 

What happens is that randomly images will not get the src attribute assigned into them. They get the CSS class `lazyloading`, the image does show on the network tab, but the `src` attribute never gets assigned so the images stay blank. Scrolling up/down makes no difference, taking sometimes a few reloads to get them to work.

Manually running `lazySizes.init()` on the browser console doesn't make a difference either.

Is this a known issue by any chance?

Update: worth mentioning that Im using webpack lazyloading for the modules that renders this view, so perhaps this is causing the issue by parsing the view after lazySizes has parsed the DOM?

**Comment by lmartins** [comment]
Just to add on this issue, I've also noticed that srcset attribute is written to the DOM (from the original `data-src` config).

This is what is being written to the page:

```
<img src="//localhost:3000/wp-content/uploads/2017/03/ffg_company-1200x0-c-default.jpg" data-srcset="
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-2000x0-c-default.jpg 2000w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-1200x0-c-default.jpg 1200w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-800x0-c-default.jpg 800w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-400x0-c-default.jpg 400w
                    " data-sizes="auto" itemprop="image" sizes="1614px" srcset="
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-2000x0-c-default.jpg 2000w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-1200x0-c-default.jpg 1200w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-800x0-c-default.jpg 800w,
                    //localhost:3000/wp-content/uploads/2017/03/ffg_company-400x0-c-default.jpg 400w
                    " class=" fade-up bg lazyautosizes lazyloading">
```

But because the image never gets the class `lazyloaded` the fade up animation never gets triggered and therefore the image stays blank.

**Comment by podlebar** [comment]
+1

**Comment by rototor** [comment]
I've got a similar problem and found a (ugly) workaround for it:

```
               var switchLoadingClass = function(e){
			addClass(e.target, lazySizesConfig.loadedClass);
			removeClass(e.target, lazySizesConfig.loadingClass);
			addRemoveLoadEvents(e.target, rafSwitchLoadingClass);
			/* Element removed from the DOM?! */
			if ( !e.target.documentElement ) {
				var elements =  document.getElementsByClassName(lazySizesConfig.loadingClass);
				for( var i = 0; i < elements.length; i++) {
					switchLoadingClass({target:elements[i]});
				}
			}
		};
```
My workaround just checks at the time a element should get loading class removed if it is still linked in the DOM. I have no idea why this is happening on my page, but my workaround just removes the lazyloading class from all images currently loading. It seems lazyloading starts on the image, then the image gets cloned and removed from the DOM but the clone gets inserted at the place of the "old" image object. Don't ask my why this is the case. But this fixed the problem for me. (lazysizes version 3.0.0)

**Comment by aFarkas** [comment]
The following should work:
Re-add the class `lazyload` in the updated hook of your component.

Please also read the following issues and solutions:
- https://github.com/aFarkas/lazysizes/issues/354
- https://github.com/aFarkas/lazysizes/issues/343

If you need more information, you will need to create a test case first. Please close otherwise.

**Comment by lmartins** [comment]
@aFarkas Hi Alexander, thanks so much for your input here. Adding the class manually does make the image to load immediately. Keep in mind though, im seeing this on other projects where I've upgraded the lazyimages library, either they have Vue components or not.
