### ISSUE TITLE
parallele image loading (preloadAfterLoad)

### ISSUE THREAD

**Issue by jimblue** [aFarkas/lazysizes#379]
Hi!

I'm using the very nice option **preloadAfterLoad** to load all images once a page is loaded.

This feature is really nice but not optimised tough.
For now images are loaded one after an other...That takes a lot of time and could be way better.

So I was wondering if it possible to handle parallele image loading once page is loaded?

**Comment by jmbelloteau** [comment]
This could be useful to better understand the problem:

<img width="839" alt="screen shot" src="https://cloud.githubusercontent.com/assets/10623367/25085488/cf866198-2362-11e7-98fb-4f62cadd652e.png">

**Comment by jmbelloteau** [comment]
After Dom ready all images behind the blue line could be load in parallel to optimise global render time... what do you think guys?

**Comment by jhabdas** [comment]
@jmbelloteau what do you make of the following note next to the option in the README?

> Note: lazySizes will then still download those not-in-view images inside of a lazy queue, so that other downloads after onload are not blocked.

**Comment by jmbelloteau** [comment]
Thanks... peace!!!

**Comment by jimblue** [comment]
Hi @jhabdas !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @jhabdas !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers
