### ISSUE TITLE
Lazysizes does not work as expected when used with Cloudinary responsive w_auto

### ISSUE THREAD

**Issue by misner** [aFarkas/lazysizes#382]
Hi,

thanks first for this awesome tool you created and maintain !

I have a "simple" vertival feed of  images and i'd like to use lazysizes to **only load the images that are inside viewport (or near)**

Cloudinary responsive w_auto feature (sending back from server the right width basically) conflicts with Lazysizes.

As I understand (as a non expert) there are 2 issues
1. lazysizes will load on page load, even before any scroll ALL images if it can't get its width/height or via some html5 sizes attributes define them
=> the issue is how w_auto works on Cloudinary is that I set the data-src = https://res.cloudinary.com/dmd2rxt22/w_auto:200/example1.jpg. and then cloudinary server send back and add via js the src with the right width

2. both use the same data-src as basis of how they work and I think they collide with each other

I created this jsfiddle:
https://jsfiddle.net/t1sh9f50
fullscreen view: https://jsfiddle.net/t1sh9f50/embedded/result/

As you see if you look at Chrome Dev Tools, 2 issues collide to make 2 bugs (that might be related):
1. all images are loaded where as my goal is to have only the images inside viewport (or near) load
2. **all images are even loaded twice on page load**...because  I think the way lazysizes works is to use the data-src but cloudinary also...so i don't really know how to do but i guess lazysizes should wait that cloudinary use the data-src provided, then cloudinary send back and change via js the image to give the src with the right width of image, then here lazysizes should grab this and apply its lazy loading effect.

If you look at chrome dev tools: now all of the images are downloaded twice 
To be precise, if you really look, you’ll see it’s not exactly the same url that due to cloudinary, the page downloads
For example for the image called example1.jpg, 2 urls and files are downloaded
https://res.cloudinary.com/dmd2rxt22/w_auto:200/example1.jpg
and then later another "example1.jpg" is downloaded
https://res.cloudinary.com/dmd2rxt22/w_1200/example1.jpg (notice here the width has been sent by server to  be 1200)

How can I make Cloudinary with w_auto work with lazysizes ?

Note: w_auto:200 means that cloudinary send the best widht by steps of 200. for exmaple if detected width of viewport is 567px, then cloudinary send back url with =600px

**Comment by aFarkas** [comment]
This is not a lazysizes issue. You should remove the cloudinary script and handle everything by lazysizes. This plugin might make it easier: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/rias

**Comment by eitanp461** [comment]
@misner I setup a demo integrating lazysizes and Cloudinary for lazily loaded responsive images - http://codepen.io/eitanp461/pen/BRLZYq

**Comment by misner** [comment]
Thanks will check it, it's really nice form you. Had given up.
