### ISSUE TITLE
How to lazysize background image?

### ISSUE THREAD

**Issue by gety9** [aFarkas/lazysizes#385]
Sorry for newbie question, but didn't find examples in sample page for background images.

I have a div:
`<div id="ibanners-home" class="ibanners-wrapper"></div>`

With the following css:
```
#ibanners-home {
    background: rgba(0, 0, 0, 0) url("/images/main-banner.jpg") no-repeat scroll center top;
    height: 500px;
    min-width: 1200px;
    width: 100%;
```

Now the banner loads 1920x500 image for all screens. 
I would like to have 3 image versions: 1366x500, 1600x500, 1920x500 that will load depending on the screen resolution.

How do i do that?

**Comment by puppetmaster3** [comment]
What is the answer?

**Comment by gety9** [comment]
At the end i used media queries, not lazy load
Cause banner was on top of the page and lazy load was not required at all.
