### ISSUE TITLE
Load only visible images

### ISSUE THREAD

**Issue by stratboy** [aFarkas/lazysizes#386]
Hi, it's not clear to me: is it possible to lazyload only visible images?

**Comment by aFarkas** [comment]
what do you mean exactly?

**Comment by stratboy** [comment]
Hi. Sometimes (as for my current project) I mean to load an image only when the window is above a certain width. In other words: no images at all on mobile devices, only desktop.
In general, when you've got a situation like this, the image dom is hidden via css (display:none). It would be great if there was an option for not loading hidden images or placed into hidden elements.

Currently, I solved this problem by using the picture element with fake base64 default and only 1 media query (min-size: the large breakpoint).

**Comment by aFarkas** [comment]
lazySizes should not load images, that are hidden using `display: none`. If this is the case I consider this a bug. But I would need a test case from you, because I can not replicate this.

**Comment by stratboy** [comment]
Ah ok, then probably the issue was due to the fact that the image was not hidden (its container was). So maybe you can also check for ancestors visibility.

I cannot give you the real page since I already corrected it and it's still a staging website. Anyway, probably you can replicate simply but placing a picture element inside a div.box and hiding the div. Should be quite the same situation. So:

> <div class="box">[picture element]</div>
> .box{ display: none; }

**Comment by stratboy** [comment]
By the way, thank you very much for you amazing work!

**Comment by aFarkas** [comment]
Thank you. But I can not replicate this issue.

Here is a simplified test case: 
https://jsbin.com/kevaletona/edit?html,output

**Comment by stratboy** [comment]
Mmm. Strange. I'll let you know if I come across similar issues again. Thank you anyway and sorry for the time. Regards

**Comment by aFarkas** [comment]
Please re-open if you can reproduce.
