### ISSUE TITLE
lazybeforeunveil, using with isotope and velocity.js for image loading effects

### ISSUE THREAD

**Issue by macsupport** [aFarkas/lazysizes#387]
I am trying to use Isotope, Lazysizes  + [velocity.js](https://github.com/julianshapiro/velocity) for image loading effects. I have some success using `lazybeforeunveil` except that the images showing in the initial viewport do not show the effect. Scrolling seems to work as expected. I'm not sure if this is the best way to implement this, using `lazybeforeunveil`, with lazysizes or if I am using it incorrectly.
Here is my [jsFiddle](http://codepen.io/macsupport/pen/pPZrgV/)

    $( document ).ready(function() {
    var $container = $('#container');
    var $item = $('.item');
    var animateOptions = {
        stagger: 200,
        delay:100,
        drag: true
      }; 
     
     $container.isotope({
     itemSelector: '.item',
     masonry: {
      columnWidth: 200,
       gutter: 10,
       fitWidth: true
     },
     transitionDuration: '0s'
     }); 
   
    document.addEventListener('lazybeforeunveil', function(e){  
    $(e.target).velocity('transition.whirlIn',animateOptions);
    $container.isotope('layout');  
     });
    });

**Comment by aFarkas** [comment]
This is a timing issue. At the time lazysizes starts downloading the images jQuery's ready event is not yet fired. Here is a fixed code pen: http://codepen.io/anon/pen/eWjjbr

**Comment by macsupport** [comment]
Thanks! Quick follow-up. Is it reasonable to also use `setTimeout` with `lazybeforeunveil` in a case like this?
