### ISSUE TITLE
Inconvenience to increase "class" how to do?

### ISSUE THREAD

**Issue by Rookie-operation** [aFarkas/lazysizes#395]
I have used "echo.js", only need to modify the "src" can, but the rotation picture is not compatible, so give up.
Recently discovered "lazysizes", but because "lazysizes" need to increase the "class" to use, which for me is very troublesome.
I as a novice third party developers, can not modify the user html code, only through the "php" to replace "src", but to replace the "class", then it will increase the workload.
So I hope that can only increase the "data-src" can be used?

**Comment by Rookie-operation** [comment]
`<img src"https://github.com/test.jpg">` 
to
 `<img lazysizes="lazyload" data-src="https://github.com/test.jpg">`
Do not modify "class" can you? @aFarkas

**Comment by aFarkas** [comment]
With the newest version you can override the externals. This would look something like this:

```js
Object.defineProperty(lazySizes, 'elements', {
    get: function(){
		return document.querySelectorAll('img[data-lazyload]');
    },
	configurable: true,
	enumerable: true,
});

window.addEventListener('lazybeforeunveil', function(e){
	if(e.defaultPrevented){return;}
	e.removeAttribute('data-lazyload');
});
```
