### ISSUE TITLE
fastdom / strictdom support

### ISSUE THREAD

**Issue by wjordan** [aFarkas/lazysizes#396]
Feature-request somewhat related to #256. Even though lazySizes avoids layout thrashing with its own logic, (optionally) supporting [`fastdom.measure`](https://github.com/wilsonpage/fastdom#fastdommeasurecallback-context)/[`fastdom.mutate`](https://github.com/wilsonpage/fastdom#fastdommutatecallback-context) could still be helpful in that it would make `lazySizes` compatible with [`strictdom`](https://github.com/wilsonpage/strictdom) ([`fastdom-strict`](https://github.com/wilsonpage/fastdom#strict-mode)) checks on other elements. Currently, running `lazySizes` alongside `fastdom-strict` generates errors like the following:

```
fastdom-strict.js:918 Uncaught Error: Can only get getBoundingClientRect during 'measure' phase
    at error (fastdom-strict.js:918)
    at Measure.test (fastdom-strict.js:580)
    at HTMLDivElement.clone.value [as getBoundingClientRect] (fastdom-strict.js:552)
    at checkElements (lazysizes.js:339)
    at Object._ (lazysizes.js:554)
    at init (lazysizes.js:633)
    at lazysizes.js:673
```

These errors make `strictdom` incompatible with `lazySizes` for detecting layout thrashing coming from other page elements.

**Comment by aFarkas** [comment]
Have you actually fully read the discussion in #256? strictdom does not test for layout thrashing, it tests for a rule that is a) unnecessary to avoid layout thrashing and even worse b) increases the potential of creating layout thrashing with other libs, especially animation libraries. At the end it tests for something, that should be seen as bad practice. Why should I produce feature bloat to empower you to do bad things?

You can get the performance timeline of chrome and check for sync layout, what should be nearer to layout thrashing than using strictdom.

**Comment by wjordan** [comment]
Thanks for the response!

If I understand correctly, your position is that the incompatibility between `lazySizes` and `fastdom-strict`/`strictdom` is not something that can be supported in `lazySizes`, but rather is an issue with `fastdom-strict`/`strictdom` being broken (testing for something which should be seen as bad practice). I will close this issue and follow-up there (with a link to this discussion).

**Comment by aFarkas** [comment]
@wjordan 
I doubt that @wilsonpage will do something here. See our discussion here: https://github.com/wilsonpage/fastdom/issues/65

Despite this I changed strictdom to actually check for real layout thrashing: 
https://github.com/aFarkas/strictdom/blob/master/strictdom.js#L290-L325
(Note: We don't have the low level functions to do this right, but there are some simple techniques that seem to work promising in chrome at least).

I also added this updated strictdom version to this demo:
http://afarkas.github.io/fastdom/examples/aspect-ratio.html

Which shows as expected a lot of layout thrashing with the normal usage. But also one layout thrashing if animation is `true` **and** `fastdom.read` is used.

For @wilsonpage, this should be interesting:
- [bugfix in combination with mouseevents](https://github.com/aFarkas/strictdom/blob/master/strictdom.js#L929)
- centralizing the onMeasure/onMutate action in the strictdom class (Implementation is shown above, [usage here](https://github.com/aFarkas/strictdom/blob/master/strictdom.js#L152-L157), this way you can offer multiple different modes (I.e.: your current phase check against this automatic check for example). Also check logLevel and throwLevel.
