### ISSUE TITLE
Firefox/Edge/IE: Images above the fold never load

### ISSUE THREAD

**Issue by dbchristopher** [aFarkas/lazysizes#397]
I'm getting a behavior in Firefox and MS browsers, that prevents images above the fold from loading. I'm able to fix this by manually calling `lazysizes.loader.unveil(domnode)` on them after page load. 

Our front end tech stack includes React, Imgix, and Lazysizes. I think this caused by a race condition where imgix isn't able to generate the srcset on a react component before Lazysizes tries to process the dom element. It would be great if Lazysizes could delay the lazyloading process on a given element until the `data-srcset` is defined

**Comment by aFarkas** [comment]
This is already possible:
Either:
Only render the class lazyload to images after/as soon as you created the data-srcset attribute. 
Or
Call `lazybeforeunveilEvent.preventDefault()` on images, which do not have a data-srcset attribute.

Please close if this helps or give some more information.

**Comment by dbchristopher** [comment]
Thanks so much! Yeah I wound up doing something with `lazybeforeunveilEvent.preventDefault()` and some async logic to manually reveal the images once the proper attributes are in place.

But I'll pass along the solution to add the lazyload class after the data-srcset list is generated. I don't believe imgix currently has any post-processing event hooks to dynamically add classes, which I think would be helpful for them.

Thanks again!
