### ISSUE TITLE
Ability to disable lazyload for above the fold images

### ISSUE THREAD

**Issue by hendrikeng** [aFarkas/lazysizes#398]
Hey there, thanks for your awesome work.

I am not sure if its already possible but i tried to find an option to disable the lazyload i.e. for hero images but still be able to make use of lazysizes auto sizes/ data-srcset and other attributes. Is that even possible?

Thanks a lot.

**Comment by aFarkas** [comment]
I don't understand you. If you don't want to lazyload above the fold images you have to switch `data-src`/`data-srcset` to `src`/`srcset` attributes.

If you can't read this:
https://github.com/aFarkas/lazysizes#tip-wherehow-to-include-lazysizes

**Comment by hendrikeng** [comment]
thanks a lot :-) i kinda asked a redundant question.
