### ISSUE TITLE
object-fit polyfill not working in IE 11

### ISSUE THREAD

**Issue by hatsumatsu** [aFarkas/lazysizes#401]
Seems like the object-fit plugin demo provided readme ( https://jsfiddle.net/trixta/x2p17f31/ ) is not working in IE 11. Images are stretched, did anything changed in the markup?

**Comment by aFarkas** [comment]
Thx for your bug report. This demo issue was produced by our new module pattern for plugins (introduced by 4.0.0-rc1). In reality it is very unlikely to happen. (i.e.: it does **not** happen if you use ES6 or CommonJS modules and it also does not happen if you manually concat/include the object-fit plugin after the lazySizes core script.)

In general I expect everybody uses build systems now. I also fixed it in version 4.0.0-rc3.
