### ISSUE TITLE
Is there a way to change the srcset, sizes=auto rendered image high DPI effective size calculation?

### ISSUE THREAD

**Issue by yuchant** [aFarkas/lazysizes#403]
I love that the plugin calculates the actual rendered size of the image, determines DPI, then pulls the ideal image dimensions, but 2x+ may require too much bandwidth. Is there a way to reduce the effective pixel calculation down to say 1.5x for displays above 2?

Say an image is rendered at 1000px on a 2x resolution screen. It would then match a 2000px image in srcset. I'd like to know if there's a way to change that calculation to 1500px.

Thank you!

**Comment by aFarkas** [comment]
there is a plugin for this: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/optimumx

**Comment by yuchant** [comment]
@aFarkas of course... thank you so much!
