### ISSUE TITLE
lazybeforeunveil not firing

### ISSUE THREAD

**Issue by ShirajG** [aFarkas/lazysizes#407]
The `lazybeforeunveil` event does not seem to be firing when the lazyloaded object starts off already in the viewport.

**Comment by ShirajG** [comment]
Ah, I think I see the resolution to this, you've added a new `lazyloaded` event when objects finish loading in the v4rc. I can use this to initialize my lazy loaded js components that happen to load already within the viewport. Thanks!

**Comment by CHEWX** [comment]
Hi @ShirajG , 

Which event are you using to detect in viewport background images?

`lazyloaded` event isn't firing for me?

Thanks,
Tom

**Comment by timkirtley** [comment]
Yes I've noticed the same thing, neither `lazybeforeunveil` or `lazyloaded` events get fired if I refresh a page half way down with lazyload elements in viewport.. they get correctly loaded and the `lazyloaded` css class, its just the events that dont seem to fire.

Elements at top of page in viewport do fire the events on refresh so seems to only be if refreshing scrolled from top..  luckily quite a rare real-world scenario so not the end of the world..

**Comment by galvarez421** [comment]
@CHEWX and @timkirtley, see https://github.com/aFarkas/lazysizes/issues/625#issuecomment-479097059 in case it might be helpful to your issues.
