### ISSUE TITLE
lazysizes seems to load wrong version

### ISSUE THREAD

**Issue by al404** [aFarkas/lazysizes#412]
I added lazysizes to my page but I  can't figure out how to make it work

My first guess was that **w** was referred to viewport size, reading better i guess is referred to image size

if i got it right  if i set until image is smaller than 300w it will load _medium if image is bigger it will load the other image

data-srcset="../dbcommon/file/cover/32024742061_medium.jpg 300w, ../dbcommon/file/cover/32024742061.jpg 600w"

testing under mac and Firefox I can't really understand what is going on

testing with different W values i find out that in the case below when  sizes < 400 it will load the first image, when is bigger it will load the other image

my images has CSS display: block and width: 100%

this what i see in firefox source 

`<img data-sizes="auto" src="../images/myimages/loading.gif" data-srcset="../dbcommon/file/cover/32024742061_medium.jpg 800w, ../dbcommon/file/cover/32024742061.jpg 1500w" alt="Love In A Time Of Madness - Jos? James" class="lazyautosizes lazyloaded" sizes="393px" srcset="../dbcommon/file/cover/32024742061_medium.jpg 800w, ../dbcommon/file/cover/32024742061.jpg 1500w" width="260" height="300">`

Am I missing something?

**Comment by aFarkas** [comment]
The **w**idth descriptor describes the physical width of the image candidate, that is referenced. The `sizes` attribute is calculated by lazySizes and must be the layout width of the display image in CSS pixels. Everything else is automatically calculated by the browser. The browser chooses the best candidate.

If you are not sure. You can post an url to a test case, but without concrete information I can not say, whether something is wrong or not.
