### ISSUE TITLE
Performance issue in DOMAttrModified and DOMSubtreeModified events

### ISSUE THREAD

**Issue by D32Secret** [aFarkas/lazysizes#413]
Dear Sir,
According to [this link](https://developers.google.com/web/tools/lighthouse/audits/mutation-events), mentioned events have some performance issues, which is making it difficult for me to use them in my app. Would you please provide a workaround for this issue or refactor them to be more efficient?

Regards,
Ali.

**Comment by aFarkas** [comment]
If you are a developer you would see that mutationevents are only used, if mutationobserver is not supported. 

With other words you already get best performance. Please stop making requests for things you don't know anything about.
