### ISSUE TITLE
Load far from viewport, and animate load when on viewport

### ISSUE THREAD

**Issue by jegbagus** [aFarkas/lazysizes#418]
hi farkas, is there an option to load the image quite far from view port, and animate loaded image when its on viewport. so fetching image and animate image having different position on viewport. 

i think it will be very great experience. People will understand that we using lazy load load image, and loaded image ready before they enter viewport, but animate it when they see it.

Thank you

**Comment by yorl1n** [comment]
Hi jegbagus, maybe loadMode option is what are you looking for (about : load far from viewport)

> lazySizesConfig.loadMode (default: 2): The loadMode can be used to constrain the allowed loading mode. Possible values are 0 = don't load anything, 1 = only load visible elements, 2 = load also very near view elements (expand option) and 3 = load also not so near view elements (expand * expFactor option). This value is automatically set to 3 after onload. Change this value to 1 if you (also) optimize for the onload event or change it to 3 if your onload event is already heavily delayed.

**Comment by aFarkas** [comment]
Please read carefully the documentation here: https://github.com/aFarkas/lazysizes#data-expand-attribute.

**Comment by jegbagus** [comment]
Thank you farkas! i think i miss those option.
