### ISSUE TITLE
Elements with class="lazy" do not get lazyloaded

### ISSUE THREAD

**Issue by bm-stschneider** [aFarkas/lazysizes#421]
I encountered a problem with lazysizes where images stay in class lazy and don't switch to the spinner or the target image.

**Comment by bm-stschneider** [comment]
Also, lazySizes.init() in the console also does not load the image.

**Comment by xiel** [comment]
Hi @bm-stschneider, can u please provide a test / jsbin link showing the problem? Thx.

**Comment by bm-stschneider** [comment]
No I think I can't do that, since it happens in a dev env and I cannot bring that somewhere online in a working state.

**Comment by bm-stschneider** [comment]
Is there anything I could check for if lazysizes comes across that image at all?

**Comment by xiel** [comment]
@bm-stschneider Are other images loading on the page? Did u change the class from . lazyload to .lazy?
```
document.addEventListener('lazybeforeunveil', function(e){
    // ... check e.target
});
```
And you can check the elements property on lazySizes (`lazySizes.elements`), which contains the elements found, observed and not loaded yet.

**Comment by bm-stschneider** [comment]
That is the config
![image](https://user-images.githubusercontent.com/30625381/29771048-3469dade-8bf2-11e7-99a4-4921c4b66ec7.png)
Manually unveil is working.

**Comment by bm-stschneider** [comment]
lazySizes.elements is undefined

**Comment by bm-stschneider** [comment]
When I copy lazySizes to the console, the images load

**Comment by bm-stschneider** [comment]
It seems that the lazySizes.loader._() is not executed on init.

**Comment by aFarkas** [comment]
> It seems that the lazySizes.loader._() is not executed on init.

Probably because it was executed some time earlier. Note that lazySizes normally executes automatically. Maybe your configuration is executed to late and lazysizes runs with the default options.

Please only re-open this issue, if you are able to provide a testcase or enough information to replicate the issue.
