### ISSUE TITLE
lazySizes + Isotope grid is messed up when loading new elements.

### ISSUE THREAD

**Issue by arthursoares** [aFarkas/lazysizes#424]
This is something new that I've found. 
I had a slower internet before and the images would load progressively and the grid would fit in place alright. Now - because of the faster connection -, as soon as I scroll, the images all load at once and i get a bugged layout.

Any suggestions on fixing this?

<img width="1617" alt="screen shot 2017-09-12 at 16 21 53" src="https://user-images.githubusercontent.com/533339/30330872-84116850-97d6-11e7-8645-20301dcf9b09.png">

https://arthursoares.com/gallery/people/

**Comment by aFarkas** [comment]
Please read through these issues:
Two possible solution are documented [here](github.com/aFarkas/lazysizes#user-content-tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps) and [here](https://github.com/aFarkas/lazysizes#user-content-updating-layout-of-js-widgets).

There are also at least two related issues:
#118
#212

You should be able to solve your problem with the information given there.
