### ISSUE TITLE
object-fit/parent-fit with sizes=auto results in incorrect image size selection

### ISSUE THREAD

**Issue by christopherdarling** [aFarkas/lazysizes#425]
We are finding that object-fit & parent-fit when combined with data-sizes="auto" results in the wrong image choice being made.

I have put together a simple test case that has a 2:1 ratio container (1000x500 at it's max size) and images with a 4:3 ratio. At the containers max size the 667x500 candidate should be chosen (on a non retina screen) but it is not.

I wonder if this is down to https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/parent-fit/ls.parent-fit.js#L140-L142 (wasn't too sure why the image ratio (0.75) was being devided by the container ratio (0.5) then multiplied by the container width === (1000 x (0.75 / 0.5) = 375 as the candidate width)

https://codepen.io/christopherdarling/pen/veEvPa

If you need any more info, do let me know

**Comment by aFarkas** [comment]
Maybe the following helps:

```
4:3 = 1.33333 //!!!! not 0.75
3:4 = 0.75
```

**Comment by christopherdarling** [comment]
Good spot. However, still results in the wrong height being chosen;
(1000 x (1.33333 / 2) = 666.65  !=== 500

**Comment by christopherdarling** [comment]
Whoops, got those the wrong way around, sorry for raising a false issue
