### ISSUE TITLE
How to handle if image load fails? 

### ISSUE THREAD

**Issue by intelcoder** [aFarkas/lazysizes#427]
I am trying to use **LQIP/blurry image placeholder/Blur up image technique**. It works well with code below if image load success. However, if image load fails, it firstly shows placeholder and shrinked empty space. 
Is there good way to provide fallback image src if data-src path fails ? 
```
 <img
     data-sizes="auto"
     src="placeholder.jpg"
     data-src={src}
     className="lazyload blur-up"
/>
```

**Comment by aFarkas** [comment]
When does this happen? Do you provide a `src` with 404 network error? If this is the case you should simply fix your 404 errors.

**Comment by intelcoder** [comment]
Yes it does return 404 but I want to replace those src to placeholder image on error. and hoped that lazysize handles it.

**Comment by aFarkas** [comment]
This is not a task for a lazyloader. 

Maybe the following code examples show how you can do this your own.

```html
<img
     data-sizes="auto"
     src="placeholder.jpg"
     data-src={src}
    onerror="this.src='placeholder.jpg'"
     className="lazyload blur-up"
/>
```

or 

```js
document.addEventListener('error', function(e){
    if(e.target.nodeName == 'IMG'){e.target.src = 'placeholder.jpg';}
}, true);

**Comment by ozergul** [comment]
With CSS

```
img.lazyloaded[data-src=""] {
    display: none;
}
```

**Comment by mrkenzi** [comment]
> This is not a task for a lazyloader.
> 
> Maybe the following code examples show how you can do this your own.
> 
> ```
> <img
>      data-sizes="auto"
>      src="placeholder.jpg"
>      data-src={src}
>      onerror="this.src='placeholder.jpg'"
>      className="lazyload blur-up"
> />
> ```
> 
> or
> 
> ```js
> document.addEventListener('error', function(e){
>     if(e.target.nodeName == 'IMG'){e.target.src = 'placeholder.jpg';}
> }, true);
> ```

thanks u! It's work for me
