### ISSUE TITLE
Load all images for regression testing

### ISSUE THREAD

**Issue by sinnwell** [aFarkas/lazysizes#435]
We are using [BackstopJS](https://github.com/garris/BackstopJS) for visual regression testing. It uses [CasperJS](http://casperjs.org) for taking screenshots of the webpage. 
Is there a way to load all images at once by calling an api method?
I can execute code in the headless browser using casper's evaluate method but I'm not able to change the JS code of my webpage.

**Comment by aFarkas** [comment]
It is [documented](https://github.com/aFarkas/lazysizes#lazysizesloaderunveildomnode):

```js
//In an ES6 browser or transform with babel
Array.from(document.querySelectorAll('.lazyload')).forEach(lazySizes.unveil);
```

**Comment by sinnwell** [comment]
Thank you so much!
