### ISSUE TITLE
How is lazy sizes SEO friendly? answer please

### ISSUE THREAD

**Issue by simonjoom** [aFarkas/lazysizes#436]
I use your amazing code for my web-site and use it with tags source

It's working good but i'm thinking if it's very good for google and other bot than without lazy sizes. 
I imagine that the code i use only the transparent gif from tag src="" can be interpreted by a bot
?? 

I have the possibility to transmit a no lazy version for bot only (with test on   ... but do that is a kind of cloaking ? what you can recommend me? 

Here the source i use for my react app: 
```
<source media={`(min-width: ${obj.width_o}px)`} data-srcset={`${urlo + ' ' + obj.width_o}w`}/>);
<source media={`(min-width: ${obj.width_l}px)`} data-srcset={`${urll + ' ' + obj.width_l}w`}/>);
<source media={`(min-width: ${obj.width_c}px)`} data-srcset={`${urlc + ' ' + obj.width_c}w`}/>);
<source media={`(min-width: ${obj.width_z}px)`} data-srcset={`${urls + ' ' + item.width}w`}/>
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                    data-src={src} 
                    data-sizes="auto"
                    height={height}
                    className="rounded lazyload"
                    onLoad={this.props.onImageLoad}
                    onError={onImageError.bind(this)}
    />


```

**Comment by aFarkas** [comment]
Google is able to execute JS, but won't scroll the page. As soon as a non scrollable UA is detected (for example Opera mobile or google bot) all images are transformed instantly.

This means google will not see the transparent image, but will probably index your `data-src={src}`.

**Comment by simonjoom** [comment]
Thanks for answer , even if i don't like too much " will probably" lol

**Comment by aFarkas** [comment]
> even if i don't like too much " will probably" lol

Sorry I know exactly how google bot renders the picture setup, but I can' tell you what it will do in your case, because you haven't give me your full setup. Do you use a picture polyfill and if yes, which one?

I answered your question and now you start to question my answer...

If knowing so much is so important for you, you should test it your own, instead of asking questions. Testing the google bot should be an easy task for a normal developer.

**Comment by simonjoom** [comment]
Many thanks to reply me again.
I'm little lazy to test if google indexed my pictures i recognize it, why i prefer to ask you directly.

For the polypill I use your lazysizes respimg polyfill extension
but i added this code at the bottom of my page so maybe better in the head?

i added like that:
```
<script type="text/javascript" defer> 
if(!window.HTMLPictureElement || !('sizes' in document.createElement('img'))){
AsyncAdd.add("/dist/respimg-polyfill.js");
}
</script>
```

nota: AsyncAdd is a tool to load some javascript async

do you think it look like good?
Thanks again for answering
