### ISSUE TITLE
Image 'load' event not always firing in IE11

### ISSUE THREAD

**Issue by t-kelly** [aFarkas/lazysizes#437]
👋 Hey there -- got a bug report that in IE11, our project's hero image is only loading the low-quality placeholder image initially specified in `src` on page load. What I understand is suppose to happen is:

1. Browser loads low-quality version of image initially specified in the `src`.
2. RIAS plugin generates `data-srcset` entries.
3. Object-fit polyfill kicks in and creates a styleElement that uses a background image instead of object-fit.
4. RespImg polyfill sees `data-srcset` and changes the `src` of the original image (not the styleElement)
5. A load event is triggered when the `src` is changed, which triggers the object-fit polyfill handler to update the styleElement with the better quality background image.

Problem is... step 5 is not always happening.

I've created [a demo of the problem at this link](http://tk-narrative.myshopify.com/?preview_theme_id=143323521). Open it in BrowserStack in a Windows 7, IE11 browser. 

The demo has all of the above steps PLUS I added a `setTimeout()` that [reapplies the change to `src` ](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/respimg/ls.respimg.js#L296) 1000ms after the first attempt. As you can see from the console output, the first change of `src` SOMETIMES triggers a load event which updates the photo, and the second change to `src` always triggers a load event.

Not proposing this as a solution... You have the context to be the best judge of that. Just hoping this gives you everything you need!

**Comment by aFarkas** [comment]
Wow, great work thank your very much. I will look into this (this weekend).

**Comment by aFarkas** [comment]
Not 100% happy with the fix, but best thing I came up with. Please test.

**Comment by t-kelly** [comment]
Seems to be working for me and my demo! Thanks @aFarkas.
