### ISSUE TITLE
Doesn't works in prod, but works in dev

### ISSUE THREAD

**Issue by sylveon** [aFarkas/lazysizes#448]
On my website, I use lazysizes here https://charlesmilette.net/terminology-themes/
It doesn't works, nothing loads on every browser I tried:

![image](https://user-images.githubusercontent.com/6440374/32984977-20e9e9b4-cc7e-11e7-9ec2-fa1a051a397d.png)

Now if I git clone it (https://github.com/sylveon/website), run `python -m SimpleHTTPServer` inside `public/` and access http://localhost:8000/terminology-themes, it works as intended:

![image](https://user-images.githubusercontent.com/6440374/32984991-47439e70-cc7e-11e7-9058-1a9fa440282f.png)

What could be happening?

**Comment by aFarkas** [comment]
You are using `rocket.min.js`. This script does stupid things. (The script tampers with native built int functions like `getElementsByClassName` and destroys the way these methods work.) 

Solution: simply remove it or request a standard conform implementation of `getElementsByClassName` by cloudflare. 

Also note, the way you load JavaScript with rocket script makes your website slower not faster. Especially lazysizes should never be deferred like this.

**Comment by sylveon** [comment]
Thanks. I knew it was something from CloudFlare, and I had my doubts on Rocket since it was pretty obvious it affected script loading.

For anybody stumbling here: add `data-cfasync="false"` to the script tag that loads the library.
