### ISSUE TITLE
Any breaking changes from 3.x.x -> 4.x.x?

### ISSUE THREAD

**Issue by t-kelly** [aFarkas/lazysizes#452]
Are there any breaking changes when migrating from 3.x.x to 4.x.x? The only I could spot was in the [changelog](https://github.com/aFarkas/lazysizes/blob/gh-pages/CHANGELOG.md)

```
* removed `picture` support for old FF 38-
```

**Comment by aFarkas** [comment]
Yes, this was the only breaking change.
