### ISSUE TITLE
Is possible to notify lazysizes that the data-src was updated?

### ISSUE THREAD

**Issue by OrKoN** [aFarkas/lazysizes#46]
Hi,

First of all, thanks for a great library!

In my case I dynamically update the URL of the image being shown. I use Ember.JS so there is a binding where I bind the src property of my component to data-src attribute. The src property may change and therefore whenever it happens the data-src is updated as well. But the change is not picked up by the lazysizes - i.e., the first time shown image remains in the src attribute forever.

Is it possible to notify lazysizes about the update?

A workaround for me would be either re-render the entire component or to set the src attribute manually. In the latter case I would loose the lazysizes' features after the src update (such as plugins or lazy load).

Best regards,
Alex

**Comment by aFarkas** [comment]
@OrKoN 
Simply also always add the class ``lazyload`, if you change the ``data-src``. In case it is still there nothing changes, in cases it is added, lazySizes will pick it up.

would look like this:

```js
img.setAttribute('data-src');
img.classList.add('lazyload');
```

**Comment by OrKoN** [comment]
@aFarkas Cool! really simple, thanks for a quick response!

For others, if you're using jQuery the addClass works as well:

$('img').addClass('lazyload');
