### ISSUE TITLE
Not working for me for youtube videos

### ISSUE THREAD

**Issue by justinechacko** [aFarkas/lazysizes#462]
http://movies.justinechacko.in/
Sorry, I am a newbie here.
I applied class and add js to header. But it seems page loading fully but not on scrolling. Please check
Also Can I use this your code with following guide
https://www.labnol.org/internet/light-youtube-embeds/27941/
Thanks

**Comment by justinechacko** [comment]
I think it is working now, but Can I use in combination with https://www.labnol.org/internet/light-youtube-embeds/27941/

**Comment by aFarkas** [comment]
You can use the [plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/video-embed) or look into the JS code of it to create a new one.
