### ISSUE TITLE
Setting data-sizes source in picture element prevents sizes from working

### ISSUE THREAD

**Issue by jsunsawyer** [aFarkas/lazysizes#472]
I'm not sure if I'm supposed to add `data-` before each instances of `sizes`, but if I do that on sources, the sizes attribute is ignored and 100vw is assumed.

Removing `data-` resolves the issue.

Example I threw together.

No size at 900w or above should ever be shown.
If `data-sizes` is set, 900w, 1150w, 1400w, 1650w display respectively.
If just `sizes` is set, 900w and above never displays.

```
<picture>
  <source
    src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%271200%27 height=%27675%27 style=%27background:%23566463%27 /%3E"
    data-srcset="https://placeholdit.imgix.net/~text?txtsize=100&txt=400&w=1600&h=900 400w, https://placeholdit.imgix.net/~text?txtsize=100&txt=650&w=1600&h=900 650w, https://placeholdit.imgix.net/~text?txtsize=100&txt=900&w=1600&h=900 900w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1150&w=1600&h=900 1150w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1400&w=1600&h=900 1400w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1650&w=1600&h=900 1650w"
    data-sizes="(min-width: 1110px) 555px, (min-width: 768px) 50vw, 100vw" />
  <img
    class="lazyload"
    src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%271200%27 height=%27675%27 style=%27background:%23566463%27 /%3E"
    data-srcset="https://placeholdit.imgix.net/~text?txtsize=100&txt=400&w=1600&h=900 400w, https://placeholdit.imgix.net/~text?txtsize=100&txt=650&w=1600&h=900 650w, https://placeholdit.imgix.net/~text?txtsize=100&txt=900&w=1600&h=900 900w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1150&w=1600&h=900 1150w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1400&w=1600&h=900 1400w, https://placeholdit.imgix.net/~text?txtsize=100&txt=1650&w=1600&h=900 1650w"
    data-sizes="(min-width: 1110px) 555px, (min-width: 768px) 50vw, 100vw" />
</picture>
```

Note: In actual use my source is uses type="image/webp".

**Comment by jonathanmelville** [comment]
Any word on this? I just ran into the same issue. Removing `data-` does "solve" the problem, but would be nice to see this patched officially.

**Comment by aFarkas** [comment]
The `sizes` attribute is specified and `data-sizes` with a value like the one above simply copies it to the `sizes` attribute. I don't recommend to do this.

`data-sizes` is only for one value i.e.: `auto`(`data-sizes="auto"`), which automatically calculates the current `px` that must be used for the `sizes` attribute. 

In case you use the standard `sizes` values don't put it in `data-sizes` put it in `sizes`, but if you think it doesn't do what it should, it is probably that you did not understand the spec.

**Comment by khalwat** [comment]
I updated the Image Optimize documentation to reflect this, thanks @aFarkas 

https://github.com/nystudio107/craft-imageoptimize

**Comment by jonathanmelville** [comment]
Thanks everyone!

**Comment by jsunsawyer** [comment]
Good to know! Will remove ALL `data-` prefixes on my picture element sizes attributes.
