### ISSUE TITLE
Iframe Autplay Possible?

### ISSUE THREAD

**Issue by Uranbold** [aFarkas/lazysizes#473]
Hello,

How can i trigger the Autoplay on the iframe. Example: 

`<iframe data-src="https://www.youtube.com/embed/mDGBR9gxY7o?rel=0" class="lazyload" width="860" height="484" frameborder="0"></iframe>`

Thanks.

**Comment by andresilvasantos** [comment]
`<iframe data-src="https://www.youtube.com/embed/mDGBR9gxY7o?rel=0&autoplay=1" class="lazyload" width="860" height="484" frameborder="0"></iframe>`
