### ISSUE TITLE
Add Class To Parent IMG

### ISSUE THREAD

**Issue by jquimera** [aFarkas/lazysizes#474]
With the lazysizes the images will carry one by one. The default class in the IMG element is lazyload and when an image is loading the lazyloading class comes into action next to it, and when the loading of that image finishes, the lazyloading class is replaced by the lazyloaded class what I want now is to use add / remove a class of the div.parent based on the classes that become active in IMG.

```
<div class="image-wrap">
  <a href="#">
      <img class="lazyload" data-src="">
   </a>
</div>
```

https://codepen.io/johnquimera/pen/jZRMBP

**Comment by aFarkas** [comment]
This is actually fully documented. Here you have an example: https://codepen.io/aFarkas/pen/KQYWzw

Please always try to fully read the documentation. (I know it is hard. but rtfm)

**Comment by jquimera** [comment]
@aFarkas Solved. Thx.
