### ISSUE TITLE
Firefox and bg-set demo - the lazyloaded class loads but the image doesn't

### ISSUE THREAD

**Issue by jacobraccuia** [aFarkas/lazysizes#475]
I have been having issues with the bgset plugin in firefox.  In the fiddle's provided in the documentation, the lazyloaded class is applied to the container but the image is not showing.  

This is the [fiddle](http://jsfiddle.net/bfqqnosp/53/) in question - and here is a screenshot showing the lazyloaded class.

<img width="1047" alt="screen shot 2018-03-03 at 12 26 56 am" src="https://user-images.githubusercontent.com/4655860/36930957-77bab450-1e7a-11e8-9e82-e96d01d22e58.png">

**Comment by aFarkas** [comment]
I just tested this in FF ESR 52 and FF 59. And I cannot fully replicate your issue. WhatI can replicate is the fact, that the `lazyloaded` class is applied before the image is loaded. 

This is a problem pf the image server I used and should normally do not happen.

The response header of the images are set to no-cache, which yields to the situation, that all images are loaded twice. Normally this header should not be set. (Lorem ipsum also has the feature to put out random pictures for the same url and for this feature this header has to be used. that the fact they also set this header for specific images is a bug with loremsipum.) 

Note: In case you want to use the bgset plugin to mimic object-fit. (What the demo uses, I strongly recommend to use CSS object-fit on `img`directly and in case you have to support old browsers the [object fit polyfill](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit).)

**Comment by jacobraccuia** [comment]
Thanks for the amazingly fast response. 

I'm running into the same issue on my site, with backgrounds images where the lazyloaded class is applied before the image loads.  I was attempting to apply a black background to the images once loaded so when they flash due to the FF bug with src swapping, it's less noticeable.

  What should I do?  I can send you a link to see it yourself if you'd like.

**Comment by aFarkas** [comment]
send me a link.

**Comment by jacobraccuia** [comment]
http://jacobraccuia.com/zuko/gallery/gallery-test/  - Can you please acknowledge when you receive this link - I'd like to remove it once you have.

**Comment by aFarkas** [comment]
I got your link and there is nothing more to say as I did already:

1. Don't use bgset, but use an `img[srcset]` with the CSS property object-ft. (This alone fixes the bug).
2. Your server uses also no-cache header, remove this header (This alone fixes the bug.).

Note: Although one thing of each already fixes the bug, both things are wrong and should be changed.

**Comment by jacobraccuia** [comment]
Thank you for your help.  I will do both of these things!
