### ISSUE TITLE
lazySizes parent fit extension not calculating based on height

### ISSUE THREAD

**Issue by terryupton** [aFarkas/lazysizes#476]
I am trying to use lazysizes with data-sizes="auto" and object-fit. I was expecting the result to be using the correct image based on the fitted size of the image (height or width < greater). However, it only ever seems to calculate the width value and use the related image on this basis.

here is an example of rendered my code;

`<div class="w-1/3 sm:w-1/4 bg-white rounded-tl sm:rounded-tl-lg">
        <img src="//localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_d92bb0696019a0325bf28b90dbd7a12d.jpg" srcset="//localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_d6e2564b036a28aad5e93c42b3513f86.jpg 1600w 800h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_c094ca9c9b6d43c136355c858c57e686.jpg 1200w 600h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_2ea06c8037255e7866b816358fd3da56.jpg 900w 450h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_1d98165b86b1953906db134e956e6646.jpg 600w 300h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_cf9a7858e7bc648abc3c457e1a211bb9.jpg 400w 200h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_2e94d6007ff6a6755ecfbcc9efdb3eea.jpg 200w 100h" data-srcset="//localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_d6e2564b036a28aad5e93c42b3513f86.jpg 1600w 800h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_c094ca9c9b6d43c136355c858c57e686.jpg 1200w 600h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_2ea06c8037255e7866b816358fd3da56.jpg 900w 450h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_1d98165b86b1953906db134e956e6646.jpg 600w 300h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_cf9a7858e7bc648abc3c457e1a211bb9.jpg 400w 200h, //localhost:8080/imager/uploads/images/general/2868/Property-Generic-Waterfront-Development-iStock-184618570_4777a34480614b5a4735c46918b34040_2e94d6007ff6a6755ecfbcc9efdb3eea.jpg 200w 100h" data-sizes="auto" data-parent-fit="cover" class="fit-cover rounded-tl sm:rounded-tl-lg lazyautosizes lazyloaded" style="object-position: 50% 50%;" alt="Photo of Luxury apartments at Waterfront Development" sizes="109px">
    </div>`

The image used is 200w x 100h but the image is being stretch to appear at 109 x 118 pixels - instead I believe that the 400w 200h should be used.

What am I doing wrong?
I have tried to use this. https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit I even swapped my code for the example of this page 
`<img data-srcset="http://lorempixel.com/800/400/people/9/ 800w 400h,
	http://lorempixel.com/600/300/people/9/ 600w,
	http://lorempixel.com/400/200/people/9/ 400w"
	 data-sizes="auto"
	 class="lazyload"
	 style="width: 400px; height: 400px; object-fit: cover;" />`

But I was getting the same incorrect results and each time the 400w 200h image was being used and stretched to show at 400px by 400px. Instead I believe the 800w 400h image should have been used.

**Comment by aFarkas** [comment]
Please use jsbin, jsfiddle, codepen or whatever to show the bug. The plugin is just working fine. I can not help, if you do not demonstrate the error.

Also note: The plugin only calculates the right `sizes` attribute, the browser chooses than the right image - based on various things.

**Comment by terryupton** [comment]
This was actually an issue with the order of my jS loading. So closing this as a result.
