### ISSUE TITLE
Help troubleshooting, script is not affecting iFrames on our site

### ISSUE THREAD

**Issue by darwinDMG** [aFarkas/lazysizes#477]
Hi, not sure if this is best place to ask for help but I'm trying to figure out why lazysizes is not working for us at https://razzball.com. Trying to get the carousel slider at the top to lazy load but it appears that all iframes in the carousel are loading at page load. 

We have:

1. Installed the script in the js folder
2. Loaded the script in functions.php 
3. Put "<script src="lazysizes.min.js" async=""></script>" in the site header
4. Added the class="lazyload" tag in the iFrame code after the src.

We're using the Brid.TV iframe player and the Slide Anything slider plugin with pop up windows; appears that SA does not see the lazy loading, wanted to see if anyone had any ideas or a workaround!

Thanks!

**Comment by aFarkas** [comment]
You have to change the `src` attribute to `data-src`.

**Comment by darwinDMG** [comment]
I think that might've done it, thank you! Will check our bandwidth stats tomorrow to confirm, but slide is loading much faster now.
