### ISSUE TITLE
calculate the sizes really not work?

### ISSUE THREAD

**Issue by glucka** [aFarkas/lazysizes#478]
lazysizes examples url
results always the same src 

320px
![screenshot from 2018-03-07 07-48-16](https://user-images.githubusercontent.com/6602365/37077849-0e1e9ffa-21dd-11e8-9dd8-546bb9f5bb64.png)
500px
![screenshot from 2018-03-07 07-48-48](https://user-images.githubusercontent.com/6602365/37077850-0e3db8c2-21dd-11e8-960b-b4c66da24c67.png)

**Comment by AleksejDix** [comment]
it does exactly what it should. Responsive image can only show 1 image at a time, so you need only 1 size. Lazysizes updates the size for you automaticity.

**Comment by glucka** [comment]
hi @AleksejDix thank you for your comment! You're right. The size attribute is calculated correctly but the wrong image is loaded! Always 640w!

**Comment by aFarkas** [comment]
@glucka 
>You're right. The size attribute is calculated correctly but the wrong image is loaded!

In that case it would be a chrome issue, not a lazysizes issue. But I'm pretty sure either your testing setup, your observation or your expectations are not correct.

I can see a lot of different images are loaded. The markup you show, doesn't say anything about the `currentSrc` that is loaded (maybe here is your error). Check the DOM property not the HTML attributes.

**Comment by glucka** [comment]
currentSrc show the right image ;) thanks for the tip
