### ISSUE TITLE
getImageRatio in ls.parent-fit is broken as "RegExp.$1" is not working and is considered unofficial

### ISSUE THREAD

**Issue by robgha01** [aFarkas/lazysizes#479]
First i want to say great work! this library is amasing.

I found out that the function in ls.parent-fit.js is using "RegExp.$1" and latest chrome that im using seams to dislike it, i found this regarding the unofficial thing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n

What i dide to fix this and get "getImageRatio" working was this:
```
var srcSetMatch = regDescriptors.exec(srcset)
if(!ratio && srcSetMatch){
    if(srcSetMatch[2] == 'w'){
        ratio = srcSetMatch[1] / srcSetMatch[3];
    } else {
        ratio = srcSetMatch[3] / srcSetMatch[1];
    }
}
```

**Comment by aFarkas** [comment]
@robgha01 
Thx, I will change it.

**Comment by aFarkas** [comment]
I have fixed the code. But had no time to fully test it. Maybe you can also look into it.
