### ISSUE TITLE
Set specific parameters on different set of images (hFac, expFactor etc...)?

### ISSUE THREAD

**Issue by maximelebreton** [aFarkas/lazysizes#480]
Hello @aFarkas and thanks again for your amazing work.

I have a website with an **horizontal slider with fullscreen images**, and a **vertical menu with thumbnails**.
I use **low quality placeholders on both**.

So I have 3 images types and need **3 different behaviours**:
- for the horizontal slider, i need to lazyload the current and `100vw` under/after the viewport
- for the vertical menu, i need to lazyload all images `100vh` under the viewport
- and for the low quality placeholders, i need to load them at `300vw` and `300vh` under/after the viewport

Because there is only globals parameters (`lazySizesConfig.hFac` etc...),, how can I handle specific parameters for specific images?

Thank you!

**Comment by lizryzhko** [comment]
Hello @aFarkas! Is it possible to add the option `data-hFac` so we could override global `hFac` for each element?

**Comment by aFarkas** [comment]
@lizryzhko 
To be honest I'm extremely reluctant to do changes to the core. Especially these kinds of changes. I see a lot of devs playing with the current configuration and they are configuring lazysizes in a way that doesn't make too much sense. 

In general lazysizes calculates 3 different `expand` values based on the config and switches between those depending on how many images are loading or in which loading state your document is. It is quite impossible to not be able to generate a config that doesn't support good performance and usability for all images on your page. Everything else goes really in to micro management and premature optimization.
