### ISSUE TITLE
Images not showing until user "does something"

### ISSUE THREAD

**Issue by algspd** [aFarkas/lazysizes#482]
**The issue:**
The images are not showing up until a "user event" is triggered: on desktop if I scroll down and move the mouse out of the viewport, the src=loading.gif will remain until the mouse goes in the viewport again or a bit more of scroll is done, etc.
On android chrome, if I scoll down and let the web inertially reach the point where images are not loaded from the first load of the web, "loading.gif" is shown until I put my finger on the screen again.

I think this is not a duplicate of #434   but some of the people with the same problem may not have noticed the relation between moving the mouse and the image load event.

**The environment:**
Tested on chrome and firefox, exactly the same behaviour. The same on android chrome.
You can check at https://caphunters.es, scrolling down to the products on the bottom and not moving the mouse, you will see a "loading" spinner until you move the mouse again. Maybe you can try a couple times until you see the effect. It is easier with android: "swipe" down making the page scroll down to the products. If you are lucky the viewport will stop over the products and spinner will show until you scroll again.

**The tests:**
I tried several setups:
- My current setup
- No setup (everything by default)
- Setting ricTimeout=0 and 50
- Also tried lazysizes-without-ric.js as suggested in other issue for a similar problem

**Why?**
¿A bug?
¿Some other js library is interfering? (only jquery and jquery.autocomplete are loaded, and some analytics and facebook stuff)
...

**Comment by aFarkas** [comment]
You are using bad markup:

Please remove all `lazyload` classes from your `source` elements.
