### ISSUE TITLE
Really slow to load images, especially if they are cached!

### ISSUE THREAD

**Issue by davidenco** [aFarkas/lazysizes#484]
Using v4.0.2 and I have a page with 10 images, each one averaging about 70KB. I am accessing the website locally on a Gigabit connection and there is no load on the server or my local workstation.

However if I load the page and then scroll straight to the bottom of the page, Chrome says all images are "pending" and then after a few seconds they all load instantly stating "(from disk cache)".

If I remove your script and try again with a clear cache, the images load instantly, even if they are already cached and loading from the disk cache.

So for whatever reason your script is choosing to delay the loading of images, but why?!

**Comment by aFarkas** [comment]
The script simply adds the image candidates to the `src`/`srcset` attributes and has absolutely no influence on the networking itself. If there is standing pending for a long time, than something else must be the problem.

**Comment by federicovezzoli** [comment]
I have the same problem @davidenco, care to share some thoughts, I can share mine after a couple of days of struggling.

**Comment by davidenco** [comment]
I removed this addon and everything worked again.

**Comment by federicovezzoli** [comment]
Argh. ok...

**Comment by aFarkas** [comment]
@federicovezzoli 
you could also post a link.

**Comment by federicovezzoli** [comment]
@aFarkas yes, sorry. 

[https://dot-agency.it/spctrm/](https://dot-agency.it/spctrm/)

What I discovered so far:
- it happens only on chrome;
- In chrome only if you keep the caching active;
- tried different libraries, even a simple attribute swap in jquery, same behaviour;
- found this bug open in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=810376
