### ISSUE TITLE
Using fitVids on lazyloaded iframes

### ISSUE THREAD

**Issue by zitrusblau** [aFarkas/lazysizes#485]
We found an issue when combining lazyloaded video iframes with the fitVids script.

We posted a solution in the fitVids' issue tracker:
https://github.com/davatron5000/FitVids.js/issues/258

https://gist.github.com/zitrusblau/47e9dbc58806b32bc6f1e7d869de638e

I wonder if replacing the `data-src` attribute once the iframe is lazyloaded wouldn't make sense in general?

**Comment by aFarkas** [comment]
Using fitvids is a really bad idea.

**Comment by zitrusblau** [comment]
@aFarkas Thanks for your reply.
Any idea which approach is recommended to achieve responsive embedded videos then?

**Comment by zitrusblau** [comment]
unfortunately a css-only solution can't take the aspect ratio into account...
