### ISSUE TITLE
Lazyloading of audio element gets stuck with .lazyloading class

### ISSUE THREAD

**Issue by florianbrinkmann** [aFarkas/lazysizes#486]
Hi,

first, thanks for the great script and its plugins! :)

I have a problem with lazy loading of `audio` elements, that get stuck in the `.lazyloading` state. You can see it here: https://codepen.io/florianbrinkmann/pen/LdxMBE

I tested it with Firefox Nightly, Chrome 64.0.3282.186 and Edge 41.16299.248.0 on Windows 10.

Thanks,
Florian

**Comment by aFarkas** [comment]
This is not how "loading" a media element works. You don't have to transform `data-src` to `src` you have to transform `preload="none"` to `preload=""`. You can do this with a plugin.

**Comment by florianbrinkmann** [comment]
Oh, yes, that works – thanks for your quick help!
