### ISSUE TITLE
Chrome Stalling when requesting a lot of images at the same time

### ISSUE THREAD

**Issue by federicovezzoli** [aFarkas/lazysizes#493]
I've used your plugin from a long time now without any problem.
Not sure if this is the correct place to post this, please forgive me.
I have encountered this strange issue recently with a site that you can see here: [https://dot-agency.it/spctrm/](https://dot-agency.it/spctrm/).

[https://www.dropbox.com/s/satj2yaphw2j8oe/spectrum_problem.png?dl=0](https://www.dropbox.com/s/satj2yaphw2j8oe/spectrum_problem.png?dl=0)

In the screenshot at the link you can see that even with the cache enabled sometimes chrome takes even 2s to give me the file. The behaviour it's very randomatic, very hard to replicate if you have a fast computer almost impossible.
Do you think it's related to lazysizes? anyone encountered something like that before?

Thanks a lot!

**Comment by aFarkas** [comment]
This site does not use lazysizes but it uses some jquery lazyloading plugin.
