### ISSUE TITLE
Lazy loading the low quality version

### ISSUE THREAD

**Issue by marcospgp** [aFarkas/lazysizes#495]
* On a project I'm working on, we're using Lighthouse for performance testing, which is pretty much mobile 3G first. This means that every http request counts!

* We are using the LQIP technique: `<img>` tags have a low quality thumbnail as `src`, and the full resolution image as `data-src`, which is lazy loaded by javascript.

* Right now we stand to gain over 2.5 seconds in load time if we were to reduce the number of HTTP requests for the thumbnails on page load.

* I was wondering if there is any interest for adding a lazy-lazyload feature to lozad, where instead of having a `src` that loads instantly and a `data-src` that is lazyloaded, we have `data-lq-src` or similar and `data-src`, which are both lazyloaded at the same time when they approach the viewport.

Is this idea stupid and/or a little crazy? I think it might sound stupid to load two images at the same time, but when you think about being mobile and 3G first, the time saved in load-time HTTP requests for long pages is valuable, and loading the two images at the same time is ok because in a slow connection the thumbnail should load noticeably faster, making it is still worth having.

Thank you for your time!!

**Comment by aFarkas** [comment]
If this is your problem you should only use LQIP for your hero image(s)/first 3-4 images and leave. Also consider that `load` time doesn't mean much. It's about first impression. When does the page look ready for the user. The user doesn't know that there are images loading below the fold and he doesn't care.

Maybe check: https://www.webpagetest.org

**Comment by aFarkas** [comment]
See also this plugin I wrote in another project. Note you will need to write some CSS. It was done to create a blurup animation using a low quality image that is lazyloaded:


```js
const regEmptySpace = /\s/g;

const matchingMedia = (source)=> {
    const media = source.getAttribute('media');
    return !media || matchingMedia(media).matches;
};

const createBlurup = (insertElement, img, src)=>{
    let timer, blurImg;
    const removeImg = ()=>{
        requestAnimationFrame(()=>{
            blurImg.remove();
        });
    };
    const onload = ()=> {
        clearTimeout(timer);
        img.removeEventListener('load', onload);

        if(blurImg){
            blurImg.classList.add('is_loaded');
            setTimeout(removeImg, 999);
        }
    };

    img.addEventListener('load', onload);

    timer = setTimeout(()=>{
        if(!img.complete){
            requestAnimationFrame(()=>{
                if(!img.complete) {
                    blurImg = document.createElement('img');
                    blurImg.className = 'mediabox_blurupmedia ' +
                        (img.className.split(regEmptySpace).filter(cName => cName.startsWith('var_')).join(' '));
                    blurImg.src = src;
                    insertElement.parentNode.insertBefore(blurImg, insertElement.nextSibling);
                }
            });
        }
    }, 33);
};

document.addEventListener('lazybeforeunveil', function(e){
    const img = e.target;
    const picture = img.closest('picture');
    const sources = picture ?
        Array.form(picture.querySelectorAll('source, img')) :
        [img]
    ;
    const source = sources.find(matchingMedia);
    const src = source.getAttribute('data-lowsrc');

    if(src){
        createBlurup(picture || img, img, src);

    }
});
```

**Comment by aFarkas** [comment]
Please see also https://github.com/aFarkas/lazysizes/issues/497 in case you are interested in to see this plugin.
