### ISSUE TITLE
Blinking image on class change with LQIP

### ISSUE THREAD

**Issue by psntr** [aFarkas/lazysizes#497]
Hello,

I'm using lazysizes, with the object-fit and parent fit plugins, combined with the LQIP blur technic.
But I came across a strange blinking issue, as class swap from 'lazyloading' to 'lazyloaded', the image blink once and then the correct image is shown. Happens on Chrome, Firefox but not on Safari.

I made a reduce test case:
[jsFiddle](https://jsfiddle.net/psntrtr/caaz6yLy/2/)
[jsFiddle Fullscreen mode](https://jsfiddle.net/psntrtr/caaz6yLy/2/show)

Screencast with Network throttle (3G)
[Video with Chrome](https://streamable.com/x79jf)

Hope someone can help with out with this weird issue.
In advance thanks for your time.

**Comment by tdurand** [comment]
Same issue here, not sure how to fix it, have you found a solution ?

**Comment by psntr** [comment]
@tdurand well I bypass the flash by reducing the animation transition to 10ms instead of 333ms, the blink or flash, it's seen when the transition is higher than 100ms or something. But at least at 10ms you don't see the blink altho the animation is less smooth.

**Comment by tdurand** [comment]
Thanks yes indeed this does work but yeah, you hardly see the transition 😉

**Comment by aFarkas** [comment]
I cannot reproduce this using Chrome, but I know that FF has some issues here.

I think the only way is to clone the hole thing and add work with two images.

In another project I created a plugin like this:
 
```js
const regEmptySpace = /\s/g;

const matchingMedia = (source)=> {
    const media = source.getAttribute('media');
    return !media || matchingMedia(media).matches;
};

const createBlurup = (insertElement, img, src)=>{
    let timer, blurImg;
    const removeImg = ()=>{
        requestAnimationFrame(()=>{
            blurImg.remove();
        });
    };
    const onload = ()=> {
        clearTimeout(timer);
        img.removeEventListener('load', onload);

        if(blurImg){
            blurImg.classList.add('is_loaded');
            setTimeout(removeImg, 999);
        }
    };

    img.addEventListener('load', onload);

    timer = setTimeout(()=>{
        if(!img.complete){
            requestAnimationFrame(()=>{
                if(!img.complete) {
                    blurImg = document.createElement('img');
                    blurImg.className = 'mediabox_blurupmedia ' +
                        (img.className.split(regEmptySpace).filter(cName => cName.startsWith('var_')).join(' '));
                    blurImg.src = src;
                    insertElement.parentNode.insertBefore(blurImg, insertElement.nextSibling);
                }
            });
        }
    }, 33);
};

document.addEventListener('lazybeforeunveil', function(e){
    const img = e.target;
    const picture = img.closest('picture');
    const sources = picture ?
        Array.form(picture.querySelectorAll('source, img')) :
        [img]
    ;
    const source = sources.find(matchingMedia);
    const src = source.getAttribute('data-lowsrc');

    if(src){
        createBlurup(picture || img, img, src);

    }
});
```

**Comment by aFarkas** [comment]
Are you interested in seeing this in a more formal way as ready to use plugin?

**Comment by psntr** [comment]
@aFarkas Thank you for the answer, I would definitely be interested into seeing this solution as a ready to use plugin. Being aware of this blinking issue on few browser made me a bit reluctant to use LQIP technic.

**Comment by aFarkas** [comment]
You can test the plugin in the master branch.

**Comment by psntr** [comment]
Thank you for adding this as a plugin. I updated my jsFiddle, but the blinking is still shown. Not sure if I implemented it the right way.

[jsFiddle](https://jsfiddle.net/caaz6yLy/12/)

**Comment by aFarkas** [comment]
@psntr 
No there were some errors in it. Note that you have to use a new `data-lowsrc` attribute and use CSS to style to new generated image.

Here is a [fiddle demo](https://jsfiddle.net/hjc5gsLr/2/embedded/result/).

See also the readme: https://github.com/aFarkas/lazysizes/tree/master/plugins/blur-up

**Comment by aFarkas** [comment]
@psntr and @marcospgp
Is this working for you?

**Comment by psntr** [comment]
@aFarkas Sorry for late reply. I'm momentary away from office but will try it again on monday. Nevertheless, I could check your fiddle demo, it seems to work without the blinking issue.
