### ISSUE TITLE
Unload plugin with Object-fit plugin fallback does not work

### ISSUE THREAD

**Issue by davemoore24** [aFarkas/lazysizes#499]
I am having an issue using object-fit and the unload plugin on browsers that do not support object-fit... in which the object-fit plugin's fall back `initFix() ` kicks in. In the GIF below, I set `	var fitSupport = false; var positionSupport = false;` and tested this in chrome and it fails just like it does in IE 11. What happens is once the image loads correctly, then it is replaced by the base64 holder. I am also using attrchange plugin. 

``` 
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
         class="img-fluid object-fit-cover lazysizes-display-clone lazyloaded"
         data-src="" 
         alt="dreamstime_m_63851413_pink.jpg" 
         srcset=""
         style="background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url(&quot;data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==&quot;);">
    
    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
         class="lazyunload img-fluid landscape object-fit-cover embed-responsive-item lazyunloaded lazyload" 
         data-src="../servlet/jb.view?table=viewex&amp;col=viewex&amp;id=pe_323031363532323938&amp;ck=d2122a3dccf6a1afa94ce35af6c6abd0&amp;mbPreviewCounter=skip" 
         alt="dreamstime_m_63851413_pink.jpg" data-parent-fit="cover" data-parent-container="prev" 
         style="display: none;">
```

![issue](https://user-images.githubusercontent.com/6215968/40143516-3fb31ec6-5921-11e8-8329-8aa85fd6a971.gif)

**Comment by aFarkas** [comment]
Please use the object-fit polyfill plugin for this. 

Beside this: Enable the unload polyfill to undo any kind of plugin, would be a real mass. Sorry I can not support it. (Especially not for the overused bgset plugin)
