### ISSUE TITLE
Dynamic Update with RIAS does not work in FF 35.0.1

### ISSUE THREAD

**Issue by OrKoN** [aFarkas/lazysizes#50]
Hi,

In FF, the lib gives the src attribute a value that was not processed by the rias plugin. So the steps to reproduce the problem are like these:

1. Dynamically assign the following values to the img element: data-absurl="false", data-sizes="120px", data-widths:"[180,320,640,960]", src:"/imgs/img_{width}.png"
2. Add the lazyload class to the img element.

Expected: img.src === src:"/imgs/img_180.png"
Actual:  img.src === src:"/imgs/img_{width}.png"

I've tried to trace the issue and this lead me to the updatePolyfill function (line 74). In FF it's executed and it sets the wrong src (as far as I see). In Chrome, this line isn't executed.

Best regards,
Alex

**Comment by aFarkas** [comment]
Yes, this is actually per design. The rias plugin currently only works in conjunction with ``data-sizes="auto"`` cross browser. Because in this case I don't need to write a ``sizes`` parser. Of course parsing "100px" is quite simple, but parsing ``sizes="calc(100em - 20px)"`` isn't.

Question is it crucial for you to define the ``sizes`` with a static value or can you switch to ``data-sizes="auto"``?

**Comment by OrKoN** [comment]
If ```data-sizes="auto"```, the size is not calculated correctly in my case. And I cannot simply set display:block on images because this would break my layout. 

In my case I can think of a workaround - either to change the layout or to specify a concrete size. But it would be nice if this works in FF eventually. Does this feature depend on some API that is not implemented in FF yet?

**Comment by aFarkas** [comment]
@OrKoN 
Just thought a little bit about it. If you can add a stactic sizes attribute you can also add a static width style. In that case data-sizes="auto" wouldn't be incorrect. 

This would look like this:

```js
$('img')
	.attr({
		'data-sizes': 'auto',
		'data-absurl': 'false',
		'data-widths': '[180,320,640,960]',
		'data-src': '/imgs/img_{width}.png'
	})
	.css('width', 120)
        .addClass('lazyload')
;
```

**Comment by aFarkas** [comment]
Does this help? In any case, I will change the code, so that the behavior of chrome matches the behavior of FF.

**Comment by aFarkas** [comment]
Simple sizes attributes are now supported as well.

**Comment by OrKoN** [comment]
Thanks a lot! :sparkles: :+1: :sparkles: 

Actually, you pointed out a great solution which would work in my case too (the one with the explicit css width). Didn't think about it though.
