### ISSUE TITLE
Invalid HTML5 when using data-srcset

### ISSUE THREAD

**Issue by dissto** [aFarkas/lazysizes#500]
When I try to validate my page I get the following error:

> Error: Element source is missing required attribute srcset.

When using the responsive code from the examples.
`<source data-srcset="path.jpg" media="(min-width: 576px) and (max-width: 767px)">`

I cannot leave the srcset empty, can I? How can I fix the invalidation error?

**Comment by aFarkas** [comment]
Simply use:

```
src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
``` on your `source` elements.

**Comment by strarsis** [comment]
It can be even further simplified:
```html
srcset="data:,1w"
`````
Is even shorter and validates fine.
