### ISSUE TITLE
bgset not working

### ISSUE THREAD

**Issue by MatTeague** [aFarkas/lazysizes#506]
Hi,

I'm trying to get bgset to work with my wordpress image however it never loads, I've also noticed on your example http://jsfiddle.net/trixta/bfqqnosp/embedded/result/ the images don't load for me as well. I checked the fiddle and the one I want to use, which is resolution switching doesn't work on that either.

My code is:
```
$image_bg     = get_sub_field( 'background_image' );
$id                  = $image_bg['ID'];
$background = wp_get_attachment_image_srcset( $id, 'hero' );
<div class="jumbotron__container lazyload" data-bgset="<?php echo esc_html( $background ); ?>" data-sizes="auto">
```
This produces the right result:

```
<div class="jumbotron__container lazyloading" data-bgset="/wp-content/uploads/2018/06/kingsbridge-1920x700.jpg 1920w, /wp-content/uploads/2018/06/kingsbridge-300x109.jpg 300w, /wp-content/uploads/2018/06/kingsbridge-768x280.jpg 768w, /wp-content/uploads/2018/06/kingsbridge-1024x373.jpg 1024w, /wp-content/uploads/2018/06/kingsbridge-132x48.jpg 132w, /wp-content/uploads/2018/06/kingsbridge-600x219.jpg 600w">
```

But like the examples, the image never loads and as you can see it just says 'lazyloading'.

Any advice you can give would be great. Thanks :)

**Comment by aFarkas** [comment]
This should be fixed now. Thank you!

**Comment by MatTeague** [comment]
Hi, thanks for looking at this. I've re-downloaded the file and duplicated the above but it's still doing the same?

**Comment by aFarkas** [comment]
@MatTeague 
Can you create a jsfiddle/codepen showing your error. I can not reproduce it.

Also the demo is now working (although the images take pretty long, which is a server problem of those image providers).
