### ISSUE TITLE
sizes attribute incorrect on page load when using data-sizes="auto"

### ISSUE THREAD

**Issue by abrambailey** [aFarkas/lazysizes#508]
![image](https://user-images.githubusercontent.com/978462/41439440-6a8702a8-6ff0-11e8-9371-af15d90715de.png)

Please see: https://www.hearingtracker.com/builder-page

When I open the chrome console or change the width of the window, suddenly the clear/larger version comes up and the sizes attribute updates to the correct value. This is a weird bug, as it only happens sometimes. I noticed it randomly in chrome and firefox on Mac.

**Comment by abrambailey** [comment]
BTW, the large images on the top and bottom of the page are the lazy loaded ones.

**Comment by aFarkas** [comment]
You have to define the layout dimensions using CSS (at least `width`, but preferable also `height`) . 

The following code will work:

```css 
/* or more specific */
img {
   display: block;
   width: 100%;
}
```

**Important: How ``sizes`` is calculated**: The automatic sizes calculation uses the display width of the image. This means that the width of the image has to be calculable at least approximately before the image itself is loaded. Often the following general CSS rule might help: ``img[data-sizes="auto"] { display: block; width: 100%; }`` (see also [specifying image/iframe dimensions with the recommended aspect ratio definition](/aFarkas/lazysizes#specify-dimensions)). If it is below ``40`` (can be configured through the ``minSize`` option), lazysizes traverses up the DOM tree until it finds a parent which is over ``40`` and uses this number.

The width auto-calculated by lazysizes can be modified using the ``lazybeforesizes`` event ([lazybeforesizes documentation](/aFarkas/lazysizes#lazybeforesizes-documentation)). Alternatively, the [parent fit plugin](/aFarkas/lazysizesplugins/parent-fit) can be used for sizing images to fit a parent / container, and is the only solution when an image's height needs to be taken into account when fitting it to its container (This also includes the use of `object-fit`).

The ``data-sizes="auto"`` feature only makes sense if you use the ``data-srcset`` attribute with *width* descriptors which allows the most appropriate image can be selected (It does not make sense if you use the x descriptor or only ``src``.).

**Comment by abrambailey** [comment]
That worked ... in my case, I needed to create a div around each image with a max-width of the image's original width ... so that images didn't blow up :)
