### ISSUE TITLE
Prevent upscaling when using data-sizes="auto"

### ISSUE THREAD

**Issue by jschroeter** [aFarkas/lazysizes#51]
```
<img
    data-sizes="auto"
    src="lqip-src.jpg"
    data-srcset="lqip-src.jpg 220w,
    image2.jpg 300w,
    image3.jpg 600w,
    image4.jpg 900w" class="lazyload" />
```

E.g. when the image will be shown at a width of 320px, lazysizes will set `sizes="320px"`. Great. But now the browser/polyfill chooses the 300px image and upscales it to 320px. The result is a blurry image.
Wouldn't it be better, if lazysizes would (maybe via a config parameter) set `sizes="600px"` in this case? Of course this will result in more data to be transferred, but downscaling usually looks much better than upscaling.

**Comment by aFarkas** [comment]
Is this really a big problem? Actually I have created a plugin, which basically does exactly the opposite and often forces upscaling to reduce network traffic.

A [demo can be seen here](http://afarkas.github.io/lazysizes/optimumx/), which show, that most images are looking just fine. 

Beside this lying about the really sizes value isn't a good thing to do as this might create unpredictable results in the future. It is possible however to restrict the list of candidates to the ones matching the criteria.

But I'm not really convinced whether this is really useful. Most cases, where something like this makes a difference in perceived quality should be solved by using a svg image.

**Comment by aFarkas** [comment]
will do on monday. Don't have the time from now on until monday. But should be ready to go at this time.

**Comment by jschroeter** [comment]
I totally agree that SVG images are the best for logos etc. But I'll describe our use case: we integrated lazysizes in [rukzuk](https://rukzuk.com) where users can e.g. insert images in a fluid grid. We provide following static sizes as `srcset`: 320, 480, 768, 1024, 1280, 1440, 1600 and 1920px. Our old self-made script choosed the equal or higher resolution, so images where never upscaled. After rolling out the lazysizes integration, users complained that sometimes images are a bit blurry.

One example: http://4day.2z58hka0qgui3gdu2sti1gz8k.zuk.io/
Both images are displayed in a width of 600px. On devices with a `devicePixelRatio` of 1, the browser will now choose the 480px image and upscales it. It now looks a little blurry. For demonstration I added a little JavaScript which sets the `sizes` attribute of the second image to 768px after 5sec. Now the image will get downscaled and looks sharp; with the cost of extra data being transferred.

So my idea was to fake the `sizes` attribute to match the equal or higher resolution. Or maybe we should provide more/other static sizes? I guess this case is only really relevant to devices with low pixel ratio.

**Comment by aFarkas** [comment]
1. I got you and I work on this.
2. I think the sizes hack does work really good, but I also think it might hurt as soon as browsers start to do smarter (i.e.: more unpredictable) resource selection algorithms (As i said, with my optimumx plugin I'm constraining the possible srcset to those candidates, which should be allowed. This way the browser can do his smart things, but is constrained in his decisions (of course this needs a little bit more code, than just lying about sizes)
3. You are already providing 8 candidates.  I don't think you need more. The only thing is you could check whether the provided candidates have the 'right' sizes. 

I'm currently looking with a 2dpr device on your example. My question for you is the following. Is this complain only there with 1x-1.5x users or also with 2x users?

**Comment by aFarkas** [comment]
I'm now looking at this with 1x device. Your demo shows that the problem is only happening in Chrome not on FF, IE (where respimage is active). 

So here is my extended question: Is this complain mostly only for a) Chrome and b) on 1x devices? This question is a little bit statistic, but important!

**Comment by aFarkas** [comment]
In general 

* this isn't exactly a lazySizes issue, but a general respimage issue.
* you will get your solution tomorrow morning or this night ;-)

**Comment by aFarkas** [comment]
@jschroeter 

I have just added this feature to the optimumx plugin. Usage looks like this:

```html
<img data-minx="1.9" data-sizes="auto" class="lazyload" data-srcset="...." />
```

This code will make sure, that on a 1x device the loaded image is never below 1x and on a 2x device never below 1.9x.

Of course you can also go for your own sizes solution. Currently I don't see any problems with that, but I don't know whether I would call it future proof. Especially in case you know the allowed widths/sizes, it gets dramatically easy:

```js
document.addEventListener('lazybeforesizes', (function(){
	var sizes = [320, 480, 768, 1024, 1280, 1440, 1600, 1920];
	return function(e){
		var i;
		for(i = 0; i < sizes.length; i++){
			if(sizes[i] >= e.details.width){
				e.details.width = sizes[i];
				break;
			}
		}
	};
})());
```

**Comment by aFarkas** [comment]
Ups, totally forgot: It would be still important for me, to know the answer of my question: **Is this complain mostly only for a) Chrome and b) on 1x devices?**

**Comment by aFarkas** [comment]
The code above is actually only perfect for 1x devices. To get the right size for other you should do something like this:

```js
document.addEventListener('lazybeforesizes', (function(){
    var sizes = [320, 480, 768, 1024, 1280, 1440, 1600, 1920];
    return function(e){
        var i;
        var dpr = window.devicePixelRatio || 1;
        var perfectSize = e.details.width * dpr;
        for(i = 0; i < sizes.length; i++){
            if(sizes[i] >= perfectSize){
                e.details.width = parseInt(sizes[i] / dpr, 10);
                break;
            }
        }
    };
})());
```

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/tree/master/plugins/optimumx#lying-sizes

**Comment by jschroeter** [comment]
Sorry for the delay and thanks for digging into this! I can confirm that its only Chrome/Webkit and 1x devices.
I will try your solution tomorrow. I also think we should be a little careful so we don't break coming bandwidth specific algorithms etc.

**Comment by aFarkas** [comment]
Yeah, you can also try to write something like this:

```js
document.addEventListener('lazybeforesizes', function(e){
    var dpr = (window.devicePixelRatio || 1);
    if(dpr < 1.1){
        e.details.width = e.details.width * 1.05;
    }
});
```

In case this is really significant, we should consider to open a Chrome bug. I already asked the developer whether there are already some complaints. But you are the first one.

**Comment by jschroeter** [comment]
I got the best results with your code in https://github.com/aFarkas/lazysizes/issues/51#issuecomment-72522376. The 5% idea is good and works in the 600px case, but other sizes can still be blurry.

Anyway, I think this isn't something we should fix. I believe the algorithm in Chrome should do something like "use nearest candidate on low bandwith, prevent upscaling by using better candidate on good bandwith". I will open a Chrome bug.

**Comment by jschroeter** [comment]
Chrome bug: https://code.google.com/p/chromium/issues/detail?id=456084

**Comment by aFarkas** [comment]
@wcoppens and @jschroeter
I just wanted to let you know, that chrome changed its behavior on low resolution devices to do no upscaling in general. I hope they will comeup with something smarter in the future (but I think they want to do some image-quality/image-size/image-resolution research first).

Well, I also updated the respimage algroithm for respimage 1.4.0-RC1 (picturefill will also do something similar).

I plan to do some small changes to lazySizes and respimage and release both end of this week/next week. If you want you can do some beta testing with both.

In respimage, I'm basically using this algo: http://jsfiddle.net/trixta/9dponzs2/

**Comment by jschroeter** [comment]
Great news, thanks for the hint and for digging into this!

**Comment by wcoppens** [comment]
@aFarkas Thats amazing, thanks for informing!
