### ISSUE TITLE
After using Lazysizes got 'Content not prioritized' error in tests

### ISSUE THREAD

**Issue by canyoudev** [aFarkas/lazysizes#513]
Hello. I am trying to use this lazy load package and noticed issue with it in my app.

Before I start using it I passed all test, like Pagespeed or varvy.com (actually, got 100/100)

![screenshot from 2018-07-05 05-36-46](https://user-images.githubusercontent.com/38894457/42315697-18bc45ce-8016-11e8-9b5c-7d2d5edfd5f0.png)

After I enable `lazysizes` I begin to receive this error on both tests!

![screenshot from 2018-07-05 05-39-04](https://user-images.githubusercontent.com/38894457/42315747-38207034-8016-11e8-896c-ec584462da9d.png)

Package by itself is working fine (as it seems to me). But why do I receive this errors? Any ideas how to fix it?

**Comment by aFarkas** [comment]
Probably you should not lazyload your first 1-3 images because they are in view and the preload parser is faster than JS can start downloading these.

**Comment by canyoudev** [comment]
No, this is not the case. After playing around I found out that setting `src` on `img` in `picture` tag is causing the issue. Also, I experience weird behavior, my LQIP are loading and cancelling on every page load when route. 

```
<picture>
            <source :data-srcset="`
              ${$store.state.baseUrl}/static/images/cdn/320x240-${article.image.url.webp} 320w,
              ${$store.state.baseUrl}/static/images/cdn/560x420-${article.image.url.webp} 560w
            `" sizes="(min-width: 768px) 33.3vw, 100vw" type="image/webp">
            <img :src="${$store.state.baseUrl}/static/images/previews/sqip-1040x780-${article.image.sqip.url}" :data-src="`${$store.state.baseUrl}/static/560x420-${article.image.url.jpegpng}`" :data-srcset="`
              ${$store.state.baseUrl}/static/images/cdn/320x240-${article.image.url.jpegpng} 320w,
              ${$store.state.baseUrl}/static/images/cdn/560x420-${article.image.url.jpegpng} 560w
            `" sizes="(min-width: 768px) 33.3vw, 100vw" :alt="article.image.alt" class="metro-block-card-image lazyload">
          </picture>
```

If I remove LQIP image `:src="${$store.state.baseUrl}/static/images/previews/sqip-1040x780-${article.image.sqip.url}"` then I have NO ERROR. How to fix this? Am I using markup wrong or this is the issue?

**Comment by canyoudev** [comment]
My point is I have no error in test with `lazyload` until I begin to use LQIP in my `picture` tag. I feel that this is wrong behavior @aFarkas 

Also reloading and cancelling of LQIP seems wrong.

**Comment by canyoudev** [comment]
Please reopen this issue, sir.
Or please assist me with right markup if you think it's my fault @aFarkas 
Or mention in Docs that you can't use LQIP in `picture` tag.

**Comment by canyoudev** [comment]
Setting `src` on `picture` `img` tag also cause this https://github.com/aFarkas/lazysizes/issues/514
If I remove `src` no issues remains- neither with above the fold content, no with duplicate downloading of LQIP.

**Comment by aFarkas** [comment]
@canyoudev 
You are using pagespeed. This is not a human it is a machine that does some tests. Some of these tests are not always revealing a problem with your page but with the algorithm used.

I just see that your lqip is pretty big (1040x780). You should use lower quality image.

You probably can trick pagespeed by using the [blur up plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/blur-up), which is is highly recommended.

**Comment by canyoudev** [comment]
I will try plugin, but the thing is in this case I am not blurring LQIP (it's polygonal SVG instead of blurred image)

So the file size is equal for any resolution, it's SVG. 1040x780 or 100x100 make no difference. 

I understand that this is a machine test, but still it's kinda cool to show green results to the client, you know...

**Comment by aFarkas** [comment]
> So the file size is equal for any resolution, it's SVG. 1040x780 or 100x100 make no difference.

Ok, but the image in `srcset` are webp or jpeg and much bigger? Maybe just do an overfade? To be honest I don't know how this looks. If this placeholder doesn't look good. You should remove it entirely. It's something to satisfy the user until the real image is loaded.
