### ISSUE TITLE
The script is not working with Jekyll

### ISSUE THREAD

**Issue by ishanSrt** [aFarkas/lazysizes#515]
I included the script in my `default.html` as said,
I then add an image as 

```
<img
src="../assets/blurry_files/a.placeholder.jpg" 
data-src="../assets/images/a.png"
class="lazyload" />
```
but it always seems to be showing the image from the `src` path.
I went ahead and tried out your demo
```
<picture>
	<!--[if IE 9]><video style="display: none"><![endif]-->
	<source
		data-srcset="500.jpg"
		media="(max-width: 500px)" />
	<source
			data-srcset="1024.jpg"
			media="(max-width: 1024px)" />
	<source
			data-srcset="1200.jpg" />
<!--[if IE 9]></video><![endif]-->
<img
		src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
		data-src="1024.jpg"
		class="lazyload"
		alt="image with artdirection" />
</picture>
```
but the same thing happening here too. No image appeared up until I changed the value of `src` to the value in `data-src`.

Only the file from `src` shows up

**Comment by ishanSrt** [comment]
similar thing happenning when trying out the plugin for blurred up images, it works with normal html but breaks down with Jekyll

**Comment by aFarkas** [comment]
Jekyll has no influence on how lazysizes works. There is no connection.

**Comment by ishanSrt** [comment]
let me tell you doing it with a normal html file works. Doing the same process in jekyll just doesn't work, Any possible reason?

**Comment by aFarkas** [comment]
I assume lazysizes is not correctly included. Type `lazySizes` in the console.

**Comment by ishanSrt** [comment]
I am no web-dev expert although I know the basics, so I just included the script and then added the classes to the `img`, build using `jekyll serve`, also pushed to GitHub pages (not working in both). I don't know which console you are referring to 😳.

**Comment by aFarkas** [comment]
https://developers.google.com/web/tools/chrome-devtools/console/
