### ISSUE TITLE
Support for both GoogleBot and BingBot

### ISSUE THREAD

**Issue by verlok** [aFarkas/lazysizes#523]
Hey there,
I see that to check if the user agent is a bot, you test for the string `glebot`, like the following:

```js
var supportScroll = ('onscroll' in window) && !(/glebot/.test(navigator.userAgent));
```

**This excludes Bingbot.**

Why don't you change the check with the following?

```js
var supportScroll = ('onscroll' in window) && !(/bot\.htm/.test(navigator.userAgent));
```

**This would work both for Google and Bing bot.**

Reference:
* Bingbot https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0
* GoogleBot https://support.google.com/webmasters/answer/1061943?hl=en

**Comment by verlok** [comment]
Clever move. 

What I've found searching around the internet in a couple of StackOverflow posts is the following RegExp, which I actually used in the recent release of my LazyLoad.

```js
export const isBot =
	(runningOnBrowser && !("onscroll" in window)) ||
	/glebot|bingbot|crawler|spider|robot|crawling/i.test(navigator.userAgent);
```

**Comment by verlok** [comment]
I guess the above can be shortened like the following

```js
/(gle|ing|ro)bot|(crawl|spid)er/i.test(navigator.userAgent);
```

**Comment by aFarkas** [comment]
> Too much? It's executed only once so I can't find any particular issue if the RegExp is a little bit longer.
What do you think?

There is absolutely no perf issue.
