### ISSUE TITLE
Errors when moving from 4.0.4 to 4.1.1

### ISSUE THREAD

**Issue by seantimm** [aFarkas/lazysizes#527]
I haven't had a chance to investigate deeper, but I'm seeing a few errors thrown when I attempted to move to version 4.1.1:

TypeError: blurImg is null
onloadBlurUp . ls.blur-up.js:58

TypeError: ele is null
hasClass . lazysizes.js:44
addClass . lazysizes.js:48
onloadBlurUp . ls.blur-up.js:55
run . lazysizes.js:127

**Comment by aFarkas** [comment]
@seantimm 
Do you have site or a testcase, where I can reproduce it? (The normal demo page works: https://jsfiddle.net/trixta/v0oq0412/embedded/result/ as expected.)

You can also mail me.

**Comment by aFarkas** [comment]
@seantimm 
Do you have more information? Maybe I can already reproduce your issue, if I have your HTML?

**Comment by seantimm** [comment]
Should be able to message you a site shortly...

**Comment by aFarkas** [comment]
@seantimm 
any news?

**Comment by seantimm** [comment]
I shot an email your way!  😄

**Comment by aFarkas** [comment]
@seantimm 
I got your message, but the link is redirected to a 404 page. Could you please check?

**Comment by seantimm** [comment]
@aFarkas Access is unfortunately scoped to primarily US-based requests.  If you're accessing from outside the US, you'll need access to a US-based proxy of some sort.  The link is walled off due to GDPR, and it might be difficult for me to open access.

**Comment by aFarkas** [comment]
give me just the html
