### ISSUE TITLE
Lazy loading youtube iframes breaks enableJsApi

### ISSUE THREAD

**Issue by rbrlortie** [aFarkas/lazysizes#529]
Hi, 

Since the iframes does `elem.contentWindow.location.replace(src);` instead of `elem.src = src;`, the iframes never gets a src with `&enablejsapi` as a parameter.

```
		var changeIframeSrc = function(elem, src){
			try {
				elem.contentWindow.location.replace(src);
			} catch(e){
				elem.src = src;
			}
		};
```

This means the API is never allowed for the iframe.

This prevents you from doing things like:

```
var player;
window.onYouTubePlayerAPIReady = function () {
  player = new YT.Player('homepage-demo-video', {
    events: {
      'onReady': onPlayerReady
    }
  });
}
function onPlayerReady(event) {
  player.playVideo();
}
```

I hacked it by doing:

```
        const checkForClass = setInterval(() => {
            if ($('#homepage-demo-video').hasClass('lazyloaded')) {
                $('#homepage-demo-video').attr('src', $('#homepage-demo-video').attr('data-src'));
                clearInterval(checkForClass);
                __.$window[0].demoLazyLoaded();
            }
        }, 25);
```

However, a class or attribute like "lazyload-force-src" that removes the try-catch would be a lot cleaner.

**Comment by aFarkas** [comment]
This looks indeed ugly and inefficient. Please read the documentation. There is an API to extend lazysizes.

You can also start your own plugin by modifying an existing one. Maybe the following plugin might be a good start:
https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/video-embed/ls.video-embed.js

**Comment by rbrlortie** [comment]
Hi @aFarkas 

The issue is clearly at the core of the plugin. Why you would do `elem.contentWindow.location.replace(src);` and only `elem.src = src;` in the catch of a trycatch without any way to bypass it is beyond me unless it's some obscure browser compatibility issue. Even then, browser hacks that breaks features should be behind a flag at the very least. 

It's not as if this was in some obscure method of the code, the `changeIframeSrc` method does this and nothing else. A plugin would be overkill and add a new layer of abstraction for no reason. All that would be needed is to add a new class.

Pseudocode:

```
var lazySizesDefaults = {
    // ...
    forceIframeSrc: 'lazyforcesrc',
    // ...
}

// ....

var changeIframeSrc = function(elem, src){
    if(hasClass(elem, lazySizesConfig.forceIframeSrc)) {
        elem.src = src;
    } else {
        try {
            elem.contentWindow.location.replace(src);
        } catch(e){
            elem.src = src;
        }
    }
};

**Comment by rbrlortie** [comment]
Reading more on the issue, I realize this is a rabbit hole caused by Firefox's behavior. On Firefox, changing the src of the iframe add a state to the browsers history stack and breaks the back button. 

One would need to create a new iframe outside the DOM with the correct src and then replace the existing one. This prevents the iframe hijacking the back button. 

This kind of code would need to replace my pseudocode above. Adding such a feature in lazysizes would be pretty great. 

I now understand your suggestion for a plugin.

Thanks,
R

**Comment by aFarkas** [comment]
@rbrlortie 
Yes and it should be easy for you:

```html
<div class="layzload" data-yt="youtube-url"></div>
```

```js
document.addEventListener('lazybeforeunveil', ({target}) => {
    const yt = target.dataset.yt;
    if(!yt){return}
    target.innerHTML = `<iframe src="${yt}"></iframe>`;
});
```

And don't think of a plugin as something big additional. As soon as you want something else do it. I have written always unpublished plugins for any of my projects.
