### ISSUE TITLE
bgset not fully working on IE11?

### ISSUE THREAD

**Issue by JamesSingleton** [aFarkas/lazysizes#531]
I am trying to use bgset, however, it looks like it does not load the image / add the style="background-image:" inside IE11. On Chrome and FireFox everything loads perfectly fine. Even on IE11 the class lazyload changes to lazyloading and then finally lazyloaded but no image is loaded. Even the bgset demo has the same issue http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

Example Code:

```
<div class="lazyload" data-bgset="sampleImage.jpg">
    <img class="lazyload" data-src="sampleImage.jpg" />
</div>
```

Example CSS:

```
div {
width: 100%;
height: 100%;
background-size: cover;
background-position: center center;
background-repeat: no-repeat;
cursor: pointer;
}

img {
display: none
}
```

**Comment by aFarkas** [comment]
I just updated the demo to use a different server and it works. As told in the other issue you should use `object-fit` plugin instead. It gives you basically the `background-size` feature directly for the `img` element.
