### ISSUE TITLE
Using bgset with an svg image element

### ISSUE THREAD

**Issue by superbia** [aFarkas/lazysizes#532]
First off, thanks for making and releasing Lazysizes!

I'm using the bgset plugin on an image element within an inline svg. To get this to work I've had to hack the bgset plugin from around line 127 to the following:

    if (bg) {
        if(elem.nodeName === 'image'){
             elem.setAttributeNS('http://www.w3.org/1999/xlink', 'href', (regBgUrlEscape.test(bg) ? JSON.stringify(bg) : bg ) );
        } else {
            elem.style.backgroundImage = 'url(' + (regBgUrlEscape.test(bg) ? JSON.stringify(bg) : bg ) + ')';
        }
    }

Is it possible to get this to work without having to hack the bgset plugin?

Cheers,

Dylan

**Comment by aFarkas** [comment]
I update the code so you can extend this part using the event `bgsetproxy`.

```js
document.addEventListener('bgsetproxy', (e) => {
  e.preventDefault();
  elem.setAttribute(e.detail.useSrc);
});
```
