### ISSUE TITLE
Which one data-srcset, src, or something else - Some images stuck loading

### ISSUE THREAD

**Issue by thatguy76** [aFarkas/lazysizes#533]
I started with img src="$imagePath" class="lazyload" and noticed some images don't load on mobile devices. So, I switched to img data-srcset="$imagePath" class="lazyload" and now having the same issue but on desktops (didn't check mobile). The images just hang there and never load. 

Sometimes when refreshing the page, the image will eventually show, but it appears as though on the images that are not loading, the class is empty when it should be "lazyloaded"

![desktop screenshot](https://user-images.githubusercontent.com/6010354/45340956-81d30680-b54d-11e8-90d0-69b04e6f849b.png)

What would be the correct way to use lazyloaded so that images always load without hanging there and showing an empty image icon?

Thanks for your help!

**Comment by aFarkas** [comment]
1. I can not replicate the empty class issue. I would need a testcase to investigate this.
2. This looks like a server problem to me.
3. You should use `data-src="" class="lazyload"`

**Comment by thatguy76** [comment]
#3 solved my issue, thanks!
