### ISSUE TITLE
Disable css class during image load possible ?

### ISSUE THREAD

**Issue by korowo** [aFarkas/lazysizes#540]
Hi, I want to disable a certain image overlay during the load of the image since i want the loading-spinner gif to have no background.

**Comment by aFarkas** [comment]
Of course this is possible. We set a `lazyloading` and a `lazyloaded` class as also dispatch certain events so you even code things. Simply RTFM.

**Comment by korowo** [comment]
hey sorry, im really new to javascript and so on. I already tried using a  simple code that changes the display property after everything is loaded `($(window).load(function() {
  $(".overlay").css("display:block");
});)`.
[Image preview of my problem](https://i.imgur.com/7yupYse.png)
