### ISSUE TITLE
Srcset border-image with bgset plugin?

### ISSUE THREAD

**Issue by maximelebreton** [aFarkas/lazysizes#547]
Hello @aFarkas,

I would like to use `srcset` on `border-image` (https://developer.mozilla.org/fr/docs/Web/CSS/border-image-source), and I think the behaviour is the same as `background-image`, so the `bgset` plugin fit this usage perfectly with a tiny modification : only change the inline `background-image` to `border-image-source`

![image](https://user-images.githubusercontent.com/1072425/47284326-77893b00-d5d6-11e8-8ae5-d543531b3c24.png)

![image](https://user-images.githubusercontent.com/1072425/47284295-5cb6c680-d5d6-11e8-825c-08777e6b4744.png)

Can you provide the border-image support, or how can I make this change in a clean way?

Thank you!

**Comment by aFarkas** [comment]
You can hook into the `bgsetproxy` event.

```js
document.addEventListener('bgsetproxy', (e) => {
  e.preventDefault(); //makes sure that the backgroundImage is not used
  e.target.style.borderImageSource = e.detail.useSrc;
});
```

**Comment by aFarkas** [comment]
Please close if this works for you.

**Comment by maximelebreton** [comment]
Thank you @aFarkas!
