### ISSUE TITLE
Using unescaped '#' characters in a data URI

### ISSUE THREAD

**Issue by horoscop** [aFarkas/lazysizes#548]
Hi,

I got the following warning:
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

![image](https://user-images.githubusercontent.com/30988645/47459377-a4ab3880-d7e4-11e8-9fbd-1777698bc94f.png)

Could you please check?

Thanks!

**Comment by aFarkas** [comment]
This is an error in your HTML. lazysizes only uses your HTML `data-*` values to assign this to `src` / `srcset` attributes.

Please check and fix your HTML.
