### ISSUE TITLE
Backfill the CHANGELOG

### ISSUE THREAD

**Issue by brendo** [aFarkas/lazysizes#552]
It'd be amazing if the CHANGELOG could be backfilled with all the changes between 4.0.4 to 4.1.4.

Picking through the diff isn't a fun experience, https://github.com/aFarkas/lazysizes/compare/4.0.4...4.1.4

**Comment by grekko** [comment]
JFYI: I took 20 minutes to backfill the Changelog to the latest release, see https://github.com/aFarkas/lazysizes/pull/626

**Comment by aFarkas** [comment]
@grekko

thank you very much!!!
