### ISSUE TITLE
lazySizes and columns (CSS) ... !?

### ISSUE THREAD

**Issue by joopvos** [aFarkas/lazysizes#553]
I guess it's impossible to instruct lazySizes to lazyload images which are loaded by CSS order (columns) ... isn't it? See what happens on [this page](http://www.mariaberkhout.nl/test/) ... and scroll ... :o

**Comment by aFarkas** [comment]
lazySizes loads the image in the visual order (CSS) not in structural order. This means it is possible. The problem is that your layout changes after images are loaded. To fix this you should follow the [readme](/aFarkas/lazysizes#user-content-specify-dimensions).
