### ISSUE TITLE
data-ratio and data-aspect-ratio

### ISSUE THREAD

**Issue by 719media** [aFarkas/lazysizes#557]
Is there any reason there are two differently named data attributes that seem to me that they could be consolidated into one?

`data-ratio` described on
http://afarkas.github.io/lazysizes/rias/
to calculate the height of an image

`data-aspectratio` described on
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit
to calculate height of image

Can parent-fit plugin just use `data-ratio` so I don't have to define the ratio twice? Minor complaint, mostly just making sure I'm not missing the reason why either of these values (when using both plugins) would ever be different?

I'm game for you to just close this issue, I just thought it was interesting/confusing when using both of these plugins together and wanted to bring it to your attention. I suppose the only change would be to implement data-ratio into the parent-fit plugin, and optionally deprecate data-aspectratio.

Thanks for your time.

**Comment by 719media** [comment]
I did just realize that the calculations are reversed of eachother, just to make it a little more confusing :)

`data-ratio` = `height / width`
`data-aspectratio` = `width / height`

**Comment by aFarkas** [comment]
I will fix sorry.

**Comment by aFarkas** [comment]
@719media 

Could you please test the newest version and confirm that it fixes your issue. I will then do a new release and update the readme. The property is now `aspect-ratio`. For me it looks like that I fixed ratio calculation already in the past and introduced an option called `traditionalRatio` for the old `height / width` calculation. But by default it should be `width / height` (For the new `aspect-ratio its always calculated this way.)

**Comment by 719media** [comment]
Looks good, except I believe it may be now `aspect-ratio` in rias, and `aspectratio` without hyphen in object-fit, it may be best if they were the same property name?
