### ISSUE TITLE
Safari repeatedly requests same 100% width image with data-sizes="auto"

### ISSUE THREAD

**Issue by tomgenoni** [aFarkas/lazysizes#558]
I'm using `data-sizes="auto"` with the following HTML. Note that this only appears to happens with images that fluid width.

```
    <img
        src="/asset/images/hero-120.jpg"
        class="hero-img lazyload"
        data-src="/asset/images/hero-481.jpg"
        data-srcset="
            /asset/images/hero-481.jpg 481w,
            /asset/images/hero-700.jpg 700w,
            /asset/images/hero-962.jpg 962w,
            /asset/images/hero-1025.jpg 1025w,
            /asset/images/hero-1200.jpg 1200w,
            /asset/images/hero-1400.jpg 1400w,
            /asset/images/hero-2050.jpg 2050w,
            /asset/images/hero-2400.jpg 2400w
        "
        data-sizes="auto"
    >
```

and in Safari, as I slowly resize the browser, the same image keeps getting requested:

![screen shot 2018-11-12 at 12 17 24 pm](https://user-images.githubusercontent.com/1171072/48373170-dd1c9480-e675-11e8-964d-ab648b56160d.png)

See https://tp-responsive-img.netlify.com/examples/hero-img.html for example

**Comment by tomgenoni** [comment]
Could you explain more why that matters? Neither Chrome nor Firefox re-request the images this way in this demo. 

And I can reproduce this same behavior using your examples in a fiddle. 

https://jsfiddle.net/o51gxc7a/1/

**Comment by tomgenoni** [comment]
Ok, thank you for looking into that. I was able to reproduce this in Chrome as well but only in the context of an app I'm working with and not with isolated examples, so there is likely some other interaction responsible there.

And thank you for your work on this project.

**Comment by ferhatb** [comment]
Verified that on Safari cache header causes the flicker and it downloads the image on every frame. On a static web page this is fine but as soon as you mutate dom <img> tag with same src still causes download.

We'll be landing an update shortly that reuses the same dom node across frames which fixes the flicker.

Thanks for patience on this.
