### ISSUE TITLE
Does data-sizes="auto" also take into account the pixel density?

### ISSUE THREAD

**Issue by stratboy** [aFarkas/lazysizes#564]
Hi, from your docs it's not clear (at least to me) if the auto-sizes feature (data-sizes="auto") will also consider pixel density along with image size.

Normally, if a sizes property is used (manually added by the developer), the browser will also consider pixel density before choosing the appropriate image. Does it happen also with your auto-sizes?

**Comment by aFarkas** [comment]
Yes of course. `data-sizes="auto"` simply calculates the current visual layout width in layout pixels and puts it in the `sizes` attribute. The browser then does its normal job and includes the devicePixelRatio of the device.
