### ISSUE TITLE
Wrong width calculation with high dpr screens

### ISSUE THREAD

**Issue by ghisleouf** [aFarkas/lazysizes#568]
Hi guys,

Here is a little demo to share with you a strange behavior on a specific use case : https://codepen.io/ghislefou/pen/BGPEmL
I want to lazy load pictures, using cloudinary.com service to serve best picture according to visitor computer.
I'm using rIaS plugin to determine picture width and screen dpr.
width property is well calculated on 1.0 dpr screen but I had to divide width by dpr to serve good picture width.

For example : 

Let's say that my div is 540px wide : 

on 1x screen, width calculation gives me 540
on 2x screen, width calculation gives me 1080

Is it normal ?

Thanks for your feedback.

PS : this is the reason why I'm overriding width property in my demo.

**Comment by ghisleouf** [comment]
Hello!

What you explain is that I don't have care about the dpr calculation made my cloudinary as explained here : https://cloudinary.com/blog/how_to_automatically_adapt_website_images_to_retina_and_hidpi_devices

Lazysizes is sending the width calculated according screen dpr automatically right?

Thanks for your answer!

**Comment by aFarkas** [comment]
> What you explain is that I don't have care about the dpr calculation made my cloudinary as explained here

Yes you don't need to do this.

> Lazysizes is sending the width calculated according screen dpr automatically right?

Not really this is a `srcset`/`sizes` feature of the browser itself.
