### ISSUE TITLE
lazysizes seems not to load new js-added elements

### ISSUE THREAD

**Issue by stratboy** [aFarkas/lazysizes#569]
Hi, I've built a small slideshow system. To make it loop, I need to clone the first and last elements and then add them to the DOM list of items. If I use lazysizes for the images, the ones inside the cloned elements don't get loaded. How can I solve? Is there any lazysizes  'reload' method? From the docs is not too clear to me sorry.

**Comment by aFarkas** [comment]
lazysizes detects any elements with class `lazyload` (or the one you have configured). If you cloned them they might have a different class then?

Otherwise I can not help as long as you don't provide a test case.

**Comment by stratboy** [comment]
Sadly I cannot provide a test case right now since I'm working on a website that's still in staging mode.
Anyway, the elements are deep copied via jquery's clone() method, and all have the same markup and lazyload class.

**Comment by stratboy** [comment]
I've found the issue. Lazysizes is working properly. The reason I don't get images loaded by lazysizes is that they're too 'far'. It's an horizontal slideshow, and hided elements are more than 200px far from view. Is there a way to make lazysizes load them even if they're too far? But, note: I would like to only expand the active area horizontally and/or only for that slideshow, not the whole page.

I'm attaching a shot of the slideshow. As you can see, slides are wide and images are small, so they are far from each other on the adiacent slides.
![schermata 2018-12-04 alle 16 53 42](https://user-images.githubusercontent.com/437598/49454721-06988e00-f7e6-11e8-9a08-9365063db2a7.png)

**Comment by aFarkas** [comment]
Search for `hFac` in the readme.

**Comment by stratboy** [comment]
Thank you, you're a super-hero.
