### ISSUE TITLE
Prevent init not working

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#57]
And I guess it's because this:
``if(lazySizesDefaults.init){
``setTimeout(init);
``}

Should be:
``if(lazySizesConfig.init){
``setTimeout(init);
``} 

Correct?

**Comment by aFarkas** [comment]
Let's pretend this is an upcomming feature of version 1.0.0

**Comment by aFarkas** [comment]
Thx.

**Comment by JonWallsten** [comment]
Let's do! ;)
