### ISSUE TITLE
Does lazysizes also load display:none elements?

### ISSUE THREAD

**Issue by stratboy** [aFarkas/lazysizes#570]
Hi, I have some elements that, in small screens don't have images, while in large screens they will.
So I would like lazysizes not to load images until the large breakpoint is reached.

Probably I will use display: none on elements inner images > will lazysizes respect the fact that images are hidden? Or will it load them anyway?

And/or, what's the best practice for achieving this result (loading images only on large breakpoints?)

Also, maybe i will need to do it with backgrounds instead of img tags, and thus I'll use bgset (for tech reasons, I cannot use object-fit for the moment).

**Comment by aFarkas** [comment]
> will lazysizes respect the fact that images are hidden?

lazysizes will not load elements that are hidden with `display: none` so you can use this technique.

> And/or, what's the best practice for achieving this result (loading images only on large breakpoints?)

The `picture` element

> for tech reasons, I cannot use object-fit for the moment
Why? We have a polyfill for this!!!

**Comment by TakayamaYoshimichi** [comment]
> And/or, what's the best practice for achieving this result (loading images only on large breakpoints?)
> The picture element

**Comment by TakayamaYoshimichi** [comment]
> And/or, what's the best practice for achieving this result (loading images only on large breakpoints?)
> 
> The picture element

Why do you think it's a best practice to use The `picture` element ?

In Firefox, the `width` and `height` given to the `source` element do not work.
With that in mind, if we can't use `object-fit`, we shouldn't use The `picture` element and apply `display: none;`, so my view is that it's on a case-by-case basis....
