### ISSUE TITLE
Adding class to the parent element

### ISSUE THREAD

**Issue by bobmitro** [aFarkas/lazysizes#572]
Hi,
How to add a class (pure javascript) to the container every time when the **lazyloaded** class is apper?

before: 
```
<div class="container">
   <img src="..." class="lazyload">
</div>
```

after:
```
<div class="container overlay">
   <img src="..." class="lazyloaded">
</div>
```

I will be very grateful for any help.

**Comment by aFarkas** [comment]
It would be great if you would read the manual first ;-). It should answer your question. Three lines of code ;-).

If you can't work this out after trying hard, I help.

**Comment by Tusko** [comment]
jQuery version
You can rewrite it to Vanilla JS

```
$(document).on('lazybeforeunveil lazyloaded', function(e) {
      if(e.type === 'lazyloaded') {
        $(e.target).parent().addClass('lazy-complete')
      } else {
        $(e.target).parent().addClass('lazy-processing')
      }
})
```
