### ISSUE TITLE
<source src> with a <picture> parent is invalid and therefore ignored. Please use <source srcset> instead.

### ISSUE THREAD

**Issue by awsomedesigner** [aFarkas/lazysizes#574]
Hello,

I use picture tag and load webp image with the source. my code is as below
```
<picture>
                            <source data-src="img/webp-img/umbrella.webp" srcset="" type="image/webp" class="lazyload">
                            <img data-src="img/umbrella.png" src="" alt="Umbrella" class="lazyload">
                        </picture> 
```
When i use lazysizes , it remove srcset from source and add src which is not deprecated.

Do helpful form your side please

**Comment by aFarkas** [comment]
Please read the documentation and compare especially your markup wit one of the `picture` examples.
