### ISSUE TITLE
Image inside a parent div of height:0 is not being properly lazyloaded

### ISSUE THREAD

**Issue by MelofunkCodes** [aFarkas/lazysizes#576]
In my [codepen](https://codepen.io/MelofunkCodes/pen/maRyaN?editors=1100), I have a menu that opens upon hovering over it, which will then expand to show an image. If the menu isn't hovered, the image does not show. The image inside however is being loaded at the beginning, vs loading only when the "overlay" is opened.

The parent div (`.parent`) initially has a `height: 0;`, that when hovered over will expand to `height: 300px;`. Using this [PR](https://github.com/aFarkas/lazysizes/issues/120) as reference, I thought the problem was that I didn't properly specify the dimensions of my `<img>`'s, but I followed that PR, and the menu image is still loading at the beginning. 😞 

<img width="1440" alt="screen shot 2018-12-19 at 6 12 48 pm" src="https://user-images.githubusercontent.com/22921878/50254014-6bdda900-03ba-11e9-9d50-738f057c975a.png">

I tried to specify:
```js
window.lazySizesConfig.loadHidden = false;
```

but that doesn't work. 

The codepen is just a basic implementation of the real menu that's having this issue, but we've configured our menu to have an initial height of 0 for animation purposes. I'm guessing this CSS rule is messing up the lazysizes calculation a bit, no? Because `.parent` has a `height:0`, perhaps lazysizes is thinking that it's children is within view, so it loads it at the beginning vs later? 

 Is there a way with this configuration, that the menu image can be triggered to load **only** when its "overlay" is opened?

Thanks!

**Comment by aFarkas** [comment]
@MelofunkCodes 
It's about the CSS property `visibility: hidden`. This property can be animated using CSS transitions.

Here is a working [jsbin](https://jsbin.com/redadagewo/edit?css,output).

```css
.parent {
	 visibility: hidden;
 }
.menu:hover > .parent {
	visibility: visible;
}
```

**Comment by MelofunkCodes** [comment]
Amazing, thanks so much! 😁
