### ISSUE TITLE
orientation change does not recalculate size

### ISSUE THREAD

**Issue by adulescentulus** [aFarkas/lazysizes#577]
First of all thanks for your effort in providing and maintaining this library.

I have an issue which I think is related to #121 but this is closed for years. When changing the orientation (Chrome desktop and Chrome Android) the images always keep its sizes. Recalculation is triggered but in [getWidth()](https://github.com/aFarkas/lazysizes/blob/3e4be86d116ab54a8de5704524594a9a253b0a2d/lazysizes.js#L106) the current width of the image is always bigger than minSize.

I am no web expert so I don't really know what I probably have done wrong. I followed all instructions for [modern transparent srcset pattern](https://github.com/aFarkas/lazysizes/tree/4.1.5#modern-transparent-srcset-pattern)

Is this a bug or am I wrong?

For seeing the problem live, please see my [webpage](https://blog.networkchallenge.de/post/rtw-cusco-tour-4/)

Thank you in advance!

**Comment by aFarkas** [comment]
You have to use the CSS property `width` in your stylesheet. Something like `width: 100%;` should work in most of your cases.

**Comment by adulescentulus** [comment]
thx it works, didn't know about this
