### ISSUE TITLE
Slow loading when scrolling

### ISSUE THREAD

**Issue by patric-eberle** [aFarkas/lazysizes#579]
As lazy defined images seem to have some kind of delay when coming into view. The behaviour seems to be the same as described on https://github.com/aFarkas/lazysizes/issues/434 but I encountered it in current Chrome, Firefox and Safari on Mac and IE11. The following is an example video from IE11. Also note, that the images repeat (same source) but still don't show instantly. The server is local and responses very fast.

![ie11_example](https://user-images.githubusercontent.com/10571945/50967358-38cd9780-14d8-11e9-923a-c197cdf4abfa.gif)

Also note, that when additional images are loaded a certain amount is loaded, then nothing happens again for a few seconds. Looking at the source I think you only load a certain amount of images at a time? Could this probably be made configurable, since it depends on use case?

Also note:
- The images are `<picture>` elements
- We also use picturefill to support IE11

**Comment by aFarkas** [comment]
Additionally you can also add the following CSS to see when lazysizes does the transformation:

```
.lazyloading,
.lazyloaded {
border: 2px solid #f00;
}
```

**Comment by patric-eberle** [comment]
Currently I'm unable to give you public access. I would inform you when this becomes live. I think it would be hard to reproduce the behaviour in a JsFiddle.

**Comment by Andruten** [comment]
We are experiencing same effect but sometimes is faster:
https://kavehome.com/pt/pt/moveis <= little bit faster
https://kavehome.com/pt/pt/s/ralf/ <= secuencial

**Comment by pankajvc** [comment]
Hello,
@aFarkas 
I have also same issue in Iphone  and safari device .
when ever load my page then image is too slow loading.

**Comment by boynet** [comment]
> Hello,
> @aFarkas
> I have also same issue in Iphone and safari device .
> when ever load my page then image is too slow loading.

give test case or it didnt happen

**Comment by shortdawg896** [comment]
Hello

**Comment by pankajvc** [comment]
> > Hello,
> > @aFarkas
> > I have also same issue in Iphone and safari device .
> > when ever load my page then image is too slow loading.
> 
> give test case or it didnt happen

Ahahah I understand.

Basically, the issue that I'm facing is that if the webpage is opened up for the first time in any system (i.e. images aren't in browser cache), then the images take too long to load. As with lazysizes, first content gets rendered and then the image. However, the images take too long to load. 

Moreover, this is not a configuration issue, as this issue only occurs with the iOS devices i.e. safari browsers. If we do the same operation in other devices or browsers then the outcome is correct.

Hope this provides you some clarity on the issue that I'm facing. Any help is highly appreciated.

Regards,
Pankaj C.

**Comment by pankajvc** [comment]
> Hello

Hello

**Comment by patric-eberle** [comment]
For anyone stumbling up on this ticket somewhen: we finally fixed this problem when we worked on an other ticket and realized that we wrongly applied lazyloading classes to `source` elements on our page. This caused a mayor slow down on the script execution.

**Comment by kristiansp** [comment]
Thank you, @patric-eberle! Just been tearing my hair over this – your comment saved me, 4 years down the road 😄
