### ISSUE TITLE
force load hidden images

### ISSUE THREAD

**Issue by yoyurec** [aFarkas/lazysizes#58]
in a project i have images in hidden **tabs**(`div``s), so they are not rendered (b'cose of display:none)
how can i force them to load?

**Comment by aFarkas** [comment]
You can either set ``lazypreload`` initially or with JS (``$('img.lazyload').addClass('lazypreload');``) or use the ``lazySizes.loader.unveil(DOMNode);`` method.

**Comment by yoyurec** [comment]
oh... too tired today ))
works OK! tnx!
