### ISSUE TITLE
expand modification after init

### ISSUE THREAD

**Issue by tomasmozeris** [aFarkas/lazysizes#581]
Hey, thanks for great library!

I would like not lazyload off screen images until first user action, my config contains:
`lazySizes.cfg.expand = 1`
On first user action I'm changing expand value:
`lazySizes.cfg.expand = 500`
However **preloadExpand** has been already set and this config modification has no effect so I end up commenting statement:
`if(preloadExpand == null)`
Any chances in future release config modifications would be taking into account after init?

**Comment by aFarkas** [comment]
This is basically already done by `lazySizes.cfg.loadMode`. Simply set it to `1` initially.

**Comment by tomasmozeris** [comment]
With `loadMode: 1` bellow the fold images is loaded after `load` event. Lets say 90% of my users clicks CTA on hero image, so I'm waisting their bandwidth. I guess I could play around with `data-expand` and after first scroll modify attribute or `loader.unveil` images I wish, but still I believe modifying expand after init would be useful.

Sorry for bothering with minor things, I'll see if I can find meaningful solution and PR it

**Comment by aFarkas** [comment]
I see the general usefulness of being able to change the `expand` option dynamically so I have changed it. But to be honest in your case it is probably just some kind of premature optimization.
