### ISSUE TITLE
Why Google PSI still suggest deffer the bellow the fold images on mobile devices..

### ISSUE THREAD

**Issue by o-nkar** [aFarkas/lazysizes#586]
I have used the lazysizes on my Shopify store and works well, but when comes to check the page speed using Google PSI.

Google still suggest deferring the images that bellow the fold.
So why lazysizes does not work here, like other lazyload scripts.

Thanks

**Comment by o-nkar** [comment]
@aFarkas Thanks for the getting back to me
I am using the Lazysizes on the Shopify website and works great in terms of functionality.
But when I am checking the website it makes the suggestion for me defer the offscreen images.
1st one using simple JS lib to load the images after the page load:
![screenshot_4](https://user-images.githubusercontent.com/40701358/51726116-b4f4dd00-208b-11e9-83ef-69b2a8debb78.png)
2nd uses the lazysizes but google suggest me to defer the offscreen images.
![screenshot_5](https://user-images.githubusercontent.com/40701358/51726122-bde5ae80-208b-11e9-9322-1468d1ecd89c.png)


Any help you make on it.

**Comment by aFarkas** [comment]
@o-nkar 
As already said: I think you can simply set `loadMode` to `1`, which should basically do exactly what google wants you.

Here some information  from the readme:

```js
window.lazySizesConfig = window.lazySizesConfig || {};

//page is optimized for fast onload event
lazySizesConfig.loadMode = 1;
```

``lazySizesConfig.loadMode`` (default: ``2``): The ``loadMode`` can be used to constrain the allowed loading mode. Possible values are 0 = don't load anything, 1 = only load visible elements, 2 = load also very near view elements (``expand`` option) and 3 = load also not so near view elements (``expand`` * ``expFactor`` option). This value is automatically set to ``3`` after `onload`. Change this value to ``1`` if you (also) optimize for the `onload` event or change it to ``3`` if your `onload` event is already heavily delayed.

**Comment by o-nkar** [comment]
Hope this will help me

Thanks

**Comment by supermanoul** [comment]
Hello! This issue is still happening in our website. The images load correctly deferred using lazysizes, however Google PageSpeed Insights throws the message "Defer offscreen images" for those same images. The `lazySizesConfig.loadMode = 1;` solution doesn't seem to fix the problem in our case, have you managed to find a workaround to solve this? Thank you for your time, the plugin works great. Just adding some more info: we are using Shopify too, just in case it matters somehow.

**Comment by acwo** [comment]
@supermanoul lazysizes is shit, use vanilla-lazyload instead, here is why: https://www.andreaverlicchi.eu/vanilla-lazyload-vs-lazysizes/

**Comment by aFarkas** [comment]
@acwo 
Interesting wording. The opinion of another lib author about his own one is probably not the most objective one. So maybe try to be a little bit nicer and follow community guidelines. lazysizes is one of those libs that had some influence on how web standards are evolving something that not everyone can tell. 

Also he is simply just lying:

lazysizes supports:
- native support
- can use data-orgin if you want
- can lazyyload videos
- can execute script
- can restore

**Comment by acwo** [comment]
@aFarkas 
You are right and I apologize. I wrote that in emotion and it shouldn't have happened. 

I encountered the same issue with Google PSI and using v-ll was a quick fix. I was angry that `lazySizesConfig.loadMode = 1;` didn't work as I expected. 

You are right that lazysizes is a very influential library. Thank you for its development.
