### ISSUE TITLE
Can't i custom load src img with condition

### ISSUE THREAD

**Issue by Keither** [aFarkas/lazysizes#587]
i wan't to custom load with condition something like that
<img class='lazy' data-src='....' data-src1='....' />

**code jquery**
if(....){
 set img src from data-src
}
else{
 set src from data-src1
}

Thank so much!
And sorry my English not good!

**Comment by aFarkas** [comment]
Of course you can. Just read the documentation:

https://github.com/aFarkas/lazysizes#js-api---events
