### ISSUE TITLE
Detect image sizes in callback/ loaded event

### ISSUE THREAD

**Issue by yoyurec** [aFarkas/lazysizes#59]
Trying to detect *portrait* images by checking loaded images sizes...

As i know i can use only one `lazybeforesizes` event for it, but looks like it fires to early (`lazybeforeunveil` fires even earlier).
```
function checkPortrait(el) {
        var imgWidth = el.clientWidth,
            imgHeight = el.clientHeight;
       console.log(imgWidth);
        console.log(imgHeight);
        if (imgWidth < imgHeight) {
            alert('Ta-da, portrait detected!');
        }
}

    document.addEventListener('lazybeforesizes', function(e) {
        checkPortrait(e.target);
    }, false);
```

it doesn't work and in console i got `0` sizes ((

how can win this challenge? ))
tnx

**Comment by yoyurec** [comment]
i hooked `checkPortrait` directly to image tag - `<img ... onload="checkPortrait(this);" ... >` - works!

**Comment by aFarkas** [comment]
Yeah, the onload event is the right event for this. The ``lazybeforesizes``  event is used to calculate the the ``sizes``  attribute in case you are using the srcset attribute in conjunction with the width descriptor. At this point the width of the image should be calculatable with CSS. In case you don't set the width with CSS the parent container, that is over 50 pixel is used as the sizes attribute.

But in case you want to know the natural width/height of your images you simply use the onload event.
