### ISSUE TITLE
Throttle and Debounce standalone functions?

### ISSUE THREAD

**Issue by saas786** [aFarkas/lazysizes#591]
Hi @aFarkas 

I was wondering if you have standalone version of your

Debounce & Throttle functions? So I can use them outside Lazysizes?

I have extracted both but debounce is not working (when I import it via es6 import).

So will appreciate if you can provide them.

Thanks

**Comment by aFarkas** [comment]
Maybe:
https://github.com/boffinHouse/rawblock/blob/gh-pages/src/utils/throttle.js
https://github.com/boffinHouse/rawblock/blob/gh-pages/src/utils/debounce.js
