### ISSUE TITLE
How to alter image URL before it's shown?

### ISSUE THREAD

**Issue by futtta** [aFarkas/lazysizes#592]
I'd like to conditionally alter the img URL before it's being loaded using JS and assumed hooking into `lazybeforeunveil` could do the trick, but have no idea if this is possible and if so, how. Any input/ pointers would be greatly appreciated!

**Comment by aFarkas** [comment]
You can create a plugin with `lazybeforeunveil`.

```js
/**
@example 
<img data-foo="bar.jpg" class="lazyload" />
*/
document.addEventListenener('lazybeforeunveil', function({target}){
    const foo = target.getAttributre('data-foo');
    if(!foo){return;}
    target.src = foo.replace(/bar/, 'baz');
});
```

**Comment by futtta** [comment]
super, thanks a lot @aFarkas !
