### ISSUE TITLE
4.1.6 custom init doesn't work

### ISSUE THREAD

**Issue by jetelusmaximus** [aFarkas/lazysizes#596]
Hello,

after update on version 4.1.6  doesn't work custom init like this:

`window.lazySizes.init();`

It's bug or your purpose?

Thank you.

Jan

**Comment by aFarkas** [comment]
It's not on purpose. But I can not reproduce your problem: 
https://jsfiddle.net/trixta/L6h0j8yo/3/

Can you please provide a test case. It would be important to solve it as soon as possible.

**Comment by jetelusmaximus** [comment]
My fault, sorry for that. Thank you for reply.  Error became from missing lazysizes.min.js in npm package, so my issue is same as #597
