### ISSUE TITLE
How to use lazysizes with object-fit cover polyfill

### ISSUE THREAD

**Issue by wujekbogdan** [aFarkas/lazysizes#599]
Currently I'm using the [object-fit-images](https://www.npmjs.com/package/object-fit-images) polyfill together with PostCSS plugin: [postcss-object-fit-images](https://github.com/ronik-design/postcss-object-fit-images). In the documentation for`data-sizes="auto"` I found that you recommend using your own polyfill for `object-fit`.

Do I really need? Can't I rely on my current solution?

**Comment by aFarkas** [comment]
@wujekbogdan

I saw once that there might be happening a rare race condition inside of [object-fit-images](https://www.npmjs.com/package/object-fit-images) polyfill which resulted in a wrong/older image to be shown. But normally you can use this polyfill with lazySizes. If you have a bug please let us both know.

You should still use the parent-fit plugin on top if you use `object-fit` in combination with `data-sizes="auto"`

**Comment by wujekbogdan** [comment]
> I saw once that there might be happening a rare race condition inside of [object-fit-images](https://www.npmjs.com/package/object-fit-images) polyfill which resulted in a wrong/older image to be shown. But normally you can use this polyfill with lazySizes. If you have a bug please let us both know.

Can I just drop it and forget about it? Or do I need to re-initialize object-fit after lazysizes is initialized?

> You should still use the parent-fit plugin on top if you use `object-fit` in combination with `data-sizes="auto"`

Sure, that's clear from the docs.

**Comment by aFarkas** [comment]
> Can I just drop it and forget about it? Or do I need to re-initialize object-fit after lazysizes is initialized?

I'm not sure about this, but it should be fine and listen for every `load` event.
