### ISSUE TITLE
[help] to get preload working

### ISSUE THREAD

**Issue by deedeefink** [aFarkas/lazysizes#603]
Using LazySizes on https://olgafink.com/test.html but would like to accommodate slow mobile connections by preloading +1 image ahead of current visible image. 

Is that possible on Bootstrap 4 and if so, how.

Thanks

**Comment by aFarkas** [comment]
Yes you can hook into the bootstrap carousel event and then use the `unveil` method on the image next to the current one. The `unveil` method is documented in my readme. The carousel event should be documented by bootstrap.
