### ISSUE TITLE
Why does lazysizes load off screen images? 

### ISSUE THREAD

**Issue by GozuPro** [aFarkas/lazysizes#604]
I have a basic demo with 16 images. I was expecting lazysizes to load only the images visible on the screen. In my example, loading the first image and probably the second as well. 
Why does it loads the **first 10 images**?

Demo: https://jsfiddle.net/8sproewf

Thanks!

**Comment by aFarkas** [comment]
lazysizes decides wether an image is inview based on the layout before an image is loaded. In your example all 16 images are in view initially. 

I hope I don't have to explain more. Just think.

**Comment by dyslexicon** [comment]
I don't mind explaining a little more, people come from everywhere, and sometimes it's easy to miss things.

Before the `src` is fetched for all the `<img>` tags, i.e., before the images are loaded, all the `<img>` elements have an initial `height` of `0px` and are therefore seen by lazysizes to be 'inview' and are thus loaded. When the images start to load on the client, at a certain point they have enough dimension to push images further down in the HTML document 'out of view' and lazysizes ceases to load. 

If we give sufficient height to the `<img>`s parent element, lazysizes works as expected.

Demo: https://jsfiddle.net/wperycxs/
