### ISSUE TITLE
ls.unload 4.1.6 has breaking changes from 4.1.5

### ISSUE THREAD

**Issue by davemoore24** [aFarkas/lazysizes#608]
In ls.unload@4.1.6, you now have to explicitly set `window.lazySizesConfig.expand` or the plugin will not work unlike 4.1.5 and previous versions. I checked the docs and nothing mentioned this. Is this the correct intent or is this a bug? jsfiddle isn't required for this.. its obvious.

**Comment by aFarkas** [comment]
I will check this. I'm currently on holiday.
