### ISSUE TITLE
Broken image on img load error

### ISSUE THREAD

**Issue by collinsethans** [aFarkas/lazysizes#615]
When an image fails to load, the broken img icon shows up. This is happening as switchLoadingClass() is not handling event.type = 'error' and setting the class 'lazyLoaded'. Also notice that the lazySizesDefaults.errorClass is never set.

Attaching a fix patch.
[lazysizes-load-err-patch.txt](https://github.com/aFarkas/lazysizes/files/2949211/lazysizes-load-err-patch.txt)

**Comment by aFarkas** [comment]
Yes this is on purpose. An image with an error is per definition `complete`. If you want special handling of broken image do it your own. Best thing is to fix the issue.

**Comment by collinsethans** [comment]
@aFarkas Thanks for your response and letting me know.

I am trying to understand: 
- Without any indication of load error, how should we handle display of that? Else, it's a negative experience for user.

- Yes, best is to fix the issue. For that we need notification (event/push to server) especially when we use it on sites that can have several thousands or even million of products and some image(s) may be accidentally deleted by maintener. I was thinking handling of load error with trigger is a better way (well, ofcourse, other method is a script to process the nginx logs, but that can be delayed identification).

**Comment by aFarkas** [comment]
This is a lazyloader. I don't handle your errors for you. If you want to handle errors it is easy:

```js
document.addEventListener('error', ({target}) => {
     // handle your error
}, true);
```

**Comment by collinsethans** [comment]
Thanks, we know how to attach the handler for error handling. We are even fine if an img with error is identified with class '.lazyloaded.lazyerror' (due to extra handler for error)

We were more curious about the trigger 'lazyloaded' -- this is triggered irrespective of load or error and therefore it's handler handles both in same way!

**Comment by aFarkas** [comment]
Yes for lazysizes it simply means that loading has ended for whatever reason.
