### ISSUE TITLE
Alt tags showing before img is loaded

### ISSUE THREAD

**Issue by bob4081** [aFarkas/lazysizes#616]
(Beginner here so please forgive me for stupid question)

For some reason my alt tags are showing while the images are loading. Happening with Safari and Firefox.

Am I doing something wrong?

Safari Screenshot (white box is alt tags...?)
<img width="304" alt="Screen Shot 2019-03-17 at 7 08 21 PM" src="https://user-images.githubusercontent.com/48660411/54502482-1bf27d80-48e8-11e9-947c-e06a2c290508.png">

My code
`<img class="lazyload" data-sizes="100vw" alt="body builder weight lifting gym venice los angeles california muscle beach"
data-srcset="https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-150,q-90,pr-true,cp-true 150w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-300,q-90,pr-true,cp-true 300w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-450,q-90,pr-true,cp-true 450w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-600,q-90,pr-true,cp-true 600w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-750,q-90,pr-true,cp-true 750w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-900,q-90,pr-true,cp-true 900w,
https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-1000,q-90,pr-true,cp-true 1000w" data-lowsrc="https://ik.imagekit.io/jnycdn/wp-content/uploads/images/2018/muscle-beach/Jonnie-Chambers-C17003-3-8-LRJ.jpg?tr=w-300,bl-30,q-70" />`

**Comment by aFarkas** [comment]
No you are not doing something wrong. It is currently not documented. You can hide your image until it is transformed:

```css
img.lazyload:not([src]) {
    visibility: hidden; /* or opacity: 0.001; but never use display: none */
}
```

**Comment by bob4081** [comment]
@aFarkas Thank you so much. And thank you for brilliant this plugin!!
