### ISSUE TITLE
Images not loading on iOS Safari

### ISSUE THREAD

**Issue by cjd118** [aFarkas/lazysizes#617]
We are having issues with lazysizes not loading random images on iOS Safari.

This is always reproduceable - on this particular page say there are 200 images in total and around 2% will not load. Different images will not load each time so there is no particular issue with the image itself.

The images that fail to load always return a 200 response in the client developer tools and the server also logs this as a 200 server side. The image loads okay when visiting it directly on Safari. 

We're using BrowserStack and testing on a real device: iPhone 8, Safari 11.

The console returns "Failed to load resource: The network connection was lost.". 

We are using HTTP/2 and wonder if this might be the cause of the issue? I can email the weblink to test this.

In the screenshot below I am on the image that fails to load: 

![iOS image loading issue](https://user-images.githubusercontent.com/1626209/54601762-ca590880-4a37-11e9-9292-fa8158cef796.png)

Any ideas? 

Thanks.

**Comment by aFarkas** [comment]
> The console returns "Failed to load resource: The network connection was lost.".

This tells us that lazysizes is doing its job and there is a network problem. Test with a real device or at least with the real simulator coming with xcode. If it is not happening there it is probably a problem on the browser stack side.

**Comment by cjd118** [comment]
@aFarkas the above screenshot from BrowserStack is a real iDevice. We've tested on physical iPhones too and can also replicate it not loading random images. 

The fact the request itself comes back as 200 but the image fails to load points to it being an issue with lazysizes.

**Comment by aFarkas** [comment]
> The fact the request itself comes back as 200 but the image fails to load points to it being an issue with lazysizes.

Why do you think this? Simplified lazySizes transforms the following element `<img data-src="bar" />` into `<img `src="bar" />`. This is everything that lazySizes has to do. 

As soon as this happens correctly the browser starts the request, decodes the image data and renders/paints it according to the CSS. lazySizes is not involved in any of those later steps mentioned above.

You mention that there is a request going out and that there is a log message stating that something bad happened with the request. As stated above lazysizes doesn't handle the request the browser and the server are doing this.

Maybe it is the following issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915103

**Comment by cjd118** [comment]
@aFarkas You're right! Looks like an issue with our version of Apache - good spot 👍
