### ISSUE TITLE
Images inside labels are not detected

### ISSUE THREAD

**Issue by bpeab** [aFarkas/lazysizes#619]
Hello,

First of all, thanks for this great library.

I stumbled across an issue where images inside `<label>` elements are not detected by the `lazySizes` library. 

```html
<label for="{{ id }}" class="...">
    <img src="{{ image }}" alt="" class="lazyload">
</label>
```

I used a partial with the `lazyload` class specified for images across the entire project I am working on and it's the only use case where images are not detected nor lazy-loaded. 

I can't seem to find any related issue with a similar use case and was wondering if somebody had a workaround ? For the moment being, I have simply disabled the lazy-loading for this particular case.

Thank you, don't hesitate if you need more informations.

**Comment by aFarkas** [comment]
@bpeab 
This sounds a little bit crazy. I think there might be more than just being wrapped by a `label`. Can you please provide a testcase or link. So I can reproduce this problem and work on a fix?

**Comment by bpeab** [comment]
Hello @aFarkas. I opened this issue to quickly. It has nothing to do with `lazySizes`.
