### ISSUE TITLE
CDN Not updated to 4.1.7

### ISSUE THREAD

**Issue by zzseba78** [aFarkas/lazysizes#620]
First of all, amazing plugin! Love it.

https://cdnjs.com/libraries/lazysizes doesn´t have the latest version of Lazysizes (4.1.7).

**Comment by bridgeport** [comment]
It's available on jsdelivr:
https://www.jsdelivr.com/package/npm/lazysizes

Strangely, none of the plugins list their minified `*.min.js` versions.
Example:
https://www.jsdelivr.com/package/npm/lazysizes?path=plugins%2Faspectratio

However, if you were to guess the minified URL, jsdelivr appears to pull the file to store on its CDN.
Example:
https://www.jsdelivr.com/package/npm/lazysizes?path=plugins%2Faspectratio
https://cdn.jsdelivr.net/npm/lazysizes@4.1.7/plugins/aspectratio/ls.aspectratio.min.js
