### ISSUE TITLE
Lazysizes should work only with simple import (vue)

### ISSUE THREAD

**Issue by filipaalvesd** [aFarkas/lazysizes#623]
It is necessary to declare it as a component to work properly. 

```
components: {
      lazySizes
}
```

As it is not a component it should works only with simple import.

`import lazySizes from 'lazysizes'`

Do I missed something?

**Comment by corygibbons** [comment]
Does this work?

`import 'lazysizes'`

**Comment by filipaalvesd** [comment]
@corygibbons, perfectly! Thanks
