### ISSUE TITLE
lazyloaded event does not always fire

### ISSUE THREAD

**Issue by galvarez421** [aFarkas/lazysizes#625]
Related to [this issue comment](https://github.com/aFarkas/lazysizes/issues/407#issuecomment-475328722), the `lazyloaded` event does not always fire for me. I am using v4.1.5. The behavior is inconsistent and does not necessarily seem to be a function of where the scroll is on the page: I have experienced this issue after reloading the page while scrolled to the top but also while scrolled down from the top. If I refresh the page multiple times, sometimes (probably at least 1 out of 5 times) some images will receive the `lazyloaded` class but the `lazyloaded` event will not fire for those elements. For what it's worth, I am experiencing this issue while using the [noscript extensions/plugin](url), so perhaps the issue is specific to this extension/plugin, but I'm not sure about that.

The effect is visble on my end because I am trying to populate a thumbnail image for each image in a set of lazy loaded images but I have to wait for the lazyloaded event to fire for each image so that I can select the lazy loaded image (to get its `src` attribute) since the image is not selectable while in the noscript element. I can also see using the following code that the `lazyloaded` event is not firing even though the images do load and do receive the `lazyloaded` class.

```
$('.lazyload').on('lazyloaded', () => {
  console.log('Lazyloaded image');
});
```

**Comment by galvarez421** [comment]
I think I may have figured out the issue I am experiencing. I am importing lazysizes and the noscript plugin using ES6 imports as follows:

```
import $ from 'jquery';
import 'lazysizes';
import 'lazysizes/plugins/noscript/ls.noscript';

$(() => {
  $('.lazyload').on('lazyloaded', () => {
    console.log('Lazyloaded image');
  });
});
```

Since lazysizes auto-initializes, it seems that it is sometimes triggering the event before the listener is registered by my code, depending on how fast the image lazy loads relative to execution of my code. Essentially there is a race condition, which explains the inconsistent behavior described in the OP.

I assumed that the `lazyloaded` event functioned like jQuery's [.ready()](https://api.jquery.com/ready/), i.e. (changes in brackets are mine):

> If the [image] becomes [lazy loaded] and the [plugin] fires [`lazyloaded`] before the code calls [the event handler registration], the [`lazyloaded` event handler] will still be executed.

In my case, I don't think it makes sense to disable auto-initialize and register the handler before initializing lazysizes because I am registering widget- and element-specific handlers via lazy loaded JS. So, for now, I believe the workaround in my case is to use other means to detect if the image has already been lazy loaded before the listener/handler is registered, e.g., checking for existence of `lazyloaded` class. But, perhaps it'd be a good idea for the `lazyloaded` event to also account for images that were lazy loaded before the event listeners were registered like jQuery's `.ready()` does?

**Comment by aFarkas** [comment]
> But, perhaps it'd be a good idea for the lazyloaded event to also account for images that were lazy loaded before the event listeners were registered like jQuery's .ready() does?

No not really. You can control when lazysizes starts `init()`, you can control wether an images was loaded `.lazyloaded` and you can control when you bind your listeners. If you initialize lazysizes and you add listeners delayed in the future it is your responsibility to handle your self-inflicted race conditions.
