### ISSUE TITLE
Feature request: Auto-sizes with object-fit properties

### ISSUE THREAD

**Issue by whatsnewsisyphus** [aFarkas/lazysizes#628]
Hello,
Thanks for maintaining lazysizes. I was working with object-fill images and thought it would be great to have the option for lazysizes to calculate sizes with object-fit in mind. For example, when dealing with hero images that are to fill full screen containers, setting sizes to container width on a portrait ratio image will lead to a low resolution image scaled up to fit the container.

If there was a way for lazysizes to consider the image size/ratio and the container ratio and set sizes width property to what it would need to cover/fill/contain accordingly that would be awesome.

**Comment by whatsnewsisyphus** [comment]
oi me... can close
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit

**Comment by aFarkas** [comment]
you got it ;-)
