### ISSUE TITLE
Native lazy-load in Blink & impact on lazysizes

### ISSUE THREAD

**Issue by futtta** [aFarkas/lazysizes#630]
As per https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/jxiJvQc-gVg Chrome (& later other non-Google Blink-based browsers) will in the near future come with support for a `loading` attribute on images (& iframes). 

I guess lazysizes could (should?) take that into account by checking if the browser supports the loading attribute

`if ('loading' in HTMLImageElement.prototype) { … }`

And if `true` (optionally or by default) leave the lazyloading to the browser if an image has the `loading="lazy"` attribute set?

**Comment by aFarkas** [comment]
thank you I will close this in favor of https://github.com/aFarkas/lazysizes/issues/629
