### ISSUE TITLE
Blur up plugin is not compatible with IE

### ISSUE THREAD

**Issue by slavanga** [aFarkas/lazysizes#631]
The blur up plugin is using the find method which is not supported by IE.
https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/blur-up/ls.blur-up.js#L33

Error in IE:
```
Object doesn't support property or method 'find'
```

The error also occurs in the official [demo](https://jsfiddle.net/trixta/v0oq0412/embedded/result/) for the plugin.
Until this is fixed the error can be prevented by including a [polyfill](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill) for the find method.

**Comment by aFarkas** [comment]
Thank you!!!
