### ISSUE TITLE
automatic sizes calculation is too large

### ISSUE THREAD

**Issue by nosilver4u** [aFarkas/lazysizes#633]
I've run into an odd case where the auto-calculated sizes attribute is larger than the native size of the image, and wondering the best way to avoid it.
This is the page: https://dev.get-business-online.com/ronitbaras/books/printed-books/reflections/
You'll note that currently lazysizes.js is not in the page, and all the images are blank, because we wanted to see what the size of the img element was right before lazysizes fires. In other words, this is the code prepared for lazysizes, but without the actual script to do anything.
If you go to the About the Author section, there is a blank space, which contains the img element in question (though the problem occurs again further down the page).

You'll see the space is designated as 495px wide, thus this is what lazysizes sets the sizes attribute as.
You can also see the original page, as it's intended to display here: https://dev.get-business-online.com/ronitbaras/books/printed-books/reflections/?ewwwio_disable=1

I don't really have any control over the site itself, as I'm just the developer for the image optimization plugin this guy is using on his site.
What I'm hoping is to find a way to prevent such issues, as I anticipate there could be other sites that use my plugin that might have the same problem.

As best as I can tell, the main issue is that the specs for srcset/sizes state that an image will be stretched to fill whatever sizes says the image should be UNLESS a width attribute is present.
While this page does have a width (and height) attribute, those are over-ridden by CSS of height=auto and width=auto.

Ideas?

**Comment by aFarkas** [comment]
Please [RTFM](/aFarkas/lazysizes#user-content-data-sizes-auto).

**Comment by aFarkas** [comment]
sorry i didn't meant it rude. The sentence was also added later. You already basically did the right thing to check the images without using lazySizes. This is why I don't understand that you didn't realize the error.

**Comment by nosilver4u** [comment]
I guess what I was trying to figure out (since I'm obviously not an expert in CSS), is whether there was any way to compensate for someone having width=auto on their site, or if it was just a case of telling them not to do such "silly" things :)
Where I'm the plugin dev and don't have much control over the end-user's site, there's a lot of crazy designs out there, and the more I can safe-guard against such breakages, the better.

What I was thinking, was perhaps something like this: if one could hook into lazybeforesizes, and check for the width=auto CSS rule; if width=auto is detected, then look at the width attribute directly on the element, and constrain to that rather than ending up with an image that is stretched.

I don't know if it is possible to detect that bit of CSS, but just throwing it out there, in case you think it would be worth pursuing.

**Comment by aFarkas** [comment]
> check for the width=auto CSS rule

Sadly we only have computed styles and have no real access to the uncomputed css value of a given element. This was basically possible with IE8- (Not sure about newer IEs) but it's not possible using a standard. Otherwise I would have done it. The problem is also `width="auto"` simply means display the image as big as the image is. It has no design restrictions and therefore the hole space can be used and will be used if the image is big. What you could do is to define a `max-width` or `min-width`. (lazySizes will initially only look into the `min-width`, but if you hook into `lazybeforesizes` you could also check `max-width` and of course your HTML attributes.)

**Comment by nosilver4u** [comment]
I kind of suspected that, thanks for the ideas!
