### ISSUE TITLE
Jumping element while using alt attributes

### ISSUE THREAD

**Issue by sowinski** [aFarkas/lazysizes#635]
Hi,

if I use the alt attribute in my image. The image starts jumping.
Here you can see an example: https://jsfiddle.net/14Ls0bza/7/
Tested on newest Firefox and Google Chrome browser.

This is also happening without using lazyload. I guess wee need a workaround for this situation? How do you handle this issue?

**Comment by aFarkas** [comment]
[RTFM](https://github.com/aFarkas/lazysizes#user-content-specify-dimensions) :-).

**Comment by sowinski** [comment]
Sorry for asking again but I did it exactly like here described: https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps

(I wanted to use the non css method, is this not working anymore)?

**Comment by aFarkas** [comment]
> I wanted to use the non css method, is this not working anymore?

Wow, I did not know that. I must say that I always use CSS to style my components and never use layout related HTML attributes. But it doesn't seem to work as soon as you specify an `alt` attribute.

I will change my docs. Sorry for that.
