### ISSUE TITLE
broken-image-symbol bug

### ISSUE THREAD

**Issue by sowinski** [aFarkas/lazysizes#636]
I wanted to remove the small broken symbol image as described here with css: https://github.com/aFarkas/lazysizes#broken-image-symbol

`img.lazyload:not([src]) {
	visibility: hidden;
}`

Unfortunately this is not working when you define it inline in the head of your document.

I guess lazysizes is ignoring the image because it is set to hidden. 
If you load it in an external css file it works, why?

**Comment by sowinski** [comment]
One possible workaround could be to set opacity to 0. Then it seems to work

**Comment by aFarkas** [comment]
Sorry I didn't see your issue. This sounds crazy and I can not confirm it. Maybe your hidden test example has also other things applied?
