### ISSUE TITLE
Interchanging menus?

### ISSUE THREAD

**Issue by anyway** [aFarkas/lazysizes#64]
Hi,

is it possible to interchange also complete div constructions with lazysizes? I want to put out a mega menu for desktop and a different menu for mobile. Different html, so that can't be solved by a normal responsive menu. I don't want to load both menus and just hide one by css. Is that possible and what is the best practice?

Thanks!

**Comment by aFarkas** [comment]
Yes, in general lazySizes is pretty simple to extend. Every element with the class lazyload triggers the event ``lazybeforeunveil``.

In general there is also a plugin, which does exactly this: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/include

In case you have further questions about it, please ask. But the documentation should cover most things.

**Comment by anyway** [comment]
Thanks for your quick reply! Okay, then i'll dive deeper into it. I just wasn't sure if it is only for pictures and iframes as described.

**Comment by aFarkas** [comment]
@anyway 
I'm closing this. In case you have any concrete questions just ask. I'm happy to help.
