### ISSUE TITLE
Using a Dynamic Imaging Service

### ISSUE THREAD

**Issue by andrewgadziksonos** [aFarkas/lazysizes#640]
Hello!  First off, thank you for this library.  It's amazing! 

I'm working through including this library onto our site, and was wondering if there was a way to dynamically modify the `data-srcset` attribute based on the parent's container dimensions?   Reasons being is that we're using a dynamic imaging service that dynamically scales images based on some supplied query parameters.  

Reading through the documentation, it seems like I need to use `data-sizes="auto"`, but wasn't sure if this is the appropriate  place to handle this sort of logic?  

Thanks for all the help,

Andrew

**Comment by aFarkas** [comment]
Yeah, we have already a plugin to integrate such services: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/rias

For doing a simple integration yourself you basically only need to generate mutliple different urls to your service. And let the browser decide which image candidate to take. For this you don't need to hook into `lazybeforesizes`, only hooking into `lazybeforeunveil` can do the trick. But of course `data-sizes="auto"` is quite convenient.

The `data-sizes="auto"` feature always takes the layout `width` of the image itself so you should write your CSS accordingly. But of course if you can't you can additionally hook into the `lazybeforesizes` and proxy the `width` of your parent element or for example take things like `max-width`/`min-width` into account.

In case you use `object-fit` in combination with `data-sizes="auto"` use the `parent-fit` plugin (which also has a feature to not use the image dimension but the dimension from an ancestor element.)

Please close if this helps.

**Comment by andrewgadziksonos** [comment]
Thank you for the help!  This is exactly what im looking for
