### ISSUE TITLE
Why not use width and height attributes to calculate data-aspectratio if available?

### ISSUE THREAD

**Issue by Hlsgs** [aFarkas/lazysizes#642]
Just a quick a hopefully not dumb question ^ :)

I'm having to do extra queries in Wordpress to get the image size so as to add the "data-aspectratio" attribute while cusmomizing the "sizes" attributes(I only use sizes="auto" when necessary), when WP already always provides the width and height attributes. This in in conjunction with object-fit and your parent fit plugin.

**Comment by aFarkas** [comment]
Thank you

**Comment by thasmo** [comment]
This is the best feature ever. :heart:

**Comment by thasmo** [comment]
Oh, I just realized - is there a reason this has not been implemented in `plugins/aspectratio`?
