### ISSUE TITLE
[Question] Offscreen slide-out mobile menu containing images

### ISSUE THREAD

**Issue by willstocks-tech** [aFarkas/lazysizes#644]
Hey @aFarkas - hope you're well?

I have a question for you - I have a site (https://willstocks.co.uk) that has a sidebar down the right hand side when viewing on a desktop. When a user is viewing the site on a phone, that sidebar is moved off into a burger menu that slides out (all fairly standard?).

On to the question: The big G is _always_ complaining about any images/widgets that I have in this sidebar/hamburger menu when running PSI/Lighthouse/web.dev tests, saying I need to defer the offscreen images. This makes sense, because they're not immediately visible in the viewport, but are if a user were to open the menu.

So my question is - is there a way for me to defer the loading/lazyload those sidebar image (in the burger menu, for mobile users) to either: after the page loads (i.e. the _last_ images to lazyload immediately) **or** just lazyload them entirely until the user opens the hamburger menu?

If it makes a difference, my site is using [SlickNav](https://github.com/ComputerWolf/SlickNav) for the mobile menu

**Comment by aFarkas** [comment]
There are multiple methods to do this:

Try first this one:
```css
.off-canvas {visibility: hidden}
.canvas-open .off-canvas {visibility: inherit}
```

In some rare cases you might additionally need to change `loadMode` to `1`.

**Comment by willstocks-tech** [comment]
Thanks @aFarkas - I will try that CSS to begin with to see if I can get that to work 😄

**Comment by willstocks-tech** [comment]
Just to check @aFarkas - do I also need to set `lazySizesConfig.loadHidden = false` as well? Or leave it at `true` and just have the images load in delayed?

**Comment by aFarkas** [comment]
If you set the parent of an `img.lazyload` to `visibility: hidden` lazysizes will automatically delay loading to a later time. In case you set `loadMode` to `1` it is guaranteed that "later time" means after `onload`. If you set `loadHidden` to `false` the hidden images are only loaded after they are becoming visible. So it really depends what you want.

**Comment by willstocks-tech** [comment]
Thanks for clarifying that - I'll go with the CSS approach initially (which should work) and if that doesn't work I'll try the `loadHidden = false` config option, before trying `loadMode = 1` 😄

**Comment by willstocks-tech** [comment]
@aFarkas - Just wanted to say, I had the chance to apply the `visibility` CSS yesterday and that worked perfectly. Thank you for your assistance 😄
