### ISSUE TITLE
demo of blur-up plug-in not working

### ISSUE THREAD

**Issue by mario-merino** [aFarkas/lazysizes#645]
It doesn't work on my Macbook, neither Chrome nor Safari

https://jsfiddle.net/trixta/v0oq0412/embedded/result/

I believe the issue lays here:

.lazyload:not([src]) {
  visibility: hidden;
}

**Comment by aFarkas** [comment]
Yeah thank you. This happens when you make a small change that is so small that you don't think you need test because you thought you are smart. But you aren't ;-)
