### ISSUE TITLE
strange sizes calculation

### ISSUE THREAD

**Issue by KhramtsovMaksim** [aFarkas/lazysizes#646]
Hello, thank you your time and for this amazing library! It's very cool!

During the debugging process, I discovered that the image size attribute was calculated incorrectly. I read and tried several solutions from the already solved issues, but nothing comes of it. I just found out that problems start with the rias & parent-fit plugins. Could you please help me? I am attaching a demo (https://codepen.io/anon/pen/ROdmRW)

**Comment by aFarkas** [comment]
I haven't looked to long on your implementation but there is at least one markup error that probably causes your issue.

You are using the following markup:

```
data-aspectratio="200/100"
```

You should instead use the ratio itself:

```
data-aspectratio="2"
```

**Comment by aFarkas** [comment]
@KhramtsovMaksim 
Did this solve your problem?

**Comment by KhramtsovMaksim** [comment]
@aFarkas , sorry for delay - Yes it works with ```data-aspectratio="2"```.
Thank you!
