### ISSUE TITLE
Unveil only loads images if they're in view on window load

### ISSUE THREAD

**Issue by STEPLADD3R** [aFarkas/lazysizes#649]
It appears that using the event listener lazybeforeunveil (as per the documentation) my background images only load if I refresh the page with them in view, otherwise usually only the first one loads, is there a way around this?

I'm just using the as per documentation js
//add simple support for background images:
document.addEventListener('lazybeforeunveil', function(e){
    var bg = e.target.getAttribute('data-bg');
    if(bg){
        e.target.style.backgroundImage = 'url(' + bg + ')';
    }
});

But I have also tried:

document.addEventListener('lazybeforeunveil', function() {
  var bgs = document.querySelectorAll('[data-bg]');
  var i;

   for(i = 0; i < bgs.length; i++) {
      bgs[i].style.backgroundImage = 'url(' + bgs[i].getAttribute('data-bg') + ')';
   }
});

They both seem to do exactly the same :/

Thank you

**Comment by aFarkas** [comment]
I don't really understand your problem. lazySizes is a lazyloader which means `lazybeforeunveil` gets called on an element as soon as this element is in view or at least close to "in view". Do you expect something different? If you still think it's a bug. Please create a simplified testcase.

**Comment by STEPLADD3R** [comment]
Sorry, the problem is that when I scroll into view, it's not showing (on background images). I have a block of 5 all containing background images, and only the first background image shows

**Comment by STEPLADD3R** [comment]
Think I've fixed the issue, I enqueued 'lazysizes-unveilhooks-js' above 'lazysizes' and it seems to be better now.
