### ISSUE TITLE
LQIP issue on Chrome

### ISSUE THREAD

**Issue by tigranpetrossian** [aFarkas/lazysizes#65]
Hey there,

I'm facing a strange issue in Chrome (both Win and Mac, v39 and v40 tested) when trying to specify a dummy image (just to preserve height avoid repaints on a fluid layout) as LQIP `src`.

I'm using a `srcset` to specify `2x` image for the browsers that support it and here's the markup:

    <img class="lazyload" src="dummy.png" data-src="image.png" srcset="" data-srcset="image@2x.png 2x"> 

With the `src="dummy.png"` specified, `src` attribute value never gets swapped in Chrome, while everything perfectly works when `src=""`. All other browsers seem to be fine.

Here's a real world example:
http://doxie.tigran.io/info/awards.html

P.S. to be reproduced on a non-retina display.

**Comment by aFarkas** [comment]
It seems I need to be more clear in my documentation. In short change your markup to something like this:

```html
<!-- in case you are using a polyfill like picturefill or respimage: -->
<img class="lazyload" src="dummy.png" data-srcset="image.png, image@2x.png 2x">

<!-- in case you are not using a polyfill -->
<img class="lazyload" src="dummy.png" data-src="image.png" data-srcset="image.png, image@2x.png 2x">
```

Here is a [longer explanation](https://github.com/aFarkas/lazysizes/issues/53#issuecomment-72705175).

**Comment by tigranpetrossian** [comment]
Hi @aFarkas,

My bad, didn't thoroughly look into issues, now it makes sense. Thanks a lot for the quick response.
