### ISSUE TITLE
Puppeteer lazyimages_without_scroll_events.js test gives "failed" as result

### ISSUE THREAD

**Issue by delitestudio** [aFarkas/lazysizes#650]
Thanks for your script. It's seamless to integrate and it works very well.

I've a question. From what I see it should be SEO friendly. However if I use the script `lazyimages_without_scroll_events.js` (taken from [puppeteer-examples](https://github.com/GoogleChromeLabs/puppeteer-examples)), which determine if lazy loaded images will be seen correctly by Google Search, I get this result:

> "Site result: FAILED"

The comment says:

> "The two screenshots below should look more or less the same. If there are missing images in the left screenshot, it's likely they are being lazy loaded using scroll events. This can present a problem for search engines which often do not run JavaScript, and therefore, do not run scroll handlers. Images need to be fully loaded when they're "in the viewport", without scrolling the page. Instead of scroll events, use a more modern approach like IntersectionObserver with a polyfill. If you're using library for lazy loading, find one that doesn't use scroll events."

In my case the screenshots are different, because in one of them some lazyloaded images are missing. Honestly it seems strange to me, because your script seems well implemented and obviously uses IntersectionObserver, and I specified one fallback src via the `data-src` attribute.

Is it an alert to take seriously or in your opinion can it be ignored?

I'm using lazysizes version 4.1.8. Thanks for your time!

**Comment by delitestudio** [comment]
I published some articles and the lazyloaded images seem to have been correctly indexed by Google- since they appear in the image search. Can we be certain it is not going to be an issue?

**Comment by aFarkas** [comment]
Pupeteer works by using a specific technique that does not equal the technique search engine bots use. So the truthfulness of the pupeteer test has nothing to do with the reality. lazySizes is based on the observation how current search engine bots work. Of course there can be some change and lazySizes breaks.

But what certainty do you want to have here? The current test obviously doesn't work as expect.

**Comment by delitestudio** [comment]
Ok good to know! Puppeteer however is mentioned in the [official Google documentation](https://developers.google.com/search/docs/guides/lazy-loading) ;)

**Comment by aFarkas** [comment]
Yeah, I'm sure that the documentation is great and puppeteer also. But the idea that using intersectionobserver improves the indexability of your images is plain wrong.

Here is also a screenshot of a small feature test of the google bot: (As you can see google bot does not support intersectionobserver)

![intersection-observer](https://user-images.githubusercontent.com/188254/57914713-7a5bbe00-788f-11e9-80ae-11496505b148.png)

**Comment by delitestudio** [comment]
I didn't understand what you mean. I don't expect that IntersectionObserver *improves* the indexability of my images, but I expect Google *can see* lazy-loaded content.

In its documentation Google says to test it with Puppeteer, but with LazyImages it gives "failed". Yet it seems to me that Google indexed them correctly. So in reality it all seems ok!

I just wanted to make sure my site got no penalties from SEO point of view. Which would be absurd since Google itself suggests to use the IntersectionObserver :)

Thanks!

**Comment by aFarkas** [comment]
> I just wanted to make sure my site got no penalties from SEO point of view.

You can totally relax here. lazySizes makes the images available for google bot.

But: If you think that google can "see" (i.e. *index*) lazy loaded images based on the usage of `IntersectionObserver` you are wrong. As proven above the current google bot doesn't even support `IntersectionObserver`.

While google has some really talented developers and spoke persons like paul irish, jake archibald, addy and so on. google doesn't always got the right facts. In this case they simply want to push the usage of some modern technologies by giving you plain wrong information.

In google fundamentals for example there are some quite bad advices given like the following:

> The first thing to keep in mind is that as the JavaScript runs all the old layout values from the previous frame are known and available for you to query. So if, for example, you want to write out the height of an element (let’s call it “box”) at the start of the frame you may write some code like this:
```js
// Schedule our function to run at the start of the frame.
requestAnimationFrame(logBoxHeight);

function logBoxHeight() {
  // Gets the height of the box in pixels and logs it out.
  console.log(box.offsetHeight);
}
```

Or this:

```js
function onScroll (evt) {

  // Prevent multiple rAF callbacks.
  if (scheduledAnimationFrame)
    return;

  scheduledAnimationFrame = true;
  requestAnimationFrame(readAndUpdatePage);
}

window.addEventListener('scroll', onScroll);
```

I wanted some years ago do get those statements corrected or at least clarified because they are either plane wrong or misleading at least. But google also have some less talented guys with some ego issues so these clearly wrong statements won't be corrected.
