### ISSUE TITLE
ls.native-loading.js behaviour

### ISSUE THREAD

**Issue by Hlsgs** [aFarkas/lazysizes#652]
Does ls.native-loading.js switch the required attributes and immediatly set the `lazyloaded` class or does it wait until the image is actually loaded by the browser lazily and then actually remove `lazyloading` and add `lazyloaded`?

I'm unfortunately unable to test the plugin properly as both Canary and Dev seem to always load all the images immediatly, either with LS loaded/involved or not, and with `loading="lazy"`. However, I did observe `lazyloaded` only beeing added after the image was actually loaded and wanted to make sure that's the way it's supposed to work.

Thanks you!

**Comment by aFarkas** [comment]
You probably still have to set the flag: [chrome://flags/#enable-lazy-image-loading](chrome://flags/#enable-lazy-image-loading).

As soon as the image is transformed the class `lazyloading` is set and only if the image is loaded or errored the class `lazyloaded` is set. So it should work as you expect.

**Comment by Hlsgs** [comment]
The flag is set. Must be some Chrome implementation quirk. I'll keep testing on newer versions on Canary.

Excellent to know that the only change will be what triggers loading loading the image. This way we can keep the existing loading effects and whatnot. Awesome, thank you!

**Comment by aFarkas** [comment]
Yes it seems still quite quirky. At the time I was developing it. It seemed quite good. I still wait with using this feature.

But I will maintain the plugin.
