### ISSUE TITLE
Delayed init

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#66]
One more thing about the delayed init! Since the config is checked and written to lazySizesConfig as soon as the file load, and not inside the timeout, any attempts to change the init property later than this file is included will fail. I like to include all vendor scripts first. Now I have to put it last of all files, and make sure it's stays there. Which might be a problem with future employees etc. I think you don't think it's a problem it's fine. Just wanted to let you know.

**Comment by aFarkas** [comment]
This is not true, you can simply change it. Using the following pattern:

```js
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
```

Also Note: That 99% of the time, you won't need to set init to ``false``. Most cases I saw this option was used, it would have been better to solve it differently. lazySizes works similar like webcomponents there is no explicit initialization needed.

**Comment by JonWallsten** [comment]
Our code is structured in such way the internal order of the files doesn't matter because they all initiate their stuff on document ready. So this is why we have a problem with the auto init method. 
I will illustrate the problem here (with contents from the files), so don't take the tags literally:
```
<script src="vendor/jquery.js"></script>
<script src="otherscripts.js"></script>
<script src="vendor/lazysizes.js">
    ...
    lazySizesConfig = window.lazySizesConfig || {};
	for(prop in lazySizesDefaults){
		if(!(prop in lazySizesConfig)){
			lazySizesConfig[prop] = lazySizesDefaults[prop];
		}
	}
	window.lazySizesConfig = lazySizesConfig;
	setTimeout(function(){
		if(lazySizesConfig.init){
			init();
		}
	});
    ...
</script>
<script src="global.js">
    ...
    //This need to outside of the module to work due to self initiating plugin
    window.lazySizesConfig = window.lazySizesConfig || {};
    window.lazySizesConfig = {
        init : false
    };
    ...
</script>
<script src="modules/.js"></script>
<script src="plugins/.js"></script>
```

So what you do is taking window.lazySizesConfig and store it in scoped lazySizesConfig.
And that's the variable you use then you check lazySizesConfig.init in the setTimeout.

So when I change the window.lazySizesConfig in the file read after lazysizes it's already to late. Since you read that right away. My original point was the the init should be checked inside the timeout, which you have corrected. But as long as you loop through window.lazySizesConfig outside the timeout, the timeout doesn't matter. It will always be the default value, unless I put the script tag for lazysizes.js after all the other tags. Hope you understand better now.

**Comment by aFarkas** [comment]
Yes, but this has nothing to do with the loop inside or outside the loop, but only with the fact, that my reference to ``lazySizesConfig`` is another than yours.

Your code looks like this and will always have trouble:

```js
    window.lazySizesConfig = window.lazySizesConfig || {};
    window.lazySizesConfig = {
        init : false
    };
```

You should write it like this:

```js
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
```

This way we both are referencing the same object and the same init property.

This said I gave you some other (better) options, which are much better for performance. Why don't you to use one of them: https://github.com/aFarkas/lazysizes/issues/60#issuecomment-73359277

**Comment by aFarkas** [comment]
@JonWallsten 
Does this work for you now? I think your error was the wrong configuration mentioned above.

I hope you understand, that it is actually a good thing that lazySizes works as soon as possible, so that images can be loaded while the DOM is progressively parsed. This is a huge advantage, especially over other lazy loader, where you need to initialize them with strong references to the image. 

As I see it, you still can order your scripts how you want. You only should have a specific order for lazySizes and it's configuration. And in case you merge all files into one, you don't need any specific order for lazySizes and even it's plugin and the configuration file. You seem to also do exceptions for other scripts (at least for jQuery).

**Comment by aFarkas** [comment]
@JonWallsten 
Did this help?

**Comment by JonWallsten** [comment]
Sorry for my late response! 
I'm not sure we fully understand each other. 
The flow we using and the way we don things is just not compatible with the way your script works.
It's our unconventional method of hiding elements on top of the images, until the images are loaded, causing this. I will just add the file at the end of the list of includes and put the delayed init outside of our normal flow/scope. Lets close this and accept that 99% of the users is not doing this.
Thank you for your time though! :-)
