### ISSUE TITLE
Youtube lazyload uses sqdefault.jpeg image that now always exists!

### ISSUE THREAD

**Issue by franciurachel** [aFarkas/lazysizes#666]
Hi Alexander,
We have been using lazysizes for years and we love it!
However, more and more often we have issues with video-embed.js loading from youtube the sqdefault.jpeg thumbnail that does not always exist!

I made some research and other images should be always there (for instance the hqdefault)
So, would not be nice to have at least a fallback in case sqdefault gives a 404?

Thanks!

**Comment by aFarkas** [comment]
So what about just always take "hqdefault"?
