### ISSUE TITLE
Problems with Fullpage.js and scrollBar disabled

### ISSUE THREAD

**Issue by mxkeke** [aFarkas/lazysizes#669]
Hello,
I'm using lazysizes with FullPage.js (https://github.com/alvarotrigo/fullPage.js) + "cards 3d extension" (https://alvarotrigo.com/fullPage/extensions/cards.html) but not works.
This is the explanation provided by their technical support:
https://github.com/alvarotrigo/fullPage.js/issues/3658

It seems a problem with the scrollBar option, if it's disabled (scrollBar:false) lazysizes doesn't work.
Is there any workaround?
Thanks.

**Comment by aFarkas** [comment]
I can't tell without seeing a demo / test case where it shows the bug.

**Comment by mxkeke** [comment]
Demo/test case:
http://www.livemotion.eu/test.html
Lazyload images:
Section 2: "cube-3d.png" 
Section 3: "machine-process.png"
Section 4: "workflow.png"
All the above images loading immediately instead to load only when the specific section is opened.


Below another example but with the lazyload system integrated with "FullPage.js" (lazyLoading: true):
http://www.livemotion.eu/test_002.html
The lazy load process works good, every images is load only when the specific section is opened.

**Comment by aFarkas** [comment]
It isn't entirely true that these images aren't lazyloaded. As you can see they are loaded after onload. If you would place an image in section 1 you would see that this image is loaded first and then section 2-4 are loaded. Also in case you have 6+ sections all with images you would see that lazysizes will stop loading those images after it has loaded 4 and then restart loading as soon as one or more has finished.

The problem why it doesn't work as you expect is that all sections are placed at the same position and basically all images are in view.

You can set the option `loadHidden = false` and it should only load the images that are currently in view. If you want to preload the next section you can hook into the fullpage event and add the class `lazypreload` to all images of the next section.
