### ISSUE TITLE
Unveilhooks not respecting delyed init

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#67]
As the title says, the event 'lazybeforeunveil' in unveilhooks is for some reason called to early in the game. The lazysizes init is delayed, but the video is being processed before images on the page. Let me know if you want me to clarify.

Edit: I screwed up. Had the lazysize.js file included to early on this particular page.

**Comment by aFarkas** [comment]
I don't really understand. Is this still a bug?

**Comment by JonWallsten** [comment]
No, you can remove this, if possible. It was all happening for the same reason I posted the other bug. Thanks!
