### ISSUE TITLE
Any breaking changes from 4 to 5?

### ISSUE THREAD

**Issue by chpio** [aFarkas/lazysizes#670]
what are the breaking changes from v4 to v5?  the changelog seem to not mention any breaking changes?!

https://github.com/aFarkas/lazysizes/blob/gh-pages/CHANGELOG.md

**Comment by aFarkas** [comment]
> Do not leak global lazySizesConfig anymore fixes #647

Can break things. In case you changed `lazySizesConfig` dynamically without creating it initially yourself.

**Comment by chpio** [comment]
thx
