### ISSUE TITLE
Optimumx does not seem to work as expected

### ISSUE THREAD

**Issue by dominiklaube** [aFarkas/lazysizes#673]
**Describe the bug**
Optimumx does not reduce srcset data properly. I can reproduce this issue on the demo page and also on my environment.

**To Reproduce**
I have a screen resolution of 1920px x 1080px and a device pixel ratio of 1.
I use Chrome 74

**Steps to reproduce the behavior:**
Go to: http://afarkas.github.io/lazysizes/rias/ --> section optimumx

**What is the expected behavior**
Expected that the srcset content will differ from the data-srcset content of the img element so that the maximum image width gets limited.

**What happened instead**
data-srcset and srcset are exactly the same

`<img src="http://app.resrc.it/S=W300M/O=20,B/http://www.your-site.co/image.jpg" data-optimumx="1.3" data-quality="75" data-sizes="auto" class="lazyautosizes lazyloaded" alt="" data-srcset="http://app.resrc.it/S=W180M/O=75,B/http://www.your-site.co/image.jpg 180w, http://app.resrc.it/S=W360M/O=75,B/http://www.your-site.co/image.jpg 360w, http://app.resrc.it/S=W540M/O=75,B/http://www.your-site.co/image.jpg 540w, http://app.resrc.it/S=W720M/O=75,B/http://www.your-site.co/image.jpg 720w, http://app.resrc.it/S=W900M/O=75,B/http://www.your-site.co/image.jpg 900w, http://app.resrc.it/S=W1080M/O=75,B/http://www.your-site.co/image.jpg 1080w, http://app.resrc.it/S=W1296M/O=75,B/http://www.your-site.co/image.jpg 1296w, http://app.resrc.it/S=W1512M/O=75,B/http://www.your-site.co/image.jpg 1512w, http://app.resrc.it/S=W1728M/O=75,B/http://www.your-site.co/image.jpg 1728w, http://app.resrc.it/S=W1944M/O=75,B/http://www.your-site.co/image.jpg 1944w, http://app.resrc.it/S=W2160M/O=75,B/http://www.your-site.co/image.jpg 2160w, http://app.resrc.it/S=W2376M/O=75,B/http://www.your-site.co/image.jpg 2376w, http://app.resrc.it/S=W2592M/O=75,B/http://www.your-site.co/image.jpg 2592w, http://app.resrc.it/S=W2808M/O=75,B/http://www.your-site.co/image.jpg 2808w, http://app.resrc.it/S=W3024M/O=75,B/http://www.your-site.co/image.jpg 3024w" sizes="545px" srcset="http://app.resrc.it/S=W180M/O=75,B/http://www.your-site.co/image.jpg 180w, http://app.resrc.it/S=W360M/O=75,B/http://www.your-site.co/image.jpg 360w, http://app.resrc.it/S=W540M/O=75,B/http://www.your-site.co/image.jpg 540w, http://app.resrc.it/S=W720M/O=75,B/http://www.your-site.co/image.jpg 720w, http://app.resrc.it/S=W900M/O=75,B/http://www.your-site.co/image.jpg 900w, http://app.resrc.it/S=W1080M/O=75,B/http://www.your-site.co/image.jpg 1080w, http://app.resrc.it/S=W1296M/O=75,B/http://www.your-site.co/image.jpg 1296w, http://app.resrc.it/S=W1512M/O=75,B/http://www.your-site.co/image.jpg 1512w, http://app.resrc.it/S=W1728M/O=75,B/http://www.your-site.co/image.jpg 1728w, http://app.resrc.it/S=W1944M/O=75,B/http://www.your-site.co/image.jpg 1944w, http://app.resrc.it/S=W2160M/O=75,B/http://www.your-site.co/image.jpg 2160w, http://app.resrc.it/S=W2376M/O=75,B/http://www.your-site.co/image.jpg 2376w, http://app.resrc.it/S=W2592M/O=75,B/http://www.your-site.co/image.jpg 2592w, http://app.resrc.it/S=W2808M/O=75,B/http://www.your-site.co/image.jpg 2808w, http://app.resrc.it/S=W3024M/O=75,B/http://www.your-site.co/image.jpg 3024w">`

Do i have a mistake? Or should the generated srcset looks like the following because the sizes attribute is 545px?
`srcset="http://app.resrc.it/S=W180M/O=75,B/http://www.your-site.co/image.jpg 180w, http://app.resrc.it/S=W360M/O=75,B/http://www.your-site.co/image.jpg 360w, http://app.resrc.it/S=W540M/O=75,B/http://www.your-site.co/image.jpg 540w, http://app.resrc.it/S=W720M/O=75,B/http://www.your-site.co/image.jpg 720w`

**Comment by aFarkas** [comment]
This is the expected behavior. The plugin only kicks in if your dpr is bigger than the `data-optimumx` value. If you want to optimize all images you can use the `auto` value which will set `0.99` for devices with a dpr of `1` and around `1.6` for devices with a dpr of `2`.

In case you set the optimumx to `1` it should also remove the `720` candidate.

Please close if this helps.

**Comment by dominiklaube** [comment]
Thanks a lot Alexander!
