### ISSUE TITLE
Jetpack's tiled galleries don't display properly due to the plugin.

### ISSUE THREAD

**Issue by Marsolav** [aFarkas/lazysizes#674]
When using Jetpack's tiled galleries, more specifically a "tiled-gallery of type-rectangular", the lazyloader seems to alter some elements of the grid, causing some pictures to be distorted, and random blank spaces to appear. Activating the "aspect ratio plugin" does improve the result a lot, but it removes vertical lines (left-right margins) between pictures. 

Excluding the CSS class would be a satisfactory alternative, but it does not seem to work with parent elements (div.tiled-gallery div.type-rectangular) and that seems to me the only way to do this.

Briefly, the expected behavior would be that the Jetpack galleries remain intact.
However, with the "aspect ratio plugin" on, some margins disappear.
Excluding the class does not seem possible.

Tested in Chrome 75.0.3770.80 and Safari 12.0.3

**Comment by aFarkas** [comment]
sounds like a CSS issue.
