### ISSUE TITLE
Issues on IE/Edge

### ISSUE THREAD

**Issue by mjcampagna** [aFarkas/lazysizes#676]
Hello,

I'm using lazysizes in non-responsive mode: 

```html
<img data-src="image.jpg" class="lazyload" />
```

And images are failing to load in IE and Edge. I've tried loading ls.respimg.min.js before lazysizes, but not having any luck.

What am I missing?

Thanks!

**Comment by boynet** [comment]
well the demo does work in edge and ie : http://afarkas.github.io/lazysizes/#examples

**Comment by aFarkas** [comment]
You don't need to include `ls.respimg` then. But there is a reason why I have generated a [bug report template](https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md). And honestly I really have problems to answer bug reports/support tickets that are basically just saying "doesn't work in my case".

You can re-open if you can provide information to make it reproducible.

**Comment by mjcampagna** [comment]
Hi aFarkas,

Thanks for the fast reply. Sorry for the barebones post, but it was late at night, and I was quite tired. Approaching the problem today with a well-rested head, turns out the problem was not lazySizes at all. I was loading the script conditionally and dynamically, using async/await, and so the problem was the lack of browser support for async/await. That's what I get for coding late at night.

I really do appreciate the reply, though. Great support! And thank you for lazySizes. It's great!

Cheers,
Matt
