### ISSUE TITLE
Images do not lazyload until mouse is moved

### ISSUE THREAD

**Issue by PascCl** [aFarkas/lazysizes#677]
**Describe the bug**
You can see the bug here: https://staging.flyawaytv.be/
When you scroll all the way to the bottom of the frontpage, you see images blocks loading.
If you then refresh the page (might need a cache clear) and you scroll down to where the image is supposed to be, the image does not load.
If you take no further actions (don't touch mouse or keyboard) the image never loads, once you move the mouse after a few seconds the image instantly loads.

You can also press the end button to scroll to the bottom of the page and the image will not load until you take another action.

**What is the expected behavior**
Images should be loaded when reaching that point of the page or should load much faster and without requiring extra action.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Issue is most obvious in the latest version of Chrome (on Windows 10)
But also there in the latest version of Firefox, but acting a bit different.

**Comment by aFarkas** [comment]
wow interesting bug. haven't yet looked into it but I can reproduce. Might take a little bit because I have quite a lot on my plate.

**Comment by aFarkas** [comment]
@PascCl 
Ok, long story short you have wrong markup. Please remove the lazyload class from your `source` elements. Only the `img` should get the `lazyload` class.

**Comment by PascCl** [comment]
Thanks!
Seems to work.
