### ISSUE TITLE
Image not loading in Chrome on first load

### ISSUE THREAD

**Issue by vishy93** [aFarkas/lazysizes#679]
I am using this on my site in my local/dev version and when I open in chrome the image(s) do not load until I press `cmd+r`. Also, not working when I disable cache. 

I have replicated from my other site where it works exactly. 

Would anyone know why this is? inspecting the elements class is still lazy not lazyloaded. 

`window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.lazyClass = 'lazy';
window.lazySizesConfig.loadMode = 1;
window.lazySizesConfig.expand = 0;
window.lazySizesConfig.expFactor = 0.01;
window.lazySizesConfig.hFac = -0.4;`

**Comment by aFarkas** [comment]
In general pretty crazy options.

For `expand` and `hFac` only positive numbers above 0 are useable. For `expFactor` only numbers above `1` is possible.

Maybe check what reasonable values are?

**Comment by vishy93** [comment]
@aFarkas Same options I am running on the other site, works splendidly there.

**Comment by aFarkas** [comment]
This might be true, but they are not logical. For example you say. If the browser network is idline lazysizes should expand the download area by `0.01`. Which means if the browser has a lot important images to download lazysizes should expand the search area by 100. Simply doesn't make any sense.

**Comment by vishy93** [comment]
> This might be true, but they are not logical. For example you say. If the browser network is idline lazysizes should expand the download area by `0.01`. Which means if the browser has a lot important images to download lazysizes should expand the search area by 100. Simply doesn't make any sense.

I have amended the settings accordingly to be respectively 1.5 and 0.4. Unfortunately, the images are still not loading.

**Comment by aFarkas** [comment]
I can not reproduce your issue. Please follow the steps described in the bug report template and then reopen.

**Comment by vishy93** [comment]
I shall do as soon as I get a chance
