### ISSUE TITLE
Smaller data encoded GIF

### ISSUE THREAD

**Issue by yoyurec** [aFarkas/lazysizes#68]
In all code/documentation you are using transparent GIF code (53 bytes): 
`data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==`

But here is smaller one (37 bytes! correct & transparent, b'cose there are a lot of smaller, but not stable versions):
`data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=`

:sunglasses: 

Article: http://probablyprogramming.com/2009/03/15/the-tiniest-gif-ever
Image encoder: http://base64css.com/

**Comment by aFarkas** [comment]
Thx very helpful

**Comment by yoyurec** [comment]
hm... made a test with IE11/10/9, iPhone6 - looks like image from article not so good (black color only or broken image icon)

*1-color GIF – 35 bytes* (or * transparent GIF pixel – 43 bytes* if you need it) from http://proger.i-forge.net/The_smallest_transparent_pixel/eBQ looks more correct!
