### ISSUE TITLE
Conditionally change the output of data-sizes

### ISSUE THREAD

**Issue by tyssen** [aFarkas/lazysizes#684]
I'm working on a site that uses Cloudinary and the RIAS plugin and for the most part it works fine.

I have my config like this:

	window.lazySizesConfig = window.lazySizesConfig || {};
	window.lazySizesConfig.rias = window.lazySizesConfig.rias || {
	prefix: 'https://res.cloudinary.com/user/image/fetch/q_auto:eco,f_auto,c_scale/w_{width}/',
	absUrl: true
	}

Most of the images I want to be full width of the column and they're fine. But some of the source images aren't that wide and I don't want them to be full width. 

But LazySizes will set the same `sizes` value on _all_ of the images which is equal to the width of the column which means that some get upscaled and stretched.

Is there an attribute I can add to the `image` tags with the smaller images which can then be passed to the config which will output a different `sizes` value for those images?

I thought I could maybe use the example you used for `data-format` which does output different values in the `srcset` but the `sizes` still equals the width of the column.

**Comment by aFarkas** [comment]
The sizes calculation is described [here](https://github.com/aFarkas/lazysizes#user-content-sizes-calculation). So you are not using CSS to style the width of your images. You can always hook into the `lazybeforesizes` event to change the output. You could for example by utilizing `max-width`.

**Comment by tyssen** [comment]
Thanks. In my case, conditionally outputting `style="width:XXpx"` if the image width is less than the max container width has done the trick. 👍
