### ISSUE TITLE
Behavior and configuring

### ISSUE THREAD

**Issue by xeontem** [aFarkas/lazysizes#688]
Hello, trying to use this library. But currently can't see how I can configure event when start to load an image. For example, I want to load an image when <img> will be 400px below the current viewport. How I can configure it?

Another question. When I scroll down, I insert dynamically elements to the DOM. Like feed on Instagram. In this case, do this library understand that DOM has been changed and a new portion of images should be loaded whenever they will be closer than 400px to the current viewport?

**Comment by aFarkas** [comment]
> For example, I want to load an image when  will be 400px below the current viewport. How I can configure it?

Please read the documentation for this. lazySizes uses a more dynamic approach. The options you might want to change are `expand` and/or `expFactor`. lazySizes loads normally more than 400 pixel but the big difference to other lazyloaders is that it only loads does images if there are no other in view images currently loading. 

> In this case, do this library understand that DOM has been changed and a new portion of images should be loaded whenever they will be closer than 400px to the current viewport?

Of course
