### ISSUE TITLE
Lazysizes with RICG approach doens't work

### ISSUE THREAD

**Issue by adriancervoni** [aFarkas/lazysizes#69]
First of all, great plugin and thanks.

I think it will be useful if we could use a native responsive approach instead of with a polyfill option. Now, if I try to set a fallback for a browser that don't read srcset image without an additional load it doesn't work:

    <img
	data-src="assets/img/img-m.jpg"
	data-srcset="assets/img/img-b.jpg 1500w, assets/img/img-m.jpg 1000w, assets/img/img-s.jpg 500w"
	alt=""
	class="lazyload">

It should render:

    <img
	src="assets/img/img-m.jpg"
	srcset="assets/img/img-b.jpg 1500w, assets/img/img-m.jpg 1000w, assets/img/img-s.jpg 500w"
	alt=""
	class="lazyload">

Any idea on how to implement it? Maybe I missed something?

**Comment by aFarkas** [comment]
Actually, I also think this is useful and I have a test, that makes sure, that this markup is rendered, if

a) the browser does not support responsive images
and
b) no polyfill is detected

So are you sure, that there is no data-src -> src transformation. Note: You should not check in Chrome!

**Comment by adriancervoni** [comment]
Yep @aFarkas, it works, my fault, I saw the img break icon while loading and I supposed that it doesn't work, I used data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== in the src and it works all fine now, thanks!
