### ISSUE TITLE
Lazysizes inside svg foreignobject

### ISSUE THREAD

**Issue by marcohanke** [aFarkas/lazysizes#691]
Hey there,
i'd like to have an responsive Image which is cropped with an svg path. So i put Lazysizes inside an SVG ForeignObject and this wont work. It loads the first entry of data-srcset and ignores the rest.

``` 
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 88" preserveAspectRatio="xMidYMin slice" style="width: 100%; padding-bottom: 88%; height: 1px; overflow: visible; box-sizing: content-box;">
    <switch>
        <foreignObject x="0" y="0" height="100%" width="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="clip-path: url(#clippath);">
            <img 
            src="/mediatypes/300hexagon/'.$file.'"
            data-sizes="auto"
            data-srcset="/mediatypes/300hexagon/'.$file.' 300w,
            /mediatypes/600hexagon/'.$file.' 600w,
            /mediatypes/900hexagon/'.$file.' 900w,
            /mediatypes/1200hexagon/'.$file.' 1200w
            "
            alt="'.$mediatitle.'"
            class="lazyload blur-up img-fluid"

            / >
        </foreignObject>
        <image class="fallback-ie" xlink:href="/mediatypes/300hexagon/'.$file.'" alt="'.$mediatitle.'" x="0" y="0" height="100%" width="100%" style="clip-path: url(#clippath);">
        </image>
    </switch>
</svg>
```

**Comment by aFarkas** [comment]
At could you generate a test case on jsfiddle please? And check what the rendered `sizes` attribute says.

**Comment by marcohanke** [comment]
size atribut is allwasy 100px.
https://jsfiddle.net/36pixel/xmv5Lnfk/10/

**Comment by aFarkas** [comment]
@marcohanke 

I'm not sure wether I want to support this by default. Need to think about this. You can solve this by hooking into `lazybeforesizes` event:

```js
document.addEventListener('lazybeforesizes', ({target, detail}) => {
  detail.width = target.getBoundingClientRect().width;
});
```

Please close if this helps.

**Comment by marcohanke** [comment]
Awesome support mate, this will do the trick, thanks!
And yes, i think it may be to special to support it by default.

**Comment by aFarkas** [comment]
> This will (nearly) do the trick. When i resize the window, size is calculated. But onload the size is still 100px. Is it possible to get the real size onload?

The event I gave you is fired always. I assume you are binding it too late. Make sure that it is included in the same package as lazysizes and make sure to execute this function immediately. This means don't put in jquery ready, don't put it in angular ngOnInit or what ever just simply execute it immediately.

**Comment by marcohanke** [comment]
Sorry, my fault.
By the way: Awesome support, big thanks !!!
