### ISSUE TITLE
Images not change

### ISSUE THREAD

**Issue by henzan02** [aFarkas/lazysizes#692]
Hi, I have read the documentation, but I'm just wondering. How come it doesn't works for me.. :( 

I need to change the image in different devices. Is it possible? 
For example : 

On desktop : yellow-Image-hd.jpg
On Mobile max-width 480px : red-Image-480.jpg
On Mobile max-width 320px : blue-Image-320.jpg

I have tested using bootstrap 4, but it doesn't works well on chrome (Inspect element & change responsive device mode)
Here's my code ; 

```
<img alt="image desc" data-sizes="auto"

data-srcset="images/katalog/blue-image-320.jpg 320,
images/katalog/red-image-480.jpg 480w,
images/katalog/image-hd.jpg 960w"

data-src="images/katalog/yellow-image-hd.jpg"

src="images/katalog/low-image.jpg"
class="lazyload img-fluid" />

<script src="http://afarkas.github.io/lazysizes/lazysizes.min.js" async=""></script>
```

Thanks

**Comment by aFarkas** [comment]
Please provide a test case as suggested by the issue template. Some markup doesn't solve your problem because it is working for me.

**Comment by aFarkas** [comment]
Just see your additional request. You want to use art direction. For this use case you have to use the picture element with three separate `source` elements.

Please close if this helps.

**Comment by henzan02** [comment]
Sorry for late response, here's my codepen : 
https://codepen.io/pen/mdbEYGJ

please help.. Thanks

**Comment by aFarkas** [comment]
Yes, you have to use the `picture` and `source` elements. `srcset` is only for one image in different sizes no for different images. You can not control which image is choosen. Some devices have for example 1x, 2x or 3x displays.
