### ISSUE TITLE
Using lazySizes with a <video> element

### ISSUE THREAD

**Issue by jonnymaceachern** [aFarkas/lazysizes#693]
Does this work with the `<video>` element?

Using `data-src` within the `source` element did not work for me:

```
<video autoplay="autoplay" loop="loop" muted>
    <source data-src="/video.mp4" type="video/mp4">
    <source data-src="/video.webm" type="video/webm">
</video>
```

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/search?q=<video&unscoped_q=<video
