### ISSUE TITLE
Increase/configure time to check cache in blurup plugin

### ISSUE THREAD

**Issue by janein** [aFarkas/lazysizes#695]
I would like to have a increase the time which is used to check if the image is already in the cache. At the moment there are 20ms hardcoded. This works fine on the demo page. But as our site is quite huge with a lot of javascript/css being parsed, the image cannot always be processed in this short time.

It would be nice to have this configurable.

https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/blur-up/ls.blur-up.js#L102

**Comment by aFarkas** [comment]
I'm currently on holiday. Will check in a a week.

**Comment by janein** [comment]
Any updates on this?
