### ISSUE TITLE
Lazy load image from css class?

### ISSUE THREAD

**Issue by PrestaShark** [aFarkas/lazysizes#698]
Hi. It is possible?
Any ideas or examples of this kind of script usage? 

Thanks!

**Comment by aFarkas** [comment]
I don't understand what you mean please create an example or something.

**Comment by PrestaShark** [comment]
Hi. Sorry.
I mean it is possible to lazy load image from css class like

.lazy_background {background:url(my_lazyloaded_background.jpg)}

**Comment by aFarkas** [comment]
Yes of course:

```html
<style>
.lazy_background {
/* your general css */
}
.lazy_background.lazyloaded {background:url(my_lazyloaded_background.jpg)}
</style>

<div class="lazyload lazy_background"></div>
```
