### ISSUE TITLE
[Question] LQIP in <picture> tag - best method?

### ISSUE THREAD

**Issue by willstocks** [aFarkas/lazysizes#699]
Hello!
This is more of a question of best practice for using an LQIP within a `<picture></picture>` element.

At the moment, my "standard" lazysizes markup for an image is:

```html
<img 
  class=" lazyload blur-up" 
  src="lqip.jpg"
  data-srcset="normal.jpg, retina.jpg 2x" 
  alt="Swapping a mouse for a graphics tablet" 
>
```

Now, I've just implemented a `<picture>` element on my site, which _currently_ has the following markup:

```html
<picture class="sidebar-ad lazyload blur-up">
 <source 
    type="image/webp" 
    media="(max-width: 320px)"
    srcset="Mobile-Small.webp"
  >
 <source 
    type="image/jpeg" 
    media="(max-width: 320px)" 
    srcset="Mobile-Small.jpg"
  >
 <source 
    type="image/webp"
    media="(max-width: 770px)" 
    srcset="Mobile-Large.webp"
  >
 <source 
    type="image/jpeg" 
    media="(max-width: 770px)" 
    srcset="Mobile-Large.jpg"
  >
 <source 
    type="image/webp" 
    media="(min-width: 771px)" 
    srcset="Non-Mobile.webp"
  >
 <source 
    type="image/jpeg" 
    media="(min-width: 771px)" 
    srcset="Non-Mobile.jpg"
  >
 <img 
    class="sidebar-ad lazyload" 
    src="fallback-lqip.jpg"
    data-srcset="fallback.jpg" 
    alt="Fallback example!"
  >
</picture>
```

What is the best way to LQIP this element (all of the `source`'s as a whole)? Would it be to declare a `src` within each `source` or does it make use of the existing `src` in the `img`?

**Comment by aFarkas** [comment]
You would need to create a lquip for every `source`

**Comment by willstocks** [comment]
Thanks @aFarkas! 

So, just tack it on to each item as follows `<source src="lqip.jpg" srcset="hq.jpg">` and the rest is taken care of? Or do I need to migrate the `source`'s to `data-srcset`?

**Comment by LeoSeyers** [comment]
> You would need to create a lquip for every `source`

Hello @aFarkas, is this recommended practice? Most of my implementations looks like @willstocks. I just used the `img` fallback and its `src` attribute for my LQIP image. 

I've tested it and it works fine so what's the difference?

**Comment by aFarkas** [comment]
@willstocks 
The pattern would look something like this:

```
<source srcset="lqip.jpg" data-srcset="hq.jpg" />
```

@LeoSeyers 
At the end there is no "must do pattern". It really depends on how you use the `picture` element. The `picture` element should be used for art direction in the first place. In those cases the image that you are using for mobile might be quite distinct from the image that you are using for desktop and in those cases you would need to provide two different lqip images.

**Comment by dhymik** [comment]
@aFarkas thank you this was very helpful to me, now I have webp lqip images implemented without headache.
