### ISSUE TITLE
Is it possible to use it with Dynamic images from Ajax request?

### ISSUE THREAD

**Issue by clarklight** [aFarkas/lazysizes#70]
I am not sure if this works with Ajax requests images, i cant manage to get it working yet. Wondering if you can give me a heads up on how to get it working, or if it would be able to perform what i need.

I am trying to loop through a list of images pulled from Ajax request from my server. But it is not working at all. 

   for(var j = 0; j<images.length; j++){
   var image3=  "http://test.info/test/"+images[0];
        console.log(image3);
  var image2= <div class='swiper-slide'><img class='lazyload'  data-src='+ image3 + ' id='viewer'/><div class=coll2></div></div>"
  }

**Comment by aFarkas** [comment]
This should work, can you add a fiddle?

**Comment by clarklight** [comment]
Yup, i will try to add a fiddle in a bit. But when i do data-src= 'image' it doesnt seem to work, it will only load the image when its src=. Not sure why

**Comment by aFarkas** [comment]
The image should load, if

a) there is a ``lazyload`` class
b) it has a ``data-src``
c) it is in viewport and is visible.

**Comment by aFarkas** [comment]
Please re-open, if you still have problems. 

In case you have. A testcase demonstrating your problem would be great. You can for example use this tool: http://plnkr.co/
