### ISSUE TITLE
Images loading multiple times

### ISSUE THREAD

**Issue by edturnuh** [aFarkas/lazysizes#703]
**Describe the bug**
Hey, I have a page that is loading bg images multiple times... sometimes it requests an image 2 or 3 times. I'm using bgset and unveilhooks. Weird!  I tried turning off OwlCarousel plugin to try and isolate the issue (Swiper.js carousel was the reason for someone else here) but the issue persisted.

**To Reproduce**
Issue is available on [https://nativebasketball.myshopify.com/](https://nativebasketball.myshopify.com/)

**Steps to reproduce the behavior:**
Just refresh the page and monitor network traffic as you scroll down and the images get requested. 

**What is the expected behavior**
Each image should only load once

**What happened instead**
Some images get loaded two or three times. It seems to change every time I refresh.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Desktop, chrome.

<img width="932" alt="Screenshot 2019-09-23 at 00 15 20" src="https://user-images.githubusercontent.com/6020808/65395790-7d177400-dd97-11e9-989a-89bb06703254.png">

**Comment by aFarkas** [comment]
@edturnuh 

Thanks for using the issue template. Unfortunately I need a password to see this page.

Normally this issue happens, if you have disabled your cache clientside or serverside. Please check this and close the issue if this helps. If this isn't the case I will need the password.

**Comment by edturnuh** [comment]
Disabling client-side cache worked!  Perfect 😄

Thanks a lot, and keep up the good work!

________________________________
