### ISSUE TITLE
Is it possible to combine parentfit with rias {width} and {height}?

### ISSUE THREAD

**Issue by dominiklaube** [aFarkas/lazysizes#704]
I have a dynamic aspect ratio and therefore want to combine parentfit with rias. Example:

`<div style="height: 300px;"><img data-src="http://placehold.it/{width}x{height}" data-sizes="auto" data-parent-fit="cover" class="lazyload" /></div>`

See pen: https://codepen.io/dominiklaube/pen/zYOevpX

My expectation would be that the {width} and the {height} will be replaced with calculated values. In reality only the {width} gets replace correctly, {height} becomes empty. Is that even possible?

**Comment by aFarkas** [comment]
Sorry for the delay I was on holiday. In this specific case you don't even need the parent-fit plugin. The parent-fit plugin is needed to adjust the `sizes` calculation for the situation where the physical apsect ratio of the image might not match the dispayed aspect ratio of your image. But in case of rias you can always provide the right apsect ratio.

But you have to provide the aspect ratio so lazysizes can calculate the right height to replace your placeholer:

```js
document.addEventListener('lazyriasmodifyoptions', function(e) {
    e.detail.aspectratio = e.target.offsetWidth / e.target.offsetHeight;
});
```

**Comment by Baedda** [comment]
Hello @aFarkas,
I think I have the same issue that @dominiklaube has faced.

I have a `<header>` element that has an `<img>` inside. The width of the image is 100% the viewport width and the height is 100% the height of the `<header>`. But there is also text on top of the image, that is responsible for the height of the `<header>`. This leads to the problem that the width **and** the height are variable.

Therefore I could use your provided code to dynamically calculate the aspectratio. But on window resize the width and the height of `<header>` do change. What means that the aspectratio also changes.

So what I need is a way to recalculate the aspectratio on resize. 

I hope this was understandable. Could you help me out?

Chris
