### ISSUE TITLE
All low quality images loading

### ISSUE THREAD

**Issue by azurehari** [aFarkas/lazysizes#707]
Hi sir,
I have 'view all products section' in my website. Almost, i have around 5000 product images in low quality and high quality respectively. With help of lazysizes, I have written in my code like,

src - low quality image
data-src - original image

I have 5000 low quality images and 5000 original images..
when i load the view all product section, After loading all of the low quality images only, the page is opening. but the original images loading fine like intersection observer. But why initially all low quality image is loading?.. It takes more than 2 mins.. how do i restrict that?

**Comment by aFarkas** [comment]
You can use this plugin if you like:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/blur-up
