### ISSUE TITLE
Serve different images depending on the resolution

### ISSUE THREAD

**Issue by VykintasZaboras** [aFarkas/lazysizes#71]
Hello,

First, Nice plugin!

But is it possible to alternate images depending on the resolution? For example my markup is:
```
<img src="first-image.png" data-srcset="second-image.jpg 768w" alt="" class="lazy"/>
```
And the "first-image.png" would be loaded only if the width is over 768 and the "second-image.jpg" if it's less. It works as expected when refreshing the page, but it doesn't if you start off with a higher resolution and then go below 768. The "first-image.png" is loaded and when resizing the window, it doesn't change to "second-image.jpg".

Any help solving this would be appreciated.

**Comment by aFarkas** [comment]
Yes, this is possible. This is implemented over the HTML5 ``srcset`` and ``picture`` implementation.

In general you should treat the ``src`` attribute as a "pure" fallback mechanism. This means, you should either leave ``src`` out entirely (no fallback) or if you want to see the image in the ``src`` you need to repeat it in your ``srcset``/``data-srcset`` attribute.

Whether you should only use ``srcset`` or you should use the ``picture`` syntax, depends on what you want to achieve.

If all images are exactly the same image and only differ in size/resolution you should choose ``srcset``. In case your images are different depending on the layout of your page (for example a different apsect ratio etc.) you should choose ``picture``.

From your expectation above I would think you need ``picture``.

Also note: 
1. That with ``srcset`` alone Chrome chooses also images that are in cache (so you need to clear your cache, to test it).
2. That with a srcset in combination with width descriptors you should use explicitly the ``sizes`` attribute. lazySizes gives you the ``data-sizes="auto"`` feature for that.

**Example for pure ``srcset`` without a ``src``:**

```html
<img data-srcset="second-image.jpg 768w, first-image.jpg 1024w" data-sizes="auto" alt="" class="lazy" />
```

**Example for pure ``srcset`` with a ``src``:**

```html
<img src="first-image.jpg" data-srcset="second-image.jpg 768w, first-image.jpg 1024w" data-sizes="auto" alt="" class="lazy" />
```

**An example using the ``picture`` syntax without ``src``:**

```html
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source data-srcset="second-image.jpg" media="(max-width: 768px)"  />
        <source data-srcset="first-image.jpg"  />
    <!--[if IE 9]></video><![endif]-->
    <img alt="" class="lazy" />
</picture>
```

**An example using the ``picture`` syntax with ``src``:**

```html
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source data-srcset="second-image.jpg" media="(max-width: 768px)"  />
        <source data-srcset="first-image.jpg"  />
    <!--[if IE 9]></video><![endif]-->
    <img src="second-image.jpg" alt="" class="lazy" />
</picture>
```

Did this help?

**Comment by VykintasZaboras** [comment]
Thanks for the response, but i can't use "sizes" attribute or the "picture" element, and it needs to have a src attribute, otherwise the markup is not valid. 

the script does what i want to achieve when you start off with a small resolution and go up. But it doesn't when you start with the larger resolution. Basically the script just ignores the "data-srcset="second-image.jpg 768w"" attribute when you start with a higher resolution.

**Comment by aFarkas** [comment]
Ok, the script exactly does what the HTML5 spec says it should do. Why can't you use picture or sizes? The ``picture`` element is exactly what you need. lazySizes turns any structure described above into a valid HTML structure and of course you can alter  all examples above slightly to serve formal valid HTML.

The following markup is valid and should do exactly what you want/need:
```html
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="second-image.jpg" media="(max-width: 768px)"  />
        <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="first-image.jpg"  />
    <!--[if IE 9]></video><![endif]-->
    <img alt="" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" />
</picture>
```

**Comment by VykintasZaboras** [comment]
"Sizes" attribute resizes the image, which is not what i want. 
It'll try the picture element, but the reason i avoid HTML5 is that the site needs to support IE8 :sob:

**Comment by aFarkas** [comment]
Oh, I wouldn't recommend lazySizes then.
