### ISSUE TITLE
Is this supposed to support video tags?

### ISSUE THREAD

**Issue by Jorenm** [aFarkas/lazysizes#712]
When I put data-src and the lazyload class on a video tag it populates the src attribute, and adds the lazyloading class, but never adds the lazyloaded class.

Not sure if this is a bug or if I'm trying to do something unsupported.

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks

**Comment by Jorenm** [comment]
That looks like it only works for posters, not for the video itself? Is this supported?

<video data-src="video.mp4" class="lazyload">
	Your browser does not support the video tag.
</video>

**Comment by aFarkas** [comment]
@Jorenm 

RTFM or look in the code your markup is wrong:

```html
<video src="video.mp4" class="lazyload" preload="none">
	Your browser does not support the video tag.
</video>
```
