### ISSUE TITLE
Images get loaded even when not in view using IntersectionObserver variant

### ISSUE THREAD

**Issue by SebastianZ** [aFarkas/lazysizes#715]
**Describe the bug**
Using lazysizes-intersection.js images outside the viewport are loaded and the options for restricting the viewport (`loadMode`, `expand`, and `expFactor`) don't work.
On https://www.gamestar.de images outside the viewport are loaded. It is expected that no images outside it are preloaded. The page uses lazysizes-intersection.js, i.e. Intersection Observers.

**To Reproduce**
See https://www.gamestar.de

**Steps to reproduce the behavior:**
1. Go to https://www.gamestar.de
2. Shrink the viewport until no images are visible
3. Reload the page
4. Open the browser developer tools and check the network requests

**What is the expected behavior**
Images marked with the `lazyload` class should not be loaded at all.

**What happened instead**
Images up to a third of the page are already loaded.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Firefox 70.0, Chrome 78, Windows 10

As far as I can tell, the code at https://github.com/aFarkas/lazysizes/blob/7a7f5d9ff60f8983def778458f1b9289a625c723/src/lazysizes-intersection.js#L351 is missing the check whether the element is intersecting like it's done in https://github.com/aFarkas/lazysizes/blob/7a7f5d9ff60f8983def778458f1b9289a625c723/src/lazysizes-intersection.js#L338-L340.

Having said that, this should probably be controlled via the `loadMode` option, though looking at the code it is not implemented in the Intersection Observer variant yet.

Sebastian

**Comment by aFarkas** [comment]
@SebastianZ 
Sorry for taking so long to answer. As it seems to me everything is working as expected. The `expand` is set to `400` not `0` (btw. it doesn't make too much sense to set it to `0`). As I can see the images that are 400 outside of the viewport are loaded and the images that are farer away are loaded. So it is working properly.

About `loadMode` yeah IO has some missing features because of the nature of IO.

Please re-open if you still think it is an issue and you are sure that you have set expand to `0` (But to be honest you should not).

**Comment by SebastianZ** [comment]
Hi @aFarkas, it took me much longer to come back to this due to other priorities.

I've tried different values for `expand` like `100` and `200` now and don't see any difference in behavior. On initial load all images down to half the page are loaded, independently of how high the viewport is.

Some more precise steps:

1. Go to https://www.gamestar.de (still has the default value of `400` for `expand`)
2. Open the browser developer tools and check the network requests
3. Shrink the viewport until no images are visible (i.e. to a height of ~200px)
4. Reload the page without caching (e.g. via <kbd>Ctrl</kbd>+<kbd>F5</kbd>
5. Go offline (e.g. in Firefox via main menu > *Web Developer* > *Work Offline*  or in Chrome in the DevTools via *Network* > *Throttling* > *Offline*)
6. Scroll down or resize the window again

=> All images in the area of ~3000px outside the viewport are loaded independently of the value set for `expand`. Due to the `expand` value of `400` it is expected that only elements within the first 600px (200px of the viewport plus the 400px of `expand`) are loaded on page load.

So am I missing something? How can I achieve that only the images outside a specific threshold outside the viewport are loaded on page load?

Sebastian
