### ISSUE TITLE
Lazyload image in SVG

### ISSUE THREAD

**Issue by firstchair** [aFarkas/lazysizes#716]
Hi,

I'm tryig to lazyload an <image>tag inside an SVG element:
`                        <svg class="column__blob column__blob--image" viewBox="0 0 640 369" xmlns="http://www.w3.org/2000/svg">
                            <defs>
                                <mask id="blob" maskUnits="userSpaceOnUse" x="0" y="0">
                                    <path fill="white" d="{{ path }}"/>
                                </mask>
                            </defs>
                            <image class="column__blob column__blob--image lazyload" width="100%" xlink:href="{{ TimberImage(post.image)|resize(10, 10)|dataUri }}" data-src="{{ TimberImage(post.image)|resize(800, 600)|tojpg }}" mask="url(#blob)"/> 
                        </svg>`

Could somebody give me some advise? Its not working...

**Comment by aFarkas** [comment]
You have to write your own transformation rule for this. Please check the manual (hint: `lazybeforeunveil`)
