### ISSUE TITLE
IE11, data-sizes and vw based units

### ISSUE THREAD

**Issue by caillou** [aFarkas/lazysizes#719]
**`vw` based units in the a `data-sizes` attribute are ignored in IE11.**

**To Reproduce:**

Here is a demo: https://jsfiddle.net/25cjfgbL/2/

While this demo does not make a lot of sense, it is the best way to reproduce the Bug.

**What is the expected behavior**

In IE11 I would expect both images to load the `20x20` source.

**Comment by aFarkas** [comment]
This is documented in the [respimg polyfill plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg):

>> If `data-srcset` with width descriptors (w descriptor) are used either the `data-sizes="auto"` feature has to be used or the `sizes` value has to consist of just one source size value with the CSS `px` unit.
