### ISSUE TITLE
Any way to programmatically load all images

### ISSUE THREAD

**Issue by AdnanCukur** [aFarkas/lazysizes#721]
I am having some issues with lazysizes in UIWebview, and I want to immediately load all images if we detect the device is ios.

currently we do this

`if(IsIOS()) lazySizesConfig.loadMode = 3`

but its not enough,  I need to load all images immediately.

**Comment by aFarkas** [comment]
@AdnanCukur 

You have two options:

1. First set `preloadAfterLoad` to `true`
2. Implement a new method called `lazySizes.prematureUnveil`

```js
import lazySizes from 'lazysizes';

if (isIOS()) {
  lazySizes.prematureUnveil = () => true;
}
```

Please reopen if this doesn't help.
