### ISSUE TITLE
Lazysises does not  do lazyload to images.

### ISSUE THREAD

**Issue by arlangalvez** [aFarkas/lazysizes#728]
Hi all. I migrate my site from vuej to vanilla js because of google crawling results issues, but now images are not doing lazyloading. they are loading even if they are not visible, so the performance impact is high even the viewport is the minimum, all the images comes to life.
how can I solve this?
![image](https://user-images.githubusercontent.com/55986072/70813144-05098a80-1d97-11ea-94f8-bef047250ad0.png)
many thanks.

**Comment by JohnAllen** [comment]
What's your website? I can maybe help but would need to look at it.
