### ISSUE TITLE
auto-sizing with wp-block-image broken

### ISSUE THREAD

**Issue by nosilver4u** [aFarkas/lazysizes#729]
Two issues we're seeing with the automatic sizes calculation:

1. When the page loads initially, such images seem to have the correct dimensions, but as soon as the image actually gets lazy-loaded, the size is much smaller than it ought to be.
2. When resizing the window, especially when you make it very small, the image(s) get smaller (naturally), but when you make the window larger, the image size is stuck to the smallest size that it was.

To Reproduce:
I can reliably reproduce #1 on this page: https://www.geeknative.com/69955/these-are-the-best-geeky-reads-of-2019/
1. Open the Chrome dev tools
2. Enable mobile mode/preview and choose the Responsive preset
3. Make sure the width is over 650px and the dpr is 2 or higher
4. refresh
The first bar-chart image (the one with 4 bars) should be approximately full-width, with some padding/margins. Instead, the image is very small, around 180x110 (smaller yet if dpr is 3).

To reproduce the second issue, simply decrease the width of the viewport, and you'll see the image get very very tiny.
Even without mobile mode and a dpr of 1, making the window smaller seems to be a "one-way" operation on the images. When you go back to increase the window size, the images remain the same size and do not stretch back out to fill the window width.

Both issues ought to be reproducible at https://dev.shanebishop.net/2019/03/wpsso-schema-test/ (not on the first/featured image, but on the second and third images, and possibly others).
--however, I myself was not able to reproduce #1 on that page, only #2. But my coworker was able to make #1 happen while I watched his screen remotely. We couldn't discern any functional difference as we are both using Chrome 78, and both had the dpr at 2.

I have noticed that the img element itself seems to be constrained by the figure element that contains it, and specifically, when watching the computed dimensions of the figure element, the height will decrease while the window size is decreased, but it will not increase when the window size is increased. Conversely, the figure element width DOES increase and decrease as one would expect it to.

One last note, on my iPhone 6s, I can replicate issue #1 in landscape orientation, which confirms that this does also affect real devices, at least for this page:  https://www.geeknative.com/69955/these-are-the-best-geeky-reads-of-2019/

**Comment by aFarkas** [comment]
Please read the documentation:
https://github.com/aFarkas/lazysizes#automatically-setting-the-sizes-attribute

**Comment by nosilver4u** [comment]
Sorry Alex, I must have missed something again! I'll go back through that section and see if I can spot what I missed.

**Comment by nosilver4u** [comment]
I'm still stuck (sorry if I'm being obtuse). The image in question has a placeholder image that is 600x371 (same size as the original), so the width ought to be "calculable" and the sizes attribute does get set to 600px as expected. But somehow the image ends up being sized down to 187.5x115.938.

Do you think it is something from the WP block layout CSS/JS that is miscalculating the dimensions of the image somehow? Or is it because the a/link element that is the parent seems to have inherited width=auto from somewhere? Note that the image right above that works properly, and is not contained in a link element, perhaps that's the problem right there?

**Comment by nosilver4u** [comment]
Really, I'm leaning towards #1 being a glitch in the WP block layout CSS/JS, because it only happens when dpr=2, and when the viewport width is 650+, which would seem quite odd for lazysizes to be doing something only under those exact conditions.

And I suppose issue #2 is probably related to core WP also. I suspect if core bothered to re-calculate the dimensions of all images consistently, then lazysizes would do the same.
