### ISSUE TITLE
Lazysizes + ie11 + srcset 1x/2x not work

### ISSUE THREAD

**Issue by Nev1oN** [aFarkas/lazysizes#730]
If you take the example of  "responsive image with the picture element" and add 1x and 2x to the source of the picture then in ie11 (windows 8.1 in my case) does not work. And use "object-fit" plugin. I use latest versions.

the problem is solved when I use:
   - lazysizes 3.0.0
   - object-fit v5.2.0-beta1
   - picturefill 3.0.2 (this plugin has nothing to do with lazysizes, but it fixes the problem and there is no need to add "respimg")

**Comment by aFarkas** [comment]
[RTFM](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg)

**Comment by Nev1oN** [comment]
I used:
  - lacisiches
  - object fit
  - respimg

it works if take picture -> source no 1x and 2x images, else not work!
