### ISSUE TITLE
Fire lazy images when page is completed loaded

### ISSUE THREAD

**Issue by amit648** [aFarkas/lazysizes#735]
Hello 

I want to fire lazy images when page is completed loaded after two seconds. Please give me some suggestions on what to do need in the script. 

Thanks

**Comment by michelarteta** [comment]
Same here, getting this warning from google: Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive.

**Comment by huseyin39** [comment]
You do not need lazysizes in this case. A JavaScript  function is enough. Check Load image async on google.

**Comment by yellow1912** [comment]
@amit648 the document is long, but the information is there, you should check it first.

> lazySizesConfig.init (default: true): By default lazysizes initializes itself, to load in view assets as soon as possible. In the unlikely case you need to setup/configure something with a later script you can set this option to false and call lazySizes.init(); later explicitly.

@michelarteta no that is not the same, Google is telling you to lazyload your images that are below the fold (off screen). That means that your lazysizes setup is probably not working correctly.

**Comment by aFarkas** [comment]
Don't know wether you mean the following option:
`lazySizesConfig.loadMode` (default: 2): The loadMode can be used to constrain the allowed loading mode. Possible values are 0 = don't load anything, 1 = only load visible elements, 2 = load also very near view elements (expand option) and 3 = load also not so near view elements (expand * expFactor option). This value is automatically set to 3 after onload. Change this value to 1 if you (also) optimize for the onload event or change it to 3 if your onload event is already heavily delayed.

If not re-open this issue.
