### ISSUE TITLE
umd.wrapper does not pass `Date` 

### ISSUE THREAD

**Issue by birdspider** [aFarkas/lazysizes#737]
**Description**

In the umd.wrapper the Date Object is not passed to the factory function.

**Detail**

compare 

https://github.com/aFarkas/lazysizes/blob/gh-pages/src/umd.wrapper#L2

with 

https://github.com/aFarkas/lazysizes/blob/gh-pages/src/common.wrapper#L2

`Date` is not passed, so inside the umd* artifacts `Date` is undefined. (because it gets shadowed by the fn param; i.e. `Date.now()`)

**Comment by emkayy** [comment]
@aFarkas Could you please release a quick fix for that?
It breaks the whole software.

Thanks a lot for this awesome module!

**Comment by aFarkas** [comment]
will do until monday
