### ISSUE TITLE
Lazysizes blocking website images when Cloudflare recaches

### ISSUE THREAD

**Issue by neilscot** [aFarkas/lazysizes#739]
**Describe the bug**
My new WP website has been running with lazysizes on cloudflare and working wonderfully well since Feb 2019. But at the start of this month (January 2020) images on my site stopped loading. My web guy says Lazysizes is blocking images when Cloudflare recaches and so can only sort it my disabling lazysizes, which seriously impacts performance. I don't understand how it could work so well and then stop. Please help.

**To Reproduce**
I am not technical in any way, so don't know what to put here. Hoping this is a known issue with an easy resolution.

**Steps to reproduce the behavior:**
Can provide URL

**What is the expected behavior**
Images should load

**What happened instead**
Images don't load. None of them

**In what environment (browser/device etc.) does this bug happen/not happen:**
Happens in all browsers in all devices.

**Comment by aFarkas** [comment]
This is because Cloudflare's rocket js overrides native code and destroys the browser API. It is not a lazysizes bug. It is a cloudflare bug. As mentioned in the other issue.
