### ISSUE TITLE
checkElems vs updateElems

### ISSUE THREAD

**Issue by brynda** [aFarkas/lazysizes#74]
In the documentation, at: https://github.com/aFarkas/lazysizes#lazysizesautosizerupdateelems, I believe "checkElems" is the correct function to call. updateElems does not exist - available are "updateElem" (without the 's' at the end) and "checkElems" ... the latter worked for what I was trying to do.
Thank you for this great plugin!
K.

**Comment by aFarkas** [comment]
Thx!
