### ISSUE TITLE
Parent Fit with aspect ratio on screen resize

### ISSUE THREAD

**Issue by origindesign** [aFarkas/lazysizes#740]
Hello, amazing plugin, huge time saver, really love the Parent Fit plugin, makes life so easy!

I have a question regarding the implementation of data-parent-fit="cover" with data-aspectratio="**"

This works as expected and on page load, sizes="auto" is replaced with sizes="**" where ** equals the width of the parent taking into account image aspect ratio to fill the height of the parent also. This is great when heights need to change through breakpoints.

However, as the screen is resized, the sizes attribute reverts back to the width of the parent element without taking into account the image aspect ratio, which is ending up with images too small being shown.  It seems in my setup, the data-aspectratio attribute is being removed from the element after it comes into view and the sizes calculation has been made.

Now I get that most people dont resize browsers, but this would be an issue flipping from portrait to landscape on a tablet.

Is this the intended function? Or am I doing something wrong?

http://dev-bostonyatchhaven.pantheonsite.io/frankenpage
You can see examples on any image on this page, load at a mobile size, then enlarge up to desktop size and note the value of the sizes attribute.

Any direction here would be very appreciated. Thanks very much :)

**Comment by origindesign** [comment]
Reopening this as I am now having the issue on a different site build, that is causing much more noticeable issues.

https://live-a-place-vermont.pantheonsite.io/ 

To Reproduce:

- on a desktop browser, scroll down and click any of the circular links to open the modal. Note the image on the right of the screen and note the sizes attribute correctly being calculated on the image's aspect ratio to fill the parent container

- Resize the browsers width or height, even just slightly, and note the image's sizes attribute now only being the width of the parent container, not taking into account the height/aspect ratio, causing a much smaller image to be loaded and stretched full window height.

Any ideas of why this is happening in my implementation? Am I missing something? Happy to provide any more details you need. I get that a codepen or something is best to strip it all back, but just checking in first if something clearly stands out or if there are other reported issues already existing (I cant find any).

thanks in advance for any help.

**Comment by origindesign** [comment]
Ive gone ahead and implemented a kind of hacky fix for my specific case on just this badly affected image.

I am hardcoding an extra data attribute to store the image ratio in.
data-aspectratio-resize

Then setting up a resize event to force the reappliction of the data-aspectratio and the loading of the image


`$(window).on('resize', function(){
setTimeout(function(){
let img = $('.selector-for-image');
                img .attr('data-aspectratio',img.data('aspectratio-resize')).addClass('lazyload');
            }, 1000);
                
            });`

**Comment by aFarkas** [comment]
Sorry for not answering this long time. Could you please create a jsfiddle/jsbin example that showcases your isolated problem.

**Comment by origindesign** [comment]
No problem, thanks for the response.

I have setup this example to show the issue I am seeing. 
https://jsfiddle.net/lindsaydubul/my7wa06q/12/

Note I am working with the Drupal plugin in my live examples, and the same issue can be seen on the portrait images here on this home page I am working on.
https://live-charlestownmarina.pantheonsite.io/

From my fiddle, steps to reproduce.
- load the page (ideally with your inspect panel already open, as this will trigger a browser resize if it is docked), inspect the image and note the sizes attr is 1045px, the data-aspectratio attr is taken into account and the height of the parent container is used to show an image that will fill the height. Also note that the data-aspectratio attribute is removed.
- right click >view image, note a 1600px is shown
- resize the window, for example just drag your docked inspect panel up a little. note the sizes attr now changes to  653px and seemingly the height and aspect ratio is no longer used in the calculations, just the width of the parent container.
- right click >view image, note a 800x600px is now shown and the parent container is 784px, so the image is now being stretched

Is there something wrong with my initial html setup? I am of the understanding that the attributes required are:

- data-parent-fit="cover" 
- data-aspectratio="*" (removed from the img tag output by javascript, potentially causing this issue?)
- data-sizes="auto"

Thank you for any help you can offer. This is an amazing plugin and we use this on all of our websites, which are always client managed content, so the ability to use this instead of offering some kind of crop plugin is a huge benefit. It allows the client to upload a landscape image and we can display this in a range of different sized containers of different aspect ratios to keep our designs more interesting.

**Comment by aFarkas** [comment]
@origindesign 
In general you haven't done something wrong, but you got to an issue where the functionality of two plugins interfere with each other. 

In general you can workaround your problem by

1. remove the aspect-ration plugin
2. define additionally `width`/`height` attributes. Your example would still work if you would add the following attributes ` width="1333" height="1000"`

I know the answer isn't the best, but I hope it helps!

**Comment by origindesign** [comment]
Thank you for the response, it seems simply disabling the aspect-ratio plugin has removed the issue. The data-aspect ratio attribute is now not being removed and the image stays correctly sized as the browser is resized.

As you suggested, some issue between the plugins, I don't know why I even had the aspect ratio plugin enabled, seems it isn't necessary. Thank you.
