### ISSUE TITLE
Is there any reason that data-src is skipped if data-srcset is found?

### ISSUE THREAD

**Issue by vovayatsyuk** [aFarkas/lazysizes#75]
I have the following code:

```html
<img data-src="logo1x.png" data-srcset="logo2x.png 2x" class="lazyload"/>
```

If I use the same code without `data-` prefixes (without lazyload), browser automatically select 2x for mobile and 1x for desktop, but when the prefixes are added 1x won't be used.

This behaviour could be fixed with the following patch:

```diff
diff --git a/lazysizes.js b/lazysizes.js
index ae2d1b0..668b3d9 100644
--- a/lazysizes.js
+++ b/lazysizes.js
@@ -330,7 +330,8 @@
 						elem.removeAttribute('src');
 					}
 
-				} else if(src){
+				}
+				if(src){
 					if(regIframe.test(elem.nodeName)){
 						changeIframeSrc(elem, src);
 					} else {

```

So, my question is: Is there any reason that data-src is skipped if data-srcset is found?

**Comment by vovayatsyuk** [comment]
Sorry, I just found that you do set the `src` for image, but later, in the [setTimeout](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L355) function.

Somehow it does not work for me. I checked it with firebug, and found that [updatePolyfill](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L355) is called, then [`el.src = full.src;` is called](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L67), but image does not appear.

img tag after lazyload:
```html
<img class=" lazyloaded" data-srcset="logo@2x.png 2x" data-src="logo.png" srcset="logo@2x.png 2x">
```

My browser is firefox 36.0.1, Windows 7 64bit. I don't use polyfill.

**Comment by aFarkas** [comment]
Yes. There is a reason for this. You would produce a double download in some browers. Simply use srcset for both image candidates. See also: https://github.com/aFarkas/lazysizes/issues/53#issuecomment-72705175

**Comment by vovayatsyuk** [comment]
What a pity. Thanks.
