### ISSUE TITLE
What does requestIdleCallback do?

### ISSUE THREAD

**Issue by simplenotezy** [aFarkas/lazysizes#751]
I'm currently debugging why lazysizes are slowing down my site significantly, and I stumpled across the "requestIdleCallback" setting. What does this do exactly?

**Comment by marko-hologram** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

It tells the browser that some function you send to `requestIdleCallback` should be invoked when browser is idling. Basically this is for functions that aren't critical for you and you want to invoke them when browser isn't doing other critical work. So functions that don't need to be invoked right now, but can be invoked at a later time when browser decides it's ok for them to run without interrupting main even loop.
