### ISSUE TITLE
Is there a way to prevent lazysizes data-bgset from inserting a <picture> element? Causing SSR issues

### ISSUE THREAD

**Issue by adrianocr** [aFarkas/lazysizes#752]
I'm using lazysizes with nuxt and everything works fine. However it's inserting an additional <picture> element when converting data-bgset="" which is causing issues because the dom node tree gets out of sync.

**Comment by aFarkas** [comment]
Sorry no, because it is built on top of the inner working of the `picture` element. Please also note that this plugin is deprecated for most use cases.

**Comment by simonmaass** [comment]
currently also stuck with SSR issues

`Mismatching childNodes vs. VNodes`

@adrianocr did u solve it somehow?

**Comment by aFarkas** [comment]
@simonmaass 
The bgset plugin is also deprecated. In most cases users shouldn't use this plugin.
