### ISSUE TITLE
Image loaded after page load

### ISSUE THREAD

**Issue by sleepinzombie** [aFarkas/lazysizes#755]
I have something like this:
`<img class="lazyload" data-src="{{ var.image }}" alt="assurance vie menu image"/>`

It's hidden inside a dropdown in the menu, and I want it to appear when I hover on the dropdown. But right now, the image loads just after the page loads completely.

Basically I think the image should not be loaded after the whole page loads.

Any help?

**What is the expected behavior**
The `img` tag should have the `lazyloaded` class after it comes into view.

**What happened instead**
The `img` tag has the `lazyloaded` class after the page loads.

**In what environment (browser/device etc.) does this bug happen/not happen:**
OS: Ubuntu 18.04; Browser: Mozilla Firefox Developer.

**Comment by aFarkas** [comment]
Please read the documentation. You will find your answer there.
