### ISSUE TITLE
isotope with lazysizes doesn't work well

### ISSUE THREAD

**Issue by lear2012** [aFarkas/lazysizes#76]
Hi im using isotope in my page and here is one part of the code:
```javascript
$('.portfolio').isotope({
            itemSelector: '.portfolio-item',
            layoutMode: layoutMode
}).isotope('layout');

And the html part is :
<img data-src="[img_url_here]" class="lazyload" />   [named Part A, these images are not within the screen at the first sight]
<img data-src="[img_url_here]" class="lazyload" />   [named Part B, these images are not within the screen at the first sight either while they are not using isotope]

The problem is that when i visit the page it requests all the images rendered by isotope while the images
 should be requested when you scroll to Part A. And normally there is a ALL tab for isotope, hover no 
 images displayed until you click ALL. The lazysizes works well for other images not using isotope. Im still
 looking into this while your help would be great appreciated. Please ask me if anything not clear, thanks.

**Comment by aFarkas** [comment]
Here is a [codepen that demonstrates isotope in conjunction with lazySizes](http://codepen.io/aFarkas/pen/VYGvde) and here is another one with [lazySizes and mixitup](http://codepen.io/aFarkas/pen/wByKeL).

**Comment by lear2012** [comment]
Hi aFarkas, i found the problem, thank you. By the way, is the 'async=""' a must in the script tag?

**Comment by lear2012** [comment]
Hi aFarkas ,  i found the problem, thank u :)

**Comment by Kracheads** [comment]
What the answer? I'm having the same issue I believe.

Thanks.

**Comment by lear2012** [comment]
Hi Kracheads, it's a long time since i got the problem, so im afraid i can't remember the details how i 
solved problem. But i would like to share some key parts of the code which maybe give some hints for you. If problem still exists, paster your code here and we can give a further discuss.
[code]
        initCases: function () {
            if ($('.portfolio').length) {
                var layoutMode = 'masonry';
                if ($('.portfolio-4-columns').length) {
                    layoutMode = 'fitRows';
                }
                var $portfolio = $('.portfolio').imagesLoaded(function () {
                    $portfolio.isotope({
                        itemSelector: '.portfolio-item',
                        layoutMode: layoutMode,
                        filter:'*'
                    }).isotope('layout');
                });
                $('.filter').on('click', 'button', function () {
                    var filterValue = $(this).attr('data-filter');
                    $portfolio.isotope({filter: filterValue});

                    $('.filter .selected').removeClass('selected');
                    $(this).addClass('selected');
                });
                $('button[class=selected]').trigger('click');
            }
        },

[/code]
