### ISSUE TITLE
How to use webp images?

### ISSUE THREAD

**Issue by simplenotezy** [aFarkas/lazysizes#762]
I populate my images using `bgset` - how can I add support for webp?

I've seen https://github.com/aFarkas/lazysizes/issues/656 but it doesn't quite show how it's done.

**Comment by aFarkas** [comment]
It is shown in the [documentation](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset):

```
data-bgset="logo.svg [type: image/svg+xml] | logo.png"
´´´

**Comment by simplenotezy** [comment]
I'm not sure I quite understand how it works then @aFarkas, could you perhaps show me the right direction?

If my srcset is like this:

    data-bgset="Australien_front_u_diamant_silver-236x300.jpg 236w, Australien_front_u_diamant_silver-600x761.jpg 600w, Australien_front_u_diamant_silver-768x975.jpg 768w, Australien_front_u_diamant_silver-807x1024.jpg 807w, Australien_front_u_diamant_silver-19x24.jpg 19w"

How can I add .webp images to it?

**Comment by simplenotezy** [comment]
@aFarkas would something like this work?

    data-bgset="Australien_front_u_diamant_silver-236x300.webp 236w, Australien_front_u_diamant_silver-600x761.webp 600w, Australien_front_u_diamant_silver-768x975.webp 768w, Australien_front_u_diamant_silver-807x1024.webp 807w, Australien_front_u_diamant_silver-19x24.webp 19w [type: image/webp] | Australien_front_u_diamant_silver-236x300.jpg 236w, Australien_front_u_diamant_silver-600x761.jpg 600w, Australien_front_u_diamant_silver-768x975.jpg 768w, Australien_front_u_diamant_silver-807x1024.jpg 807w, Australien_front_u_diamant_silver-19x24.jpg 19w"
