### ISSUE TITLE
Hidden images are still loading

### ISSUE THREAD

**Issue by adamchipperfield** [aFarkas/lazysizes#766]
I have a custom "carousel" which toggles the opacity of a number of slides every few seconds. Each element has a background image and makes use of the bgset plugin. It works totally fine except when loading:

- Each image loads, despite being hidden
- Setting `window.lazySizes.cfg.loadHidden` to `false` does nothing
- This is even still the case when not using bgset and using a standard background image

Here's an example of one of the slide elements:

```
<div
  data-bgset="[Standard srcset implementation, works fine]"
  class="lazyload"
  role="img"
>
  ...
</div>
```

Am I approaching this incorrectly?

**Comment by aFarkas** [comment]
use `visibility: hidden`

**Comment by adamchipperfield** [comment]
This still doesn't work. I've tried on both a parent element and an image element. The image is still loaded.

**Comment by aFarkas** [comment]
Can you create a test case? https://jsbin.com/?html,output
