### ISSUE TITLE
Is lazysizes dead?

### ISSUE THREAD

**Issue by zhrance** [aFarkas/lazysizes#767]
Sorry for being so bold but since the last commit is on 17 december I'm wondering if lazysizes will be maintained. There are some huge issues in this version that makes lazysizes useless. The basics don't work in several browsers. I understand this is something I can use for free and was very enthusiastic when I start using this a little less than a year ago. Just want to know if this seriously gets maintained. Otherwise I start creating an alternative. Would love to hear.

**Comment by strarsis** [comment]
I can confirm this, in Safari on iOS the image is not loaded at all.

**Comment by aFarkas** [comment]
It is maintained, but it is a simple peace of feature that doesn't need to be changed every month. Second I decided to not answer any stupid bug reports anymore.

I'm not here to try to reproduce something where the bug author was unable follow the issue template for example.

I'm not here to explain developers how the `picture` element or the `srcset` or the `sizes` attributes work. This is something that you must understand before you can use this library.

**Comment by zhrance** [comment]
@aFarkas thank you for your reply. Glad to hear you keep maintaining it. I understand your frustrations regarding question that are not a bug but lack of knowledge. Although I have to say that if images are not caching in 2 browsers it's a bug (https://github.com/aFarkas/lazysizes/issues/748) that needs a quick fix. Again, I understand this takes a lot of your time and got a lot of appreciation for the work you do. If there is a way I can help you out or support you, let me know.

**Comment by aFarkas** [comment]
> Although I have to say that if images are not caching in 2 browsers it's a bug (#748) that needs a quick fix.

You are aware of the fact that this statement is simply not true.

**Comment by zhrance** [comment]
> > Although I have to say that if images are not caching in 2 browsers it's a bug (#748) that needs a quick fix.
> 
> You are aware of the fact that this statement is simply not true.

Did some testing again in Firefox on Mac (75.0) on the first image when you open https://afarkas.github.io/lazysizes/. You are right that the image is cached. The first time it will also set the class Is-is-cached but when you refresh the browser the class is gone even though the image is cached.

![Apr-14-2020 19-00-50](https://user-images.githubusercontent.com/429941/79252703-554a4380-7e82-11ea-8294-0bf9dd838beb.gif)

**Comment by strarsis** [comment]
@aFarkas: When you check out a lazy loaded image (with object-fit cover extension) in Safari (browserstackcom), the image will not load in iOS/OSX Safari browser.

**Comment by aFarkas** [comment]
@strarsis
I can not reproduce your claims with real devices. If this would be true I would have many many users complaining about this and not just you.

**Comment by strarsis** [comment]
@aFarkas: Apparently the issue stems from the browser support of webp.
Example for reproducing the issue: https://codepen.io/strarsis/pen/gOaMgRN
URL to example usable for BrowserStack: https://cdpn.io/strarsis/fullpage/gOaMgRN
BrowserStack screenshots: https://www.browserstack.com/screenshots/05b79ae1c180a896d1e83ec08a1475a0a5834b1d

Browser support status for webp format: https://caniuse.com/#feat=webp
Safari doesn't support webp yet. webp and jpeg formats are offered for the lazily loaded image.
Do I need to add a lazysizes plugin or code to allow for format feature detection/fallback?

**Comment by strarsis** [comment]
@aFarkas: After using `<picture` with `<source` for each image format, it now also works in Safari. 👍

**Comment by aaronstezycki** [comment]
I can also confirm @zhrance issue with ls-is-cached class is also not working. Im currently testing in chrome, with a simple pattern... 

``` 
<img class="img lazyload" data-src="SRC.jpg" />
```

And this pattern inconsistently applies the cached class. Sometimes it works, mostly it does not.

**Comment by aaronstezycki** [comment]
@aFarkas @zhrance A little more testing, reveals that the class does not get added to the IMG element when the element loads in view of the browser. 

If the img element has not loaded, and you scroll down to the element, it adds `lazyloaded' and 'ls-is-cached' consistently. But not when the img is in view upon refresh. Its quite tricky to debug, but its definitely an inconsistent behaviour.

**Comment by yellow1912** [comment]
@aaronstezycki sound like a bug with the observer that detects if the element is in view or not. What if you scroll up then down again?

**Comment by aFarkas** [comment]
@yellow1912 

read here: https://github.com/aFarkas/lazysizes/issues/748#issuecomment-733886271
