### ISSUE TITLE
data-sizes="auto" doesn't work in Chrome

### ISSUE THREAD

**Issue by rtorresn10** [aFarkas/lazysizes#773]
Hello I'm using the autosizing and its works in Safari correctly, but in Chrome strangely doesn't not work.

My images are something like this:

```html
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
    data-src="image-1608x.jpg"
    data-sizes="auto"
    data-srcset="image-282x.jpg 282w, image-324x.jpg 324w, image-402x.jpg 402w, image-804x.jpg 804w, image-564x.jpg 564w, image-648x.jpg 648w, image-804x.jpg 804w, image-1608x.jpg 1608w"
    class="lazyload">
``` 

I know that may I'm doing something wrong, but I don't find any solution.

**Comment by aFarkas** [comment]
@rtorresn10 
I can not use your bug report. Please always provide a test case. Especially `data-sizes="auto"` relies on the computed styles and therefore some HTML code alone doesn't help.

In most cases the [readme helps](/aFarkas/lazysizes#user-content-sizes-calculation)!

**Comment by rtorresn10** [comment]
@aFarkas Thanks for your response!

I made this example for you:
https://glitch.com/edit/#!/stormy-receipt?path=index.html%3A21%3A205

**Comment by rtorresn10** [comment]
@aFarkas Thanks for you response.

I made this example for you:
https://glitch.com/edit/#!/stormy-receipt?path=index.html%3A38%3A10

In Chrome only take one image and when you resize the window the image don't change.
But in safari it works fine.
