### ISSUE TITLE
Add option to load image progressively from top to bottom?

### ISSUE THREAD

**Issue by tomasts248** [aFarkas/lazysizes#775]
Something like this
![222018_03052020](https://user-images.githubusercontent.com/32283036/80930938-bc259300-8d84-11ea-950c-88335e3ea751.jpg)
where the image loads from top to bottom as it is downloaded. Do note I have no idea if this is feasible or not. Regards.

**Comment by aFarkas** [comment]
This has nothing to do with lazysizes.

**Comment by tomasts248** [comment]
I apologize you are correct
