### ISSUE TITLE
Help with verticle tab menu image visibility hidden but still load

### ISSUE THREAD

**Issue by arenatheme** [aFarkas/lazysizes#776]
![Screen Shot 2020-05-05 at 11 02 55](https://user-images.githubusercontent.com/37363217/81034083-2abb3b80-8ec0-11ea-8307-35b390c8d094.png)
I don't know why it visibility hidden block but still load.
https://xstore-how-to.myshopify.com/

**Comment by aFarkas** [comment]
I don't fully understand what you mean. But if an element is `visibility: hidden` lazysizes is downloading it but with a very low priority meaning that all inview images are loaded prior. It is actually a good thing.

For how to configure it you can read the manual.
