### ISSUE TITLE
Lazysizes does not load images before some user action

### ISSUE THREAD

**Issue by OrKoN** [aFarkas/lazysizes#78]
Hi,

After I have updated lazysizes to 1.0.0, I see the problem of images which are in the view-port not showing up unless one scrolls the page or puts focus on some element. 

In my case, the `lazyload` class is added to the img component after the page is fully rendered.  I would expect the image to be shown immediately.

The img tag looks like this right before the `lazyload` class is added: 

```
<img id="ember286" class="ember-view vclResponsiveImage" data-src="/example/img_{width}.jpg" style="height: 20em;" data-sizes="auto" data-widths="[75, 240]" data-absurl="false">
```

Thanks in advance for any help.

P.S. I can provide instructions and code to reproduce the problem if needed

**Comment by aFarkas** [comment]
I'm sorry. Don't know, what goes wrong. My testcase seems to work fine:
http://plnkr.co/edit/qx0ogB22Dc646On1zNYX?p=preview

Yeah, more information would be great.

**Comment by OrKoN** [comment]
@aFarkas The problem is more likely again in how I use lazysizes togerther with Ember (although the same code previously worked). To reproduce the issue jspm is needed:
```
npm install jspm -g
```

And the code to reproduce is here: https://github.com/ember-vcl/img:

```
 git clone https://github.com/ember-vcl/img
 cd img
 npm install
 npm test
```

This will start a local browsersync server on port 3333. The `lazyload` class is added on the line jspm_packages/ember-vcl/img@0.1.2/main.js:95

**Comment by aFarkas** [comment]
Found the bug. Will fix it on my side until then you can fix it by doing this:

```css
img {
    min-width: 3px;
    min-height: 3px;
}
```

**Comment by OrKoN** [comment]
@aFarkas Thanks!
