### ISSUE TITLE
Drop MutationObserver condition

### ISSUE THREAD

**Issue by aeyoll** [aFarkas/lazysizes#782]
Hello,
Mutations Events has been discouraged and deprecated for many years now. What do you think about dropping this condition and only have the MutationObserver? : https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-core.js#L618

I can do a PR if you're interested.
Thanks

**Comment by aFarkas** [comment]
There is not much to gain and a little bit to loose a by removing those lines.  I would wait a little bit.
