### ISSUE TITLE
lazySizes does not work with the correct video embed code

### ISSUE THREAD

**Issue by Volev** [aFarkas/lazysizes#784]
Hello! I have been using lazysizes for a long time for video, but such an HTML5 code entry is not correct, although this works:
```
<figure>
    <video class="lazyload" type="video/mp4" width="512" height="512"  src="https://www.us.com"></video>
</figure>
```
Yes it works. 
But lazysizes does not work with video in such a combination of code. This is the correct code: 

```
<figure>
    <video class="lazyload" width="512" height="512">
            <source
                src="https://www.us.com"
                type="video/mp4"
        </video>
</figure>
```

I have to switch to such code to embed a video. But I can not refuse the lazysizes, i like its very optimization plugin. 

Please fix it. Finally.

Or maybe there is some other solution?

**Comment by aFarkas** [comment]
I really don't understand what you want from me. We provide an [issue template](https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md)- Please follow the instructions and also include a test case!
