### ISSUE TITLE
lazySizes does not work with the correct video embed code

### ISSUE THREAD

**Issue by Volev** [aFarkas/lazysizes#786]
**Describe the bug**
lazysizes does not work with video in such a combination of code. This is the correct code:
```
<figure>
    <video class="lazyload" width="512" height="512">
            <source data-src="https://static.videezy.com/system/resources/previews/000/040/400/original/190816-samutprakarn_2.mp4" src="https://farm9.staticflickr.com/8200/8248153196_7a7664e147_b.jpg" type="video/mp4"
        </video>
</figure>
```

**To Reproduce**
https://codepen.io/bola4ka/full/LYpvxrW

**Steps to reproduce the behavior:**
If you look at the source code of the page. It can be seen that the script does not work.

You will see that the class of the video tag has changed, but this did not affect the data-src and src attributes.

As a result, this misunderstanding does not allow you to watch the video.

**What is the expected behavior**
The src attribute will change to the correct link, as is the case with regular images.

**What happened instead**
The data-src and src attributes are not changed in any way and are ignored by the script.

**In what environment (browser/device etc.) does this bug happen/not happen:**
In any. 
However, I use Google Chrome. Version 81.0.4044.138 (Official Build), (64 bit)

**P.S:
Mr. aFarkas, Please fix it.
This appeal is in addition to this: https://github.com/aFarkas/lazysizes/issues/784

Regards, Mr.Volev.

**Comment by aFarkas** [comment]
Your HTML code doesn't make too much sense. The post is never a video src.

Please check the [unveilhooks plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks) to solve your problem.
