### ISSUE TITLE
lazySizes work with video

### ISSUE THREAD

**Issue by Volev** [aFarkas/lazysizes#787]
Hello, friend!

Please make the lazySizes work with tag video and tag **SOURCE with attributes**. Make so that it also works as with loading images.

What your sent me, it does not work with tag video and tag **SOURCE** with **attributes** "data-src", "src":
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks

Works with anything but not video with tag **source** and attributes "data-src", "src". :(

Regards, Mr.Volev

**Comment by aFarkas** [comment]
@Volev 
1. Please stop opening multiple issues with the same content.
2. Your code shows some misunderstanding of the video element. The unveilhooks plugin is able to switch the `data-poster` attribute on the `video` element and is able to change the `preload="none"` attribute to `preload=""` on `audio`/`video` elements. If you need something else you can still write your own plugin.
