### ISSUE TITLE
Lazysizes does not load the first images you see on the screen.

### ISSUE THREAD

**Issue by amoralesdesign** [aFarkas/lazysizes#790]
Lazysizes does not load the first images. They are the first photos that the user sees as soon as they land on the page.

Right after the blank photos, lazysizes works perfectly. But even if you scroll up or down lazysizes never load the first rows of images.
![Captura de pantalla 2020-05-27 a las 15 51 59](https://user-images.githubusercontent.com/4416148/83029473-0112b180-a033-11ea-8349-45b0136e31a0.png)

Every photo that does not load has the lazyloading class, but never changes its class to lazyloaded

I'm using VueJs ^2.5.17. I've tried this with Google Chrome and Safari.

It looks a lot like this problem: https://github.com/aFarkas/lazysizes/issues/311

**Comment by amoralesdesign** [comment]
I've solved this by putting in this directive for lazysizes and vuejs:
https://www.npmjs.com/package/vue-lazysizes

In my case I have a Laravel and vuejs project compiled all with webpackjs.

Since lazysizes is called within the id=app of all my web, it seems that there was a conflict between lazysizes and vuejs.

With this I solved it, I hope it helps people.

**Comment by aFarkas** [comment]
@amoralesdesign 
Thanks for your information. My question would have been wether you use the [attr change plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/attrchange) and if yes and still have problems, wether you can simply re-add the `lazyload` class inside of vue lifecycle hooks yourself. (For my personal info: Did you use the attr change plugin?)

**Comment by amoralesdesign** [comment]
> @amoralesdesign
> Thanks for your information. My question would have been wether you use the [attr change plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/attrchange) and if yes and still have problems, wether you can simply re-add the `lazyload` class inside of vue lifecycle hooks yourself. (For my personal info: Did you use the attr change plugin?)

No, I didn't know about the existence of that plugin inside lazySizes.
I'll try it out later. Thank you.

**Comment by jakedowns** [comment]
I'm running into this with a laravel vue project as well, adding that plugin didn't seem to help
