### ISSUE TITLE
Lazysizes upgrade to 5.2.2 not respecting config settings

### ISSUE THREAD

**Issue by vishy93** [aFarkas/lazysizes#792]
Hi I have been looking to update Lazysizes from 4.1.8 to 5.2.2 - but in doing so the lazy loading doesn't work any longer. 

The images are not loaded. I have configured my configurations as below, work well in 4.1.8 just not in 5.2.2. Has their been a change to the way we can configure options in version 5?

[https://codepen.io/vishpatel93/pen/oNjQOpN](url)

`window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.lazyClass = "lazy";
window.lazySizesConfig.loadMode = 1;
window.lazySizesConfig.expand = 0;
window.lazySizesConfig.expFactor = 0.01;
window.lazySizesConfig.hFac = 0;`

**Comment by aFarkas** [comment]
@vishy93 
This break was as designed. You can see [here](https://github.com/aFarkas/lazysizes/issues/647#issuecomment-491790117). While this break isn't really nice. Creating a global by lazysizes was a bad decision in the first place.

You can fix this easily by either simply put your `window.lazySizesConfig` before the llazysizes script or by extending `window.lazySizes.cfg`. Of course if you use a module bundler with ES6 `import` you would simply extend the imported `lazysizes` module.

I hope that is ok for you.
