### ISSUE TITLE
Angular Universal ngFor

### ISSUE THREAD

**Issue by h3d0** [aFarkas/lazysizes#794]
**Describe the bug**
lazysizes is supposed to **not render** the off-screen images.

**To Reproduce**
Run the steps.
**Steps to reproduce the behavior:**
Provide all necessary steps to reproduce the bug.

**What is the expected behavior**
1. Run `ng new --routing foo.`
2. Run `ng add @nguniversal/express-engine`
3. Add an off-screen image using Angular's `ngFor`.

**What happened instead**
The browser Network tab reports all images loaded:

![image](https://user-images.githubusercontent.com/7346327/83624037-cbbe1480-a59a-11ea-856f-7e5e15b55ddb.png)

Lighthouse returns:

![image](https://user-images.githubusercontent.com/7346327/83624080-d8db0380-a59a-11ea-88d5-a406f57bf9bf.png)

**In what environment (browser/device etc.) does this bug happen/not happen:**
Chrome 83

**Comment by aFarkas** [comment]
@h3d0

lazySizes follows a technique that preloads images in a more intelligent way. To my knowledge no other lazyloader is doing it like this. Normally you can only specify wether a lazyloader should preload or not. lazySizes is different in the way that lazySizes loads first all in view images and then with a delay/lower priority all close to the view images. 

This is at the end the best way (for UX) to lazy load images but might be too intelligent for Lighthouse. The "estimated savings" are a joke. Of course you can configure lazySizes in a way that is more less user friendly but suites your lighthouse test more.
