### ISSUE TITLE
Chrome stopped working for me

### ISSUE THREAD

**Issue by teejayhh** [aFarkas/lazysizes#80]
Hello, we where using you script a while now and its awesome. But we noticed today that chrome doesn't play well anymore. I found this -> http://stackoverflow.com/questions/28155861/google-chrome-version-40-srcset-attribute-problems and it seems no that the largest image gets cached and wont be replaced. You can have a look at our site -> http://futureburo.com/burology. FF and Safari work as expected. If you disable the browser cache in chrome or open your inspector everything is fine. So is there a way to for the JS implementation rather than native browser stuff which seems to change all the time. 

Cheers Thomas

**Comment by aFarkas** [comment]
I'm not 100% sure what you mean but you clearly should use ``picture`` instead of only ``srcset``. For example the first image could have the following markup

```html
<picture>
	<!--[if IE 9]><video style="display: none;><![endif]-->
	<source
			data-srcset="http://a2b1a74d3fa3479994c3-fd335b8e141dbd805066b266bc164c65.r77.cf2.rackcdn.com/app_img_asset_00_09_5500fd31efb0c.jpg_w_1200-h_540-q_95-c_c-b_0.jpg"
			media="(min-width: 760px)" />
	<source
			data-srcset="http://a2b1a74d3fa3479994c3-fd335b8e141dbd805066b266bc164c65.r77.cf2.rackcdn.com/app_img_asset_00_09_5500fd31efb0c.jpg_w_640-h_640-q_95-c_c-b_0.jpg"  />
	<!--[if IE 9]></video><![endif]-->
	<img
			src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
			class="lazyload"
			alt="image with artdirection" />
</picture>
```

This way you control, which image is used and not the browser. If you don't want to use ``media`` attributes in your markup you can configure them in JS:

```html
<script>
	window.lazySizesConfig = window.lazySizesConfig || {};
	window.lazySizesConfig.customMedia = {
		'--large': '(min-width: 760px)'
	};
</script>

<picture>
	<!--[if IE 9]><video style="display: none;><![endif]-->
	<source
			data-srcset="http://a2b1a74d3fa3479994c3-fd335b8e141dbd805066b266bc164c65.r77.cf2.rackcdn.com/app_img_asset_00_09_5500fd31efb0c.jpg_w_1200-h_540-q_95-c_c-b_0.jpg"
			media="--large" />
	<source
			data-srcset="http://a2b1a74d3fa3479994c3-fd335b8e141dbd805066b266bc164c65.r77.cf2.rackcdn.com/app_img_asset_00_09_5500fd31efb0c.jpg_w_640-h_640-q_95-c_c-b_0.jpg"  />
	<!--[if IE 9]></video><![endif]-->
	<img
			src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
			class="lazyload"
			alt="image with artdirection" />
</picture>
```

Or in case you want to control them in CSS, you can add the [following plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/custommedia).

Did this help?

**Comment by teejayhh** [comment]
Thanx, I will try this out and let you know. But can you confirm that chromes behavior changed a little bit compared to the behavior from FF and Safari.

**Comment by aFarkas** [comment]
Yes, it changed. But this change was an optimization. It's important: If you use ``srcset`` you say to the browser here are different sources, these sources have different resolutions, choose what you want. In case you use picture you say: browser, you have to select the first ``source`` with a matching media query. (Of course you can also mix both patterns and give multiple image candidates for one source element inside the srcset attribute).

**Comment by teejayhh** [comment]
cool all worked well, picture is working perfectly. Thx for you help
