### ISSUE TITLE
loadHidden option is not working in v5.1.2 and above

### ISSUE THREAD

**Issue by davidmerrique** [aFarkas/lazysizes#804]
**Describe the bug**
Even though I have `window.lazySizesConfig.loadHidden = false;` set, images with `img { visibility: hidden; }` are still loading.

**To Reproduce**
https://codepen.io/davidmerrique/pen/KKVNOOE

**Steps to reproduce the behavior:**
```html
<img class="lazyload" data-src="https://picsum.photos/200/300" alt=""/>
<p>Text will be pushed down when the image loads.</p>
<p>The image has visibility: hidden; and should not load because of window.lazySizesConfig.loadHidden = false;</p>
<script>
  window.lazySizesConfig = window.lazySizesConfig || {};
  window.lazySizesConfig.loadHidden = false;
</script>
<script src="https://unpkg.com/lazysizes@5.2.2/lazysizes.js"></script>
```
```css
img {
  visibility: hidden;
}
```

**What is the expected behavior**
The image should not load

**What happened instead**
The image loaded 😢 

**In what environment (browser/device etc.) does this bug happen/not happen:**
Tested in Firefox, Chrome, Safari 

If you change the version to 5.1.1 (`<script src="https://unpkg.com/lazysizes@5.1.1/lazysizes.js"></script>`) it works as expected

**Comment by aFarkas** [comment]
@davidmerrique 
Sorry the manual isn't that clear about this, but it works as intended. It's basically a feature not a bug. Sometimes people use `visibility: hidden;` on the image to hide a broken image symbol. Therefore `visibility: hidden;` on the `img` element isn't taken into account alone. A parent has to have `visibility: hidden;`.

```html
<div style="visibility: hidden">
    <img class="lazyload" data-src="https://picsum.photos/200/300" alt=""/>
</div>
```

I hope that is ok and you can work around this? ;-)
