### ISSUE TITLE
Image is being downloaded multiple times on resize (even if it's the same image)

### ISSUE THREAD

**Issue by hendrikeng** [aFarkas/lazysizes#805]
**Describe the bug**
Image is being downloaded multiple times on resize (even if it's the same image)

**To Reproduce**
http://jsfiddle.net/trixta/w96o9xm5/ 

**Steps to reproduce the behavior:**
Load fiddle, resize

**What is the expected behavior**
do not download the same image multiple times

**In what environment (browser/device etc.) does this bug happen/not happen:**
Chrome

**Comment by aFarkas** [comment]
This is by design and pretty much normal. If the size changes an image candidate selection algorithm is run and then the image re-selected. The browser solves this problem by having a cache. If you open your dev tools you are also disabling the image download cache.
