### ISSUE TITLE
LazySizes with Swiper slider

### ISSUE THREAD

**Issue by keerthanaswarnakumar** [aFarkas/lazysizes#807]
Hi,

I am using your plugin and it works perfectly fine except when it comes to slider.  I am using swiper slider for my website and I have a large number of sliders loading in a page with huge images. So I am using lazySizes to make the page lightweight by lazyloading the images.  

All the images which are below the fold(below the viewport) are lazyloaded as expected.  But when the page viewport reaches the Slider, it loads all the images irrespective of the visibility(Loads the images which are not visible) . 

**Expected behavior**
Need the lazysizes to lazy load all the images that are not visible, Even the slider images that are hidden on viewport.  

Thanks in advance.

**Comment by aFarkas** [comment]
i would need a test case. To see the problem. on my machine it works. Please re-open if you can provide a testcase.

**Comment by keerthanaswarnakumar** [comment]
It is working fine when the container is in full width.  When the container is restricted to some width, then the images that are not visible also loaded.  Refer my codepen with the URL below,
https://lw-magento-sprint28.test/black-led-decorative-lamp-jaipur-lantern.html

Screenshot:
https://nimb.ws/HMtr8A

**Comment by eballeste** [comment]
this plugin fixes it! 
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/attrchange
