### ISSUE TITLE
Preloading within slideshow

### ISSUE THREAD

**Issue by OliverFisher** [aFarkas/lazysizes#81]
Hello

I'm using your excellent plugin to lazy load images within a slideshow (Royal Slider). Whilst it is working, I would ideally want the ability to preload at least the next image along in the slider. I notice in your documentation you mention the 'Intelligent prefetch/preload' which I can see does indeed work very well on vertically scrolling images (like if I disable the slider and just have the images one on top each other) - I assume there is a certain amount of pixels it has to get near to the image to trigger the preloading?

However, within the slider this works less well, and the images are a little slow and "jumpy" when cycling through the slideshow and don't appear to be preloading. I also saw in the documentation the lazySizesConfig.preloadClass where you say "Note: This class can be also dynamically set ($currentSlide.next().find('.lazyload').addClass('lazypreload');)." Now it seems like this might provide the answer I'm looking for but as my programming knowledge is pitiful at best, I am uncertain how exactly to use this code. If you could point me in the right direction I'd be very grateful!

This is the page I'm working on if you'd like to see what I mean: http://frontwardsdesign.co.uk/geoffreypreston/project/the-new-house/

Many thanks
Oliver

**Comment by aFarkas** [comment]
will look into this, either in 9 or in 20h.

**Comment by OliverFisher** [comment]
Thank you, much appreciated!

**Comment by aFarkas** [comment]
I have created a small jQuery plugin for you:

```js
(function($){
	$.fn.lazysizesRoyal = function(){
		var addPrevNextPreload = function(){
			var setPreload;
			var slider = $(this).data('royalSlider');

			if(!slider){return;}
			setPreload = function(){
				slider.currSlide.holder
					.next()
					.add(slider.currSlide.holder.prev())
					.find('.lazyload')
					.addClass('lazypreload')
				;
			};
			setPreload();
			slider.ev.on('rsAfterSlideChange', setPreload);
		};
		return this.each(addPrevNextPreload);
	};
})(jQuery);
```

Usage would look something like this:

```js
jQuery('.royalSlider').lazysizesRoyal();
```

Note:
1. This has to be run **after** the royalSlider script!

**Comment by OliverFisher** [comment]
Hello

That is incredibly kind of you! Thank you so much. However, I cannot get it to work. I have put your plugin code in a separate js file which I am enqueueing after Royal Slider, and then I am adding the initialising code jQuery('.royalSlider').lazysizesRoyal(); just before the closing body tag, again after the initialising code of Royal Slider - is this correct? Do I need to change any of the '$' in the code to 'jQuery' as I am within Wordpress? I am not getting any errors in the console and the script is enqueueing correctly. Please forgive me if I am doing something stupid (I almost certainly am)!

Thanks again for your help.
Oliver

**Comment by OliverFisher** [comment]
Please ignore me - I figured out what I was doing wrong, it was a classic schoolboy error (I'm too embarrassed to admit what exactly)! It works like a dream now - thank you once again!
Oliver
