### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by bcharpentier17000** [aFarkas/lazysizes#811]
There is image links broken in your demo
http://afarkas.github.io/lazysizes/#examples

Also, does this works on background-image ?

**Comment by aFarkas** [comment]
> There is image links broken in your demo
Yeah, I know I had no real interest in fixing them. Maybe I remove the demo.

There are multiple ways to implement background images support.

Here is one:

```html
<div class="foo lazyload"></div>
<style>
.foo.lazyload {
  background-image: none;
}
.foo.lazyloaded {
  background-image: yep;
}
</style>
```

If you want to fix the errors just do it.
