### ISSUE TITLE
Lazyload support for video tag poster

### ISSUE THREAD

**Issue by KyleBurger** [aFarkas/lazysizes#812]
I didn't see it mentioned in the docs, but was wondering about support for lazy loading the poster image on a video element.

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/unveilhooks

**Comment by KyleBurger** [comment]
@aFarkas thanks, this looks like it should work except that the "data-poster" attribute is not being replaced with "poster" when the class "lazyload" has been updated to "lazyloaded".

**Comment by aFarkas** [comment]
https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md
