### ISSUE TITLE
data-size auto selecting image larger than calculated width

### ISSUE THREAD

**Issue by brandlewco** [aFarkas/lazysizes#816]
When inspecting images with data-size="auto" I've noticed it often selects an image with a larger width than required.

```
      <img
      data-sizes="auto"
      data-src="https://img.com/img.jpg?nf_resize=fit&w=450"  
      data-srcset="https://img.com/img.jpg??nf_resize=fit&w=450 450w,
      https://img.com/img.jpg??nf_resize=fit&w=780 780w,
      https://img.com/img.jpg??nf_resize=fit&w=1440 1440w,
      https://img.com/img.jpg??nf_resize=fit&w=1920 1920w"
      class="lazyload"
      alt="caption"/>

```

so an image like this, in a container of 542px, will often select 1440.
as shown in console: image selected / container size format
<img width="466" alt="Screen Shot 2020-07-15 at 12 55 52 PM" src="https://user-images.githubusercontent.com/32404892/87592990-992a3000-c69f-11ea-8992-44ec6f5d9133.png">

[checked this issue and already have image display set to block](https://github.com/aFarkas/lazysizes/issues/800#issuecomment-643572952)

**Comment by aFarkas** [comment]
Without a test case I can not reproduce your issue. If you want to constrain the browsers retina image selection use the optimumx plugin: https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md
