### ISSUE TITLE
Unable to use Lazysize with Desandro's Masonry 

### ISSUE THREAD

**Issue by testcodeaccount2** [aFarkas/lazysizes#817]
I am using the Glint template from Colorlib. It uses Desandro's masonry JS library, and it has an issue being lazyloaded. I have followed the instructions for using Lazysize, but the issue persists.

I have a Codepen of the issue: (https://codepen.io/Kenari7/pen/RwrOedM). A few of the photos at the beginning are not lazyloaded, to show how the masonry should work, but the rest of the photos are lazyloaded. The problem is that those lazyloaded masonry photos overlap each other, and I have no idea how to fix it. All I do know is that resizing the browser window will cause the masonry photos to re-layout themselves, which will fix the overlap issue. This indicates to me that the solution to this issue should be simple.

The Codepen I shared only reveals the section of JS that involves manipulating the masonry library in order to make it easier to work with. The HTML is also exposed.

**Comment by aFarkas** [comment]
This is extensively explained in the [readme](https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps) and in [different issues](https://github.com/aFarkas/lazysizes/issues/424).
