### ISSUE TITLE
Unveilhooks not always firing data-bg correctly?

### ISSUE THREAD

**Issue by jmbattle0** [aFarkas/lazysizes#818]
**Describe the bug**
I am trying to use the unveilhooks plugin to lazyload images with data-bg, however it seems that the images do not always load and display consistently.  I'm using lazysizes 5.2.0, but 

**To Reproduce**
Here is a test URL of a static version of the page I wish to use lazysizes on, this is using data-bg:
https://www.kawai-global.com/menutest/product_static.htm

Here is the actual page which is currently using background:url() to load the images, but looks ugly (because the images display as they are loading):
https://www.kawai-global.com/product/

**Steps to reproduce the behavior:**
Refresh the page at the above URL a few times.
Here is video capture that demonstrates what happens:
https://drive.google.com/file/d/15rYL2PebCGkJ5xF5IWUs9li02CpdHRSn/view?usp=sharing

**What is the expected behavior**
The images should always display.

**What happened instead**
The images sometimes do not display correctly.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Windows 10 desktop, Chrome 84.0

**Comment by warmwhisky** [comment]
Hey did you find any solution to this? I have this issue now. 25% of the time the images do not load and give no hint as to why.

**Comment by jmbattle0** [comment]
Hello,

No, unfortunately, I couldn't find a solution, so just disabled lazyloading on those images... ;(

@aFarkas closed this issue, so I guess he does not believe it is a problem, or that there is a problem with my implementation.

I noticed that the test URL I provided previously was invalid, however the URL should be working again now.

If you're able to find a solution, please let me know!

**Comment by aFarkas** [comment]
@jmbattle0 
Yes, it was offline and I don't believe that it is a script failure. There are many problems that can cause this problem.

For example some carousels do copy the markup change it and throw it back in using `innerHtml` while images are loading. This results to the situation that the DOM references break. Solution use a proper carousel script or delay lazysizes start after the carousel.

In your case it is much simpler. You load every script separate. This results in the situation that you first load lazysizes which starts working and transforms the header images and then after that situation you load unveilhooks. Solution: Combine your scripts or at least load unveilhooks before lazysizes.

**Comment by jmbattle0** [comment]
@aFarkas 

Thank you for your reply.

>Solution: ...load unveilhooks before lazysizes.

That worked, thank you very much!

**Comment by warmwhisky** [comment]
So far so good for me too. I was dreading moving to a different library as my bg images have hover images too which seems tricky to manage.
