### ISSUE TITLE
is there an option to disable the plugin?

### ISSUE THREAD

**Issue by boynet** [aFarkas/lazysizes#82]
I have some heavy website that bassicly is a full page slider with each slide is article with big images, the problem is on some browsers(latest firefox and ie11) while the slider is moving the animation become a bit of laggish while the plugin loading the next close images, is there a way to disable the plugin and re-enable it again?

**Comment by aFarkas** [comment]
I would assume this happening, because image decoding and painting (espeially large and CSS resized) images are a heavy task.

Yes you can. (This was added with version 1.0.1)

```js
//pause the script
lazySizesConfig.loadMode = 0;

//and restart it
lazySizesConfig.loadMode = 3;
lazySizes.loader.checkElems();
```

Please keep me informed ;-).

**Comment by boynet** [comment]
thanks working great :) could be documented

**Comment by aFarkas** [comment]
@boynet 
I'm interested in the cause and whether I might be able to improve the situation. Was this problem caused by checking the position of images while animating (layout trashing) or due to image decoding/resizing/painting. Can you give me an URL, at least as soon as your site is deployed?

**Comment by boynet** [comment]
yes here is the link: http://bit.ly/1Ilyz8R (its bitly cause i dont want it to be inexed)
right now its after the fix if you want me to undo it just say

**Comment by boynet** [comment]
hi @aFarkas :) I think its no longer working?(at least in 3.0.0-rc3)
when I setting` lazySizesConfig.loadMode = 0` after scrolling the` loadMode` is auto changed to 3.

really love this plugin but again I am working on very animated website and on low mobile devices I want to turn off lazysizes when animation occurs

**Comment by theigl** [comment]
I'm also looking for a solution working with the current version of lazysizes. Is there any way to pause the script?

**Comment by sulliops** [comment]
Also looking for a way to pause lazysizes.
