### ISSUE TITLE
Blur-up causing SSR problems in vuejs

### ISSUE THREAD

**Issue by simonmaass** [aFarkas/lazysizes#822]
**Describe the bug**

```
import lazySizes from 'lazysizes';
import 'lazysizes/plugins/blur-up/ls.blur-up';
```

If i also import the blur-up plugin i get SSR problems when using https://ssr.vuejs.org/

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

![image](https://user-images.githubusercontent.com/32599710/90670437-79b09500-e253-11ea-9d71-b088a25ace87.png)

**To Reproduce**
Provide a url where the bug can be reproduced. (Use for example: [jsbin](https://jsbin.com), [codepen](https://codepen.io), [jsfiddle.net](https://jsfiddle.net) or [codesandbox.io](https://codesandbox.io)

**Steps to reproduce the behavior:**
Provide all necessary steps to reproduce the bug.

**What is the expected behavior**

**What happened instead**

**In what environment (browser/device etc.) does this bug happen/not happen:**

**Comment by aFarkas** [comment]
@simonmaass 
I must say that this is one of those harder problems, that can't be fixed. Generally the only way to fix it is by using proper web components to hide the added DOM nodes from vue or to create some kind of vue wrapper. Both things are currently out of scope. Which makes me sad. I might create a web component in some distant future though.
