### ISSUE TITLE
Mutation events and Performance 

### ISSUE THREAD

**Issue by jaxuk** [aFarkas/lazysizes#824]
This is not so much a bug, but an opportunity to make lazysizes even better. 

Currently 2 mutation event types are being used `DOMNodeInserted` and `DOMAttrModified`. It's now recommended to move to using using Mutation Observers instead which are async. More info here: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

**Comment by aFarkas** [comment]
@jaxuk 
`MutationObserver` is already in use. Mutation events are only used as a fallback for IE10.

**Comment by jaxuk** [comment]
Ahh ok... I should have looked deeper into the code. It was picked up by scanning with dareboost.com
