### ISSUE TITLE
Lazysizes responsive images with artdirection and different aspect ratio for devices

### ISSUE THREAD

**Issue by roberthenniger** [aFarkas/lazysizes#829]
We have a theme which uses the lazysizes plugin to lazyload the perfect sized image for every screen size.
Since the theme is using normal img tags which do not support the <picture> tag i was wondering on how we can use responsive images in combination with different aspect ratios. I don't understand how the height parameter can be implemented into the URL. Was testing the following but it seems the height is replaced with an empty string.

`<picture><source data-srcset="//cdn.shopify.com/s/files/1/XXXXXX/XXXXX/XXXX/products/filename_{width}x{height}_crop_center.jpg?v=1598371469" data-aspectratio=1.3> <img data-src="//cdn.shopify.com/s/files/1/XXXXXX/XXXXX/XXXX/products/filename_{width}x{height}_crop_center.jpg v=1598371469" data-media-id="XXXXXXXXX" class="ProductItem__Image Image--lazyLoad Image--fadeIn" alt="image with artdirection" data-widths="[200,400,600,700,800]" data-sizes="auto" data-aspectratio=1.3/></picture>`

Would be very helpful to have an example on where to define the height or aspect ratio? We want the cdn crop the image and not do it on client side.

**Comment by aFarkas** [comment]
Could you please make a full example. From your code I don't understand which plugins you use and if you want support I will need some example to fiddle around.

**Comment by roberthenniger** [comment]
@aFarkas we use the lazysizes and RIaS Plugin.

`<picture><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 2x" media="(min-width: 1200px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 2x" media="(min-width: 992px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 2x" media="(min-width: 768px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_{width}x{height}_crop_center.jpg?v=1598904079 2x" media="(min-width: 576px)"><img src="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_600x600_crop_center.jpg?v=1598904079"></picture>`

I would like to have different aspect ratio work in combination with the data-widths so that lazysizes chooses the best width for the image and calculates the corresponding height. Or can I specify the height for every width manually? This would be my prefered solution since i could calculate it easily.

**Comment by roberthenniger** [comment]
`<picture><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_800x400_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_1600x800_crop_center.jpg?v=1598904079 2x" media="(min-width: 1200px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_400x400_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_800x800_crop_center.jpg?v=1598904079 2x" media="(min-width: 992px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_600x800_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_1200x1600_crop_center.jpg?v=1598904079 2x" media="(min-width: 768px)"><source srcset="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_600x600_crop_center.jpg?v=1598904079 1x, https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_1200x1200_crop_center.jpg?v=1598904079 2x" media="(min-width: 576px)"><img src="https://cdn.shopify.com/s/files/1/0469/0044/5344/files/DAWN_brandimage_AY_03_2048x_1_600x600_crop_center.jpg?v=1598904079"></picture>`

Working picture code with different aspect ration and HDPI images for retina. Have no idea where to specify the data-widths and how the plugin calculates the height based on the data-aspectratio. And what happens when you have the natural aspect ratio and do not have the aspect ratio value?

**Comment by aFarkas** [comment]
> I would like to have different aspect ratio work in combination with the data-widths so that lazysizes chooses the best width for the image and calculates the corresponding height. Or can I specify the height for every width manually? This would be my prefered solution since i could calculate it easily.

You can do both as you like. But I really can not write the code for you. Either read the manual more carefully or at least provide enough information and follow the simple bug reporting template: https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by roberthenniger** [comment]
@aFarkas Can you at least point me into the direction? I havent seen something like that in the docs. And I dont want to send a bug report. Would argue that the docs do miss examples here and is quite thin when it comes to art direction
