### ISSUE TITLE
Flickering images on many small images load (throttleDelay)

### ISSUE THREAD

**Issue by jakubsemerak** [aFarkas/lazysizes#830]
I need to show a lot of small images in menu immediately after mouse hover. Now when I use as low throttleDelay as recommended, I still get flickering images after hovering mouse menu. Can I please somehow force those images to be loaded immediately after menu is shown? I do not want to preload those images and also want to respect throttleDelay recommendation (min 66). Or what are the dangers to use throttleDelay below 66?

Or could I change the batch of how many images are  will be shown at the same time?

https://i.imgur.com/AiCNu0L.gif

Thank you very much! :)

**Comment by aFarkas** [comment]
Simply use the JS API to force load all images in that submenu on first `:hover`.
