### ISSUE TITLE
lazysizes - Aspect ratio not working for sources when {width} and {height} placeholders used

### ISSUE THREAD

**Issue by roberthenniger** [aFarkas/lazysizes#831]
Aspect Ratio is not calculated for every picture source and only taken from the img itself.

https://jsfiddle.net/roberthenniger/o6qzsh9m/
https://stackoverflow.com/questions/64431104/lazysizes-aspect-ratio-not-working-for-sources-when-width-and-height-place

Would expect the lazysizes to use the aspect ratio from the source instead of image since otherwise no different aspect ratio for different screen size is possible. 

**What happened instead**
Lazysizes uses the aspect ratio from the img tag itself.

Tested on Chrome 85. on Mac, Safari 14.0

**Comment by roberthenniger** [comment]
Also saw that issue https://github.com/aFarkas/lazysizes/issues/490which seems not the same topic. Was trying to use a custom function to calculate the height myself but it seems that its only triggered for the img tag itself and not four all sources of the picture.

**Comment by aFarkas** [comment]
I have just added a [fix for this](https://github.com/aFarkas/lazysizes/commit/c42e73b1c08aacc05af848577138efc46d0b9df8). Could yoou checkout and try the newest change? Thank yo
