### ISSUE TITLE
Responsive support not working anymore on Chrome

### ISSUE THREAD

**Issue by AnderUstarroz** [aFarkas/lazysizes#833]
This is very weird but seems like responsive images using data-srcset doesn't work anymore on Chrome, I was getting crazy on my project when I actually find out it doesn't work on the Demo page either. 

**Steps to reproduce the behavior:**

1. Go to the [Demo page](http://afarkas.github.io/lazysizes/#examples) using Chrome (v86.0.4240.111).
2. Go to section "**Responsive image with srcset and sizes attribute**"
3. Reduce the size of the browser into a 500px wide window.
4. Right click and "Copy image address"

**What is the expected behavior**
According the code:
```
<img sizes="460px" data-sizes="auto" data-src="https://farm5.staticflickr.com/4078/5441060528_31db7838ba_z.jpg" data-srcset="https://farm5.staticflickr.com/4078/5441060528_31db7838ba_m.jpg 240w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_n.jpg 320w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba.jpg 500w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_z.jpg 640w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_b.jpg 1024w" class="no-src lazyautosizes ls-is-cached lazyloaded" srcset="https://farm5.staticflickr.com/4078/5441060528_31db7838ba_m.jpg 240w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_n.jpg 320w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba.jpg 500w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_z.jpg 640w,
	https://farm5.staticflickr.com/4078/5441060528_31db7838ba_b.jpg 1024w" src="https://farm5.staticflickr.com/4078/5441060528_31db7838ba_z.jpg">
```
The following image must be loaded:
`https://farm5.staticflickr.com/4078/5441060528_31db7838ba.jpg` (500w)

**What happened instead**
The image `https://farm5.staticflickr.com/4078/5441060528_31db7838ba_b.jpg` gets loaded.

**In what environment (browser/device etc.) does this bug happen:**
- **Chrome** Version 86.0.4240.111 (Official Build) (x86_64) 
Tested on a MAC OS Catalina 10.15.7 (19H2)

**Comment by aFarkas** [comment]
This works fine for me: maybe read this article: https://learnedia.com/responsive-images-srcset-attribute-picture-element/
