### ISSUE TITLE
How to disable lazyload for viewport backgroundimage, but still use data-bgset for responsivness

### ISSUE THREAD

**Issue by mshefiti** [aFarkas/lazysizes#834]
I would like to know if there is a way to disable lazyload for viewport backgroundimage, but still use data-bgset to make the background image responsive?

**Comment by aFarkas** [comment]
can't understand.

**Comment by mshefiti** [comment]
I want to use the "bgset.js" independent from lazyload. 
Is that possible?

**Comment by LeadDreamer** [comment]
Am I being too snarky when I say "you can copy the code and use it how you want"?  You don't have to only use the NPM package.  I've done this for a few projects where the packaged functionality doesn't match my use - I just lose the support and updates, but then again, I'm taking ownership of my own problems.

**Comment by aFarkas** [comment]
Or zou can read the manual. The answer is described there.

**Comment by mshefiti** [comment]
> Or zou can read the manual. The answer is described there.

And "zou" could have given a hint, instead of assuming people dont read short manuals.
