### ISSUE TITLE
Lazysizes chooses smaller image instead of bigger image

### ISSUE THREAD

**Issue by bartrylant** [aFarkas/lazysizes#836]
I'm using lazysizes with images in a responsive Bootstrap setup. It looks like lazysizes chooses the image below the needed width instead of the better image. E.g., I have multiple images in the srcset

```
image-small.png 400w,
image-large.png 800w
```

If I load the webpage and the initial size of the container (and image width = 100%) is 680px, lazysizes shows image-small.png instead of image-large.png. When I resize the page, it changes for the better picture.
I've checked with setting the width of the images to 100% of the parent, and also tried the parent fill plugin. but no succes.

**Comment by bartrylant** [comment]
It seems that lazysizes sets `sizes="115px"` (even when I inspect in dev tools, the container has a width of 680px). I have no idea where this comes from…

**Comment by jurajkapsz** [comment]
> It seems that lazysizes sets sizes="115px" (even when I inspect in dev tools, the container has a width of 680px). I have no idea where this comes from…

@bartrylant What was the solution? I have the same issue, with every screen resize, the `sizes` value just gets smaller.

**Comment by bartrylant** [comment]
I've added
```
<script type="text/javascript">
$(document).on('lazybeforesizes', function(e){
    //use width of parent node instead of the image width itself
    (e.orginalEvent || e).detail.width = $(e.target).parents(':not(picture)').innerWidth() || e.detail.width;
});
</script>
```
and
```
<style>
   img[data-sizes="auto"] { display: block; width: 100%; }
</style>
```
This seems to work. I've never had to do something like this before, but I never use bootstrap so I don't know the quirks of it.

**Comment by jurajkapsz** [comment]
@bartrylant Thanks very much! I was able to do it with the `lazybeforesizes` event and setting up my own width.
