### ISSUE TITLE
Some images in demo are returning a 4xx

### ISSUE THREAD

**Issue by sherwinski** [aFarkas/lazysizes#838]
**Describe the bug**
Hey there 👋, just wanted to give you a heads up that some of the images on the [lazysizes demo](https://afarkas.github.io/lazysizes/#examples) are missing/returning an error.

**To Reproduce**
https://afarkas.github.io/lazysizes/#examples

**Comment by aFarkas** [comment]
Yeah, if someone wants to fix. I appreciate a PR maybe even with better images.
