### ISSUE TITLE
Size is not calculated correctly

### ISSUE THREAD

**Issue by yellow1912** [aFarkas/lazysizes#839]
**Describe the bug**
The larger src is used instead of the correct one

**To Reproduce**
I created a codepen here, I also have a link to the live site if you want I can send directly via PM
https://codepen.io/raineng/pen/mdEZxzM

**Steps to reproduce the behavior:**
On this same site, most images are loaded correctly on mobile, but a few are being loaded with wrong size. It seems like it has something to do with object fit setting

**What happened instead**
In mobile mode, 320x480, 1024w version is used, perhaps 512w should be used instead?

**In what environment (browser/device etc.) does this bug happen/not happen:**
I tried on latest version of Chrome and Firefox on Windows

----------------------------------------------------------
Edit 1:

I tried to remove all object-fit but the same issue still happens.

Edit 2"

I think this happens because the default DPR for my browser is set to 2 now, if it is changed to 1 then then the correct size will be used. I will need to look into this more.

**Comment by aFarkas** [comment]
Please read a) a good article about responsive image one that explains art direction and resoltuion switching and b) read the lazysizes especially the part how  `data-sizes="auto"` works.

**Comment by yellow1912** [comment]
You are right, it's not about art direction though, it's the sizes thing (dpr) that tripped me up.
