### ISSUE TITLE
Any possibility to prevent browser upscaling low-res images to a certain %?

### ISSUE THREAD

**Issue by wcoppens** [aFarkas/lazysizes#84]
I'm experiencing a similar issue like https://code.google.com/p/chromium/issues/detail?id=456084 in which the 'image decision' mechanism of chrome decides to upscale a low-res image to a certain % between the low-res and high-res image. 

I was wondering what the best practices would be with Lazysizes to solve this issue?
One i'm considering is by telling chrome the image is 400px width but actually is 600 or 800 (depending on the diff between low/high res version)

Thanks!

**Update** 

I just found a similar issue about this question, sorry!

**Comment by aFarkas** [comment]
One of the solution in #51 helped? 

In general it would be useful, if you would provide an example there: https://code.google.com/p/chromium/issues/detail?id=456084

**Comment by wcoppens** [comment]
Well i decided to wait until chrome comes with a better implementation of the src-set. 

I will provide the example anytime soon.
