### ISSUE TITLE
lazysizes with picture and responsive "sizes" and "srcset" parameters

### ISSUE THREAD

**Issue by steveoriol** [aFarkas/lazysizes#840]
**Describe the bug**
When i use lazysizes with picture and responsive "sizes" and "srcset" parameters, the images do not load in the right dimension. 

**To Reproduce**
[codepen](https://codepen.io/steveoriol/pen/ExyBRmL)

**Steps to reproduce the behavior:**
with the codepen window, try to modify the width of the window.

**What is the expected behavior**
For a width of 350px on a computer (ratio of 1), the correct image of 400x400px will load well, but it is not dimensioned to 80 of the width ....

For a width of 930px on a computer (ratio of 1), the correct image should be the image of 200x200px while it is the image of 1000x1000 that is loaded.

For a width of 1240px on a computer (ratio of 1), the correct image should be the image of 250x250px while the image of 1000x1000 is loaded.

For iPhone 6/7/8 (375x667 ratio of 2), the correct image should be the 600x600px image while the 800x800 image is loaded.

**Comment by steveoriol** [comment]
Apparently, it works much better if I leave the "sizes" in the "source" tags rather than putting "data-sizes":
https://codepen.io/steveoriol/pen/JjKgOmo

**Comment by aFarkas** [comment]
@steveoriol 
I think your expectations are quite wrong here. `data-sizes` simply and only has one value meaning `data-sizes="auto"`. I simply copy `data-sizes` to `sizes` if someone adds something else into it. But this has no lazysizes  functionality and to be honest I never understood why some people write such code. I'm pretty sure this fallback it is not even documented.

By not using `data-sizes="auto"` and removing `sizes` from your `source` elements you totally destroy everything, but no one says you should do this.

**Comment by steveoriol** [comment]
Thank you Alexander, 
But I do not understand why if I use `data-sizes="auto"` for the `source` elements, I do not have the same result as if I set directly the `sizes` for the `source` elements to the value of the `data-sizes` of the `img` element ? (If you simply copy it...)
Example: https://codepen.io/steveoriol/pen/JjKgOmo?editors=1000

**Comment by aFarkas** [comment]
There is no `data-sizes` on `source` elements only on `img`. It doesn't make too much sense to implement something like this. Not even the HTML standard discusses adding `autosize` to a `source` element.
