### ISSUE TITLE
Lazy Load video-js tags (Brightcove video player)

### ISSUE THREAD

**Issue by markhume** [aFarkas/lazysizes#844]
I've been using lazysizes and it's working great for images and iframes.  However some videos that I have embedded from Brightcove are using their < video-js > tag for the player in place of a normal < video > tag.  Is it possible to lazyload this content?  I see you can use the unveilhooks.js plugin for some tags but I couldn't work out how to use it for <video-js>

Any tips appreciated!

**Comment by aFarkas** [comment]
Yes, you have a `lazybeforeunveil` event that you can use to start video js on the element.  But from this event you have to use the video-js API. Can't help you there.
