### ISSUE TITLE
Feature request: option to load force load images above fold first

### ISSUE THREAD

**Issue by thdoan** [aFarkas/lazysizes#845]
There are some cases where images just below the fold (but within the expand zone) load before the images above the fold, possibly because they have a smaller file size or some other reason. Is there a way to configure lazysizes to force load visible images above the fold before starting to lazy load the other images right below the fold but within the expand zone?

**Comment by aFarkas** [comment]
yes, rtfm. loadmode

**Comment by thdoan** [comment]
I rtfm.

https://cdpn.io/thdoan/debug/KKgaBPM/ZoABaLyejjGr

![image](https://user-images.githubusercontent.com/4110567/102026482-e72c8800-3d52-11eb-9d95-5559dd51fd95.png)

It doesn't happen every time, but image 3 should never be loaded before image 2 if `loadMode = 1`.

**Comment by aFarkas** [comment]
I was checking it. But now it is gone. Also the test case was not clear to me. All your `source` elements had proper `srcset` attributes was this intentional?
