### ISSUE TITLE
Any point in using loading="lazy" alongside LazySizes?

### ISSUE THREAD

**Issue by TheMangoTrain** [aFarkas/lazysizes#846]
HTML5's `loading="lazy"` is a good start to have native lazy-loading, but it's crude. Presumably you still need to build your own logic to deliver any of the features that LazySizes offers.

**Question:** Considering the above, is there any point to ever use `loading="lazy"` (instead of LazySizes), other than in a barebones web foundation (without external JS libraries)?

**Question:** Is there a risk of conflict by having both on the same element? Is this already handled in LazySizes?

**Comment by aFarkas** [comment]
I hope native loading gets better, but using native lazy loading and lazysizes at the same time isn't indeed that useful. I just made a plugin for the early adopters but don't see a reason why someone should use it.
