### ISSUE TITLE
data-bgset not auto-sizing to parent container

### ISSUE THREAD

**Issue by c9mbundy** [aFarkas/lazysizes#847]
I'm having trouble getting this to work, and assume that I'm doing something wrong,

In a case such as below - is this the correct specification for data-bgset?

Basically, I want to to choose the first image large enough to cover the parent with, without upscaling.
I also want it to reselect the image if the viewport size changes, hence changing the width of the parent container.
In practice, it always gets the last image for the largest resolution, which is much larger than necessary to meet the parent width.

```
<script src="/ls.bgset.min.js"></script>
<script src="/ls.parent-fit.js"></script>
<script src="/lazysizes.min.js"></script>

<div style="width:25%; height:auto;">
	<div class="lazyload"
		data-bgset="/image270.jpg [(max-width: 270px)] | /image320.jpg [(max-width: 320px)] | /image480.jpg [(max-width: 480px)] | /image640.jpg [(max-width: 640px)] | /image768.jpg [(max-width: 768px)] | /image992.jpg [(max-width: 992px)] | /image1920.jpg"
		data-sizes="auto"
		style="background-size:cover;width:100%;height:auto;padding-top:calc(100%*9/16);">
	</div>
</div>
```

**Comment by c9mbundy** [comment]
Some more testing indicates that it's selecting the image based on the viewport width, rather than the parent width.

I have data-sizes="auto" and the css setting  background-size:cover - which I thought were the triggers for parent sizing ??

**Comment by aFarkas** [comment]
1. without a test case it is impossible to check what is going wrong. (follow: https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md)
2. bgset is deprecated for the use of background-size cover.
3. you are using `sizes` with art direction which does not make any sense.

Please read an article about how to properly use responsive image (until you understand what I mean with point 3). If you still fail, create a test case and re-open.

**Comment by c9mbundy** [comment]
Thanks.

Actually, I think I understand #3 and I had tried using resolution switching:

`data-bgset="/image270.jpg 270w, /image320.jpg 320w, /image480.jpg 480w, /image640.jpg 640w, /image768.jpg 768w /image992.jpg 992w, /image1920.jpg"`

But it was likewise always falling through to the last image, so I tried using art-direction thinking that perhaps the plugin(s) used that as a guide for the parent size.

So are you saying that data-bgset will not support background-size:cover for data-sizes="auto" and hence the fall-through ?

This is problematic for me, as the images are not consistently sized, which is why I needed 'cover' sizing.

Is there any way around this?

**Comment by aFarkas** [comment]
1. in case of resolution switching especially with chrome. Chrome always takes last if this image is already in cache.
2. no data-bgset would support cover also with data-sizes="auto" in case of art direction you won't need sizes though.

But I would urge you to use `object-fit` on the image itself. It's basically the same thing but much better without any custom syntax and better performance. In case you need to support old browser use either this lazysizes only one
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit or the other most used one.
3. to help you concrete I still need test case.
