### ISSUE TITLE
When testing lazy+responsive images, Chrome is loading a version of the images much wider than my viewport's width

### ISSUE THREAD

**Issue by thomas-wisc** [aFarkas/lazysizes#852]
Hi,

I'm using the last JS version of the JS library, and created the following piece of code, trying to show an image in a lazy and responsive way.

```
<center><picture>
<source type="image/webp" data-srcset="myimage_480_252.webp 480w, myimage_680_357.webp 680w, myimage_768_403.webp 768w, myimage_1024_538.webp 1024w, myimage_1600_840.webp 1600w">
<source type="image/png" data-srcset="myimage_480_252.png 480w, myimage_680_357.png 680w, myimage_768_403.png 768w, myimage_1024_538.png 1024w, myimage_1600_840.png 1600w">
<img class="lazyload" data-src="myimage_800_420.png" width="800" height="420" alt="My Image" title="My Image">
</picture></center>
```

I tested it with the last version of Google Chrome and the mobile viewport. If I browse the 'Network' tab, when I scroll down to the image, Chrome loads the '1024_538.webp' version, when I expected that the 480, 680 or 768 width images were loaded.

As far as I understand, the web-browser checks the mobile viewport's width, and then load the appropriate version of the image. I tried with the 'Responsive' option of mobile devices, and also with 'Surface Duo' (width = 540), 'iPad' (width=768) or 'Moto G4' (width=360). But Chrome loads always the 1024 or 1600 width image.

I inserted the following code to get the dimensions
```
setTimeout(function(){
    alert(Math.max(document.documentElement.clientWidth, window.innerWidth) +'x'+ (window.devicePixelRatio));
});
```
and, for instance, for 'Moto G4' I get "360x3" and Chrome loads the 1024 width image.

**What happened instead**

**In what environment (browser/device etc.) does this bug happen/not happen:**

**Comment by aFarkas** [comment]
It is funny that you post your monologue simply above the questions to produce a concise bug report. This is not how you should report a bug. And this is no bug. lazysizes core doesn't influence image candidate selection at all. but you can if you want with optimumx plugin.

**Comment by thomas-wisc** [comment]
Dear @aFarkas,

My sincere apologies for having disturbed you. This is the first time I report a bug via GitHub, and I thought I was doing it in the right way.

Best wishes,
T
