### ISSUE TITLE
How to add a class to a parent after image is lazyloaded

### ISSUE THREAD

**Issue by Celio2021** [aFarkas/lazysizes#854]
Hi,

First of all, thank you for your excellent and beautiful work.

I have an image embed in a link (a element). Followed by a figcaption. I would like that the figcaption only appears when the image contains the lazyloaded class.

I have tried several things in jquery, but nothing that works correctly.

I am a perfect beginner, sorry for this question, maybe a little naive. Sorry for my bad english too.
Thank you already for your help.

Celio

**Comment by aFarkas** [comment]
Hi Celio,  

no problem. Something that would be nice in the future: You should provide me with the code that you got so far. With your problem I needed 15 minutes to reproduce your problem and then 2 minutes to fix it. Please follow the issue template.

I think the following jsbin should help:
https://jsbin.com/sezaxicebi/1/edit?html,output
