### ISSUE TITLE
Url of images in srcset having whitespace on Safari

### ISSUE THREAD

**Issue by nedimcimpo** [aFarkas/lazysizes#855]
When image url is inspected in Safari and is having "," inside url for any reason, whitespace is shown after "," sign and image appears to be broken

This: f_auto,q_auto,fl_preserve_transparency,c_limit,w_1920 becomes
this : f_auto, q_auto, fl_preserve_transparency, c_limit, w_1920

Issue is only with Safari, on Chrome, FF, Edge... all is working as expected

OS: MacOS 11.1
Browser: Safari 14.0.2

<img width="1666" alt="Screenshot 2021-01-07 at 14 38 53" src="https://user-images.githubusercontent.com/10185705/103899582-e3dcb000-50f6-11eb-9cdd-32776e6ba4dc.png">

**Comment by aFarkas** [comment]
I would assume that this is a browser bug. But could you please provide a test case on jsbin or codesandbox to make reproducible.

**Comment by nedimcimpo** [comment]
https://codesandbox.io/s/happy-sea-e8on1?file=/src/App.js

**Comment by aFarkas** [comment]
@nedimcimpo 
This seems to be a simple formatting issue of Safari's dev HTML view. There are no whitespaces. You can check the console output here:
https://codesandbox.io/s/musing-frost-7nbl5?file=/src/App.js

Please close if this solves your problem or give me some more information about your problem.

**Comment by nedimcimpo** [comment]
I know but soon as it gets into ... DOM, Safari adds white spaces.
I will close this as an issue on this library but issue with Safari still remains. Thx.

**Comment by aFarkas** [comment]
@nedimcimpo 
I don't understand what you mean. I'm logging the `srcset` and `currentSrc` from the DOM and there are no whitespaces it is a pure style issue of Safari's dev tools. They obviously wanted to pretty print the `srcset` value, but are using a simplified srcset parsing algorithm.

**Comment by opassion** [comment]
@nedimcimpo I have the same problem. Do you have any solution? This is definitely not this library issue. But Safari is adding white space automatically after comma.

**Comment by nedimcimpo** [comment]
> @nedimcimpo I have the same problem. Do you have any solution? This is definitely not this library issue. But Safari is adding white space automatically after comma.

@opassion 
No. Safari is still adding whitespace but I have to say that it works fine now. How? It beats me.
