### ISSUE TITLE
Print mode for the page. No pictures

### ISSUE THREAD

**Issue by uPagge** [aFarkas/lazysizes#856]
When the page is printed, all the pictures are missing, instead the loading icon. Maybe fix it somehow

**Comment by aFarkas** [comment]
@uPagge 
Sadly to my knowledge this is not possible. Some years ago I experimented with something like this:
https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/print/ls.print.js which worked in IE but not others. Something that might be possible is to start download all images if the user wants to print, then render an info with CSS print stylesheets that he should abort and then re-print to get all images.

As I remember not even the native `picture` element support `source media="print"`. With something like that it would be possible. If you want to try do it ;-)
