### ISSUE TITLE
Disable lazy loading but keep sizes="auto" for above the fold images.

### ISSUE THREAD

**Issue by powerfulwebdesign** [aFarkas/lazysizes#860]
It would be great if there was a way to turn off the loading="eager" tag generation so that above the fold images arent lazy loaded. The sizes="auto" feature is amazing for srcset images, so its not worth turning off lazysizes completely.

**Comment by aFarkas** [comment]
I'm not sure wether I understand you: But if an image is in view it is already **immediately** lazy loaded. You can't get it faster.

**Comment by powerfulwebdesign** [comment]
I probably wasn't very clear. When native lazy loading browser support is turned on, all of the lazy loaded images are given the loading="lazy" tag, even if they are above the fold. Setting loading="eager" would be great for above the fold. 

You plugin's autosizes feature is very useful, so turning off lazysizes for above the fold images is not an option.

**Comment by bekahmcdonald** [comment]
I agree, @powerfulwebdesign. This would be a really useful feature to have.

**Comment by aFarkas** [comment]
@bekahmcdonald and @powerfulwebdesign 
If an image is above the fold `loading="lazy"` is handled the same way as if you would add `loading="eager"`. There is nothing to do here.

**Comment by bekahmcdonald** [comment]
I don't agree, but understand the impact is minimal. 
https://web.dev/browser-level-image-lazy-loading/#avoid-lazy-loading-images-that-are-in-the-first-visible-viewport

**Comment by aFarkas** [comment]
@bekahmcdonald 
Your disagreement is based on a knowledge gap.

In short: The difference of `loading="lazy"` vs `loading="eager"` is by no means minimal! You should add `eager` to initially in view images and the perf difference can be quite dramatic. Of course if you need `sizes="auto"` you can't.
But at the time lazysizes is executed there is no performance benefit to use `eager` anymore... 

This is also why there might be a native `sizes="auto"` or `autosize` in the future, but only in conjunction with `loading="lazy"`.

To understand, read this: https://calendar.perfplanet.com/2013/big-bad-preloader/

**Comment by bekahmcdonald** [comment]
Ah, that makes sense. I can see now I was thinking about this in totally the wrong way. 

Thanks for the knowledge share!
