### ISSUE TITLE
getOptimumX is never called

### ISSUE THREAD

**Issue by yellow1912** [aFarkas/lazysizes#863]
**Describe the bug**
The function to get optimumx is never called (I'm using latest version of the plugin and latest version of lazysizes 5.3.0)

**To Reproduce**
I used the following configs:

```
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.constrainPixelDensity = true;

window.lazySizesConfig.getOptimumX = function (_element) {
  console.log('aaaaaaaaaaaaaaaa');
  // calculation goes here
}

```

My image looks like this:

`<img class="object-cover w-full h-full object-center img-fluid lazyload" loading="auto" width="256" height="256" data-optimumx="auto" data-src="https://mysouce.com/assets/img/kv_1603350960_small.jpg" data-srcset="https://mysouce.com/assets/img/kv_1603350960_tiny.jpg 64w, https://mysouce.com/assets/img/kv_1603350960_small.jpg 256w, https://mysouce.com/assets/img/kv_1603350960_medium.jpg 512w, https://mysouce.com/assets/img/kv_1603350960_large.jpg 1024w" data-sizes="auto" data-aspectratio="1" >
`
**What is the expected behavior:**

I expect getOptimumX to be called, or perhaps I misunderstand how it should work?

**What happened instead:**

It seems like a wrong version of the image is displayed which causes it to look blurry

**In what environment (browser/device etc.) does this bug happen/not happen:**

It happens on latest Chrome

**Keywords help others to find this issue:**
OptimumX

**Comment by aFarkas** [comment]
without a test case I can not reproduce your issue. It works for me just fine.

**Comment by yellow1912** [comment]
Sorry, after further checking, this is not a bug but a big mis-understanding of how javascript work on my end I think.

I was doing something like this


```
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.constrainPixelDensity = true;

window.lazySizesConfig.getOptimumX = function (_element) {
  console.log('aaaaaaaaaaaaaaaa');
  // calculation goes here
}
import 'lazysizes';
import 'lazysizes/plugins/bgset/ls.bgset';
import 'lazysizes/plugins/native-loading/ls.native-loading';
import 'lazysizes/plugins/parent-fit/ls.parent-fit';
import 'lazysizes/plugins/object-fit/ls.object-fit';
import 'lazysizes/plugins/aspectratio/ls.aspectratio';
import 'lazysizes/plugins/optimumx/ls.optimumx';

lazySizes.init();
```

I was thinking that the code will be executed in order, I was wrong. The import is done first before anything else so I have to move the configuration out to another file and import it on top of everything.

**Comment by aFarkas** [comment]
if you use `import` you shouldn't use the global config at all.

```js
import lazySizes from 'lazysizes';
/* ... */
Object.assign(lazySizes.cfg, {
    // your config
});

lazySizes.init();
```

**Comment by yellow1912** [comment]
Thank you @aFarkas for showing me the right way to do it, fixed in my code.
