### ISSUE TITLE
Can you please explain a bit regarding the number returns by getOptimumX?

### ISSUE THREAD

**Issue by yellow1912** [aFarkas/lazysizes#864]
**Describe your problem/question**
On the readme page of the plugin, I see an example code like this:

```
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.config.getOptimumX = function(/*element*/){
    var dpr = window.devicePixelRatio || 1;
    if(dpr > 2.5){
        dpr *= 0.6; // returns 1.8 for 3
    } else if(dpr > 1.9){
        dpr *= 0.8; // returns 1.6 for 2
    } else {
        dpr -= 0.01;
    }
    return Math.min(Math.round(dpr * 100) / 100, 2);
};
```

My question is related to the part where you try to return say 0.99 for 1, why should we always reduce that number a bit like that instead of returning exactly 1? I could not find it mentioned anywhere on the readme.

**Add tags/keywords**
optimumx

**Comment by aFarkas** [comment]
If you set optimumx to the same value as the users dpr or lower the image candidates are not constrained and only the browsers native implementation is used. This can result in to the situation that a browser with `1` dpr chooses `2` dpr image because the next lower resolution is `0.95`
