### ISSUE TITLE
Issues with navbar link scrolling and section offset

### ISSUE THREAD

**Issue by sulliops** [aFarkas/lazysizes#865]
On one of my websites, I use a bit of jQuery to have navbar links smooth scroll down to the sections they link to using "easeInOutExpo". After finding this plugin, I implemented it with all the images on a page (there are many) in order to reduce page load time.

The problem is that, now, clicking my navbar links to scroll down to the appropriate section results in an offset on top of the start of the section I navigated to, because lazysizes is loading all the images of various heights before it.

Is there any part of the plugin that would allow me to retain the size of the image before it actually loads, thus keeping the parent divs at the right responsive height? The simple way to solve my issue would be to set a height for each image div according to the image's actual size, however that breaks things on different size devices as I'm using Bootstrap's responsive image classes.

**Comment by aFarkas** [comment]
> Is there any part of the plugin that would allow me to retain the size of the image before it actually loads, thus keeping the parent divs at the right responsive height?

No, it is not possible to know the height on client side before the image is (partially) loaded.  You can solve this by implementing [aspect ratio pattern using CSS](https://github.com/aFarkas/lazysizes#user-content-specify-dimensions) in a responsive way. For that you must know the height and width of your images this can be done server side.
