### ISSUE TITLE
lazysizes in jsdelivr gives bad performance in Google Pagespeed

### ISSUE THREAD

**Issue by dickyj** [aFarkas/lazysizes#866]
Hi,
Just recently, I put my site thru Google Pagespeed using
"https://cdn.jsdelivr.net/npm/lazysizes@5.3.0/lazysizes.min.js"

It is giving very inconsistent results ranging from load times of 1s to 4s.
That lowers the score of pagespeed dramatically.
Any reason why it occurred recently?
Thanks.

**Comment by aFarkas** [comment]
Obviously without seeing the page I can only guess and I don't do that.

If performance is a concern you should combine your scripts and shouldn't link to a third party server. At the end page speed is an artificial test and the load time doesn't say too much about performance.
