### ISSUE TITLE
sizes=auto returns a very big number

### ISSUE THREAD

**Issue by yellow1912** [aFarkas/lazysizes#867]
**Describe the bug**

data-sizes="auto" returns a huge number like 334080px (not always this number but always a huge number which makes no sense)

**To Reproduce**
Please check this link https://codepen.io/raineng/pen/bGBLLjo

**Steps to reproduce the behavior:**
It seems like a unique mix of image with position absolute, object-fit cover and perhaps some other conditions I have not been able to pinpoint. 

**What is the expected behavior:**
Sizes should be calculated correctly.

**What happened instead:**
A huge sizes is returned thus the large src-set is always used.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Windows 10, latest chrome. Seems to happen on Android, latest chrome as well. Firefox seems to have the same issue however.

**Keywords help others to find this issue:**
sizes auto, huge sizes, wrong sizes

**Comment by aFarkas** [comment]
The parent-fit plugin doesn't support a `data-aspectratio="3840/2160"` value like this. Only the calculated value is supported: hence: `data-aspectratio="1.778"` would be ok.

Also I would suggest that you remove the aspect-ratio plugin entirely you can do this with CSS much better (use inline CSS for padding-bottom). The aspect-ratio plugin was for multiple `source` elements.

**Comment by yellow1912** [comment]
Thank you, what you suggested fixed the issue. I did both things that you recommended.
