### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#87]
Hi!
I have found a possible bug. Not sure if I screwed up the markup or not. Please take a look!

Here's the code:
```
<picture>
     <!--[if IE 9]><video style="display: none;"><![endif]-->
     <source data-srcset="http://lorempixel.com/output/nature-q-c-427-407-9.jpg" media="(min-width: 480px)">
      <!--[if IE 9]></video><![endif]-->
     <img data-srcset="http://lorempixel.com/output/nature-q-c-427-407-3.jpg" class="lazyload">
</picture>
```

Images are loaded by an ajax-call after page load and added to the dom.
Whenever the screensize in smaller than 480px they aren't lazyloaded. 
Not on resize either. Unless you resize to at least 480px. Then they get loaded like they should.
If I remove the <source> element it's working. To make things even trickier I have to mention that it's so far it's only Chrome on desktop. Firefox works fine. So it's really an edge case!

**Comment by aFarkas** [comment]
Your markup looks good and I couldn't really reproduce it. I'm currently at work will try later.

**Comment by aFarkas** [comment]
Just a short question, does it help if you add the following element as first child to your ``head``:

```html
<meta name="viewport" content="width=400, initial-scale=1" />
```

**Comment by aFarkas** [comment]
Or does it help if you have the following markup?

```html
<picture>
     <!--[if IE 9]><video style="display: none;"><![endif]-->
     <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="http://lorempixel.com/output/nature-q-c-427-407-9.jpg" media="(min-width: 480px)">
      <!--[if IE 9]></video><![endif]-->
     <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="http://lorempixel.com/output/nature-q-c-427-407-3.jpg" class="lazyload">
</picture>
```

Do you use the emulate feature of chrome devtools?

**Comment by aFarkas** [comment]
@JonWallsten 
Do you have any information on this, did something above help?

**Comment by JonWallsten** [comment]
Sorry, been a really busy day! I'll report back soon!

**Comment by JonWallsten** [comment]
I'm using <meta name="viewport" content="width=device-width, initial-scale=1" /> already btw.

**Comment by aFarkas** [comment]
Then please just try this markup:

```html
<picture>
     <!--[if IE 9]><video style="display: none;"><![endif]-->
     <source data-srcset="http://lorempixel.com/output/nature-q-c-427-407-9.jpg" media="(min-width: 480px)">
      <!--[if IE 9]></video><![endif]-->
     <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="http://lorempixel.com/output/nature-q-c-427-407-3.jpg" class="lazyload">
</picture>
```

And if this doesn't help, the following markup:

```html
<picture>
     <!--[if IE 9]><video style="display: none;"><![endif]-->
     <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="http://lorempixel.com/output/nature-q-c-427-407-9.jpg" media="(min-width: 480px)">
      <!--[if IE 9]></video><![endif]-->
     <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="http://lorempixel.com/output/nature-q-c-427-407-3.jpg" class="lazyload">
</picture>
```

**Comment by JonWallsten** [comment]
Back at work! Will try now.

**Comment by aFarkas** [comment]
Ok, thank you. Well it is always recommended to add a data uri, but I filed an issue here:
https://code.google.com/p/chromium/issues/detail?id=478153
