### ISSUE TITLE
Images does not show in IE browser

### ISSUE THREAD

**Issue by ashehzadgec** [aFarkas/lazysizes#870]
**Describe your problem/question**
A complete but concise description of your problem and how you are trying to fix it and where you are struggling.
I am using awesome library with loading=lazy attribute with fallback code when lazy attr is not supported by browser then call the lazysizes. Everything seems to work fine until I test it on IE browser. Can you guide me why is that happening? Do I need to use polyfill for that if that then will I need to put it before body on each page or how. Bcs I don't see any option to install it through npm and then import in bundler.
**Make it reproduce-able**
If your problem is with code or the expected answer should include code provide a live code example using https://jsbin.com/ or https://codesandbox.io/.

// this is the code I am using

if ('loading' in HTMLImageElement.prototype) {
		const images = document.querySelectorAll('img[loading="lazy"]');
		images.forEach((img) => {
			img.src = img.dataset.src;
		});
	} else {
		// Dynamically import the LazySizes library
		const script = document.createElement('script');
		script.src = './lazysizes.min.js';
		document.body.appendChild(script);
	}

**Add tags/keywords**
Make sure others can find your problem.

⚠️ Search for existing open/closed issues/discussions before you ask your question.
⚠️ I work on my spare time on helping users out. This means make it easy for me to simply see your live problem and help to fix it.
🤘 No panic: Don't be afraid to ask a question.

**Comment by ashehzadgec** [comment]
Hey

I am using locomotive smooth scroll with your library but default configuration causing one issue that my page is not fully scrolled when a media query is activated. I found this thread on locomotive page. Can you help me how I can use your library with it.

Pls also reply the first above questions too. I really appreciate your efforts.

Regards,
Shehzad Asif

**Comment by aFarkas** [comment]
@ashehzadgec 
Your second post sounds like a different problem. About `import` and `install` that is documented in the readme:

The package is called `layzsizes` and is exported as a default module. You can configure it over the `cfg` key:

```js
import lazysizes from 'lazysizes';

lazysizes.cfg.lazyClass = 'lazy-foo';
```

About your other problems it is quite hard to say anything here without seeing the problem in action. I need to be able to reproduce it. Please over something.

You second problem seems to happen because the height of an image changes after loading and therefore the scroll target is changing during the animation. The solution is also described in [the readme](https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps). 

For your first IE problem I really need a test case to even start checking it.

**Comment by ashehzadgec** [comment]
> Hey
> 
> I am using locomotive smooth scroll with your library but default configuration causing one issue that my page is not fully scrolled when a media query is activated. I found this thread on locomotive page. Can you help me how I can use your library with it.
> 
> Pls also reply the first above questions too. I really appreciate your efforts.
> 
> Regards,
> Shehzad Asif

Hi

I am writing the solution for above library problem with lazysizes.js. I dig into their configuration (locomotive library). The culprit behind this behavior is the use of following syntax:

<img data-src="your-path" data-srcset="yout-path-for-different-images">

The thing is data-src and data-srcset is also used in locomotive for lazy loading but with different method. It is that was causing the unusual behavior of the page and images. I removed these attributes and used only default src and srcset attribute and it start working and the issue was resolved. You will not see the lazysizes.js in devtools for these images but still your images will be lazy loaded that can be seen in devtools. If you are not using data-src and data-srcset attribute on images like for example using on image wrapper then it will not cause any issue and you can use these attributes safely. I hope this may help others.

Happy lazy images

Regards,
Shehzad Asif

**Comment by ashehzadgec** [comment]
Hey

First of all, thanks for pointing me in the right direction, the page was
not fully scrollable due to image aspect ratio bcs I was using height auto.
After fixing it everything works fine as expected. Thanks for providing
this amazing library.

I have one question that it is not working with svg images (not inline).
SVG supported or not?

Regards,
Shehzad Asif

**Comment by aFarkas** [comment]
SVG is supported. We only check for `data-src` -> `src` + some others. If you want to transform others you have to write them your own. Just check the readme.
