### ISSUE TITLE
How should I combine the markup with third parties plugins?

### ISSUE THREAD

**Issue by dommm** [aFarkas/lazysizes#88]
I was checking around, What's the right way to implement markup with let's say [picturefill](http://scottjehl.github.io/picturefill/)? What are the correct tags to use for responsive images here?

**Comment by aFarkas** [comment]
Is this not clear: 
https://github.com/aFarkas/lazysizes#markup-api

**Comment by dommm** [comment]
My bad, it is very clear. Thanks for quick respond.
