### ISSUE TITLE
image in hidden div

### ISSUE THREAD

**Issue by kava81** [aFarkas/lazysizes#880]
Hi,
I have a lazy load image in a hidden div above the fold. (div open on hover)

It's seems that image load immediately.

is there a way to avoid this?

thanks

**Comment by aFarkas** [comment]
Images that are inside of the view but are hidden (using `visibility: hidden`) are loaded delayed but preloaded after load so you can animate them in. If you want not load `visibility: hidden` elements you can change this using a [documented configuration property](https://github.com/aFarkas/lazysizes#js-api---options). (see `loadHidden`)
