### ISSUE TITLE
Questions about unveilhooks

### ISSUE THREAD

**Issue by serenity81** [aFarkas/lazysizes#881]
I have replied to another thread with the issue but maybe its better to add a new issue

How do you import the module I see you have to add:
import lazySizes from 'lazysizes';
import 'ls.unveilhooks';

1) But where do you add these lines?

2) Do you also have to add a link as such:
<script src="lazysizes.min.js" ></script>

**Comment by aFarkas** [comment]
@serenity81 
This really depends:

1. if you are using a module bundler like rollup, webpack or parcel you would use `import` in one of your JS files/modules.
2. if you don't use a bundler just simply include the lazysizes using a `script` inside of every html file you create.
3. if you support only modern browsers you could do a mix, but maybe that is too advanced.

Hope this helps. Otherwise ask.

**Comment by serenity81** [comment]
Thanks but I was referring to ls.unveilhooks how do I add the module

where should I add these lines:

import lazySizes from 'lazysizes';
import 'ls.unveilhooks';

**Comment by aFarkas** [comment]
This  is also answered above. Are you using a bundler and if yes which one?

**Comment by serenity81** [comment]
My framework is Laravel so Mix/Webpack is installed by default. I am not currently using Webpack but could if it's necessary.

1) But if a bundeler is not needed can I use something like the below because its not working:

<html>
<head>
<title>Page Title</title>
</head>
<body>
<div data-bg="mages.webp'" class="lazyload"></div>

<script src="scripts/ls.unveilhooks.js" defer></script>
<script src="scripts/lazysizes.min.js'" defer></script>
</body>
</html>

2) Is importing still needed:
import lazySizes from 'lazysizes';
import 'ls.unveilhooks';

**Comment by serenity81** [comment]
My framework is Laravel so Mix/Webpack is installed by default. I am not currently using Webpack but could if it's necessary.

1. But if a bundeler is not needed can I use something like the below because its not working:
`
<body>
<div data-bg="image.webp" class="lazyload"></div>
<script src="scripts/ls.unveilhooks.js" defer></script>
<script src="scripts/lazysizes.min.js'" defer></script>
</body>
`
2. Is importing still needed:
import lazySizes from 'lazysizes';
import 'ls.unveilhooks';

**Comment by aFarkas** [comment]
No if you include your files using script tags you don't need to `import` anything. 

Although it is of course advised that you use webpack or another bundler and create one script that imports both files.

**Comment by serenity81** [comment]
Sorry pasted the message twice.
Thanks for the reply but code like:

Img with data-bg="image.webp" class="lazyload"
 
then followed by :
<script src="scripts/ls.unveilhooks.js" defer></script>
<script src="scripts/lazysizes.min.js'" defer></script>

doesn't work and no image is rendered

**Comment by aFarkas** [comment]
Could you please create a [jsbin](https://jsbin.com/?html,output) or something similar that demonstrates your problem?

**Comment by serenity81** [comment]
Here is it
[https://jsbin.com/cejijelalo/edit?html,output](url)

**Comment by serenity81** [comment]
Just copy and paste the link it didn't work for me when I clicked on it

**Comment by aFarkas** [comment]
@serenity81 
You forgot to add some height to the div. It was loaded but didn't occupy some space.
Here is the [fixed version](https://jsbin.com/nusewupupi/1/edit?html,output)

**Comment by serenity81** [comment]
I cannot see an image in output window

**Comment by aFarkas** [comment]
wrong version (forgot to copy lazyload to the bg class): https://jsbin.com/nusewupupi/2/edit?html,output

**Comment by serenity81** [comment]
Thanks
But how will this work for responsive images that don't have a fixed PX height
