### ISSUE TITLE
bgset plugin - add alt/width/height attributes

### ISSUE THREAD

**Issue by mateusvahl** [aFarkas/lazysizes#887]
Chrome lighthouse is flagging dynamic images added via `bgset` plugin with missing `alt` and `width` `height` attributes,  I would like to be able to add it via attributes like `data-alt=""` and `data-width=""` `data-height=""`, let me know if that makes sense.

![Screen Shot 2021-04-12 at 19 55 30](https://user-images.githubusercontent.com/4995440/114472903-8eb6ab80-9bc9-11eb-8f6c-5d622629f61e.png)r

![Screen Shot 2021-04-12 at 19 54 35](https://user-images.githubusercontent.com/4995440/114472900-8d857e80-9bc9-11eb-937a-8bfdef386134.png)

**Comment by aFarkas** [comment]
The `img` of the bgset plugin is `display: none`. Therefore there is no layout shift and it is also not part of the HTML content. In essence the lighthouse tests should not apply.
