### ISSUE TITLE
Rerun lazysizes functionality after HTTP AJAX request updates markup

### ISSUE THREAD

**Issue by robskrob** [aFarkas/lazysizes#893]
**Describe your problem/question**
A complete but concise description of your problem and how you are trying to fix it and where you are struggling.
On load the `lazysizes` plugin works great and does what I expect -- lazyloading the iFrame assets as one scrolls. However, when my browser sorts the items that it is lazy loading, it makes an API call to a server, fetches the markup and then replaces the existing markup with the requested markup. When this happens the iFrame assets still have the data attribute `data-src`, and `lazysizes` does not appear to be programmatically resetting these attributes to `src` while scrolling.

Is there a way that I can "rerun" the  `lazysizes` after the markup has been updated via the AJAX HTTP call so that the lazy loaded assets can be lazy loaded?

I have searched around in the issues to see if there is something similar to my problem. I found [this one](https://github.com/aFarkas/lazysizes/issues/283), but it does not appear to solve my problem.

**Make it reproduce-able**
I'm really sorry I do not have time at this present moment to make this reproducible. Hopefully the above description is good enough. I cannot believe that I am the first and only person to come across this scenario so hopefully there's an answer here. Maybe I misread the documentation?

**Comment by aFarkas** [comment]
>  I cannot believe that I am the first and only person to come across this scenario so hopefully there's an answer here.

Me, neither but the described problem is actually solved automatically by lazysizes. The that you are experiencing this problem means that probably some other code is producing some serious conflict...

You can re-open if you can provide a link to a test case without reproduction we can only guess and pray but can't help you.

**Comment by robskrob** [comment]
@aFarkas thank you for responding! and thank your prayers! 

I actually found a different JS npm modules that provides a solution for me: https://github.com/ApoorvSaxena/lozad.js

So on page load all I do is run:
```
this.observer = lozad(); // lazy loads elements with default selector as '.lozad'
this.observer.observe();
```

And then after I make an AJAX request to the server which replaces the current markup with the markup from the response from the server, I just run `this.observer.observe();` which allows for the new markup to be lazy loaded.

**Comment by robskrob** [comment]
Maybe if I have time I can look at your source code and either A figure out what I am doing wrong or B find the bug in your project and provide a PR 🙂
