### ISSUE TITLE
What's the policy for a fixed height?

### ISSUE THREAD

**Issue by dommm** [aFarkas/lazysizes#90]
I've encountered on images, that require to have a fixed height.

Example:
1.Container width 1024px = Image dimensions 1024px by 500px
2.Container width 320px = Image dimensions 320px by 150px

When I load the webpage in media screen with breakpoint above 1000px, the image from first example gets loaded.
When I load the webpage in media screen with breakpoint above 300px, the image from first example gets loaded.

Why?

My markup is according to your documentation:
`						<img
							data-sizes="auto"
							data-src="{{ cover.url('fixedDefault') }}"
							data-srcset="{{ cover.url('fixedDefault') }} 290w,{{ cover.url('fixedSmall') }} 400w,{{ cover.url('fixedMedium') }} 600w,{{ cover.url('fixedLarge') }} 760w"
							class="lazyload uk-border-rounded" 
							alt="{{ cover.title }}"
						/>`

**Comment by aFarkas** [comment]
In general, I don't really understand your requirement and I also don't understand really, what goes wrong.

I can just guess, that you either want to do art direction, then you need to use the ``picture`` element or you do test with Chrome, where you can not predict, which image is loaded, if the biggest image is already in cache.

**Comment by dommm** [comment]
It's for post cover,which needs to have fixed height and I want to eliminate the load size as much as possible, because it's the image with largest size dimension in whole website. 

I was testing it in Chrome, Where I loaded the same image in desktop media. The return was, a largest image was loaded.

Than I loaded the same content in mobile media and again, a largest image was loaded. I was expecting to be loaded the smallest image. 

So, I think your first guess may be correct. I have not much knowledge about it, but as I read about the `picture` element, you can define a media, in which a certain image gets loaded? Is it correct, or I misunderstood?

**Comment by aFarkas** [comment]
Yes, that's right. It seems that you need ``picture`` then.

This looks something like this:

```html
<picture>
    <!--[if IE 9]><audio><![endif]-->
    <source
            srcset="http://placehold.it/500x600/11e87f/fff"
            media="(max-width: 450px)" />
    <source
            srcset="http://placehold.it/700x300"
            media="(max-width: 720px)" />
    <source
            srcset="http://placehold.it/1400x600/e8117f/fff"
            media="(max-width: 1100px)" />
    <source
            srcset="http://placehold.it/1800x900/117fe8/fff" />
    <!--[if IE 9]></audio><![endif]-->
    <img
            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
            alt="image with artdirection" />
</picture>
```

With lazySizes this looks then something like this:

```html
<picture>
    <!--[if IE 9]><audio><![endif]-->
    <source
            srcset="http://placehold.it/500x600/11e87f/fff"
            media="(max-width: 450px)" />
    <source
            data-srcset="http://placehold.it/700x300"
            media="(max-width: 720px)" />
    <source
            data-srcset="http://placehold.it/1400x600/e8117f/fff"
            media="(max-width: 1100px)" />
    <source
            data-srcset="http://placehold.it/1800x900/117fe8/fff" />
    <!--[if IE 9]></audio><![endif]-->
    <img
            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
            class="lazyload"
            alt="image with artdirection" />
</picture>
```

 In case you want to separate the media query from your markup (separation of concerns), You can either use the customMedia option of lazySizes (moves the media query implementation from markup to your JS) or you can even add the [customMedia extension](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/custommedia) to move it into your CSS.

**Comment by dommm** [comment]
Understand.
Thank you for you support and time! You're GREAT!
