### ISSUE TITLE
lazySizesConfig needed for parent-fit to work?

### ISSUE THREAD

**Issue by goldmerc** [aFarkas/lazysizes#909]
Following the docs, i'm using...

```
<script src="../lazysizes.min.js" async=""></script>
<script src="../plugins/parent-fit/ls.parent-fit.min.js"></script>
```

But I get an error about lazySizesConfig not being defined. It works if I add this line before the scripts...

`<script>window.lazySizesConfig = window.lazySizesConfig || {};</script>`

But I'm not using any additional config. Just need parent-fit to use auto sizes with CSS object-fit:cover.

It's not a big deal, but I can't find anything in the docs about needing to create a lazySizesConfig object to use parent-fit. Am I missing something? or doing something wrong?

Thanks. Great project btw.

**Comment by aFarkas** [comment]
This would be a bug. But I can't replicate your issue. You should create a testcase.

But your markup has some problems. You should combine both scripts. In case you want to use them separate you must ensure that both scripts are loaded before the core script executes otherwise it is possible that the core scripts starts to transform images before parent-fit is loaded.

**Comment by goldmerc** [comment]
Thanks Alexander. Not sure how to create a testcase. But the following code causes the issue for me running in chrome.  You just need to drop in the parent-fit and lazysizes js where shown. 

If I uncomment the window.lazySizesConfig line the error goes away. I'm probably just doing something wrong! Thanks for your help.
```
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<script>
			//window.lazySizesConfig = window.lazySizesConfig || {};

			/*! parent-fit - v4.0.4 */
		        // parent-fit js

			/*! lazysizes - v5.3.2 */
		        // lazysizes js
		</script>
		<style>
		    .container {
		        position: relative;
		    }

		    .container:before {
		        display: block;
		        width: 100%;
		        content: "";
		        padding-bottom: 400px;
		        height: 0;
		    }

		    .container img {
		        position: absolute;
		        display: block;
		        top: 0;
		        left: 0;
		        width: 100%;
		        height: 100%;
		        object-fit: cover;
		        font-family: "object-fit: cover";
		    }
		</style>
	</head>
	<body>
		<div class="container" style="width: 400px;">
    		<img 
			class="lazyload" 
			src="" 
			data-src="" 
			data-srcset="" 
			data-sizes="auto" >
		</div>
	</body>
</html>
```

**Comment by aFarkas** [comment]
I don't see errors: https://jsbin.com/nolovisaza/1/edit?html,console,output
Please re-open if you can make it reproducible.
