### ISSUE TITLE
size="100vw" loads non retina sized 1024w image instead of 2048w image, on iOS 8, iPad.

### ISSUE THREAD

**Issue by lasseyls** [aFarkas/lazysizes#91]
The following markup will load the 1024w jpeg image instead of the correct 2048w jpeg image on an iPad Air (retina display) iOS Safari 8. It seems the ```sizes="100vw"``` sizes attribute is causing the trouble. If I manually change 100vw to 1024px (for iPad test in landscape) then it will correctly load the 2048w jpeg.

I have included the respimg polyfill for iOS support.

```<img class="lazyload" data-sizes="100vw" data-srcset="/images/generated/resp-368px-2-1024.jpg 1024w, /images/generated/resp-368px-2-2048.jpg 2048w, /images/generated/resp-368px-2-1440.jpg 1440w, /images/generated/resp-368px-2-2560.jpg 2560w, /images/generated/resp-368px-2-5120.jpg 5120w" sizes="100vw">```

**Comment by aFarkas** [comment]
I would assume that this is a respimage bug not a lazysizes one. Can you test the following things for me:

1. Test:
```html
<img srcset="/images/generated/resp-368px-2-1024.jpg 1024w, /images/generated/resp-368px-2-2048.jpg 2048w, /images/generated/resp-368px-2-1440.jpg 1440w, /images/generated/artwork/gritt_uldall_jessen/resp-368px-2-2560.jpg 2560w, /images/generated/resp-368px-2-5120.jpg 5120w" sizes="100vw">
```

2. Test:
```html
<picture>
    <source  srcset="/images/generated/resp-368px-2-1024.jpg 1024w, /images/generated/resp-368px-2-2048.jpg 2048w, /images/generated/resp-368px-2-1440.jpg 1440w, /images/generated/artwork/gritt_uldall_jessen/resp-368px-2-2560.jpg 2560w, /images/generated/resp-368px-2-5120.jpg 5120w" sizes="100vw" />
    <img sizes="100vw">
</picture>
```
3. Test:
And add the following to your JS

```js
setTimeout(function(){
    alert(Math.max(document.documentElement.clientWidth, window.innerWidth) +'x'+ (window.devicePixelRatio));
});
```

**Comment by lasseyls** [comment]
First test:
Also loads the small 1024w image, so same behaviour as with lazyload class.

Second test:
does not work, <picture> isn't supported on iOS and the polyfill only targets lazyload items I guess?

Third test:
The JS test alerts "1024x2".

**Comment by lasseyls** [comment]
Using sizes="auto" works on iOS safari 8. The sizes attribute isn't natively supported by iOS Safari 8. 

I cannot however use sizes="auto" for all my images, since I am trying to trick the browser into picking the 2048w / 1024w (retina / non retina) version of an image that isn't sized 100vw in the DOM, but the src it chooses should be chosen based upon the viewport width, event though I only display it at like 50vw. It works fine in Chrome on Desktop at non-retina, but it doesn't work with retina?

**Comment by lasseyls** [comment]
I am basically just trying to cheat the browser by defining that an image in the srcset has a different size than the actually jpeg-file has. So I define a 1024w image for a src that's actually only 512px wide, and then I would like the image to be displayed at 50vw in the DOM, but it should pick the src using the full viewport width of 1024px (and take into account the retina version, which is what is breaking at the moment).

**Comment by aFarkas** [comment]
Are you using the [respimg plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg) or are you using the [full respimage polyfill](https://github.com/aFarkas/respimage)?

**Comment by lasseyls** [comment]
The respimg plugin

**Comment by aFarkas** [comment]
Ok, this explains it. There is the [not-supported section](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg#what-is-not-supported). One line says 

> If srcset width width descriptors (w descriptor) are used either the data-sizes="auto" feature has to be used or the sizes value has to consist of just one source size value with the CSS px unit.

So you can't use the "vw" unit. Either you use a full polyfill like respimage or picturefill or you can do something like this:

```html
<img class="lazyload" data-trickedimg="" data-srcset="/images/generated/resp-368px-2-1024.jpg 1024w, /images/generated/resp-368px-2-2048.jpg 2048w, /images/generated/resp-368px-2-1440.jpg 1440w, /images/generated/resp-368px-2-2560.jpg 2560w, /images/generated/resp-368px-2-5120.jpg 5120w" />
```

```js
document.addEventListener('lazybeforeunveil', function(e){
    if(e.target.getAttribute('data-trickedimg') != null){
        e.target.setAttribute('sizes', Math.max(document.documentElement.clientWidth, window.innerWidth));
    }
});
```

**Comment by aFarkas** [comment]
I think my last comment should fix your issue. If ti does please close it, otherwise I need more informations/a test case.
