### ISSUE TITLE
When scrolling images are resized 

### ISSUE THREAD

**Issue by Isengo1989** [aFarkas/lazysizes#913]
**Describe the bug**
When opening the console or scrolling on the iphone or ipad images are being resized to the point where you can't see them anymore

**To Reproduce**
Use an image which has vertically more px the horizontally

**Steps to reproduce the behavior:**
Open browser (chrome) and console and drag it up and down or scroll with ipad

**What is the expected behavior:**
No resizing the image

**What happened instead:**
![2021-07-22_21-03_1](https://user-images.githubusercontent.com/8600299/126694998-ab424a24-5d27-4e70-a25e-bcfdfff3de94.png)
![2021-07-22_21-03](https://user-images.githubusercontent.com/8600299/126695011-d31443de-e380-4924-8fb5-6fe091024b7f.png)

**In what environment (browser/device etc.) does this bug happen/not happen:**

**Keywords help others to find this issue:**

⚠️ Search for existing open/closed issues/discussions before you report the issue.
⚠️ If you do not provide enough information to reproduce your bug. We won't be able to work on the issue. In most cases just providing a fraction of your code is not enough!

**Comment by saschen** [comment]
@Isengo1989 hi, i have the same problem. What was you solution to fix this?
