### ISSUE TITLE
Browser Console Warning

### ISSUE THREAD

**Issue by wpjames** [aFarkas/lazysizes#914]
I am getting this warning in Chrome browser console.

```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
lazysizes.min.js:1
Learn more: User-Agent String Reduction
```

EDIT - I just noticed this warning is only present in the development version of Chrome, not in the regular version.

Version 93.0.4577.8 (Official Build) dev (64-bit)

**Comment by aFarkas** [comment]
lazysizes access userAgent for detecting googlebot and also has uses feature detection has another solution. So should work in the future. lazysizes does not browser sniff for real browsers, so shouldn't do much harm. Hope this answer your question.
