### ISSUE TITLE
How to access css file after npm install

### ISSUE THREAD

**Issue by MaluNoPeleke** [aFarkas/lazysizes#918]
**Describe your problem/question**
I have installed via npm and cannot figure out how to add the js to my website because I can only find it in the node_modules folder but not somewhere else.

**Make it reproduce-able**
`npm install lazysizes --save`
In root directory of web project.

**Add tags/keywords**
#npm #embed

**Comment by aFarkas** [comment]
You are using a bundler like webpack, rollup or parcel right?

Then you include the JS file by simply importing it via:

```js
import 'lazysizes'
```

**Comment by MaluNoPeleke** [comment]
No, I am using [Kirby CMS](https://getkirby.com/) (based on PHP) which I have installed via Composer + [this plugin](https://github.com/bnomei/kirby3-srcset) which requires your package.
