### ISSUE TITLE
error when remove image before finished  lazyloaded

### ISSUE THREAD

**Issue by boynet** [aFarkas/lazysizes#92]
````
Uncaught TypeError: Cannot read property 'className' of null
````
in this line on the latest version:
https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L30

I think its happen when there is an image that need to be lazyloaded and I remove it from dom before lazysizes has finished to do the magic

**Comment by aFarkas** [comment]
Do you have a testcase or can you mail me your project to reproduce this error.

**Comment by boynet** [comment]
I am trying of mimick it :/ but somehow I am getting a different error:
http://jsfiddle.net/yzhau0ra/
if you dont see the error in the console try to play with the settimeout time. I am still trying to get the same error I cant show you the project cause its cordova app

**Comment by aFarkas** [comment]
I just fixed this one. Something that might help me, with the other one, is a stacktrace of this error with the current unminified master version. 

Normally this method is called via an event (load and so on), so I should still have a reference to it, even if it is removed from the dom.

**Comment by boynet** [comment]
now I get it :) you gave me an idea, it happen when I remove the parent with the image see:
http://jsfiddle.net/880hhjat/

 its very edge case I dont know if its need to be fixed

**Comment by aFarkas** [comment]
This should be fixed now. Can you please test and confirm this?

**Comment by boynet** [comment]
thanks confirim fixed I update the jsfiddle to latest version http://jsfiddle.net/880hhjat/
