### ISSUE TITLE
Dine In table selection on fulfillment page for kiosk

### ISSUE THREAD

**Issue by rahul72925** [aFarkas/lazysizes#946]
**Is your feature request related to a problem? Please describe.**
Currently Dine table selection available on checkout page for kiosk. If there is no table available then the selection of product is totally become waste for customer.

**Describe the solution you'd like**
Table selection should be on fulfillment page. When customer select the Dine In fulfillment, in a next step they are able to select there table. If there is no table then they can't proceed from that step.

**Comment by ryandc** [comment]
You have the wrong repo.
