### ISSUE TITLE
Source of DOM Events is an Issue for Web Components

### ISSUE THREAD

**Issue by vanthome** [aFarkas/lazysizes#95]
If you want to wrap lazysizes in a Web Component you might have multiple instances of the component in use.
If you want to listen for the `lazybeforeunveil` event you should be able to listen for this on the actual element corresponding to your component instance and not on the `document` because otherwise you need to add the same listener for every instance as you cannot check for the existence of a listener according to this:
http://stackoverflow.com/questions/9046741/get-event-listeners-attached-to-node-using-addeventlistener
So the only way to do this, is to filter the events which is bad for perf.

**Comment by aFarkas** [comment]
The ``lazybeforeunveil`` event is fired at the ``.lazyload`` element itself and bubbles to the ``document`` so you should be able to listen for all events at the component level. But you should make sure, that lazySizes is only initialized once for the hole document.

Not sure whether I understood everything right. Do you have a testcase?

**Comment by vanthome** [comment]
Ok, that works indeed if I bind my listener to the element! Thanks.

**Comment by idoshamun** [comment]
Can you provide your example of using lazysizes with web components, please...

**Comment by vanthome** [comment]
I think I did in the initial description. Also, it's the same problem, whether you use Ember, Angular or whatever framework.

**Comment by idoshamun** [comment]
But you said you managed to get it working, so I wonder how? (I'm using
Polymer btw)

**Comment by vanthome** [comment]
I listen to the DOM events like this: https://github.com/ember-vcl/img/blob/master/main.js#L179
