### ISSUE TITLE
Rias: iOS 8.1 & above don't show the proper images sizes

### ISSUE THREAD

**Issue by bjtitus** [aFarkas/lazysizes#96]
It appears that respimg has a code change to fix an issue in iOS 8.1 for incorrect image sizes being fetched. It doesn't look like that change has made it over to rias and caused serious issues for me. When I tried to implement then fix from respimg it didn't work properly.

It appears that the respimg fix needs to be applied listening to a different event (perhaps after polyfill from rias). I will submit a pull request for this a little later and see if that makes any sense.

Thought I'd go ahead and file an issue since this may be something the author is aware of and has plans to fix.

**Comment by aFarkas** [comment]
This should be fixed now. For the rias extension you don't need to use the special ios fix (but you can). Please close if this fixes your bug.

**Comment by aFarkas** [comment]
Please re-open, if this doesn't answer your question/the bug still exists.
