### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#97]
Uncaught TypeError: (loadElements[i].parentNode || dummyParent).toLowerCase is not a function
lazysizes.noscript.js:15 

Markup: 
```
<figure class="lazyload" data-noscript="">
  <noscript>
    <picture>
      <!--[if IE 9]><video style="display: none;><![endif]-->
        <source srcset="<%=Model.Image.GetImageUrl()%>" />
	<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="<%=Model.Image.AltText%>">
      <!--[if IE 9]></video><![endif]-->
    </picture>
  </noscript>
</figure>
```

**Comment by aFarkas** [comment]
This should be fixed now. Please close this issue, if you can confirm it.

**Comment by JonWallsten** [comment]
Tried the latest and got an error in unveilhooks, the following file after lazysizes.
Last line in lazysizes needs a semicolon: }));
First line in unveilhooks should have one in the beginning just in case:
;(function(window, document){

**Comment by aFarkas** [comment]
This is now a different error? What is with the original error is this gone?

The [last line in lazySizes already has a semicolon](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L549). If this is not related to the original issue and you still think this is a bug please file a different issue. To me it doesn't look as an error.

**Comment by aFarkas** [comment]
Could you please confirm, that this bug is fixed and what is about this other thing?

For me it sounds that you are copying your files manually instead of using a gulp/grunt concat step. As already said the [last line in lazySizes already has a semicolon](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L549).

**Comment by JonWallsten** [comment]
Weird! I always go to the raw-file and do a CTRL+A & CTRL+C, and you are right. It's there. I have no idea what happened this time. The initial problem seems to be solved.
