### ISSUE TITLE
Using noscript plugin with img load event

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#98]
Is it possible to attach load event to images when using noscript plugin?

**Comment by aFarkas** [comment]
Yes, you can do two different things. Either you are using event capturing and filter your images inside the event handler or you add your load events inside a timeout of the ``lazybeforeunveil`` event.

I would prefer to use event capturing:

```js
document.addEventListener('load', (function(){
    var onLoad = function(){
        //this is your img
    };
    return function(e){
        $(e.target).filter('.my-image').each(onLoad);
    };
})(), true);
```

Please close if this helps.

**Comment by JonWallsten** [comment]
Stupid of me not to include my code. 

Lets take this scenario:

```
<figure class="lazyload" data-noscript="">
    <noscript>
		<picture>
            <!--[if IE 9]><video style="display: none;><![endif]-->
            <source srcset="<%=Model.Image.GetImageUrl()%>" />
			<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="<%=Model.Image.AltText%>">
            <!--[if IE 9]></video><![endif]-->
		</picture>
    </noscript>
</figure>
```
The img uses a Base64-image. Won't that defeat the whole load-event? Or do you trigger a new one manually when you remove the noscript tag?

**Comment by aFarkas** [comment]
lazySizes does not trigger a load event. Even an image with a data uri fires a load event.

In case you don't need the load event and only need to know when a transformation is happening, the ``lazybeforeunveil`` event is triggered.

Please also move your image out of the commented ``video`` element:

```html
<figure class="lazyload" data-noscript="">
    <noscript>
        <picture>
            <!--[if IE 9]><video style="display: none;><![endif]-->
            <source srcset="<%=Model.Image.GetImageUrl()%>" />
            <!--[if IE 9]></video><![endif]-->
            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="<%=Model.Image.AltText%>">
        </picture>
    </noscript>
</figure>
```

**Comment by JonWallsten** [comment]
Ah I see. I think I got it to work. But I have one concern though. If the load event is triggered when the data uri is parsed, won't it be triggered before the actual image (<source srcset ) is loaded? Which defeats the purpose of the load event in my particular case?

**Comment by aFarkas** [comment]
If you want to be save, you can add a filter:

```js
document.addEventListener('load', (function(){
	var onLoad = function(){
		//this is your img
	};
	var hasDataUri = function(){
		return /^data:/.test(this.currentSrc || this.src || '');
	};
	return function(e){
		$(e.target).filter('.my-image').not(hasDataUri).each(onLoad);
	};
})(), true);
```

**Comment by JonWallsten** [comment]
Oh, now I get it. How stupid of me. It's safe to use the real image as the source since it won't be rendered inside the noscript tag. So to summarize I remove all data-src/data-srcset, move the lazyload class from img to noscript-tag and add a new class to the images for controlling the load event. Sounds about right? Thanks!

**Comment by aFarkas** [comment]
yes, sounds right.
